package X;

import com.meta.wearable.warp.core.api.transport.socket.SocketClientTransport;
import java.util.List;
import java.util.Set;

/* JADX INFO: renamed from: X.PFy, reason: case insensitive filesystem */
/* JADX INFO: loaded from: classes12.dex */
public abstract class AbstractC54902PFy extends PLT {
    public static final List A00;
    public static final List A01;
    public static final Set A02;
    public static final Set A03;
    public static final Set A04;
    public static final Set A05;
    public static final Set A06;
    public static final Set A07;

    static {
        Set[] setArr = new Set[2];
        setArr[0] = PLT.A01;
        String[] strArr = new String[30];
        strArr[0] = "com.facebook.mk";
        strArr[1] = "com.oculus.horizon.dev";
        strArr[2] = "com.oculus.panelapp.settings";
        strArr[3] = "com.oculus.shellenv";
        strArr[4] = "com.facebook.games";
        strArr[5] = "com.facebook.home.dev";
        strArr[6] = "com.facebook.bonfire";
        strArr[7] = "com.facebook.workdev";
        strArr[8] = "com.facebook.home";
        strArr[9] = "com.facebook.phone";
        strArr[10] = SocketClientTransport.SOCKET_SERVER_PACKAGE_DEBUG;
        strArr[11] = "com.facebook.mlite";
        strArr[12] = "com.facebook.akira";
        strArr[13] = "com.facebook.appmanager.dev";
        strArr[14] = "com.facebook.daykira";
        strArr[15] = "com.facebook.wearable.monza";
        strArr[16] = "com.instagram.direct";
        strArr[17] = "com.facebook.wakizashi";
        strArr[18] = "com.facebook.horizon";
        strArr[19] = "com.facebook.react.panelapp";
        strArr[20] = "com.facebook.together.together.stable";
        strArr[21] = "com.facebook.together.together.release_nightly";
        strArr[22] = "com.facebook.together.together.stable";
        strArr[23] = "com.facebook.together.together.staging";
        strArr[24] = "com.meta.mr.awe";
        strArr[25] = "com.meta.ar.arshellux";
        strArr[26] = "com.oculus.vrshell.home";
        strArr[27] = "com.oculus.externaldisplayservice";
        strArr[28] = "com.facebook.orca.debug";
        A01 = AbstractC465925m.A1G(AbstractC148856g7.A1H("com.instagram.android.debug", strArr, 29), setArr, 1);
        Set[] setArr2 = new Set[2];
        setArr2[0] = PLT.A00;
        String[] strArr2 = new String[10];
        strArr2[0] = "com.facebook.globalsecurity";
        strArr2[1] = "com.facebook.mlite_debug";
        strArr2[2] = "com.oculus.rooms";
        strArr2[3] = "com.facebook.horizon";
        strArr2[4] = "com.facebook.together.together.stable";
        strArr2[5] = "com.facebook.together.together.release_nightly";
        strArr2[6] = "com.facebook.together.together.stable";
        strArr2[7] = "com.facebook.together.together.staging";
        A00 = AbstractC465925m.A1G(AbstractC54852PDx.A0P("com.facebook.orca.debug", "com.instagram.android.debug", strArr2, 8, 9), setArr2, 1);
        String[] strArr3 = new String[57];
        strArr3[0] = "com.facebook.adsmanager";
        strArr3[1] = "com.facebook.akira";
        strArr3[2] = "com.facebook.appmanager";
        strArr3[3] = "com.facebook.appmanager.dev";
        strArr3[4] = "com.facebook.arstudio.player";
        strArr3[5] = "com.facebook.assistantplayground";
        strArr3[6] = "com.facebook.bishop";
        strArr3[7] = "com.facebook.pages.app";
        strArr3[8] = "com.facebook.creatorstudio";
        strArr3[9] = "com.facebook.daykira";
        strArr3[10] = "com.instagram.direct";
        strArr3[11] = "com.facebook.lite";
        strArr3[12] = "com.facebook.games";
        strArr3[13] = "com.facebook.phone";
        strArr3[14] = "com.facebook.home";
        strArr3[15] = "com.facebook.home.dev";
        strArr3[16] = "com.instagram.android";
        strArr3[17] = "com.instagram.lite";
        strArr3[18] = "com.facebook.katana";
        strArr3[19] = "com.facebook.orca";
        strArr3[20] = "com.facebook.react.panelapp";
        strArr3[21] = "com.facebook.talk";
        strArr3[22] = "com.facebook.mk";
        strArr3[23] = "com.facebook.mlite";
        strArr3[24] = "com.facebook.wearable.monza";
        strArr3[25] = "com.oculus.assistant";
        strArr3[26] = "com.oculus.vrshell";
        strArr3[27] = "com.oculus.firsttimenux";
        strArr3[28] = "com.oculus.horizon";
        strArr3[29] = "com.oculus.horizon.dev";
        strArr3[30] = "com.oculus.gemini.upload";
        strArr3[31] = "com.oculus.metacam";
        strArr3[32] = "com.oculus.panelapp.settings";
        strArr3[33] = "com.oculus.vrshell.home";
        strArr3[34] = "com.oculus.ocms";
        strArr3[35] = "com.oculus.systemutilities";
        strArr3[36] = "com.oculus.twilight";
        strArr3[37] = "com.oculus.userserver2";
        strArr3[38] = "com.oculus.updater";
        strArr3[39] = "com.oculus.systemux";
        strArr3[40] = "com.oculus.xrstreamingclient";
        strArr3[41] = "com.facebook.bonfire";
        strArr3[42] = SocketClientTransport.SOCKET_SERVER_PACKAGE_PROD;
        strArr3[43] = SocketClientTransport.SOCKET_SERVER_PACKAGE_DEBUG;
        strArr3[44] = "com.facebook.study";
        strArr3[45] = "com.instagram.barcelona";
        strArr3[46] = "com.instagram.basel";
        strArr3[47] = "com.facebook.wakizashi";
        strArr3[48] = "com.whatsapp";
        strArr3[49] = "com.whatsapp.w4b";
        strArr3[50] = "com.facebook.horizon";
        strArr3[51] = "com.facebook.together.together.stable";
        strArr3[52] = "com.facebook.together.together.release_nightly";
        AbstractC81823ll.A1T("com.facebook.together.together.stable", "com.facebook.together.together.staging", "com.facebook.orca.debug", strArr3);
        A03 = AbstractC148856g7.A1H("com.instagram.android.debug", strArr3, 56);
        String[] strArrA1b = AbstractC81763lf.A1b("com.facebook.adsmanager", "com.facebook.akira", 67, 1);
        strArrA1b[2] = "com.facebook.appmanager";
        strArrA1b[3] = "com.facebook.appmanager.dev";
        strArrA1b[4] = "com.facebook.arstudio.player";
        strArrA1b[5] = "com.facebook.assistantplayground";
        strArrA1b[6] = "com.instagram.barcelona";
        strArrA1b[7] = "com.instagram.basel";
        strArrA1b[8] = "com.facebook.bishop";
        strArrA1b[9] = "com.facebook.pages.app";
        strArrA1b[10] = "com.facebook.creatorstudio";
        strArrA1b[11] = "com.facebook.daykira";
        strArrA1b[12] = "com.instagram.direct";
        strArrA1b[13] = "com.facebook.lite";
        strArrA1b[14] = "com.facebook.games";
        strArrA1b[15] = "com.facebook.phone";
        strArrA1b[16] = "com.facebook.home";
        strArrA1b[17] = "com.facebook.home.dev";
        strArrA1b[18] = "com.instagram.android";
        strArrA1b[19] = "com.instagram.lite";
        strArrA1b[20] = "com.facebook.katana";
        AbstractC81823ll.A0y("com.facebook.orca", "com.facebook.react.panelapp", "com.facebook.talk", "com.facebook.mk", strArrA1b);
        strArrA1b[25] = "com.facebook.mlite";
        strArrA1b[26] = "com.facebook.wearable.system.data";
        strArrA1b[27] = "com.facebook.wearable.apps.mwear";
        strArrA1b[28] = "com.facebook.wearable.system.notification";
        AbstractC81803lj.A1L("com.facebook.wearable.monza", "com.oculus.assistant", strArrA1b);
        strArrA1b[31] = "com.oculus.captionservice";
        strArrA1b[32] = "com.oculus.vrshell";
        strArrA1b[33] = "com.oculus.firsttimenux";
        strArrA1b[34] = "com.oculus.horizon";
        AbstractC81823ll.A11("com.oculus.horizon.dev", "com.oculus.gemini.upload", "com.oculus.metacam", "com.oculus.panelapp.settings", strArrA1b);
        strArrA1b[39] = "com.oculus.vrshell.home";
        strArrA1b[40] = "com.oculus.ocms";
        strArrA1b[41] = "com.oculus.q4bservice";
        strArrA1b[42] = "com.oculus.systemutilities";
        J2C.A1G("com.oculus.twilight", "com.oculus.userserver2", "com.oculus.updater", "com.oculus.systemux", strArrA1b);
        strArrA1b[47] = "com.oculus.xrstreamingclient";
        strArrA1b[48] = "com.oculus.companion.server";
        AbstractC81823ll.A14("com.facebook.bonfire", SocketClientTransport.SOCKET_SERVER_PACKAGE_PROD, SocketClientTransport.SOCKET_SERVER_PACKAGE_DEBUG, "com.facebook.study", strArrA1b);
        AbstractC81823ll.A1T("com.instagram.barcelona", "com.instagram.basel", "com.facebook.wakizashi", strArrA1b);
        strArrA1b[56] = "com.facebook.wearable.system.launcher";
        strArrA1b[57] = "com.whatsapp";
        strArrA1b[58] = "com.whatsapp.w4b";
        strArrA1b[59] = "com.facebook.horizon";
        strArrA1b[60] = "com.facebook.together.together.stable";
        strArrA1b[61] = "com.facebook.together.together.release_nightly";
        strArrA1b[62] = "com.facebook.together.together.stable";
        strArrA1b[63] = "com.facebook.together.together.staging";
        AbstractC81803lj.A1M("com.facebook.react.panelapp", "com.facebook.orca.debug", strArrA1b);
        A02 = AbstractC148856g7.A1H("com.instagram.android.debug", strArrA1b, 66);
        String[] strArr4 = new String[3];
        strArr4[0] = "com.facebook.work";
        strArr4[1] = "com.facebook.workdev";
        A07 = AbstractC148856g7.A1H("com.facebook.workchat", strArr4, 2);
        String[] strArrA1b2 = AbstractC81763lf.A1b("com.instagram.direct", "com.instagram.android", 5, 1);
        strArrA1b2[2] = "com.instagram.lite";
        A04 = AbstractC54852PDx.A0P("com.instagram.barcelona", "com.instagram.basel", strArrA1b2, 3, 4);
        A06 = AbstractC54852PDx.A0P("com.whatsapp", "com.whatsapp.w4b", new String[2], 0, 1);
        String[] strArr5 = new String[22];
        strArr5[0] = "com.oculus.assistant";
        strArr5[1] = "com.oculus.browser";
        strArr5[2] = "com.oculus.captionservice";
        strArr5[3] = "com.oculus.companion.server";
        strArr5[4] = "com.oculus.explore";
        strArr5[5] = "com.oculus.firsttimenux";
        strArr5[6] = "com.oculus.vrshell.home";
        strArr5[7] = "com.oculus.horizon";
        strArr5[8] = "com.oculus.horizon.dev";
        strArr5[9] = "com.oculus.metacam";
        strArr5[10] = "com.oculus.nux.ota";
        strArr5[11] = "com.oculus.ocms";
        strArr5[12] = "com.oculus.panelapp.settings";
        strArr5[13] = "com.oculus.updater";
        strArr5[14] = "com.oculus.q4bservice";
        strArr5[15] = "com.oculus.store";
        strArr5[16] = "com.oculus.systemux";
        strArr5[17] = "com.oculus.xrstreamingclient";
        strArr5[18] = "com.oculus.systemutilities";
        strArr5[19] = "com.oculus.twilight";
        strArr5[20] = "com.oculus.userserver2";
        A05 = AbstractC148856g7.A1H("com.oculus.externaldisplayservice", strArr5, 21);
    }
}
