package X;

/* JADX INFO: renamed from: X.4xE, reason: invalid class name and case insensitive filesystem */
/* JADX INFO: loaded from: classes4.dex */
public abstract class AbstractC110064xE {
    public static String A00(int i) {
        switch (i) {
            case 2:
                return "STELLA_APP_COMPONENT_TTI";
            case 4:
                return "STELLA_APP_PROCESS_MEDIA_CAPTURE";
            case 5:
                return "STELLA_APP_FETCH_RAW_MEDIA";
            case 10:
                return "STELLA_APP_THUMBNAIL_LIST_QUERY_RESPONSE";
            case 11:
                return "STELLA_APP_FULL_SCREEN_MEDIA_QUERY_RESPONSE";
            case 12:
                return "STELLA_APP_FULL_SCREEN_MEDIA_TTI";
            case 14:
                return "STELLA_APP_BLUELINK_READY";
            case 15:
                return "STELLA_APP_PLUGIN_LATENCY";
            case 17:
                return "STELLA_APP_CAPTURE_NOTIF_TO_THUMBNAIL_UI";
            case 1143:
                return "STELLA_APP_STELLA_FIRMWARE_UPDATE_FUNNEL";
            case 1327:
                return "STELLA_APP_ON_DEMAND_CONTACT_PHOTO";
            case 1341:
                return "STELLA_APP_ASSISTANT_RESOURCE_OTA";
            case 1536:
                return "STELLA_APP_SLOW_APP_COMPONENT";
            case 1813:
                return "STELLA_APP_CAPTURED_MEDIA_SYNC_USER_FLOW";
            case 1926:
                return "STELLA_APP_MEDIA_GALLERY_TTRC";
            case 1972:
                return "STELLA_APP_WIFI_CONNECTION_SETUP";
            case 1990:
                return "STELLA_APP_ROUTE_REQUEST";
            case 2035:
                return "STELLA_APP_ARRIVED";
            case 2471:
                return "STELLA_APP_POST_TO_FEED";
            case 2483:
                return "STELLA_APP_FOA_PROVIDER_LINKING_META_LINKED_ACCOUNT_SYNC";
            case 2649:
                return "STELLA_APP_USER_PAIRING_FAIL";
            case 2712:
                return "STELLA_APP_SHARE_LOCATION_FROM_PHONE";
            case 2745:
                return "STELLA_APP_WIFI_FETCH_ASSET";
            case 2949:
                return "STELLA_APP_BLUELINK_SERVICE_REQUEST";
            case 2993:
                return "STELLA_APP_WIP_CONNECTIVITY_WIFI";
            case 3202:
                return "STELLA_APP_DYNAMIC_PHOTO_IMPORT";
            case 3587:
                return "STELLA_APP_IMPORT_UX_FLOW";
            case 3760:
                return "STELLA_APP_ACS_MNEMO_PIPELINE";
            case 3782:
                return "STELLA_APP_IMPORT_SESSION";
            case 3881:
                return "STELLA_APP_DGW_INPROGRESS_THREAD_LIFECYCLE";
            case 3949:
                return "STELLA_APP_FETCH_DEVICE_ERROR_REPORT";
            case 3991:
                return "STELLA_APP_OTA_ARTIFACT_INSTALL";
            case 4000:
                return "STELLA_APP_MWA_MEDIA_SAVE_QPL_EVENT";
            case 4062:
                return "STELLA_APP_FIRMWARE_OTA_SHOW_CLOUD_OTA_UPSELL";
            case 4085:
                return "STELLA_APP_MENTION_TYPEAHEAD_SEARCH";
            case 4115:
                return "STELLA_APP_SSG_EYE_TRACKING_CALIBRATION";
            case 4210:
                return "STELLA_APP_NAVIGATION_TTRC";
            case 4281:
                return "STELLA_APP_DEVICE_HOME_WIDGET_TTRC";
            case 4305:
                return "STELLA_APP_CHANGE_EIS_MODE_FLOW";
            case 4362:
                return "STELLA_APP_TOPAZ_EYE_TRACKING_CALIBRATION";
            case 4570:
                return "STELLA_APP_DEVICE_HTTP_REQUEST";
            case 4646:
                return "STELLA_APP_FOA_PROVIDER_LINKING";
            case 4647:
                return "STELLA_APP_HIGH_CPU";
            case 4717:
                return "STELLA_APP_MCU_FLYTRAP_INIT";
            case 4828:
                return "STELLA_APP_TAR_QPL_EVENT";
            case 5145:
                return "STELLA_APP_FIRMWARE_OTA_DOWNLOAD";
            case 5322:
                return "STELLA_APP_APP_MONITORING";
            case 5442:
                return "STELLA_APP_EDITED_MEDIA_SYNC_USER_FLOW";
            case 5466:
                return "STELLA_APP_DEVICE_BUG_REPORTER_BACKGROUND_PROCESSING";
            case 5492:
                return "STELLA_APP_AI_MODEL_FETCH_PERF";
            case 5634:
                return "STELLA_APP_NAV_NOTIFICATION";
            case 5881:
                return "STELLA_APP_EMG_ADVANCED_DIAGNOSTICS";
            case 5890:
                return "STELLA_APP_REQUEST_FETCH_CHANNEL";
            case 6091:
                return "STELLA_APP_IOS_SLOW_PLUGINS";
            case 6260:
                return "STELLA_APP_SHOW_FULL_SCREEN_VIDEO_TTRC";
            case 6402:
                return "STELLA_APP_DELETE_DEVICE_ERROR_REPORT";
            case 6578:
                return "STELLA_APP_PERMALINK_SNAPSHOT_LOAD";
            case 6760:
                return "STELLA_APP_DEVICE_ASSET_URI_FETCH";
            case 6819:
                return "STELLA_APP_AUTO_EXPORT_ADOPTION";
            case 6911:
                return "STELLA_APP_CLOUD_RESTORE";
            case 6957:
                return "STELLA_APP_FETCH_THUMBNAIL_BLE_FLOW";
            case 7197:
                return "STELLA_APP_AI_RESPONSE_TIME";
            case 7296:
                return "STELLA_APP_DEVICE_ASSET_LOAD";
            case 7320:
                return "STELLA_APP_WEARALE_ASSET_DELIVERY_SERVER_EXEC";
            case 7517:
                return "STELLA_APP_VOICE_DICTATION";
            case 7599:
                return "SCROLL_PERF_STELLA_GALLERY";
            case 7700:
                return "STELLA_APP_BACKGROUND_ACTIVATION";
            case 7853:
                return "STELLA_APP_ACTIVE_NAVIGATION";
            case 7996:
                return "STELLA_APP_MWA_MEDIA_UNDERSTANDING_PLATFORM_JOB_FLOW";
            case 8298:
                return "STELLA_APP_MWA_IOS_DEVICE_CONNECTIVITY";
            case 8477:
                return "STELLA_APP_WIFI_SETTINGS_FLOW";
            case 8500:
                return "STELLA_APP_STELLA_PAIRING_FUNNEL";
            case 8582:
                return "STELLA_APP_USER_PAIRING";
            case 8780:
                return "STELLA_APP_OTA_ARTIFACT_DOWNLOAD";
            case 8886:
                return "STELLA_APP_SECURE_PAIRING_OPTIMISTIC_MODE";
            case 8966:
                return "STELLA_APP_PROCESS_QUICKCLIPS";
            case 9236:
                return "STELLA_APP_META_AI_TTS_READ_ALOUD_FIRST_AUDIO";
            case 9336:
                return "STELLA_APP_BTC_CONNECTION_UPDATE";
            case 9461:
                return "STELLA_APP_BASIC_MEDIA_EDITOR_TRIM_TOOL_TTRC";
            case 9617:
                return "STELLA_APP_STELLA_ASSISTANT_SETUP_FUNNEL";
            case 9845:
                return "STELLA_APP_STARTUP_PLUGINS";
            case 9881:
                return "STELLA_APP_APP_FLOW";
            case 10365:
                return "STELLA_APP_BLUELINK_FETCH_ASSET";
            case 10369:
                return "STELLA_APP_OPEN_AUTOCAPTURE_SESSION_VIEWER";
            case 10420:
                return "STELLA_APP_DEVICE_TELEMETRY_LIST";
            case 10430:
                return "STELLA_APP_MWA_VIDEO_PLAYER";
            case 10629:
                return "STELLA_APP_BASIC_MEDIA_EDITOR_SAVE_EDIT_TTRC";
            case 10891:
                return "STELLA_APP_GALLERY_DATABASE_QUERY";
            case 10910:
                return "STELLA_APP_SHARINGSERVICE_MWA_EVENT";
            case 10928:
                return "STELLA_APP_LOGOUT";
            case 10931:
                return "STELLA_APP_MEDIA_DELETION";
            case 11078:
                return "STELLA_APP_AUTOFIX_PERF";
            case 11089:
                return "STELLA_APP_MEDIA_SAVE_TO_CAMERA_ROLL";
            case 11176:
                return "STELLA_APP_GALLERY_GRID_INITIAL_LOAD";
            case 11322:
                return "STELLA_APP_PAIRING_CONNECTION";
            case 11423:
                return "STELLA_APP_STELLA_DEVICE_SETTINGS_CHANGE";
            case 11538:
                return "STELLA_APP_BASIC_MEDIA_EDITOR_BOOST_TTRC";
            case 11541:
                return "STELLA_APP_HOME_TAB_SERVER_MODULES";
            case 11557:
                return "STELLA_APP_SCROLL_PERF";
            case 11578:
                return "STELLA_APP_BLUELINK_SESSION";
            case 11649:
                return "STELLA_APP_TELEMETRY_BACKGROUND_FLUSH";
            case 11724:
                return "STELLA_APP_SHARINGSERVICE_ESSENTIAL_EVENT";
            case 11916:
                return "STELLA_APP_TASK_VISIT";
            case 12159:
                return "STELLA_APP_FIRMWARE_OTA_INSTALL";
            case 12189:
                return "STELLA_APP_WEARABLE_SKU_SERVER_EXEC";
            case 12275:
                return "STELLA_APP_FOA_PROVIDER_LINKING_META_ACCOUNT_SYNC";
            case 12286:
                return "Mysteriously Vanishing Marker";
            case 12293:
                return "STELLA_APP_GRAPHQL_QUERY_RESPONSE";
            case 12336:
                return "STELLA_APP_LOGIN";
            case 12395:
                return "STELLA_APP_DEVICE_STATES";
            case 12621:
                return "STELLA_APP_BASIC_MEDIA_EDITOR_REVERT_EDIT_TTRC";
            case 12624:
                return "STELLA_APP_BASIC_MEDIA_EDITOR_CROP_TOOL_TTRC";
            case 12709:
                return "STELLA_APP_SHOW_FULL_SCREEN_PHOTO_TTRC";
            case 12737:
                return "STELLA_APP_ACCESSORY_SETUP_KIT_PAIRING_FLOW";
            case 12741:
                return "STELLA_APP_DATA_FETCHER";
            case 12787:
                return "STELLA_APP_BASIC_MEDIA_EDITOR_LIGHTING_TOOL_TTRC";
            case 12867:
                return "STELLA_APP_MEDIA_GALLERY_SCROLL_PERF";
            case 12907:
                return "STELLA_APP_TAIL_LOAD";
            case 13300:
                return "STELLA_APP_AUDIO_CONNECTIVITY_ATTEMPT";
            case 13489:
                return "STELLA_APP_MWA_SEARCH_REQUEST";
            case 13641:
                return "STELLA_APP_WIFI_DIRECT_P2P_GROUP_SETUP";
            case 13653:
                return "STELLA_APP_COMPILATION_CLIP_VIEW_TTI";
            case 13723:
                return "STELLA_APP_BATTERY_INSIGHT";
            case 13733:
                return "STELLA_APP_EMG_TROUBLESHOOTING_FLOW";
            case 13788:
                return "STELLA_APP_PLACE_SEARCH_REQUEST";
            case 13898:
                return "STELLA_APP_BASIC_MEDIA_EDITOR_LANDING_TTRC";
            case 13938:
                return "STELLA_APP_STELLA_OOBE_FUNNEL";
            case 14534:
                return "STELLA_APP_STELLA_LOGIN_FUNNEL";
            case 14598:
                return "STELLA_APP_DYNAMIC_PHOTO_EDIT";
            case 14707:
                return "STELLA_APP_DEVICE_JOB_SCHEDULED";
            case 14770:
                return "STELLA_APP_SHOW_FULL_SCREEN_MEDIA_TTRC";
            case 14909:
                return "STELLA_APP_NATIVE_PROVIDER_LINKING";
            case 14982:
                return "STELLA_APP_USER_ED_EVENTS";
            case 14988:
                return "STELLA_APP_STOP_NAVIGATION";
            case 15183:
                return "STELLA_APP_DEVICE_BATTERY_PERCENTAGE";
            case 15314:
                return "STELLA_APP_UPLOAD_DEVICE_ERROR_REPORT";
            case 15514:
                return "STELLA_APP_WEARABLE_ASSET_DELIVERY_SERVER_EXEC_PRE_PAIRING";
            case 15603:
                return "STELLA_APP_START_NAVIGATION";
            case 15685:
                return "STELLA_APP_SHARINGSERVICE_EVENT";
            case 15706:
                return "STELLA_APP_FIRMWARE_OTA_CHECK";
            case 15882:
                return "STELLA_APP_DEVICE_TELEMETRY_PROCESS_BATCH";
            case 15903:
                return "STELLA_APP_MEDIA_IMPORTING_USER_WAIT";
            case 15954:
                return "STELLA_APP_ROUTE_PREVIEW_REQUEST";
            case 16040:
                return "STELLA_APP_TASK_TRANSITIVE_TOTAL";
            case 16091:
                return "STELLA_APP_USER_PAIRING_SUCCESS";
            case 16099:
                return "STELLA_APP_REROUTE_UPDATE";
            case 16319:
                return "STELLA_APP_USER_PAIRING_START";
            case 16359:
                return "STELLA_APP_QUERY_DEVICE_ERROR_REPORT";
            case 26196:
                return "STELLA_APP_MEDIA_IMPORTING_THUMBNAILS_USER_WAIT";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
