package X;

/* JADX INFO: renamed from: X.4pZ, reason: invalid class name and case insensitive filesystem */
/* JADX INFO: loaded from: classes4.dex */
public abstract class AbstractC106004pZ {
    public static String A00(int i) {
        switch (i) {
            case 9:
                return "IG_CAMERA_TTFF";
            case 10:
                return "IG_CAMERA_TTI";
            case 11:
                return "IG_CAMERA_TTCP";
            case 16:
                return "IG_CAMERA_DOWNLOAD_METADATA";
            case 17:
                return "IG_CAMERA_DOWNLOAD_PREVIEWS";
            case 18:
                return "IG_CAMERA_TIME_TO_FIRST_GALLERY_LOAD";
            case 20:
                return "IG_CAMERA_REPORT_EFFECT";
            case 21:
                return "IG_CAMERA_DOWNLOAD_EFFECT_STORIES";
            case 22:
                return "IG_CAMERA_CAMERA_DID_SHOW_EFFECTS";
            case 23:
                return "IG_CAMERA_EFFECT_SELECTED_PRE_CAPTURE";
            case 24:
                return "IG_CAMERA_DRAFT_EFFECT_LINK_LOAD";
            case 1308:
                return "IG_CAMERA_SHUTTER_BUTTON";
            case 1391:
                return "IG_CAMERA_MUSIC_PLAYER";
            case 1813:
                return "IG_CAMERA_STOP_GREEN_SCREEN_SESSION";
            case 1942:
                return "IG_CAMERA_IG_ANDROID_GALLERY_SELECTION_FLOW_DEBUG";
            case 2053:
                return "IG_CAMERA_DANCIFICATION_AUDIO_BEAT_DETECTION";
            case 2060:
                return "IG_CAMERA_EFFECT_COLLECTION_DOWNLOAD";
            case 2142:
                return "IG_CAMERA_DANCIFICATION_PREVIEW_RENDER";
            case 2363:
                return "IG_CAMERA_EFFECT_SELECTED_POST_CAPTURE";
            case 2412:
                return "IG_CAMERA_MEDIA_CODEC_METHODS_TRACKER";
            case 2791:
                return "IG_CAMERA_EFFECT_SEARCH_FETCH";
            case 3664:
                return "IG_CAMERA_IG_ANDROID_EXTERNAL_IMPORT_MANAGED_FLOW";
            case 3864:
                return "IG_CAMERA_TRANSCODE_FRAME_TO_THUMBNAIL";
            case 3948:
                return "IG_CAMERA_JPEGLOADING";
            case 3968:
                return "IG_CAMERA_UPDATE_GREEN_SCREEN_SESSION";
            case 4259:
                return "IG_CAMERA_START_TOUCH_UP_SESSION";
            case 4380:
                return "IG_CAMERA_DANCIFICATION_PRE_TRANSCODE";
            case 4517:
                return "IG_CAMERA_EFFECT_COLLECTION_ADD_EFFECT";
            case 4647:
                return "IG_CAMERA_MINI_GALLERY_CATEGORY_PAGE_LOAD_E2E";
            case 4812:
                return "IG_CAMERA_BASEL_SHARE";
            case 4814:
                return "IG_CAMERA_IG_STICKER_RENDERED";
            case 4888:
                return "IG_CAMERA_TIME_TO_RENDER_PHOTO";
            case 4910:
                return "IG_CAMERA_USE_AUDIO_CLICK";
            case 5174:
                return "IG_CAMERA_START_GREEN_SCREEN_SESSION";
            case 5237:
                return "IG_CAMERA_EFFECT_COLLECTION_EXPIRED_CACHE_DIFF";
            case 5298:
                return "IG_CAMERA_STOP_TOUCH_UP_SESSION";
            case 5327:
                return "IG_CAMERA_AUDIO_FILTER";
            case 5733:
                return "IG_CAMERA_BASEL_SHARE_INTENT_RECEIVED";
            case 6435:
                return "IG_CAMERA_MUSIC_IN_CAPTURE";
            case 6472:
                return "IG_CAMERA_DANCIFICATION_VOLTRON_MODULE_DOWNLOAD";
            case 6701:
                return "IG_CAMERA_MINI_GALLERY_CATEGORIES_FETCH";
            case 6747:
                return "IG_CAMERA_REEL_SHARE_NUX";
            case 6846:
                return "IG_CAMERA_ADD_TEXT";
            case 7088:
                return "IG_CAMERA_EFFECT_COLLECTION_SMART_EVICTION";
            case 7390:
                return "IG_CAMERA_RECORDING";
            case 7683:
                return "IG_CAMERA_MUSIC_BROWSER_SEARCH";
            case 7801:
                return "IG_CAMERA_QCCM_PRECAPTURE_BUTTON_MANAGER_ERROR_EVENT_V2";
            case 7820:
                return "IG_CAMERA_MUSIC_BROWSER_NULL_STATE";
            case 8291:
                return "IG_CAMERA_WRITE_DEVICE_CAPABILITIES";
            case 8660:
                return "IG_CAMERA_PEOPLE_SEARCH";
            case 8675:
                return "IG_CAMERA_AMG_MEDIA_SCANNER";
            case 9037:
                return "IG_CAMERA_MINI_GALLERY_LOAD";
            case 9259:
                return "IG_CAMERA_DANCIFICATION_FLOW";
            case 9422:
                return "IG_CAMERA_GALLERY_LOAD";
            case 9684:
                return "IG_CAMERA_CREATION_SESSION";
            case 9724:
                return "IG_CAMERA_DANCIFICATION_AUDIO_DOWNLOAD";
            case 9942:
                return "IG_CAMERA_TIME_TO_RENDER_VIDEO";
            case 10092:
                return "IG_CAMERA_C2PA_READING";
            case 10569:
                return "IG_CAMERA_MAGIC_CUT_ELIGIBILITY_CHECK";
            case 10696:
                return "IG_CAMERA_MUSIC_BROWSER_SEARCH_QUERY";
            case 10733:
                return "IG_CAMERA_DANCIFICATION_TTFF";
            case 10781:
                return "IG_CAMERA_IG_CAMERA_FETCH_TARGET_EFFECT_TRAY";
            case 10841:
                return "IG_CAMERA_SMART_EVICTION";
            case 10905:
                return "IG_CAMERA_DANCIFICATION_TRANSCODING";
            case 11035:
                return "IG_CAMERA_IG_CAMERA_FETCH_EFFECTS_FOR_REUPLOAD";
            case 11064:
                return "IG_CAMERA_EFFECT_COLLECTION_SAVE_EFFECT";
            case 11259:
                return "IG_CAMERA_SCENEX_CONTEXTUAL_MUSIC";
            case 11401:
                return "IG_CAMERA_MINI_GALLERY_PREFETCH";
            case 11467:
                return "IG_CAMERA_MUSIC_BROWSER_KEYWORD_SEARCH_QUERY";
            case 11527:
                return "IG_CAMERA_QCCM_PRECAPTURE_BUTTON_MANAGER_ERROR_EVENT";
            case 11596:
                return "IG_CAMERA_IG_STICKER_BROWSER_OPEN";
            case 11676:
                return "IG_CAMERA_EFFECT_COLLECTION_SINGLE_EFFECT_DOWNLOAD";
            case 11870:
                return "IG_CAMERA_AMG_SUGGESTION_GENERATION";
            case 12092:
                return "IG_CAMERA_VOICE_MESSAGE_RECORDING";
            case 12265:
                return "IG_CAMERA_IG_ANDROID_DRAFT_ASSET_ERROR";
            case 12287:
                return "IG_CAMERA_IG_ANDROID_GALLERY_FIRST_LOAD";
            case 12804:
                return "IG_CAMERA_MUSIC_BROWSER_OPEN";
            case 13364:
                return "IG_CAMERA_QCCM_STICKER_OVERLAY_ERROR_EVENT";
            case 13490:
                return "IG_CAMERA_DIRECT_GALLERY_LOAD";
            case 13730:
                return "IG_CAMERA_TIME_TO_PERCEIVED_PHOTO_CAPTURE";
            case 13802:
                return "IG_CAMERA_EFFECT_COLLECTION_UPDATE_EFFECT";
            case 14308:
                return "IG_CAMERA_DANCIFICATION_RETIMING";
            case 14419:
                return "IG_CAMERA_ST_VIDEO_TRACK_THUMBNAIL";
            case 14542:
                return "IG_CAMERA_EDIT_TEXT";
            case 14560:
                return "IG_CAMERA_DANCIFICATION_VISUAL_BEAT_DETECTION";
            case 14983:
                return "IG_CAMERA_MUSIC_BROWSER_LYRICS";
            case 15167:
                return "IG_CAMERA_VIEWPORT_THUMBNAILS_LOADED";
            case 15668:
                return "IG_CAMERA_MEDIA_DRAFTS_MIGRATION";
            case 15759:
                return "IG_CAMERA_MEMORY_STATS_LOGGING_OVERHEAD";
            case 15841:
                return "IG_CAMERA_MUSIC_AUDIBILITY";
            case 25543:
                return "IG_CAMERA_EFFECT_LINK_LOAD";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
