package X;

/* JADX INFO: renamed from: X.4rY, reason: invalid class name and case insensitive filesystem */
/* JADX INFO: loaded from: classes4.dex */
public abstract class AbstractC107234rY {
    public static String A00(int i) {
        switch (i) {
            case 1460:
                return "LABYRINTH_MOBILE_THIRD_PARTY_CHECK_VALIDITY";
            case 1487:
                return "LABYRINTH_MOBILE_ICLOUD_DRIVE_FILE_STATUS";
            case 2068:
                return "LABYRINTH_MOBILE_GET_METADATA_3P_INACTIVE_EB";
            case 2199:
                return "LABYRINTH_MOBILE_ANDROID_KEY_VALUE_BACKUP_RESTORE_SUCCESS";
            case 2911:
                return "LABYRINTH_MOBILE_RESET_BACKUP";
            case 3100:
                return "LABYRINTH_MOBILE_OPTOUT_KVS";
            case 3158:
                return "LABYRINTH_MOBILE_OPTOUT_GDRIVE";
            case 3480:
                return "LABYRINTH_MOBILE_ICLOUD_DRIVE_STARTUP_CHECK";
            case 3603:
                return "LABYRINTH_MOBILE_FETCH_TPID";
            case 3604:
                return "LABYRINTH_MOBILE_WEB_TO_MOBILE_ONBOARDING_FLOW";
            case 3637:
                return "LABYRINTH_MOBILE_RESTORE_WITH_KEYCHAIN";
            case 3647:
                return "LABYRINTH_MOBILE_VIRTUAL_DEVICE_MANAGEMENT";
            case 3811:
                return "LABYRINTH_MOBILE_TOTAL_MESSAGE_VISIBILITY";
            case 4067:
                return "LABYRINTH_MOBILE_PASSKEY_UPSELL";
            case 4200:
                return "LABYRINTH_MOBILE_CROSS_APP_RECOVERY_CODE_SYNC";
            case 4236:
                return "LABYRINTH_MOBILE_PIN_REMINDERS_DATA";
            case 4416:
                return "LABYRINTH_MOBILE_GENERATE_PIN_RESET";
            case 4627:
                return "LABYRINTH_MOBILE_EMPLOYEE_40C_MIGRATION";
            case 4661:
                return "LABYRINTH_MOBILE_GDRIVE_RESTORE";
            case 5017:
                return "LABYRINTH_MOBILE_RESTORE_BACKUP";
            case 5028:
                return "LABYRINTH_MOBILE_AUTO_EB_GET_UPSELL_TYPE";
            case 5191:
                return "LABYRINTH_MOBILE_STARTUP_AUTO_RESTORE_BACKUP";
            case 5728:
                return "LABYRINTH_MOBILE_ANDROID_AUTO_BACKUP_RESTORE";
            case 5916:
                return "LABYRINTH_MOBILE_THREAD_RESTORE_CARD";
            case 6176:
                return "LABYRINTH_MOBILE_CREATE_PIN_ENTRYPOINT";
            case 6366:
                return "LABYRINTH_MOBILE_ICLOUD_KEYCHAIN_STARTUP_CHECK";
            case 6383:
                return "LABYRINTH_MOBILE_IRB_SETTINGS";
            case 6427:
                return "LABYRINTH_MOBILE_GENERATE_NEW_RECOVERY_CODE";
            case 6489:
                return "LABYRINTH_MOBILE_EB_NUX";
            case 6551:
                return "LABYRINTH_MOBILE_THIRD_PARTY_CHECK_AVAILABILITY";
            case 6880:
                return "LABYRINTH_MOBILE_OPTIN_GDRIVE";
            case 7285:
                return "LABYRINTH_MOBILE_PAKE_HANDSHAKE_INITIATOR";
            case 7298:
                return "LABYRINTH_MOBILE_GDRIVE_SETUP";
            case 7395:
                return "LABYRINTH_MOBILE_PIN_CHANGE";
            case 7496:
                return "LABYRINTH_MOBILE_ANDROID_AUTO_BACKUP_SETUP";
            case 8190:
                return "LABYRINTH_MOBILE_PIN_UPSELL_40C_MIGRATION";
            case 8273:
                return "LABYRINTH_MOBILE_VESTA_MIGRATION_FETCH";
            case 8566:
                return "LABYRINTH_MOBILE_VERIFY_KEYS";
            case 9027:
                return "LABYRINTH_MOBILE_PIN_UPSELL_TYPE_FETCH";
            case 9222:
                return "LABYRINTH_MOBILE_DEVICE_REENROLLMENT";
            case 9245:
                return "LABYRINTH_MOBILE_DRIVE_DEPRECATION_DEEPLINK";
            case 9464:
                return "LABYRINTH_MOBILE_PIN_REMINDER";
            case 9475:
                return "LABYRINTH_MOBILE_ANDROID_KEY_VALUE_BACKUP_SUCCESS";
            case 9511:
                return "LABYRINTH_MOBILE_THIRD_PARTY_EXTEND_TTL";
            case 9611:
                return "LABYRINTH_MOBILE_ADD_DEVICE";
            case 9656:
                return "LABYRINTH_MOBILE_THIRD_PARTY_ADD_DEVICE";
            case 9737:
                return "LABYRINTH_MOBILE_ANDROID_KEY_VALUE_BACKUP_TRIGGER_SUCCESS";
            case 9745:
                return "LABYRINTH_MOBILE_PASSKEY_RESTORE";
            case 9886:
                return "LABYRINTH_MOBILE_BLOCKSTORE_RESTORE";
            case 10202:
                return "LABYRINTH_MOBILE_FETCH_BACKUP_STATUS_OMNISTORE";
            case 10393:
                return "LABYRINTH_MOBILE_OPTOUT_BACKUP";
            case 10400:
                return "LABYRINTH_MOBILE_PAKE_HANDSHAKE_RESPONDER";
            case 10523:
                return "LABYRINTH_MOBILE_PIN_REMINDER_V2";
            case 10539:
                return "LABYRINTH_MOBILE_VIRTUAL_DEVICE_MANAGEMENT_REMOVE_DEVICE";
            case 10567:
                return "LABYRINTH_MOBILE_VIRTUAL_DEVICE_VALIDATION_STARTUP_CHECK";
            case 11010:
                return "LABYRINTH_MOBILE_INTERSTITIAL_SCREEN_IMPRESSION";
            case 11012:
                return "LABYRINTH_MOBILE_CHECK_BACKUP_STATUS";
            case 11237:
                return "LABYRINTH_MOBILE_PASSKEY_SETUP";
            case 11392:
                return "LABYRINTH_MOBILE_INBOX_RESTORE_BANNER_CLICK";
            case 11433:
                return "LABYRINTH_MOBILE_DEVICE_STATUS_UPLOAD";
            case 11555:
                return "LABYRINTH_MOBILE_CREATE_VIRTUAL_DEVICE";
            case 11620:
                return "LABYRINTH_MOBILE_BLOCKSTORE_VALIDATION";
            case 11722:
                return "LABYRINTH_MOBILE_THIRD_PARTY_REMOVE_VIRTUAL_DEVICE";
            case 11932:
                return "LABYRINTH_MOBILE_LOCKBOX_MIGRATION";
            case 11940:
                return "LABYRINTH_MOBILE_THREAD_RESTORE_BANNER";
            case 12127:
                return "LABYRINTH_MOBILE_AUTO_RESTORE_OPTIN";
            case 12241:
                return "LABYRINTH_MOBILE_DEFAULT_EB_UPSELL";
            case 12261:
                return "LABYRINTH_MOBILE_VIRTUAL_DEVICE_REMOVAL";
            case 12439:
                return "LABYRINTH_MOBILE_ICLOUD_DRIVE_RESTORE_CHECK";
            case 12449:
                return "LABYRINTH_MOBILE_LOCKBOX_WRITE_RC";
            case 12723:
                return "LABYRINTH_MOBILE_SETUP_BACKUP";
            case 12768:
                return "LABYRINTH_MOBILE_IRB_STATUS_BOTTOMSHEET";
            case 12834:
                return "LABYRINTH_MOBILE_AUTO_EB_PERSIST_UPSELL_TYPE";
            case 12882:
                return "LABYRINTH_MOBILE_BLOCKSTORE_SETUP";
            case 13110:
                return "LABYRINTH_MOBILE_OPTIN_KVS";
            case 13354:
                return "LABYRINTH_MOBILE_THIRD_PARTY_SYNCHRONIZE";
            case 13520:
                return "LABYRINTH_MOBILE_FETCH_BACKUP_STATUS_STARTUP_JOB";
            case 13578:
                return "LABYRINTH_MOBILE_DEANON_MESSAGES_API";
            case 13849:
                return "LABYRINTH_MOBILE_GENERATE_ONE_TIME_CODE";
            case 14012:
                return "LABYRINTH_MOBILE_AUTO_RESTORE_APP_JOB";
            case 14240:
                return "LABYRINTH_MOBILE_GENERATE_RECOVERY_CODE";
            case 14357:
                return "LABYRINTH_MOBILE_FETCH_BACKUP_STATUS";
            case 14706:
                return "LABYRINTH_MOBILE_AUTO_RESTORE_OPTOUT";
            case 14754:
                return "LABYRINTH_MOBILE_THIRD_PARTY_CREATE_VIRTUAL_DEVICE";
            case 14953:
                return "LABYRINTH_MOBILE_PAKE_RESPONDER_GENERATE_CODE";
            case 15157:
                return "LABYRINTH_MOBILE_RESTORE_COMPREHENSION_BOTTOMSHEET";
            case 15341:
                return "LABYRINTH_MOBILE_SETUP_KEYCHAIN_RECOVERY";
            case 15358:
                return "LABYRINTH_MOBILE_TROUBLESHOOT_KVS";
            case 15423:
                return "LABYRINTH_MOBILE_ICLOUD_DRIVE_SHADOW_TEST";
            case 15434:
                return "LABYRINTH_MOBILE_STARTUP_JOB";
            case 15478:
                return "LABYRINTH_MOBILE_THIRD_PARTY_REMOVE_ALL_VIRTUAL_DEVICES";
            case 15694:
                return "LABYRINTH_MOBILE_PAKE_SHOULD_GENERATE_CODE";
            case 15825:
                return "LABYRINTH_MOBILE_PIN_SETUP";
            case 15892:
                return "LABYRINTH_MOBILE_DELETE_BACKUP";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
