package X;

/* JADX INFO: renamed from: X.4lt, reason: invalid class name and case insensitive filesystem */
/* JADX INFO: loaded from: classes4.dex */
public abstract class AbstractC103774lt {
    public static String A00(int i) {
        switch (i) {
            case 1022:
                return "DOLLY_WEB_CANCEL_ORDER_FLOW";
            case 1679:
                return "DOLLY_WEB_SELF_SERVE_REPLACEMENT_SHIPPING_ADDRESS_VALIDATION";
            case 1956:
                return "DOLLY_WEB_ORDER_UPDATE_SHIPPING_ADDRESS";
            case 1970:
                return "DOLLY_WEB_SWITCH_TO_SINGLE_ADDRESS_SHIPPING";
            case 2009:
                return "DOLLY_WEB_CHANGE_SHIPPING_COUNTRY";
            case 2013:
                return "DOLLY_WEB_ORDER_UPDATE_PAYMENT_METHOD";
            case 2354:
                return "DOLLY_WEB_SELF_SERVE_RETURN_SHIPPING_ADDRESS_VALIDATION";
            case 2623:
                return "DOLLY_WEB_RX_ENTRYPOINT_LOAD";
            case 2650:
                return "DOLLY_WEB_BUY_NOW_STORAGE_SELECTION";
            case 3143:
                return "DOLLY_WEB_INITIAL_LOAD";
            case 3495:
                return "DOLLY_WEB_PLACE_ORDER";
            case 3523:
                return "DOLLY_WEB_BUY_NOW_ACCESSORY_SELECTION";
            case 3530:
                return "DOLLY_WEB_CHECKOUT_FLOW";
            case 3868:
                return "DOLLY_WEB_EMAIL_SIGNUP";
            case 4769:
                return "DOLLY_WEB_REPLACEMENT_FLOW";
            case 4827:
                return "DOLLY_WEB_UNIFIED_SEARCH_SERVER";
            case 5432:
                return "DOLLY_WEB_ADD_TO_CART_SERVER_SIDE";
            case 5441:
                return "DOLLY_WEB_SEARCH_ARTICLE_RESULT";
            case 5656:
                return "DOLLY_WEB_ADD_PROMO_CODE";
            case 6120:
                return "DOLLY_WEB_RETURN_FLOW";
            case 6343:
                return "DOLLY_WEB_CHANGE_LOCALE_FLOW";
            case 6724:
                return "DOLLY_WEB_MODULE_LOAD";
            case 7238:
                return "DOLLY_WEB_RX_BUYFLOW_TRANSITIONS_VIDEO_LOAD";
            case 7545:
                return "DOLLY_WEB_ORDER_OPEN_UPDATE_PAYMENT_METHOD_MODAL";
            case 7766:
                return "DOLLY_WEB_ORDER_OPEN_UPDATE_SHIPPING_ADDRESS_MODAL";
            case 7783:
                return "DOLLY_WEB_RX_BUYFLOW_FRAME_NAVIGATION";
            case 8254:
                return "DOLLY_WEB_CHANGE_LOCALE_FLOW_NON_ECOMM";
            case 8309:
                return "DOLLY_WEB_RX_BUYFLOW_SUNGLASS_IMG_LOAD";
            case 8884:
                return "DOLLY_WEB_CHANGE_LOCALE_INTERACTION";
            case 9082:
                return "DOLLY_WEB_NAVIGATION";
            case 9401:
                return "DOLLY_WEB_CHECKOUT_WITH_META_SERVER_SIDE";
            case 9797:
                return "DOLLY_WEB_CART_FLOW";
            case 9962:
                return "DOLLY_WEB_TOP_NAV_CONFIG_QUERY";
            case 10031:
                return "DOLLY_WEB_HOTSPOT_INTERACTION";
            case 10705:
                return "DOLLY_WEB_BUY_NOW";
            case 10892:
                return "DOLLY_WEB_CHANGE_ITEM_QUANTITY";
            case 12064:
                return "DOLLY_WEB_UNIFIED_SEARCH_INTERACTION";
            case 12159:
                return "DOLLY_WEB_ORDER_UPDATE_SHIPPING_ADDRESS_FLOW";
            case 12415:
                return "DOLLY_WEB_ADD_TO_CART";
            case 13037:
                return "DOLLY_WEB_REMOVE_CART_ITEM";
            case 13311:
                return "DOLLY_WEB_ORDER_HISTORY_LOAD_MORE_ORDERS";
            case 13870:
                return "DOLLY_WEB_OPEN_APP_DETAIL";
            case 13912:
                return "DOLLY_WEB_UNIFIED_SEARCH_FLOW";
            case 14331:
                return "DOLLY_WEB_VIDEO_FLYOUT";
            case 14407:
                return "DOLLY_WEB_VIRTUAL_TRY_ON_INITIAL_LOAD";
            case 14470:
                return "DOLLY_WEB_INITIAL_LOAD_SERVER";
            case 14657:
                return "DOLLY_WEB_GALAXY_SERVER_ENV_CONFIG";
            case 14710:
                return "DOLLY_WEB_MIX_AND_MATCH_RX_ENTRYPOINT_LOAD";
            case 14760:
                return "DOLLY_WEB_SAVE_CREDIT_CARD";
            case 14826:
                return "DOLLY_WEB_FEEDBACK_FLOW";
            case 14896:
                return "DOLLY_WEB_RX_MODAL_INITIAL_LOAD";
            case 15046:
                return "DOLLY_WEB_INTERACTION";
            case 15377:
                return "DOLLY_WEB_SAVE_ADDRESS";
            case 15875:
                return "DOLLY_WEB_SEARCH_ARTICLE_FLOW";
            case 16050:
                return "DOLLY_WEB_ORDER_UPDATE_PAYMENT_METHOD_FLOW";
            case 16269:
                return "DOLLY_WEB_RETURN_FIND_ORDER_FLOW";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
