package X;

/* JADX INFO: renamed from: X.4pr, reason: invalid class name and case insensitive filesystem */
/* JADX INFO: loaded from: classes4.dex */
public abstract class AbstractC106184pr {
    public static String A00(int i) {
        switch (i) {
            case 3:
                return "IG_DIRECT_IG_DIRECT_INBOX_FETCH_TTI";
            case 5:
                return "IG_DIRECT_IRIS_TIME_TO_NEW_CONTENT";
            case 12:
                return "IG_DIRECT_RECEIVE_LATENCY";
            case 1166:
                return "IG_DIRECT_INBOX_SNAPSHOT_LOCAL_REVERB_THREAD_FETCH";
            case 1231:
                return "IG_DIRECT_THREAD_MISSING_USER_EIMU_FALLBACK";
            case 1320:
                return "IG_DIRECT_DEIDENTIFIED_REQUEST_PROVIDER_PREPARE";
            case 2143:
                return "IG_DIRECT_MESSAGE_SENT_SPEED";
            case 2752:
                return "IG_DIRECT_ARMADILLO_EXPRESS_MESSAGE_TO_DISK";
            case 2903:
                return "IG_DIRECT_IRIS_SUBSCRIPTION";
            case 3126:
                return "IG_DIRECT_DIRECT_LOCAL_SEND_SPEED";
            case 3738:
                return "IG_DIRECT_MESSAGING_READY";
            case 3799:
                return "IG_DIRECT_INBOX_TTRC";
            case 4420:
                return "IG_DIRECT_IG_DIRECT_E2EE_RECEIVER_FETCH_REQUEST";
            case 5681:
                return "IG_DIRECT_MESSAGE_TEXT_RELIABILITY";
            case 5776:
                return "IG_DIRECT_E2EE_MESSAGE_MEDIA_RELIABILITY";
            case 6221:
                return "IG_DIRECT_ACS_TOKENS_RETRIEVE";
            case 6283:
                return "IG_DIRECT_GROUP_LEAVE";
            case 6372:
                return "IG_DIRECT_INBOX_TAB_TTRC";
            case 6459:
                return "IG_DIRECT_MESSAGE_TEXT_SEND_TO_SENT";
            case 6650:
                return "IG_DIRECT_PREVIEW_DELIVERY_TRACE";
            case 6757:
                return "IG_DIRECT_PUSH_TO_THREADVIEW";
            case 7110:
                return "IG_DIRECT_IGD_REPLY_CONTEXT_PAGINATION";
            case 7326:
                return "IG_DIRECT_PREVIEW_DELIVERY_AMEND";
            case 7738:
                return "IG_DIRECT_GROUP_JOIN";
            case 7840:
                return "IG_DIRECT_DIRECT_INIT";
            case 7871:
                return "IG_DIRECT_IG_DIRECT_RECEIVER_FETCH_REQUEST";
            case 7966:
                return "IG_DIRECT_MESSAGING_INFRA_READY";
            case 8182:
                return "IG_DIRECT_MSYS_MAILBOX_USE";
            case 8458:
                return "IG_DIRECT_INSTAMADILLO_MESSAGE_SEND";
            case 8620:
                return "IG_DIRECT_MESSAGE_POINT_QUERY";
            case 8737:
                return "IG_DIRECT_MSYS_INIT_RATE";
            case 8778:
                return "IG_DIRECT_OHAI_CONFIG_QUERY";
            case 8817:
                return "IG_DIRECT_XMA_NAVIGATION";
            case 9039:
                return "IG_DIRECT_THREAD_CREATION";
            case 9384:
                return "IG_DIRECT_E2EE_MESSAGE_MEDIA_FAILURES";
            case 9767:
                return "IG_DIRECT_IG_DIRECT_HANDLE_SNAPSHOT_INTERCEPT";
            case 10409:
                return "IG_DIRECT_IG_DIRECT_HANDLE_SUCCESS_INBOX_SNAPSHOT";
            case 11005:
                return "IG_DIRECT_MEMU_ONBOARD_CAMERA_UNEXPECTED";
            case 11213:
                return "IG_DIRECT_OPEN_MESSAGE_MEDIA_SEND_TO_SENT";
            case 11483:
                return "IG_DIRECT_MESSAGE_PEEK_LOAD";
            case 11563:
                return "IG_DIRECT_THEME_CHANGE";
            case 11711:
                return "IG_DIRECT_THREADLIST_TO_THREADVIEW_TTRC";
            case 12175:
                return "IG_DIRECT_ARMADILLO_TIME_TO_NEW_CONTENT";
            case 12259:
                return "IG_DIRECT_MESSAGE_REQUESTS_PREFETCH_LATENCY";
            case 12274:
                return "IG_DIRECT_THREAD_SNAPSHOT";
            case 12403:
                return "IG_DIRECT_SET_E2EE_ELIGIBILITY_FAILURE";
            case 12454:
                return "IG_DIRECT_IG_DIRECT_COMPOSER_BOTTOMSHEET";
            case 12688:
                return "IG_DIRECT_E2EE_MESSAGE_MEDIA_SEND_TO_SENT";
            case 12755:
                return "IG_DIRECT_JOINT_TIME_TO_NEW_CONTENT";
            case 12784:
                return "IG_DIRECT_IG_DIRECT_OPEN_RECEIVER_FETCH_REQUEST";
            case 13001:
                return "IG_DIRECT_TLTV_TAP_TO_ACTIVITY_CREATE";
            case 13022:
                return "IG_DIRECT_IG_DIRECT_THREAD_CREATION";
            case 13105:
                return "IG_DIRECT_IG_DIRECT_HANDLE_SUCCESS_THREAD_SNAPSHOT";
            case 13365:
                return "IG_DIRECT_TEST_USER_PERCENT_SAMPLING";
            case 13414:
                return "IG_DIRECT_THREAD_DELETE";
            case 13519:
                return "IG_DIRECT_STORY_MENTION_SEND";
            case 13780:
                return "IG_DIRECT_STORY_MENTION";
            case 13848:
                return "IG_DIRECT_REVERB_LOCAL_THREAD_FETCH";
            case 13960:
                return "IG_DIRECT_RESNAPSHOT_COUNT";
            case 14263:
                return "IG_DIRECT_APP_ICON_TO_DIRECT_INBOX_ICON_BADGE";
            case 14724:
                return "IG_DIRECT_RECEIVER_FETCH_CACHE";
            case 14736:
                return "IG_DIRECT_IG_DIRECT_MID_FIX";
            case 14935:
                return "IG_DIRECT_FOA_DIRECT_LOCAL_SEND_SPEED";
            case 15027:
                return "IG_DIRECT_XMA_RENDER";
            case 15186:
                return "IG_DIRECT_REALTIME_FRESHNESS";
            case 15332:
                return "IG_DIRECT_IG_DIRECT_UNEXPECTED_EVENT";
            case 15475:
                return "IG_DIRECT_PREFETCH_CLIPS_RESHARE_MEDIA";
            case 15487:
                return "IG_DIRECT_MESSAGE_MEDIA_RELIABILITY";
            case 16128:
                return "IG_DIRECT_IGD_MEDIA_UPLOAD_DEDUPLICATION";
            case 16202:
                return "IG_DIRECT_OPEN_MESSAGE_MEDIA_RELIABILITY";
            case 16238:
                return "IG_DIRECT_INSTAMADILLO_SYNC";
            case 16262:
                return "IG_DIRECT_SEEN_STATE";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
