package X;

/* JADX INFO: renamed from: X.F7m, reason: case insensitive filesystem */
/* JADX INFO: loaded from: classes8.dex */
public abstract class AbstractC34149F7m {
    public static String A00(Integer num) {
        switch (num.intValue()) {
            case 1:
                return "ACS_TOKEN";
            case 2:
                return "WAFFLE_TOKEN";
            case 3:
                return "WAFFLE_ACCOUNT_PAUSED";
            case 4:
                return "WAFFLE_ACCOUNT_NOT_LINKED_AND_TRY_TO_MAP";
            case 5:
                return "ABPROP_OFF";
            case 6:
                return "NO_USER_ID";
            case 7:
                return "AFS_PJ_ELIGIBLE";
            case 8:
                return "NO_USER";
            case 9:
                return "FAIL_ENCODE_REQUEST_DATA";
            case 10:
                return "RESPONSE_DATA_PARSING";
            case 11:
                return "HTTP_CONNECTION";
            case 12:
                return "REQUEST_FAILURE";
            case 13:
                return "TOS_NOT_ACCEPTED";
            case 14:
                return "CHANNEL_PAYLOAD_INVALID";
            case 15:
                return "CHANNEL_DROP_METADATA_DOWNLOAD_FAIL";
            case 16:
                return "CHANNEL_DROP_NO_POSITION";
            case 17:
                return "CHANNEL_DROP_FOLLOWED";
            case 18:
                return "CHANNEL_DROP_SCREEN_MISMATCH";
            case 19:
                return "DATA_IN_CACHE_EXPIRED";
            case 20:
                return "USER_FOLLOWED_NEWSLETTER_DURING_COOLDOWN";
            case 21:
                return "NO_BIZ_JID";
            case 22:
                return "CTWA_PAYLOAD_INVALID";
            case 23:
                return "CTWA_PARSER_ERROR";
            case 24:
                return "CTWA_NEEDS_USYNC";
            case 25:
                return "STATUS_PAYLOAD_INVALID";
            case 26:
                return "MEDIA_HASH_UNMATCHED";
            case 27:
                return "MEDIA_PREFETCH_USER_PREFERENCE_NOT_ALLOWED";
            case 28:
                return "STATUS_DROP_IMPRESSION";
            case 29:
                return "STATUS_DROP_CACHE_TTL";
            case 30:
                return "STATUS_DROP_ITEM_EXPIRED";
            case 31:
                return "STATUS_DROP_ITEM_INTEGRITY_CHECK_FAILED";
            case 32:
                return "STATUS_DROP_CTWA_MISSING_CLIENT_FILTERS";
            case 33:
                return "STATUS_DROP_CTWA_PAYLOAD_MISSING";
            case 34:
                return "STATUS_DROP_CTWA_PAYLOAD_MALFORMED";
            case 35:
                return "STATUS_DROP_CTWA_PAYLOAD_MISSING_LID_OR_JID";
            case 36:
                return "STATUS_DROP_SOURCE_URL_MISSING";
            case 37:
                return "STATUS_DROP_BIZ_ALREADY_BLOCKED";
            case 38:
                return "STATUS_MEDIA_NOT_AVAILABLE";
            case 39:
                return "MEDIA_URL_EXPIRED";
            case 40:
                return "STATUS_THUMBNAIL_NOT_AVAILABLE";
            case 41:
                return "STATUS_DROP_UNSUPPORTED_FORMAT";
            case 42:
                return "STATUS_DROP_DASH_MANIFEST_INVALID";
            case 43:
                return "STATUS_BIZ_PROFILE_NOT_AVAILABLE";
            case 44:
                return "STATUS_DROP_BIZ_PROFILE_NOT_BUSINESS_ACCOUNT";
            case 45:
                return "STATUS_BIZ_PROFILE_PIC_NOT_AVAILABLE";
            case 46:
                return "STATUS_DROP_INVALID_CTA";
            case 47:
                return "STATUS_DROP_WRONG_SCHEMA_VERSION";
            case 48:
                return "STATUS_DROP_PARTNERSHIP_DISABLE";
            case 49:
                return "STATUS_DROP_NO_BROWSER_DESTINATION";
            case 50:
                return "STATUS_DROP_FB_PAGE_BACKED_MISSING_PAGE_URL";
            case 51:
                return "STATUS_DROP_IG_BACKED_MISSING_PAGE_URL";
            case 52:
                return "STATUS_DROP_UNKNOWN_PROFILE_TYPE";
            case 53:
                return "STATUS_DROP_BIZ_PROFILE_MAX_RETRIES";
            case 54:
                return "STATUS_DROP_BIZ_PROFILE_URL_MISSING";
            case 55:
                return "STATUS_DROP_PARTNER_PROFILE_PIC_URL_MISSING";
            case 56:
                return "STATUS_PARTNER_PROFILE_PIC_NOT_AVAILABLE";
            case 57:
                return "STATUS_DROP_EXCEEDS_MAX_CARDS";
            case 58:
                return "DUPLICATE_REQUEST_DETECTED";
            case 59:
                return "WAIST_PAYLOAD_INVALID";
            case 60:
                return "WAIST_LOCALIZED_COUNTRY_NAME_FAILURE";
            case 61:
                return "MISSING_FETCH_INTERRUPTED_REASON";
            case 62:
                return "FETCH_TERMINATED";
            case 63:
                return "NO_AD_IN_CACHE_FETCHING_IN_PROGRESS";
            case 64:
                return "NO_AD_IN_CACHE_MEDIA_IN_PROGRESS";
            case 65:
                return "NO_AD_IN_CACHE_NO_AD_FROM_SERVER";
            default:
                return "UNKNOWN";
        }
    }
}
