package X;

/* JADX INFO: renamed from: X.4kx, reason: invalid class name and case insensitive filesystem */
/* JADX INFO: loaded from: classes4.dex */
public abstract class AbstractC103234kx {
    public static String A00(int i) {
        switch (i) {
            case 1168:
                return "CAA_REG_REG_CP_PHONE";
            case 1328:
                return "CAA_REG_REG_TOS_TO_SPI";
            case 1554:
                return "CAA_REG_REG_CONF_CHANGE_PHONE";
            case 1986:
                return "CAA_REG_REG_SAVE_PASSWORD_TO_NEXT";
            case 2005:
                return "CAA_REG_REG_SPI_TO_TRANSITION";
            case 2179:
                return "CAA_REG_REG_USERNAME_TO_NEXT";
            case 2534:
                return "CAA_REG_REG_IG_NAME_SOAP_TO_NEXT";
            case 2545:
                return "CAA_REG_REG_CONF_CHANGE_EMAIL";
            case 2575:
                return "CAA_REG_REG_GENDER_TO_NEXT";
            case 2973:
                return "CAA_REG_REG_DATE_OF_BIRTH_TO_NEXT";
            case 3622:
                return "CAA_REG_REG_GENDER";
            case 4061:
                return "CAA_REG_COUNTRY_CODE_RENDER_PROCESS";
            case 4132:
                return "CAA_REG_REG_ACCOUNT_CREATION";
            case 4291:
                return "CAA_REG_REG_FB_NAME_TO_NEXT";
            case 4562:
                return "CAA_REG_REG_CP_EMAIL";
            case 4693:
                return "CAA_REG_REG_PROFILE_PHOTO";
            case 4804:
                return "CAA_REG_REG_DATE_OF_BIRTH";
            case 5273:
                return "CAA_REG_REG_SUMA_MULTIPLE_ACCOUNTS";
            case 5771:
                return "CAA_REG_REG_FB_NAME";
            case 5872:
                return "CAA_REG_REG_AGE";
            case 6471:
                return "CAA_REG_REG_PASSWORD_TO_NEXT";
            case 6574:
                return "CAA_REG_REG_FBTH_ACCOUNT_CREATION";
            case 7163:
                return "CAA_REG_REG_CP_EMAIL_TO_NEXT";
            case 7446:
                return "CAA_REG_REG_EXISTING_LOGIN_CHECK";
            case 7582:
                return "CAA_REG_CAA_USERNAME_VALIDATION";
            case 7637:
                return "CAA_REG_COUNTRY_CODE_SEARCH_FILTER_PROCESS";
            case 8014:
                return "CAA_REG_REG_USERNAME";
            case 8441:
                return "CAA_REG_REG_TRANSITION_TO_NEXT";
            case 8620:
                return "CAA_REG_REG_ACCOUNT_CREATION_PROD";
            case 9148:
                return "CAA_REG_REG_TRANSITION";
            case 9224:
                return "CAA_REG_REG_CONFIRMATION_PROD";
            case 9749:
                return "CAA_REG_REG_CONFIRMATION";
            case 10197:
                return "CAA_REG_ACCOUNT_CREATION_CRITICAL_OBSERVER";
            case 10605:
                return "CAA_REG_REG_SUMA_SINGLE_ACCOUNT";
            case 10736:
                return "CAA_REG_REG_CONFIRMATION_PROCESS";
            case 10753:
                return "CAA_REG_REG_OVERALL_STEPS";
            case 11011:
                return "CAA_REG_REG_CONFIRMATION_BOTTOM_SHEET";
            case 11497:
                return "CAA_REG_NTA_LANDING_TO_NEXT";
            case 11576:
                return "CAA_REG_REG_CONFIRMATION_TO_PP";
            case 11804:
                return "CAA_REG_REG_FB_SESSIONLESS_INTERSTITIAL";
            case 12101:
                return "CAA_REG_REG_WELCOME_TO_NEXT";
            case 12272:
                return "CAA_REG_REG_CONFIRMATION_CLICK";
            case 12327:
                return "CAA_REG_REG_CP_PHONE_TO_NEXT";
            case 12513:
                return "CAA_REG_REG_PASSWORD";
            case 12627:
                return "CAA_REG_REG_SESSIONLESS_ACCOUNT_SETUP";
            case 12823:
                return "CAA_REG_REG_TWO_STEP_CONFIRMATION";
            case 13043:
                return "CAA_REG_REG_TERMS_OF_SERVICE";
            case 13044:
                return "CAA_REG_REG_NTA_UPSELL";
            case 13536:
                return "CAA_REG_REG_NAME_IG_SOAP";
            case 13553:
                return "CAA_REG_REG_SUMA_LANDING";
            case 13797:
                return "CAA_REG_REG_SAVE_LOGIN_INFO";
            case 13880:
                return "CAA_REG_PROPAGATED_BLOCKER_OBSERVER";
            case 14514:
                return "CAA_REG_REG_TOS_TO_CONFIRMATION";
            case 15277:
                return "CAA_REG_REG_PASSWORD_VALIDATION_PROCESS";
            case 15494:
                return "CAA_REG_REG_CONF_TO_TOS";
            case 15581:
                return "CAA_REG_REG_WELCOME";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
