package X;

import com.whatsapp.companiondevice.tethered.crypto.ShortcakeJni;

/* JADX INFO: renamed from: X.4uj, reason: invalid class name and case insensitive filesystem */
/* JADX INFO: loaded from: classes4.dex */
public abstract class AbstractC109044uj {
    public static String A00(int i) {
        switch (i) {
            case ShortcakeJni.MLKEM768_PUBLIC_KEY_SIZE /* 1184 */:
                return "OCULUS_UNITY_SDK_OCULUS_UNITY_INPUT_SYSTEM_USED";
            case 1336:
                return "OCULUS_UNITY_SDK_GST_AVATARS_OPEN";
            case 1391:
                return "OCULUS_UNITY_SDK_DISCOVER_SPACES";
            case 1805:
                return "OCULUS_UNITY_SDK_OCULUS_UNITY_INPUT_SYSTEM";
            case 1835:
                return "OCULUS_UNITY_SDK_SAMPLE_OPEN";
            case 2174:
                return "OCULUS_UNITY_SDK_OCULUS_UNITY_ANCHORS_SETCOMPONENTSTATUS";
            case 2428:
                return "OCULUS_UNITY_SDK_OVRPASSTHROUGHLAYER_ADDDEFERREDSURFACEGEOMETRIES";
            case 2439:
                return "OCULUS_UNITY_SDK_OCULUS_UNITY_ANCHORS_SAVEANCHOR";
            case 2442:
                return "OCULUS_UNITY_SDK_UPST_OPEN";
            case 2845:
                return "OCULUS_UNITY_SDK_EDITOR_SETTINGS_CHANGED";
            case 2904:
                return "OCULUS_UNITY_SDK_XRSIM_SES_INTERACTION";
            case 2952:
                return "OCULUS_UNITY_SDK_UPST_GOTOSOURCE";
            case 3087:
                return "OCULUS_UNITY_SDK_ID_FRAME_UPDATE";
            case 3202:
                return "OCULUS_UNITY_SDK_EDITOR_TELEMETRY_CONSENT";
            case 3312:
                return "OCULUS_UNITY_SDK_SAMPLE_CLOSE";
            case 3390:
                return "OCULUS_UNITY_SDK_UPST_CLOSE";
            case 3406:
                return "OCULUS_UNITY_SDK_SAVE_SPACES";
            case 3675:
                return "OCULUS_UNITY_SDK_ID_PANEL_OPEN";
            case 3998:
                return "OCULUS_UNITY_SDK_OCULUS_UNITY_OVRINPUT_MIGRATION";
            case 4054:
                return "OCULUS_UNITY_SDK_EDITOR_LINK_CLICKED";
            case 4112:
                return "OCULUS_UNITY_SDK_OVRPASSTHROUGHLAYER_DESTROYSURFACEGEOMETRIES";
            case 4302:
                return "OCULUS_UNITY_SDK_OCULUS_UNITY_ANCHORS_QUERYANCHORS";
            case 4440:
                return "OCULUS_UNITY_SDK_JETSON_TIME_TO_FUN";
            case 4459:
                return "OCULUS_UNITY_SDK_UPST_FIX";
            case 4948:
                return "OCULUS_UNITY_SDK_DOWNLOAD_CONFIGURATION";
            case 5226:
                return "OCULUS_UNITY_SDK_ID_PANEL_INTERACTION";
            case 5278:
                return "OCULUS_UNITY_SDK_UPST_OPTION";
            case 5342:
                return "OCULUS_UNITY_SDK_OCULUS_UNITY_INPUT_COMPAT";
            case 5597:
                return "OCULUS_UNITY_SDK_XRSIM_TOGGLE_STATE";
            case 5644:
                return "OCULUS_UNITY_SDK_EDITOR_SHUTDOWN";
            case 5766:
                return "OCULUS_UNITY_SDK_OCULUS_UNITY_ANCHORS_ERASEANCHOR";
            case 5986:
                return "OCULUS_UNITY_SDK_ID_COMPONENT_TRACKED";
            case 6247:
                return "OCULUS_UNITY_SDK_ID_SETTINGS_ACCESSED";
            case 6301:
                return "OCULUS_UNITY_SDK_OCULUS_UNITY_SDK_SCENE_USEOVRSCENEMODELLOADER";
            case 6351:
                return "OCULUS_UNITY_SDK_ID_PANEL_CLOSE";
            case 6410:
                return "OCULUS_UNITY_SDK_SUBMIT_FEEDBACK";
            case 6446:
                return "OCULUS_UNITY_SDK_XRSIM_PACKAGE_INSTAL";
            case 6526:
                return "OCULUS_UNITY_SDK_COMPONENT_ADDED";
            case 6676:
                return "OCULUS_UNITY_SDK_SCENE_INACTIVTY";
            case 6822:
                return "OCULUS_UNITY_SDK_OVRPASSTHROUGHLAYER_LATEUPDATE";
            case 6852:
                return "OCULUS_UNITY_SDK_SBB_ADD_BLOCK";
            case 6875:
                return "OCULUS_UNITY_SDK_SHARE_SPACES";
            case 7426:
                return "OCULUS_UNITY_SDK_OCULUS_UNITY_RENDER_THREADING_MODE";
            case 7980:
                return "OCULUS_UNITY_SDK_GST_APPID_SET";
            case 8034:
                return "OCULUS_UNITY_SDK_SAMPLE_RUN";
            case 8088:
                return "OCULUS_UNITY_SDK_ID_RUN";
            case 8175:
                return "OCULUS_UNITY_SDK_SCENE_ACTIVITY";
            case 8177:
                return "OCULUS_UNITY_SDK_OCULUS_UNITY_SDK_SCENE_USEOVRSCENEMANAGER";
            case 8270:
                return "OCULUS_UNITY_SDK_ERASE_SPACES";
            case 8671:
                return "OCULUS_UNITY_SDK_OVRPASSTHROUGHLAYER_UPDATESURFACEGEOMETRYTRANSFORMS";
            case 8716:
                return "OCULUS_UNITY_SDK_ERASE_SPACE";
            case 9071:
                return "OCULUS_UNITY_SDK_OVRPASSTHROUGHLAYER_CREATEANDADDMESH";
            case 9337:
                return "OCULUS_UNITY_SDK_SBB_OPEN";
            case 9447:
                return "OCULUS_UNITY_SDK_XRSIM_EDITOR_RUN";
            case 9481:
                return "OCULUS_UNITY_SDK_SCENE_OPEN";
            case 9910:
                return "OCULUS_UNITY_SDK_SBB_DELETE_BLOCK";
            case 10081:
                return "OCULUS_UNITY_SDK_SBB_OPEN_SCENE_WITH_BLOCK";
            case 10140:
                return "OCULUS_UNITY_SDK_EDITOR_PAGE_OPEN";
            case 10311:
                return "OCULUS_UNITY_SDK_UPST_SUMMARY";
            case 10328:
                return "OCULUS_UNITY_SDK_UPST_PROCESS";
            case 10344:
                return "OCULUS_UNITY_SDK_SBB_RUN_BLOCK";
            case 10649:
                return "OCULUS_UNITY_SDK_OVRPASSTHROUGHLAYER_UPDATECOLORMAPFROMCONTROLS";
            case 10744:
                return "OCULUS_UNITY_SDK_GST_SSA_CLOSE";
            case 10953:
                return "OCULUS_UNITY_SDK_SBB_UPDATE_BLOCK";
            case 11480:
                return "OCULUS_UNITY_SDK_SAVE_SPACE_LIST";
            case 11575:
                return "OCULUS_UNITY_SDK_ID_SETTINGS_CHANGED";
            case 11581:
                return "OCULUS_UNITY_SDK_EDITOR_PAGE_CLOSE";
            case 11881:
                return "OCULUS_UNITY_SDK_SBB_INSTALL_BLOCK_DATA";
            case 12012:
                return "OCULUS_UNITY_SDK_BB_VARIANTS_WINDOW";
            case 12280:
                return "OCULUS_UNITY_SDK_AI_WIZARD_REQUEST";
            case 12305:
                return "OCULUS_UNITY_SDK_SCENE_SPACEQUERY";
            case 12498:
                return "OCULUS_UNITY_SDK_GST_AVATARS_CLOSE";
            case 13165:
                return "OCULUS_UNITY_SDK_EDITOR_BUILD";
            case 13232:
                return "OCULUS_UNITY_SDK_EDITOR_START_RAMP_KEYS";
            case 13251:
                return "OCULUS_UNITY_SDK_GST_URL_OPEN";
            case 13482:
                return "OCULUS_UNITY_SDK_OVRPASSTHROUGHLAYER_REMOVESURFACEGEOMETRY";
            case 13667:
                return "OCULUS_UNITY_SDK_EDITOR_START";
            case 13713:
                return "OCULUS_UNITY_SDK_BB_DOWNLOAD_CONTENT";
            case 13992:
                return "OCULUS_UNITY_SDK_SBB_REMOVE_SDK";
            case 14233:
                return "OCULUS_UNITY_SDK_SBB_INSTALL_SDK";
            case 14669:
                return "OCULUS_UNITY_SDK_OVRANCHOR_CONFIGURE_TRACKER";
            case 14733:
                return "OCULUS_UNITY_SDK_OCULUS_UNITY_RENDERING_PATH";
            case 14908:
                return "OCULUS_UNITY_SDK_BB_VARIANTS_WINDOW_OPEN";
            case 14994:
                return "OCULUS_UNITY_SDK_SCENE_CLOSE";
            case 15073:
                return "OCULUS_UNITY_SDK_OCULUS_UNITY_ANCHORS_CREATESPATIALANCHOR";
            case 15494:
                return "OCULUS_UNITY_SDK_QUERY_SPACES";
            case 15539:
                return "OCULUS_UNITY_SDK_OCULUS_UNITY_XR_PLUGIN";
            case 15699:
                return "OCULUS_UNITY_SDK_XRSIM_PLAY_BUTTON";
            case 15833:
                return "OCULUS_UNITY_SDK_OCULUS_UNITY_OVRMANAGER_INIT";
            case 15847:
                return "OCULUS_UNITY_SDK_COMPONENTS_STATUS";
            case 15848:
                return "OCULUS_UNITY_SDK_XRSIM_SETTINGS";
            case 15934:
                return "OCULUS_UNITY_SDK_GST_SSA_OPEN";
            case 16026:
                return "OCULUS_UNITY_SDK_UPST_INTERACTIONFLOW";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
