package X;

/* JADX INFO: renamed from: X.4qm, reason: invalid class name and case insensitive filesystem */
/* JADX INFO: loaded from: classes4.dex */
public abstract class AbstractC106754qm {
    public static String A00(int i) {
        switch (i) {
            case 1:
                return "IG_STORIES_STORY_STICKER_NETWORK_TIME";
            case 1098:
                return "IG_STORIES_LOAD_STICKERS";
            case 1166:
                return "IG_STORIES_STORIES_SPONSORED_LABEL_CTA_STICKER_POSITION";
            case 1557:
                return "IG_STORIES_DIRECT_STORY_LOAD";
            case 1593:
                return "IG_STORIES_IG_STORY_VIEWER_NOTIF_LIST";
            case 2183:
                return "IG_STORIES_SUPERLIKE_VIEWERS_LIST_RENDER";
            case 2557:
                return "IG_STORIES_AI_SUGGESTIONS_STORY_PUBLISH";
            case 3067:
                return "IG_STORIES_STORY_ITEM_VIEWER";
            case 3189:
                return "IG_STORIES_STORY_LIKES";
            case 3443:
                return "IG_STORIES_SUPERLIKE_PUSH_RECEIVED";
            case 3647:
                return "IG_STORIES_BACKGROUND_GRADIENT_GENERATION";
            case 3700:
                return "IG_STORIES_HIDE_STORY";
            case 3777:
                return "IG_STORIES_AVATAR_QUICK_REACTION_BOUND";
            case 4062:
                return "IG_STORIES_STORY_GALLERY_LAYOUT_LOAD";
            case 4160:
                return "IG_STORIES_REWATCH_COUNT_RENDER";
            case 4210:
                return "IG_STORIES_SEARCH_STICKERS";
            case 4235:
                return "IG_STORIES_NOMINATION_STICKER_CONSUMPTION";
            case 4260:
                return "IG_STORIES_CUSTOM_LIST_FETCH";
            case 4460:
                return "IG_STORIES_ADD_STICKER";
            case 4509:
                return "IG_STORIES_AURA_CUSTOM_LIST_SHEET_IMPRESSION";
            case 4607:
                return "IG_STORIES_NOMINATION_STICKER_CREATION";
            case 4733:
                return "IG_STORIES_AI_SUGGESTIONS_POSTCAP_LOADING_SCREEN";
            case 5233:
                return "IG_STORIES_IG_ARCHIVE_PAGE_LOAD";
            case 5271:
                return "IG_STORIES_HIGHLIGHT_COVER_PHOTO_CHANGE";
            case 5814:
                return "IG_STORIES_SPOTLIGHT_STORY";
            case 5935:
                return "IG_STORIES_AI_TRANSITIONS_LOADING_SCREEN";
            case 6208:
                return "IG_STORIES_CUSTOM_LIST_INDICATOR_RENDER";
            case 6455:
                return "IG_STORIES_KARAOKE_CAPTIONS_ASR_REQUEST";
            case 6457:
                return "IG_STORIES_REPLY_STORY";
            case 6612:
                return "IG_STORIES_STORY_NOTIFICATION_CHAINING";
            case 6710:
                return "IG_STORIES_STORIES_SPONSORED_LABEL_SOCIAL_CONTEXT";
            case 7328:
                return "IG_STORIES_DELETE_STORY";
            case 7336:
                return "IG_STORIES_STATE_HOLDER_INIT";
            case 7491:
                return "IG_STORIES_AY_MIDCARD_TAP";
            case 7505:
                return "IG_STORIES_FEED_STORIES_TRAY_SHOWN";
            case 7733:
                return "IG_STORIES_TEXT_TOOL";
            case 7792:
                return "IG_STORIES_EXTENDED_STORY_VIEW";
            case 7927:
                return "IG_STORIES_ADD_TO_HIGHLIGHTS";
            case 7973:
                return "IG_STORIES_EXTEND_STORY";
            case 8123:
                return "IG_STORIES_VIEWERS_LIST_SEARCH";
            case 8206:
                return "IG_STORIES_AY_MIDCARD_IMPRESSION";
            case 8237:
                return "IG_STORIES_VIEWER_TIMESTAMP_RENDER";
            case 8336:
                return "IG_STORIES_STORIES_CREATIVE_STICKER_POSITION";
            case 8460:
                return "IG_STORIES_CREATION_CANVAS_FORMAT";
            case 8536:
                return "IG_STORIES_MIXED_ATTRIBUTION_UNEXPECTED_EVENT";
            case 8620:
                return "IG_STORIES_STORY_CREATION_LONGPRESS_TO_VIDEO";
            case 8841:
                return "IG_STORIES_SAVE_TO_CAMERA_ROLL";
            case 9473:
                return "IG_STORIES_AI_SUGGESTIONS_CONSENT_DIALOG";
            case 9670:
                return "IG_STORIES_STORY_CREATION_FLOW";
            case 9705:
                return "IG_STORIES_STORYLINE_TAP";
            case 9850:
                return "IG_STORIES_STORY_CAMERA_PHOTO_ERROR";
            case 10053:
                return "IG_STORIES_STORY_GALLERY_THUMBNAILS";
            case 10284:
                return "IG_STORIES_SILENT_POST_TO_HIGHLIGHT";
            case 10335:
                return "IG_STORIES_IG_STORIES_MUSIC_STICKER_EDITOR_PREVIEW_LATENCY";
            case 10970:
                return "IG_STORIES_STATE_HOLDER_UPDATE";
            case 11118:
                return "IG_STORIES_STORIES_CAMERA_METADATA_LOGGING";
            case 11511:
                return "IG_STORIES_EXTERNAL_SHARING_TO_STORY";
            case 11632:
                return "IG_STORIES_CREATION_TAB_STICKY_PREF";
            case 12092:
                return "IG_STORIES_S2S_RESHARE_PRODUCER_NUX_IMPRESSION";
            case 12183:
                return "IG_STORIES_SUPERLIKE_ACTIVITY_RENDER";
            case 12375:
                return "IG_STORIES_CREATIVE_PRODUCT_STICKER_RENDERING_INVALIDATION";
            case 12542:
                return "IG_STORIES_AY_MIDCARD_API";
            case 12626:
                return "IG_STORIES_VIEW_NOTIFY_RECEIVED";
            case 13212:
                return "IG_STORIES_FACE_SWAP_GENERATION";
            case 13582:
                return "IG_STORIES_STORYLINE_IMPRESSION";
            case 13640:
                return "IG_STORIES_CUSTOM_LIST_EDIT";
            case 13711:
                return "IG_STORIES_AI_CUTOUT_COLLAGE_LOADING_SCREEN";
            case 13909:
                return "IG_STORIES_IG_ARCHIVE_MEDIA";
            case 14061:
                return "IG_STORIES_CREATIVE_PRODUCT_STICKER_IMAGE_LOAD";
            case 14079:
                return "IG_STORIES_AI_SUGGESTIONS_MEDIA_SCAN";
            case 14081:
                return "IG_STORIES_STORYLINE_LAUNCH_VIEWER";
            case 14285:
                return "IG_STORIES_ANIMATED_CUTOUT_COLLAGE_UPLOAD";
            case 14954:
                return "IG_STORIES_STORIES_SPONSORED_LABEL_CTA_STICKER_REPOSITIONED_CLIENT_SIDE";
            case 15102:
                return "IG_STORIES_STORY_GQL_SUBSCRIPTION";
            case 15242:
                return "IG_STORIES_STORY_NOTIFICATION_NAVIGATION";
            case 15485:
                return "IG_STORIES_AI_SUGGESTIONS_GALLERY_HSCROLL_IMPRESSION";
            case 15487:
                return "IG_STORIES_VIEW_MODELS_UPDATE";
            case 15773:
                return "IG_STORIES_CUSTOM_LIST_CREATE";
            case 16074:
                return "IG_STORIES_CUSTOM_LIST_DELETE";
            case 16124:
                return "IG_STORIES_AURA_STORY_PUBLISH";
            case 16127:
                return "IG_STORIES_SAVE_STORY_TEMPLATE_OVERLAY";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
