package X;

/* JADX INFO: renamed from: X.4rJ, reason: invalid class name and case insensitive filesystem */
/* JADX INFO: loaded from: classes4.dex */
public abstract class AbstractC107084rJ {
    public static String A00(int i) {
        switch (i) {
            case 1178:
                return "INSPIRATION_SHARING_FOUNDATION_CACHE_CLEAR";
            case 1221:
                return "INSPIRATION_SHARING_FOUNDATION_RECOMMENDATION_IMPRESSION_DELIVERY";
            case 1262:
                return "INSPIRATION_SHARING_FOUNDATION_ATS_MIDCARD_LOAD";
            case 1784:
                return "INSPIRATION_SHARING_FOUNDATION_MODEL_RUNNER_VIDEO_FRAME_EXTRACTION_PERF";
            case 1946:
                return "INSPIRATION_SHARING_FOUNDATION_MEDIA_PROVIDER";
            case 2029:
                return "INSPIRATION_SHARING_FOUNDATION_TAP_EDIT_PREVIEW";
            case 2063:
                return "INSPIRATION_SHARING_FOUNDATION_CACHE_READ";
            case 2068:
                return "INSPIRATION_SHARING_FOUNDATION_ADVANCED_PRO_SECONDARY_PIPELINE";
            case 2248:
                return "INSPIRATION_SHARING_FOUNDATION_CLIENT_RECS_GENERATION";
            case 2265:
                return "INSPIRATION_SHARING_FOUNDATION_RETRY_API_PERF";
            case 2664:
                return "INSPIRATION_SHARING_FOUNDATION_MEDIA_DELETION_SYNC";
            case 2702:
                return "INSPIRATION_SHARING_FOUNDATION_MODEL_RUNNER_AUDIO_EXTRACTION_PERF";
            case 3198:
                return "INSPIRATION_SHARING_FOUNDATION_MEDIA_INSIGHTS_CLEAR_STORAGE_WORKER";
            case 3542:
                return "INSPIRATION_SHARING_FOUNDATION_CLIENT_RECS_SUGGESTION";
            case 4653:
                return "INSPIRATION_SHARING_FOUNDATION_MEDIA_PREVIEW_TEARDOWN";
            case 5270:
                return "INSPIRATION_SHARING_FOUNDATION_MODEL_INFERENCE_PERF";
            case 5387:
                return "INSPIRATION_SHARING_FOUNDATION_AFTER_SHARING_UPSELL_IMPRESSION";
            case 5688:
                return "INSPIRATION_SHARING_FOUNDATION_SINGLE_MEDIA_USS_EDIT_PREPROCESSING";
            case 5746:
                return "INSPIRATION_SHARING_FOUNDATION_PREFETCH_ACTUAL_RESOLVE";
            case 5927:
                return "INSPIRATION_SHARING_FOUNDATION_HIDE_A_REC";
            case 6178:
                return "INSPIRATION_SHARING_FOUNDATION_POG_THUMBNAIL_TTRC";
            case 6589:
                return "INSPIRATION_SHARING_FOUNDATION_SINGLE_VIDEO_PROCESSING_PIPELINE";
            case 7968:
                return "INSPIRATION_SHARING_FOUNDATION_MODEL_RUNNER_VIDEO_PROCESSOR_PERF";
            case 8061:
                return "INSPIRATION_SHARING_FOUNDATION_MEDIA_VALIDATOR";
            case 8269:
                return "INSPIRATION_SHARING_FOUNDATION_UEG_BURNT_MEDIA_EXPORT";
            case 8289:
                return "INSPIRATION_SHARING_FOUNDATION_CLIENT_RECS_CLEANUP";
            case 8786:
                return "INSPIRATION_SHARING_FOUNDATION_PHOTO_TO_VIDEO_LOADING";
            case 9177:
                return "INSPIRATION_SHARING_FOUNDATION_EMP_VVP_LIFECYCLE";
            case 9399:
                return "INSPIRATION_SHARING_FOUNDATION_SINGLE_MEDIA_POST_PROCESS";
            case 9402:
                return "INSPIRATION_SHARING_FOUNDATION_ADVANCED_PRO_PIPELINE";
            case 9468:
                return "INSPIRATION_SHARING_FOUNDATION_SINGLE_MEDIA_PROCESS";
            case 9477:
                return "INSPIRATION_SHARING_FOUNDATION_USS_DESTINATION_LAUNCH";
            case 9654:
                return "INSPIRATION_SHARING_FOUNDATION_RECOMMENDATION_PREVIEW_ACCURACY";
            case 9961:
                return "INSPIRATION_SHARING_FOUNDATION_RECOMMENDATION_PRE_PROCESSOR_JOB_ENQUEUE_PERF";
            case 10146:
                return "INSPIRATION_SHARING_FOUNDATION_MODEL_DOWNLOADER_PERF";
            case 10325:
                return "INSPIRATION_SHARING_FOUNDATION_SECONDARY_MODEL_MEDIA_POST_PROCESS";
            case 10380:
                return "INSPIRATION_SHARING_FOUNDATION_POG_VALIDATION";
            case 10443:
                return "INSPIRATION_SHARING_FOUNDATION_SINGLE_MEDIA_UPLOAD";
            case 10902:
                return "INSPIRATION_SHARING_FOUNDATION_MEDIA_COUNT_UPLOAD";
            case 11290:
                return "INSPIRATION_SHARING_FOUNDATION_CLIENT_RECS_DELIVERY";
            case 11323:
                return "INSPIRATION_SHARING_FOUNDATION_CACHE_WRITE";
            case 11557:
                return "INSPIRATION_SHARING_FOUNDATION_ADVANCED_PRO_SECONDARY_PIPELINE_MODEL";
            case 11701:
                return "INSPIRATION_SHARING_FOUNDATION_POG_RESOLVING";
            case 12721:
                return "INSPIRATION_SHARING_FOUNDATION_RECOMMENDATION_PRE_PROCESSOR";
            case 12843:
                return "INSPIRATION_SHARING_FOUNDATION_PREFETCHER_INITIAL_RESOLVE";
            case 13093:
                return "INSPIRATION_SHARING_FOUNDATION_ADVANCED_PRO_HANDSHAKE";
            case 13134:
                return "INSPIRATION_SHARING_FOUNDATION_SIGNAL_EXTRACTION_PERF";
            case 13306:
                return "INSPIRATION_SHARING_FOUNDATION_USS_COMPONENT_HANDOFF";
            case 13675:
                return "INSPIRATION_SHARING_FOUNDATION_MEDIA_RESOLVING_CRMC";
            case 13699:
                return "INSPIRATION_SHARING_FOUNDATION_VIDEO_METADATA_UPLOAD";
            case 13848:
                return "INSPIRATION_SHARING_FOUNDATION_MEDIA_LOCATION_RESOLVING";
            case 14266:
                return "INSPIRATION_SHARING_FOUNDATION_MODEL_RUNNER_PERF";
            case 14827:
                return "INSPIRATION_SHARING_FOUNDATION_EXTENDED_MEDIA_INSIGHTS";
            case 15604:
                return "INSPIRATION_SHARING_FOUNDATION_MEDIA_SCAN_PERF";
            case 15738:
                return "INSPIRATION_SHARING_FOUNDATION_MUSIC_LYRICS_PRE_UEG_DOWNLOAD";
            case 15774:
                return "INSPIRATION_SHARING_FOUNDATION_LIVE_PHOTO_CLIP_RENDER_EXTRACT";
            case 15810:
                return "INSPIRATION_SHARING_FOUNDATION_SINGLE_MEDIA_FETCH";
            case 16101:
                return "INSPIRATION_SHARING_FOUNDATION_MEDIA_RESOLVER";
            case 16132:
                return "INSPIRATION_SHARING_FOUNDATION_USE_CASES_CARD_RENDERING";
            case 16321:
                return "INSPIRATION_SHARING_FOUNDATION_BATCH_VIDEO_PROCESSING_PIPELINE";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
