package X;

import java.util.Set;

/* JADX INFO: renamed from: X.NoD, reason: case insensitive filesystem */
/* JADX INFO: loaded from: classes11.dex */
public abstract class AbstractC51875NoD {
    public static final Set A00() {
        C015707m[] c015707mArr = new C015707m[72];
        AbstractC466525s.A1R("audio_do_work_has_work_cycle_count", false, c015707mArr, 0);
        c015707mArr[1] = AbstractC32971bt.A0Z("audio_do_work_has_work_max_decode_time_ms", false);
        AbstractC466825v.A1F("audio_do_work_has_work_max_overall_time_ms", false, c015707mArr);
        AbstractC81803lj.A1O("audio_do_work_has_work_max_processing_time_ms", false, c015707mArr);
        AbstractC81803lj.A1P("audio_do_work_has_work_total_decode_time_ms", false, c015707mArr);
        AbstractC81803lj.A1Q("audio_do_work_has_work_total_overall_time_ms", false, c015707mArr);
        AbstractC81803lj.A1R("audio_do_work_has_work_total_processing_time_ms", false, c015707mArr);
        AbstractC81803lj.A1S("audio_do_work_has_work_total_samples_processed", false, c015707mArr);
        AbstractC81803lj.A1T("audio_l_audio_stuck_count", false, c015707mArr);
        AbstractC31898DxN.A1G("audio_m_audio_stuck_count", false, c015707mArr);
        AbstractC31898DxN.A1H("audio_sample_rate", false, c015707mArr);
        AbstractC31898DxN.A1I("audio_timestamp_clock_diff_1000_ms_count", false, c015707mArr);
        c015707mArr[12] = AbstractC32971bt.A0Z("audio_timestamp_clock_diff_100_ms_count", false);
        AbstractC31898DxN.A1J("audio_timestamp_clock_diff_200_ms_count", false, c015707mArr);
        AbstractC31898DxN.A1K("audio_timestamp_clock_diff_500_ms_count", false, c015707mArr);
        GV2.A1K("audio_timestamp_clock_diff_bad_count", false, c015707mArr);
        GV2.A1L("audio_timestamp_clock_diff_negative_count", false, c015707mArr);
        c015707mArr[17] = AbstractC32971bt.A0Z("audio_timestamp_clock_diff_ns_max", false);
        c015707mArr[18] = AbstractC32971bt.A0Z("audio_track_underrun_count_at_release", false);
        c015707mArr[19] = AbstractC32971bt.A0Z("audio_xl_audio_stuck_count", false);
        c015707mArr[20] = AbstractC32971bt.A0Z("audio_xxl_audio_stuck_count", false);
        c015707mArr[21] = AbstractC32971bt.A0Z("audio_xxxl_audio_stuck_count", false);
        c015707mArr[22] = AbstractC32971bt.A0Z("current_audio_track_position_ns", false);
        c015707mArr[23] = AbstractC32971bt.A0Z("blocking_gc_count_delta", false);
        c015707mArr[24] = AbstractC32971bt.A0Z("blocking_gc_time_ms", false);
        c015707mArr[25] = AbstractC32971bt.A0Z("gc_count_delta", false);
        c015707mArr[26] = AbstractC32971bt.A0Z("heap_used_bytes", false);
        c015707mArr[27] = AbstractC32971bt.A0Z("avg_decoding_time_media_composition_ms", false);
        c015707mArr[28] = AbstractC32971bt.A0Z("avg_video_demux_time_ms", false);
        c015707mArr[29] = AbstractC32971bt.A0Z("camera_session_id", false);
        c015707mArr[30] = AbstractC32971bt.A0Z("cold_start_proxy_excluded_ms", false);
        c015707mArr[31] = AbstractC32971bt.A0Z("configuration_name", true);
        c015707mArr[32] = AbstractC32971bt.A0Z("consecutive_no_render_count", true);
        c015707mArr[33] = AbstractC32971bt.A0Z("video_tracks_count", false);
        c015707mArr[34] = AbstractC32971bt.A0Z("debug_error_trace", false);
        c015707mArr[35] = AbstractC32971bt.A0Z("debug_message", false);
        c015707mArr[36] = AbstractC32971bt.A0Z("effective_stuck_time_ms", false);
        c015707mArr[37] = AbstractC32971bt.A0Z("debug_rendering_statistics", true);
        c015707mArr[38] = AbstractC32971bt.A0Z("decoder_debug_info", false);
        c015707mArr[39] = AbstractC32971bt.A0Z("demux_decode_exit_path", true);
        c015707mArr[40] = AbstractC32971bt.A0Z("display_pending_delay_ms", true);
        c015707mArr[41] = AbstractC32971bt.A0Z("demux_decode_wrappers_type_count", false);
        c015707mArr[42] = AbstractC32971bt.A0Z("device_battery_level", false);
        c015707mArr[43] = AbstractC32971bt.A0Z("device_thermal_status", false);
        c015707mArr[44] = AbstractC32971bt.A0Z("last_frame_advance_time_ms", true);
        c015707mArr[45] = AbstractC32971bt.A0Z("last_frame_read_sample_data_time_ms", true);
        c015707mArr[46] = AbstractC32971bt.A0Z("max_concurrent_tracks_preloaded", false);
        c015707mArr[47] = AbstractC32971bt.A0Z("media_composition_hash", false);
        c015707mArr[48] = AbstractC32971bt.A0Z("media_tracks_added", false);
        c015707mArr[49] = AbstractC32971bt.A0Z("media_track_added_time_ms", false);
        c015707mArr[50] = AbstractC32971bt.A0Z("media_tracks_removed", false);
        c015707mArr[51] = AbstractC32971bt.A0Z("media_track_removed_time_ms", false);
        c015707mArr[52] = AbstractC32971bt.A0Z("invalid_metadata_list", false);
        c015707mArr[53] = AbstractC32971bt.A0Z("is_display_pending", true);
        c015707mArr[54] = AbstractC32971bt.A0Z("overall_track_switch_stuck_time_ms", true);
        c015707mArr[55] = AbstractC32971bt.A0Z("project_id", false);
        c015707mArr[56] = AbstractC32971bt.A0Z("project_load_type", true);
        c015707mArr[57] = AbstractC32971bt.A0Z("proxy_wait_time_ms", false);
        c015707mArr[58] = AbstractC32971bt.A0Z("reason", false);
        c015707mArr[59] = AbstractC32971bt.A0Z("render_pts_us", false);
        c015707mArr[60] = AbstractC32971bt.A0Z("retry_attempt_number", false);
        c015707mArr[61] = AbstractC32971bt.A0Z("software_decoder_count", false);
        c015707mArr[62] = AbstractC32971bt.A0Z("stuck_source", true);
        c015707mArr[63] = AbstractC32971bt.A0Z("surface_valid", true);
        c015707mArr[64] = AbstractC32971bt.A0Z("track_resize_status", true);
        c015707mArr[65] = AbstractC32971bt.A0Z("track_switch_between_render_avg", true);
        c015707mArr[66] = AbstractC32971bt.A0Z("track_switch_between_render_max_avg", true);
        c015707mArr[67] = AbstractC32971bt.A0Z("track_switch_count", true);
        c015707mArr[68] = AbstractC32971bt.A0Z("track_switch_stuck_count", true);
        c015707mArr[69] = AbstractC32971bt.A0Z("media_accuracy_validation_error", false);
        c015707mArr[70] = AbstractC32971bt.A0Z("media_accuracy_validation_timeout", false);
        return AbstractC148856g7.A1H(AbstractC32971bt.A0Z("target_audio_track_position_ns_time_stamp_based", false), c015707mArr, 71);
    }

    public static final Set A01() {
        String[] strArr = new String[C26698BmO.NEWSLETTER_ADMIN_PROFILE_STATUS_MESSAGE_FIELD_NUMBER];
        strArr[0] = "min_time_to_render_first_frame_during_seek";
        strArr[1] = "avg_rendered_frames_per_seek_second";
        strArr[2] = "avg_max_time_to_render_frame_during_seek";
        strArr[3] = "good_seeks";
        strArr[4] = "acceptable_seeks";
        strArr[5] = "bad_seeks";
        strArr[6] = "very_bad_seeks";
        strArr[7] = "rendered_frames_per_seek_second_bucket";
        strArr[8] = "good_seek_fps";
        strArr[9] = "acceptable_seek_fps";
        strArr[10] = "bad_seek_fps";
        strArr[11] = "very_bad_seek_fps";
        strArr[12] = "total_seek_calls";
        strArr[13] = "seek_shape";
        strArr[14] = "seek_rendered_count";
        strArr[15] = "seek_no_render_count";
        strArr[16] = "seek_skipped_backward_threshold_count";
        strArr[17] = "seek_scrub_handoff_dropped_count";
        strArr[18] = "seek_scrub_handoff_unattributed_count";
        strArr[19] = "total_rendered_frames_during_seek";
        strArr[20] = "total_seek_duration";
        strArr[21] = "temporal_layer_seek_skipped_frames";
        strArr[22] = "seek_reason";
        strArr[23] = "good_seek_ceiling_ms";
        strArr[24] = "acceptable_seek_ceiling_ms";
        strArr[25] = "bad_seek_ceiling_ms";
        strArr[26] = "bad_seek_time_to_seek_ms";
        strArr[27] = "bad_seek_time_to_step_a_clear_and_refresh_ms";
        strArr[28] = "bad_seek_time_to_step_b_render_back_frame_step_ms";
        strArr[29] = "bad_seek_time_to_step_c_seek_media_extractor_step_ms";
        strArr[30] = "bad_seek_time_to_step_d_linear_decode_step_ms";
        strArr[31] = "bad_seek_step_da_keyframe_jump_time_ms";
        strArr[32] = "bad_seek_decode_loop_count";
        strArr[33] = "bad_seek_position_advancement_us";
        strArr[34] = "bad_seek_step_db_negative_pts_filter_time_ms";
        strArr[35] = "bad_seek_negative_pts_empty_dequeue_count";
        strArr[36] = "bad_seek_negative_pts_loop_count";
        strArr[37] = "bad_seek_negative_pts_initial_decode_time_ms";
        strArr[38] = "bad_seek_decoder_time_correction_us";
        strArr[39] = "bad_seek_step_dc_decoder_decode_time_ms";
        strArr[40] = "bad_seek_decode_and_advance_all_tracks_time_ms";
        strArr[41] = "bad_seek_is_trimmed_clip";
        strArr[42] = "bad_seek_per_frame_decode_cost_ms";
        strArr[43] = "avg_per_frame_decode_cost_ms";
        strArr[44] = "bad_seek_decoder_throughput";
        strArr[45] = "avg_decoder_throughput";
        strArr[46] = "bad_seek_time_to_render_total_ms";
        strArr[47] = "bad_seek_total_frames_rendered";
        strArr[48] = "bad_seek_time_to_demux_decode_ms";
        strArr[49] = "bad_seek_demux_decode_invocations";
        strArr[50] = "bad_seek_time_to_synchronize_tracks_ms";
        strArr[51] = "bad_seek_synchronize_tracks_invocations";
        strArr[52] = "bad_seek_time_to_step_ca_refresh_tracks_ms";
        strArr[53] = "bad_seek_time_to_step_cb_calculate_seek_to_time_ms";
        strArr[54] = "bad_seek_time_to_step_cc_demux_decode_seek_keyframe_ms";
        strArr[55] = "bad_seek_time_to_step_cd_seek_audio_tracks_ms";
        strArr[56] = "bad_seek_step_c_cancel_extraction_join_ms";
        strArr[57] = "bad_seek_step_c_cancel_extraction_lock_ms";
        strArr[58] = "bad_seek_step_c_decoder_flush_ms";
        strArr[59] = "bad_seek_step_c_demuxer_seek_ms";
        strArr[60] = "bad_seek_step_c_sample_time_reopen_ms";
        strArr[61] = "bad_seek_step_c_wrapper_seek_to_ms";
        strArr[62] = "bad_seek_cb_tolerance_seek_target_ms";
        strArr[63] = "bad_seek_cb_track_filter_loop_ms";
        strArr[64] = "bad_seek_cb_swap_to_proxy_ms";
        strArr[65] = "bad_seek_cb_wrapper_future_join_ms";
        strArr[66] = "bad_seek_cb_skip_track_seek_check_ms";
        strArr[67] = "bad_seek_cb_update_trim_ms";
        strArr[68] = "bad_seek_cb_tolerance_decode_target_ms";
        strArr[69] = "bad_seek_cb_track_validation_loop_ms";
        strArr[70] = "bad_seek_cb_measured_total_ms";
        strArr[71] = "bad_seek_cb_unenumerated_remainder_ms";
        strArr[72] = "bad_seek_cb_partition_complete";
        strArr[73] = "bad_seek_custom_fps";
        strArr[74] = "bad_seek_is_backward";
        strArr[75] = "bad_seek_player_start_position_us";
        strArr[76] = "bad_seek_player_end_position_us";
        strArr[77] = "bad_seek_active_elements";
        strArr[78] = "bad_seek_current_operation_count";
        strArr[79] = "bad_time_to_seek_total_ms";
        strArr[80] = "large_seek_frame_gap_count";
        strArr[81] = "extra_large_seek_frame_gap_count";
        strArr[82] = "large_seek_frame_gap_time_ms";
        strArr[83] = "extra_large_seek_frame_gap_time_ms";
        strArr[84] = "backward_seek_count";
        strArr[85] = "forward_seek_count";
        strArr[86] = "boundary_crossing_count";
        strArr[87] = "decoder_creation_count";
        strArr[88] = "step_c_total_ms";
        strArr[89] = "step_d_total_ms";
        strArr[90] = "total_decode_loops";
        strArr[91] = "decode_loop_max";
        strArr[92] = "interrupted_seek_count";
        strArr[93] = "thumbnail_decoded_count";
        strArr[94] = "thumbnail_missed_count";
        strArr[95] = "thumbnail_not_hardware_count";
        strArr[96] = "worst_seek_time_to_seek_ms";
        strArr[97] = "worst_seek_is_backward";
        strArr[98] = "worst_seek_decode_loop_count";
        strArr[99] = "worst_seek_active_elements";
        strArr[100] = "worst_seek_step_c_ms";
        strArr[101] = "worst_seek_step_d_ms";
        strArr[102] = "worst_seek_player_start_position_us";
        strArr[103] = "worst_seek_player_end_position_us";
        strArr[104] = "direction_change_count";
        strArr[105] = "tolerance_seek_count";
        strArr[106] = "tolerance_avg_ms";
        strArr[107] = "tolerance_max_ms";
        strArr[108] = "track_alignment_tolerance_us";
        strArr[109] = "final_rendering_tolerance_us";
        strArr[110] = "backward_seek_threshold_us";
        strArr[111] = "max_active_tracks";
        strArr[112] = "seek_ms_since_prev_seek_end";
        strArr[113] = "seek_keyframe_index_state";
        strArr[114] = "seek_keyframe_distance_max_us";
        strArr[115] = "seek_keyframe_distance_count";
        strArr[116] = "seek_preview_stuck_detector_enabled";
        strArr[117] = "seek_preview_stuck_count";
        strArr[118] = "seek_preview_stuck_total_ms";
        strArr[119] = "seek_preview_stuck_max_gap_ms";
        strArr[120] = "scrub_velocity_avg_comp_ms_per_wall_ms";
        strArr[121] = "scrub_velocity_max_comp_ms_per_wall_ms";
        strArr[122] = "scrub_thumbnail_engaged_count";
        strArr[123] = "scrub_decoder_seek_count";
        strArr[124] = "scrub_frame_offset_avg_us";
        return AbstractC148856g7.A1H("scrub_frame_offset_max_us", strArr, C26698BmO.SPLIT_PAYMENT_MESSAGE_FIELD_NUMBER);
    }
}
