package X;

/* JADX INFO: renamed from: X.4rO, reason: invalid class name and case insensitive filesystem */
/* JADX INFO: loaded from: classes4.dex */
public abstract class AbstractC107134rO {
    public static String A00(int i) {
        switch (i) {
            case 1:
                return "INSTAGRAM_SHOPPING_PDP_TTI";
            case 2:
                return "INSTAGRAM_SHOPPING_PDP_LOAD";
            case 3:
                return "INSTAGRAM_SHOPPING_SHOP_HOME_TTI";
            case 4:
                return "INSTAGRAM_SHOPPING_SHOP_HOME_LOAD";
            case 5:
                return "INSTAGRAM_SHOPPING_PROFILE_SHOP_TTI";
            case 6:
                return "INSTAGRAM_SHOPPING_PROFILE_SHOP_LOAD";
            case 7:
                return "INSTAGRAM_SHOPPING_FUCHSIA_TTI";
            case 8:
                return "INSTAGRAM_SHOPPING_FUCHSIA_LOAD";
            case 9:
                return "INSTAGRAM_SHOPPING_CHECKOUT_TTI";
            case 10:
                return "INSTAGRAM_SHOPPING_PRODUCT_COLLECTION_LOAD";
            case 11:
                return "INSTAGRAM_SHOPPING_PLACE_ORDER_TTI";
            default:
                switch (i) {
                    case 1030:
                        return "INSTAGRAM_SHOPPING_CHECKOUT_TTRC";
                    case 1427:
                        return "INSTAGRAM_SHOPPING_UPDATE_CART";
                    case 1637:
                        return "INSTAGRAM_SHOPPING_WISHLIST_TTI";
                    case 1998:
                        return "INSTAGRAM_SHOPPING_CHECKOUT_NUX_TO_PUX_TTRC";
                    case 2017:
                        return "INSTAGRAM_SHOPPING_VIEW_SHOP_HOME";
                    case 2444:
                        return "INSTAGRAM_SHOPPING_PREFETCH_SHOP_HOME";
                    case 2452:
                        return "INSTAGRAM_SHOPPING_SHOPPING_CREATION";
                    case 2773:
                        return "INSTAGRAM_SHOPPING_TOTAL_QUEUE";
                    case 2813:
                        return "INSTAGRAM_SHOPPING_ADD_OFFER";
                    case 2839:
                        return "INSTAGRAM_SHOPPING_SHOPNET_SUGGESTED_PRODUCTS_TTI";
                    case 3183:
                        return "INSTAGRAM_SHOPPING_PRODUCT_TAG_VISUAL_SEARCH";
                    case 3399:
                        return "INSTAGRAM_SHOPPING_VS_SUGGESTED_PRODUCTS_TTI";
                    case 3433:
                        return "INSTAGRAM_SHOPPING_TAG_PRODUCT_SEARCH_TTI";
                    case 3552:
                        return "INSTAGRAM_SHOPPING_PRODUCT_TAG_ROW_RACE_CONDITION";
                    case 3631:
                        return "INSTAGRAM_SHOPPING_PAYMENT_METHOD_LOAD";
                    case 4766:
                        return "INSTAGRAM_SHOPPING_OPEN_SHOPPING_SEARCH";
                    case 4769:
                        return "INSTAGRAM_SHOPPING_ADD_CREDIT_CARD_LOAD";
                    case 5360:
                        return "INSTAGRAM_SHOPPING_PRODUCT_TAG_VISUAL_SEARCH_DIALOG";
                    case 5613:
                        return "INSTAGRAM_SHOPPING_OFFER_LOAD";
                    case 5761:
                        return "INSTAGRAM_SHOPPING_INDEX_CART_TTI";
                    case 6386:
                        return "INSTAGRAM_SHOPPING_SAVE_OFFER";
                    case 6950:
                        return "INSTAGRAM_SHOPPING_MERCHANT_CART_TTI";
                    case 6971:
                        return "INSTAGRAM_SHOPPING_SHOPPING_ACTIVITY_FEED_LOAD";
                    case 7130:
                        return "INSTAGRAM_SHOPPING_VS_SUGGESTED_PRODUCTS_LOAD";
                    case 7647:
                        return "INSTAGRAM_SHOPPING_CHECKOUT_ASYNC_LOAD_NUX";
                    case 7899:
                        return "INSTAGRAM_SHOPPING_OPEN_CART";
                    case 7982:
                        return "INSTAGRAM_SHOPPING_TEXT_SEARCH_TTI";
                    case 8670:
                        return "INSTAGRAM_SHOPPING_CHECKOUT_ASYNC_LOAD_PUX";
                    case 9020:
                        return "INSTAGRAM_SHOPPING_VIEW_SHOPPING_ACTIVITY_FEED";
                    case 9405:
                        return "INSTAGRAM_SHOPPING_ADD_CREDIT_CARD_SAVE";
                    case 9472:
                        return "INSTAGRAM_SHOPPING_PDP_2ND_PAGE_RENDER_TIME";
                    case 9638:
                        return "INSTAGRAM_SHOPPING_PLACE_ORDER";
                    case 9828:
                        return "INSTAGRAM_SHOPPING_OPEN_SHOP_HOME";
                    case 10082:
                        return "INSTAGRAM_SHOPPING_SHOPPING_MEDIA_HALF_SHEET_LOAD";
                    case 10257:
                        return "INSTAGRAM_SHOPPING_ADD_EDIT_SHIPPING_ADDRESS_LOAD";
                    case 10339:
                        return "INSTAGRAM_SHOPPING_VIEW_SUBDESTINATION";
                    case 11017:
                        return "INSTAGRAM_SHOPPING_SHOPIFY_SDK_UNEXPECTED_ERROR";
                    case 12133:
                        return "INSTAGRAM_SHOPPING_SHOPPING_CONSUMPTION_FLOW";
                    case 12162:
                        return "INSTAGRAM_SHOPPING_VIEW_WISHLIST";
                    case 12224:
                        return "INSTAGRAM_SHOPPING_VIEW_PDP";
                    case 12450:
                        return "INSTAGRAM_SHOPPING_ADD_PAYPAL";
                    case 12739:
                        return "INSTAGRAM_SHOPPING_QUEUE_LOAD";
                    case 12812:
                        return "INSTAGRAM_SHOPPING_SHIPPING_INFO_LOAD";
                    case 13465:
                        return "INSTAGRAM_SHOPPING_PDP_TAIL_LOAD";
                    case 13640:
                        return "INSTAGRAM_SHOPPING_ADD_SHOP_PAY";
                    case 13760:
                        return "INSTAGRAM_SHOPPING_SIZE_GUIDE";
                    case 14103:
                        return "INSTAGRAM_SHOPPING_CHECKOUT_NUX_TO_PUX_TTI";
                    case 14162:
                        return "INSTAGRAM_SHOPPING_TAG_PRODUCT_TTI";
                    case 14560:
                        return "INSTAGRAM_SHOPPING_CONTINUE_SHOPPING_TTI";
                    case 14772:
                        return "INSTAGRAM_SHOPPING_SHOPPING_MEDIA_HALF_SHEET_TTI";
                    case 15047:
                        return "INSTAGRAM_SHOPPING_SHOPNET_SUGGESTED_PRODUCTS_LOAD";
                    case 15452:
                        return "INSTAGRAM_SHOPPING_ADD_EDIT_SHIPPING_ADDRESS_SAVE";
                    case 15631:
                        return "INSTAGRAM_SHOPPING_SHIPPING_INFO_SAVE";
                    case 15887:
                        return "INSTAGRAM_SHOPPING_EXPLORE_PIVOTS";
                    case 15943:
                        return "INSTAGRAM_SHOPPING_TAG_PRODUCT";
                    case 15997:
                        return "INSTAGRAM_SHOPPING_VIEW_RECONSIDERATION";
                    case 24436:
                        return "INSTAGRAM_SHOPPING_SHOPPING_ACTIVITY_FEED_TTI";
                    case 28187:
                        return "INSTAGRAM_SHOPPING_SHOPPING_ONBOARDING_BLOKS_ENTRY_PERF";
                    default:
                        return "UNDEFINED_QPL_EVENT";
                }
        }
    }
}
