package X;

/* JADX INFO: renamed from: X.4mT, reason: invalid class name and case insensitive filesystem */
/* JADX INFO: loaded from: classes4.dex */
public abstract class AbstractC104124mT {
    public static String A00(int i) {
        switch (i) {
            case 1106:
                return "FB_HORIZON_USER_CARD_LOAD";
            case 1172:
                return "FB_HORIZON_MEDIA_SHARE_TO_FB_FEED";
            case 1258:
                return "FB_HORIZON_SHARING_FB_STORIES";
            case 1279:
                return "FB_HORIZON_LLM_REGISTRATION";
            case 1350:
                return "FB_HORIZON_HOMEWORLD_PERSISTENCE_TEXTURE_LOADING";
            case 1521:
                return "FB_HORIZON_SHARING_PHOTO_UPLOAD";
            case 1703:
                return "FB_HORIZON_SOCIAL_PANEL_FOLLOWING_LIST_LOAD";
            case 1757:
                return "FB_HORIZON_SUGGESTED_WORLDS_LOAD";
            case 2029:
                return "FB_HORIZON_CANT_MISS_EVENTS_LOAD";
            case 2044:
                return "FB_HORIZON_DECLINE_PARTY_INVITE";
            case 2289:
                return "FB_HORIZON_LLM_SESSION_RESET";
            case 2435:
                return "FB_HORIZON_HOMEWORLD_PERSISTENCE_OBJECT_LOADING";
            case 2441:
                return "FB_HORIZON_HORIZON_CUSTOM_UI_BINDING_UPDATE";
            case 2444:
                return "FB_HORIZON_SVR_ACTIVITY_INIT";
            case 2533:
                return "FB_HORIZON_ASSET_SPAWN";
            case 2666:
                return "FB_HORIZON_LLM_SPEAKING";
            case 2828:
                return "FB_HORIZON_PARTY_GAMES_LOAD";
            case 2830:
                return "FB_HORIZON_PEOPLE_SEARCH";
            case 2835:
                return "FB_HORIZON_HANGOUT_LOAD";
            case 2952:
                return "FB_HORIZON_WORLD_DETAIL_PAGE_SIMILAR_WORLDS_SHELF";
            case 3098:
                return "FB_HORIZON_PHOTO_BOARD_INSTANTIATE";
            case 3119:
                return "FB_HORIZON_WORLD_POST_GALLERY_LOAD";
            case 3294:
                return "FB_HORIZON_FRIENDS_ACTIVE_LOAD";
            case 3549:
                return "FB_HORIZON_PEOPLE_TAB_LOAD";
            case 3600:
                return "FB_HORIZON_HOMEWORLD_FETCH_PERSISTENCE";
            case 3665:
                return "FB_HORIZON_SVR_ACTIVITY_HSR_CENTRAL";
            case 3686:
                return "FB_HORIZON_HORIZON_CUSTOM_UI_MODEL_UPDATE";
            case 3903:
                return "FB_HORIZON_MEDIA_SHARE_TO_FB_REELS";
            case 4036:
                return "FB_HORIZON_PEOPLE_FOLLOWERS_TAB_ALL_LOAD";
            case 4051:
                return "FB_HORIZON_FEATURED_PUI_OPEN_E2E";
            case 4182:
                return "FB_HORIZON_ACCEPT_PARTY_INVITE";
            case 4307:
                return "FB_HORIZON_NEW_WORLDS_TOP_CREATORS_LOAD";
            case 4358:
                return "FB_HORIZON_INTEGRITY_REC2VIDEO_GENERATION";
            case 4361:
                return "FB_HORIZON_USER_PRESENCE_ONLINE_STATUS_TEXT";
            case 4914:
                return "FB_HORIZON_IDENTITY_PANEL_LOAD";
            case 4992:
                return "FB_HORIZON_IWP_JETPACK_ITEM_PURCHASE";
            case 4994:
                return "FB_HORIZON_SVR_DEVICECONFIG_INIT";
            case 5005:
                return "FB_HORIZON_SVR_VR_ACCOUNT_MANAGER";
            case 5036:
                return "FB_HORIZON_HOMEWORLD_PICTURE_FRAME_GAME_OBJECT_LOADING";
            case 5193:
                return "FB_HORIZON_PEOPLE_FOLLOWING_TAB_ALL_LOAD";
            case 5337:
                return "FB_HORIZON_SEARCH_RESULT_LOAD";
            case 5399:
                return "FB_HORIZON_CREATOR_RULES_GAME_OBJECT_LOADING";
            case 5448:
                return "FB_HORIZON_JOIN_PARTY_FROM_INVITE";
            case 5529:
                return "FB_HORIZON_PUI_OPEN";
            case 5889:
                return "FB_HORIZON_POST_DETAIL_PAGE_LOAD";
            case 6045:
                return "FB_HORIZON_PLAYER_PET_ASSET_LOAD";
            case 6161:
                return "FB_HORIZON_LLM_LISTENING";
            case 6255:
                return "FB_HORIZON_PARTICLE_FX_LOAD";
            case 6492:
                return "FB_HORIZON_NEW_TRENDING_LOAD";
            case 6777:
                return "FB_HORIZON_HOMEWORLD_PICTURE_FRAME_PERSONALIZATION_LOADING";
            case 6811:
                return "FB_HORIZON_WORLD_DETAIL_LOAD";
            case 6902:
                return "FB_HORIZON_VOIP_WORLD_JOIN";
            case 7179:
                return "FB_HORIZON_SHARING_VIDEO_UPLOAD";
            case 7274:
                return "FB_HORIZON_PVP_FEED_LOAD";
            case 7292:
                return "FB_HORIZON_CONNECT_TO_PARTY_VOIP";
            case 7635:
                return "FB_HORIZON_WORLD_DETAIL_POST_SECTION_LOAD";
            case 7737:
                return "FB_HORIZON_WORLD_TAB_LEADERBOARD_LOAD";
            case 7897:
                return "FB_HORIZON_WORLD_TAB_OPEN_E2E";
            case 7946:
                return "FB_HORIZON_SERVICE_GRAPH_LOAD";
            case 8095:
                return "FB_HORIZON_FEATURED_EVENTS_LOAD";
            case 8167:
                return "FB_HORIZON_NUX_ASSET_DOWNLOAD";
            case 8248:
                return "FB_HORIZON_PEOPLE_TAB_ALL_LOAD";
            case 8472:
                return "FB_HORIZON_PROFILE_PANEL_LOAD";
            case 8500:
                return "FB_HORIZON_EXPLORATION_ONLY_LOAD";
            case 8674:
                return "FB_HORIZON_LINK_SHARE_TO_FB_GROUPS";
            case 8884:
                return "FB_HORIZON_WELCOME_BOARD_LOAD";
            case 8914:
                return "FB_HORIZON_LOADING_SCREEN";
            case 8941:
                return "FB_HORIZON_VOIP_EVENTS";
            case 8947:
                return "FB_HORIZON_PUI_OPEN_NATIVE";
            case 9201:
                return "FB_HORIZON_VENUES_DOOR_SET_DATA";
            case 9234:
                return "FB_HORIZON_WORLD_TAB_DAY_ZERO_LOAD";
            case 9262:
                return "FB_HORIZON_GLOBAL_NAV_LOAD";
            case 9404:
                return "FB_HORIZON_APP_LOAD";
            case 9784:
                return "FB_HORIZON_EDIT_MODE_ENTITY_PROPERTY_EDIT";
            case 10214:
                return "FB_HORIZON_SHARING_REELS_SAVE_DRAFTS";
            case 10377:
                return "FB_HORIZON_VSDK_VOICE_SERVICE_REQUEST";
            case 10396:
                return "FB_HORIZON_LEAVE_HW_PARTY";
            case 10591:
                return "FB_HORIZON_LINK_SHARE_TO_MESSENGER";
            case 10619:
                return "FB_HORIZON_ASSET_LIBRARY";
            case 10655:
                return "FB_HORIZON_WORLD_NAVIGATION";
            case 10710:
                return "FB_HORIZON_MEDIA_CAROUSEL_LOAD";
            case 10750:
                return "FB_HORIZON_PEOPLE_FOLLOWERS_TAB_LOAD";
            case 10816:
                return "FB_HORIZON_IWP_ENTITLEMENT";
            case 10886:
                return "FB_HORIZON_USER_PRESENCE_ONLINE_STATUS";
            case 11378:
                return "FB_HORIZON_FEATURE_LAOD";
            case 11396:
                return "FB_HORIZON_PVE_FEED_LOAD";
            case 11424:
                return "FB_HORIZON_FRIENDS_ACTIVITY_LOAD";
            case 11604:
                return "FB_HORIZON_WORLD_TAB_FOR_YOU_LOAD";
            case 11666:
                return "FB_HORIZON_NOESIS_UI_RENDERING";
            case 11712:
                return "FB_HORIZON_CANCEL_PARTY_INVITE";
            case 11713:
                return "FB_HORIZON_QUESTS_IN_WORLD_DETAILS";
            case 11962:
                return "FB_HORIZON_MEDIA_SHARE_TO_FB_GROUPS";
            case 12040:
                return "FB_HORIZON_ART_FEED_LOAD";
            case 12288:
                return "FB_HORIZON_PEOPLE_DISCOVER_TAB_LOAD";
            case 12362:
                return "FB_HORIZON_LINK_SHARE_TO_FB_FEED";
            case 12535:
                return "FB_HORIZON_SHARING_IG_STORIES";
            case 12620:
                return "FB_HORIZON_WORLD_TAB_JOIN_NOW_LOAD";
            case 12879:
                return "FB_HORIZON_LINK_SHARING_GENERATE";
            case 13029:
                return "FB_HORIZON_CONNECT_TO_PARTY_VOIP_VERTS";
            case 13064:
                return "FB_HORIZON_PEOPLE_DISCOVER_TAB_ALL_LOAD";
            case 13072:
                return "FB_HORIZON_LLM_ON_PARTIAL_RESPONSE";
            case 13702:
                return "FB_HORIZON_INSTANCES_INVITED_LOAD";
            case 13723:
                return "FB_HORIZON_MEDIA_SHARE_TO_HZ_WORLDS";
            case 13853:
                return "FB_HORIZON_IWP_ITEM_PURCHASE";
            case 13858:
                return "FB_HORIZON_PEOPLE_NEARBY_SHELF_LOAD";
            case 13892:
                return "FB_HORIZON_HORIZON_CUSTOM_UI_RENDERING";
            case 14123:
                return "FB_HORIZON_MIXED_CONTENT_LOAD";
            case 14171:
                return "FB_HORIZON_VOIP_WORLD_LEAVE";
            case 14186:
                return "FB_HORIZON_PROFILE_PANEL_2_LOAD";
            case 14282:
                return "FB_HORIZON_WEARABLE_PANEL_OPEN";
            case 14427:
                return "FB_HORIZON_SUGGESTED_WORLDS_HANG_OUT_LOAD";
            case 14487:
                return "FB_HORIZON_FEATURED_GAMES_LOAD";
            case 14734:
                return "FB_HORIZON_REACT_BUNDLE_LOAD";
            case 14762:
                return "FB_HORIZON_MESSAGING_OVERLAY_LOAD";
            case 14779:
                return "FB_HORIZON_PUZZLE_LOAD";
            case 14788:
                return "FB_HORIZON_FEATURED_PUI_PRE_OPEN";
            case 14819:
                return "FB_HORIZON_QUEST_PUI_PANEL_LEFT_PANE";
            case 14836:
                return "FB_HORIZON_EXPLORATION_LOAD";
            case 14854:
                return "FB_HORIZON_SEND_PARTY_INVITE";
            case 14916:
                return "FB_HORIZON_SHARING_VIDEO_PLAYBACK";
            case 15297:
                return "FB_HORIZON_ASSET_FETCH";
            case 15473:
                return "FB_HORIZON_SCENE_TRANSITION_MANAGER";
            case 15627:
                return "FB_HORIZON_IWP_ITEM_CREATION";
            case 15700:
                return "FB_HORIZON_QUEST_PUI_PANEL_COMPONENT";
            case 15865:
                return "FB_HORIZON_PERSISTENT_VARIABLES_LOAD";
            case 15873:
                return "FB_HORIZON_INTEGRITY_REC2VIDEO_LAUNCH";
            case 15945:
                return "FB_HORIZON_JOIN_PARTY_FROM_GESTURE";
            case 16091:
                return "FB_HORIZON_SAVE_SNAPSHOT_TO_DISK";
            case 16211:
                return "FB_HORIZON_WEARABLE_UI";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
