package X;

/* JADX INFO: renamed from: X.4pX, reason: invalid class name and case insensitive filesystem */
/* JADX INFO: loaded from: classes4.dex */
public abstract class AbstractC105984pX {
    public static String A00(int i) {
        switch (i) {
            case 1075:
                return "IG_BRAND_EXPERIENCE_QP_DIRECT_THREAD_LOADED";
            case 1188:
                return "IG_BRAND_EXPERIENCE_QP_POST_CREATED";
            case 1241:
                return "IG_BRAND_EXPERIENCE_QP_ACCOUNT_INSIGHTS_HEADER";
            case 1276:
                return "IG_BRAND_EXPERIENCE_QP_CLOSE_FRIENDS_HEADER";
            case 1411:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_STORY_INSIGHTS_HEADER";
            case 1449:
                return "IG_BRAND_EXPERIENCE_QP_LIVE_VIEWER_BADGES_CTA_TOOLTIP";
            case 1516:
                return "IG_BRAND_EXPERIENCE_QP_SHOPPING_SAVE_DIRECTORY_TOOLTIP";
            case 1526:
                return "IG_BRAND_EXPERIENCE_QP_PROFILE_OTHER_CHECKOUT_TOOLTIP";
            case 1730:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_ADD_YOURS_PIVOT_PAGE_CREATOR_ENTRY_MEGAPHONE";
            case 2064:
                return "IG_BRAND_EXPERIENCE_QP_PROFILE_OTHER_PROMPT";
            case 2400:
                return "IG_BRAND_EXPERIENCE_IG_BRANDED_CONTENT_AND_SHOPPING_ACTIVITY_FEED_HEADER";
            case 2529:
                return "IG_BRAND_EXPERIENCE_QP_LIVE_SHOPPING_TOOLTIP";
            case 2735:
                return "IG_BRAND_EXPERIENCE_QP_BRANDED_CONTENT_DISCLOSURE_FLOW_LOADED";
            case 2737:
                return "IG_BRAND_EXPERIENCE_QP_PROFILE_TOOLTIP";
            case 2766:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_EXPLORE_TOOLTIP";
            case 2771:
                return "IG_BRAND_EXPERIENCE_QP_SHOPPING_PRODUCT_PICKER_LOADED";
            case 2866:
                return "IG_BRAND_EXPERIENCE_QP_SUBSCRIPTION_SETTINGS_LOADED";
            case 2989:
                return "IG_BRAND_EXPERIENCE_QP_STORY_VIEW_FUNDRAISER_STICKER_TOOLTIP";
            case 3416:
                return "IG_BRAND_EXPERIENCE_QP_FEED_SHARING_PROMPT";
            case 3528:
                return "IG_BRAND_EXPERIENCE_QP_FEED_PROMPT";
            case 3675:
                return "IG_BRAND_EXPERIENCE_QP_OTHER_PROFILE_PAGE_PROMPT";
            case 3868:
                return "IG_BRAND_EXPERIENCE_QP_VIDEO_CALL_LOADED";
            case 3878:
                return "IG_BRAND_EXPERIENCE_QP_INBOX_CLOSE_FRIENDS_FILTER_APPLIED";
            case 3982:
                return "IG_BRAND_EXPERIENCE_QP_SHOPPING_PDP_BANNER_PROMPT";
            case 4115:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_SELF_PROFILE_PAGE_CREATOR_INVITE_MEGAPHONE";
            case 4213:
                return "IG_BRAND_EXPERIENCE_QP_COMMENT_POSTED";
            case 4381:
                return "IG_BRAND_EXPERIENCE_QP_SHOPPING_BUY_ON_INSTAGRAM_HEADER";
            case 4450:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_SEARCH_META_AI_BOTTOMSHEET_LOADED";
            case 4749:
                return "IG_BRAND_EXPERIENCE_QP_PROFESSIONAL_SETTING_TOOLTIP";
            case 4984:
                return "IG_BRAND_EXPERIENCE_QP_EDIT_PROFILE";
            case 5921:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_SHOPPING_PRODUCT_DETAILS_LOADED";
            case 6029:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_STORIES_AUDIO_BROWSER_HEADER";
            case 6095:
                return "IG_BRAND_EXPERIENCE_QP_BRANDED_CONTENT_SETTINGS_LOADED";
            case 6213:
                return "IG_BRAND_EXPERIENCE_QP_FEED_PROMOTE_CTA_TOOLTIP";
            case 6254:
                return "IG_BRAND_EXPERIENCE_QP_FEED_TOOLTIP";
            case 6382:
                return "IG_BRAND_EXPERIENCE_QP_THREAD_LOADED";
            case 6403:
                return "IG_BRAND_EXPERIENCE_QP_PROFILE_PROMPT";
            case 6591:
                return "IG_BRAND_EXPERIENCE_QP_FEED_SHARING_HEADER";
            case 6679:
                return "IG_BRAND_EXPERIENCE_QP_LIVE_ROOMS_TOOLTIP";
            case 6720:
                return "IG_BRAND_EXPERIENCE_QP_SHARE_TO_FB_SWITCHED_OFF";
            case 6905:
                return "IG_BRAND_EXPERIENCE_QP_PROFILE_FLOATING_BANNER_PROMPT";
            case 7059:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_MEDIA_GALLERY";
            case 7087:
                return "IG_BRAND_EXPERIENCE_QP_EDIT_HIGHLIGHT_MEGAPHONE";
            case 7187:
                return "IG_BRAND_EXPERIENCE_QP_SURVEY";
            case 7496:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_EXPLORE_2X2_GRID_LOADED";
            case 7500:
                return "IG_BRAND_EXPERIENCE_QP_SHARE_POST_LOADED";
            case 7823:
                return "IG_BRAND_EXPERIENCE_QP_IGTV_VIEWER_PROMPT";
            case 7871:
                return "IG_BRAND_EXPERIENCE_QP_FEED_BOTTOMSHEET";
            case 7893:
                return "IG_BRAND_EXPERIENCE_QP_INBOX_LOW_BOTTOMSHEET";
            case 8154:
                return "IG_BRAND_EXPERIENCE_QP_SHARE_TO_FB_SWITCHED_ON";
            case 8216:
                return "IG_BRAND_EXPERIENCE_QP_SELF_REEL_VIEW";
            case 8469:
                return "IG_BRAND_EXPERIENCE_QP_SHOPPING_PDP_HEADER";
            case 8775:
                return "IG_BRAND_EXPERIENCE_QP_INBOX_HEADER";
            case 8810:
                return "IG_BRAND_EXPERIENCE_QP_PROFILE_OTHER_TOOLTIP";
            case 9014:
                return "IG_BRAND_EXPERIENCE_QP_ACTIVITY_FEED_PROMPT";
            case 9094:
                return "IG_BRAND_EXPERIENCE_QP_SHARE_COLLECTION_BUTTON_LOADED";
            case 9135:
                return "IG_BRAND_EXPERIENCE_QP_FOLLOW_REQUEST_SCREEN_MEGAPHONE";
            case 9141:
                return "IG_BRAND_EXPERIENCE_QP_SELF_FOLLOWERS_LIST_SCREEN_MEGAPHONE";
            case 9338:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_ADD_YOURS_PIVOT_PAGE_CONSUMER_ENTRY_MEGAPHONE";
            case 9356:
                return "IG_BRAND_EXPERIENCE_QP_SHOPPING_STORY_POSTED";
            case 9454:
                return "IG_BRAND_EXPERIENCE_QP_REEL_CREATED";
            case 9586:
                return "IG_BRAND_EXPERIENCE_QP_NAVIGATION_TOOLTIP";
            case 9642:
                return "IG_BRAND_EXPERIENCE_QP_FEED_COMPOSER_PROMPT";
            case 9713:
                return "IG_BRAND_EXPERIENCE_QP_QUICK_PROMOTION_TEST";
            case 9715:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_AUD_SHARING_BOTTOMSHEET_LOW";
            case 9736:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_PENDING_INBOX_RANKING_DROPDOWN_TOOLTIP";
            case 9803:
                return "IG_BRAND_EXPERIENCE_QP_FEATURED_PRODUCT_MEDIA_TOOLTIP";
            case 9965:
                return "IG_BRAND_EXPERIENCE_QP_IGTV_DISCOVER_HEADER";
            case 10392:
                return "IG_BRAND_EXPERIENCE_QP_PROFILE_CLIPS_SUBTAB_TOOLTIP";
            case 10398:
                return "IG_BRAND_EXPERIENCE_QP_INBOX_HIGH_BOTTOMSHEET";
            case 10451:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_NOTES_AUDIO_BROWSER_HEADER";
            case 10668:
                return "IG_BRAND_EXPERIENCE_QP_SETTINGS_PAGE_PROMPT";
            case 10697:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_PROFILE_RESTRICTED";
            case 10731:
                return "IG_BRAND_EXPERIENCE_QP_INBOX_PROMPT";
            case 10753:
                return "IG_BRAND_EXPERIENCE_QP_PROFILE_HEADER";
            case 10820:
                return "IG_BRAND_EXPERIENCE_QP_LOCATION_PAGE_INFO_LOADED";
            case 10836:
                return "IG_BRAND_EXPERIENCE_QP_APP_FOREGROUND";
            case 10917:
                return "IG_BRAND_EXPERIENCE_QP_IN_THREAD_MESSAGE_FOOTER";
            case 11002:
                return "IG_BRAND_EXPERIENCE_QP_MESSAGE_REQUEST_ACTION_DIALOG";
            case 11032:
                return "IG_BRAND_EXPERIENCE_QP_SAVE_HOME_LOADED";
            case 11259:
                return "IG_BRAND_EXPERIENCE_QP_IG_COMMENT_SHEET_OPEN";
            case 11500:
                return "IG_BRAND_EXPERIENCE_QP_LIVE_COMPOSE";
            case 11502:
                return "IG_BRAND_EXPERIENCE_QP_VIDEO_CALL_PEEK_PROMO_PROMPT";
            case 11550:
                return "IG_BRAND_EXPERIENCE_QP_FEED_HEADER";
            case 11764:
                return "IG_BRAND_EXPERIENCE_QP_BRANDED_CONTENT_STORY_SHARED";
            case 11792:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_MUSIC_IN_FEED_AUDIO_BROWSER_HEADER";
            case 11848:
                return "IG_BRAND_EXPERIENCE_QP_PROFILE_FOLLOW_BUTTON_CLICKED";
            case 11853:
                return "IG_BRAND_EXPERIENCE_QP_LIVE_BADGES_TOOLTIP";
            case 12007:
                return "IG_BRAND_EXPERIENCE_QP_PROFILE_OTHER_HEADER";
            case 12417:
                return "IG_BRAND_EXPERIENCE_QP_LOGGED_IN_USER_ID_LOADED";
            case 12586:
                return "IG_BRAND_EXPERIENCE_QP_FEED_COMMENT_HEADER";
            case 12635:
                return "IG_BRAND_EXPERIENCE_QP_STORY_CREATION";
            case 12698:
                return "IG_BRAND_EXPERIENCE_QP_STORY_VIEWER_PROMOTE_CTA_TOOLTIP";
            case 12818:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_STORY_AUDIO_BROWSER_HEADER";
            case 12833:
                return "IG_BRAND_EXPERIENCE_QP_INBOX_FILTER_TOOLTIP";
            case 13276:
                return "IG_BRAND_EXPERIENCE_QP_INBOX_TOOLTIP";
            case 13391:
                return "IG_BRAND_EXPERIENCE_QP_IN_THREAD_MESSAGE_FOOTER_DOUBLE_TAP_TO_HEART";
            case 13570:
                return "IG_BRAND_EXPERIENCE_QP_ACTIVITY_FEED_HEADER";
            case 13807:
                return "IG_BRAND_EXPERIENCE_QP_CLIPS_CREATION_SHARE_SHEET_LOADED";
            case 13826:
                return "IG_BRAND_EXPERIENCE_QP_PROFILE_PAGE_PROMPT";
            case 13881:
                return "IG_BRAND_EXPERIENCE_QP_HASHTAG_FEED_TOOLTIP";
            case 13988:
                return "IG_BRAND_EXPERIENCE_QP_FEATURED_PRODUCT_MEDIA_INTERSTITIAL";
            case 14015:
                return "IG_BRAND_EXPERIENCE_QP_STORY_CREATED";
            case 14120:
                return "IG_BRAND_EXPERIENCE_IG_QP_SURFACE_MEGAPHONE";
            case 14324:
                return "IG_BRAND_EXPERIENCE_QP_EXPLORE_PROMPT";
            case 14326:
                return "IG_BRAND_EXPERIENCE_QP_FEED_BANNER";
            case 14349:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_PENDING_INBOX_HEADER";
            case 14439:
                return "IG_BRAND_EXPERIENCE_QP_PROFILE_PAGE";
            case 14825:
                return "IG_BRAND_EXPERIENCE_QP_LIVE_BROADCASTER_SHOPPING_TOOLTIP";
            case 14906:
                return "IG_BRAND_EXPERIENCE_QP_DIRECT_STICKER_TRAY_HEADER";
            case 14934:
                return "IG_BRAND_EXPERIENCE_QP_SESSION_START";
            case 14949:
                return "IG_BRAND_EXPERIENCE_QP_EXPLORE_HEADER";
            case 15033:
                return "IG_BRAND_EXPERIENCE_QP_ARCHIVE_MEGAPHONE";
            case 15178:
                return "IG_BRAND_EXPERIENCE_QP_AUDIO_PAGE_ENTRY_HEADER";
            case 15206:
                return "IG_BRAND_EXPERIENCE_QP_ACTIVITY_FEED_TOOLTIP";
            case 15239:
                return "IG_BRAND_EXPERIENCE_QP_ACCOUNT_SETTING_TOOLTIP";
            case 15585:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_REELS_MIDCARD_LOADED";
            case 15792:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_REELS_AUDIO_BROWSER_HEADER";
            case 15856:
                return "IG_BRAND_EXPERIENCE_QP_LIVE_ROOMS_INTERSTITIAL";
            case 15867:
                return "IG_BRAND_EXPERIENCE_QP_CLIPS_VIEWER_FRIEND_LANE_OPEN";
            case 15934:
                return "IG_BRAND_EXPERIENCE_QP_INBOX_SEARCH_HEADER";
            case 16195:
                return "IG_BRAND_EXPERIENCE_QP_INSTAGRAM_AUD_STORY_REPLIES_BOTTOMSHEET_LOW";
            case 16284:
                return "IG_BRAND_EXPERIENCE_QP_CLIPS_VIEWER_LOADED";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
