package X;

/* JADX INFO: renamed from: X.4s5, reason: invalid class name and case insensitive filesystem */
/* JADX INFO: loaded from: classes4.dex */
public abstract class AbstractC107564s5 {
    public static String A00(int i) {
        switch (i) {
            case 1:
                return "MARKETPLACE_RELAY";
            case 5:
                return "MARKETPLACE_RELAY_MUTATION";
            case 8:
                return "MARKETPLACE_FEED_IMAGE_LOAD";
            case 9:
                return "MARKETPLACE_HOME_TTI";
            case 11:
                return "MARKETPLACE_SEARCH_RESULT_TTI";
            case 13:
                return "MARKETPLACE_SHOPS_TTI";
            case 14:
                return "MARKETPLACE_HOME_LOAD";
            case 15:
                return "MARKETPLACE_DAILY_DEALS_TTI";
            case 16:
                return "MARKETPLACE_SEARCH_NULLSTATE_TTI";
            case 20:
                return "MARKETPLACE_COMPOSER_POST_TTI";
            case 21:
                return "MARKETPLACE_B2C_PRODUCT_DETAILS";
            case 23:
                return "MARKETPLACE_RENTAL_MAP_VIEW_TTI_MOBILE";
            case 25:
                return "MARKETPLACE_COMPOSER_EDIT_TTI";
            case 28:
                return "MARKETPLACE_AUTOS_TTI";
            case 31:
                return "MARKETPLACE_MARKETPLACE_NOTIFICATIONS_TTI";
            case 34:
                return "MARKETPLACE_COMPOSER_TTI";
            case 35:
                return "MARKETPLACE_EDIT_COMPOSER_TTI";
            case 37:
                return "MARKETPLACE_FOLLOWING_INFORMATION_TTI";
            case 40:
                return "MARKETPLACE_FOLLOWING_TTI";
            case 41:
                return "MARKETPLACE_INBOX_TTI";
            case 47:
                return "MARKETPLACE_SAVED_ITEMS_TTI";
            case 49:
                return "MARKETPLACE_SELLER_FOLLOWER_TTI";
            case 51:
                return "MARKETPLACE_SAVED_LIST_ITEMS_TTI";
            case 52:
                return "MARKETPLACE_INITIAL_MESSAGING_TTI";
            case 53:
                return "MARKETPLACE_MESSAGING_TTI";
            case 55:
                return "MARKETPLACE_PROFILE_TTI";
            case 56:
                return "MARKETPLACE_BUY_SELL_GROUP_HOME_TTI";
            case 57:
                return "MARKETPLACE_FILTERED_CATEGORY_SEARCH_TTI";
            case 61:
                return "MARKETPLACE_PROPERTY_FOR_SALE_TTI";
            case 62:
                return "MARKETPLACE_PROPERTY_FOR_RENT_TTI";
            case 64:
                return "MARKETPLACE_HOME_TTRC";
            case 67:
                return "MARKETPLACE_HOME_PAGINATION_TTI";
            case 68:
                return "MARKETPLACE_SEARCH_PAGINATION_TTI";
            case 71:
                return "MARKETPLACE_SEARCH_RESULT_TTRC";
            case 78:
                return "MARKETPLACE_ECOMM_UNIFIED_LANDING_TTI";
            case 86:
                return "MARKETPLACE_FILTERS_TTI";
            case 92:
                return "MARKETPLACE_YOU_TTRC";
            case 93:
                return "MARKETPLACE_UNIFIED_INVENTORY_TTRC";
            case BmJ.SHARED_DEVICE_ALLOWLIST_ACTION_FIELD_NUMBER /* 94 */:
                return "MARKETPLACE_COMMERCE_PROFILE_TTRC";
            case BmJ.CONTACT_MANAGER_METADATA_ACTION_FIELD_NUMBER /* 95 */:
                return "MARKETPLACE_SELLER_INSIGHTS_TTRC";
            case C26698BmO.STATUS_NOTIFICATION_MESSAGE_FIELD_NUMBER /* 98 */:
                return "MARKETPLACE_ECOMM_HOME_TTRC";
            case C26698BmO.MESSAGE_HISTORY_NOTICE_FIELD_NUMBER /* 102 */:
                return "MARKETPLACE_PDP_TTRC";
            case 1710:
                return "MARKETPLACE_MP_JOBS_COMPOSER_TTRC";
            case 2220:
                return "MARKETPLACE_LOCAL_PAGINATION_ADS_HEAD_LOAD_WWW_GRAPHQL";
            case 2489:
                return "MARKETPLACE_LOCAL_PAGINATION_BOOSTED_LISTING_ADS_HEAD_LOAD_WWW_GRAPHQL";
            case 2769:
                return "MARKETPLACE_HOME_PAGINATION_TAIL_LOAD_WWW_GRAPHQL";
            case 2793:
                return "MARKETPLACE_SEARCH_PAGINATION_FCRT";
            case 2802:
                return "MARKETPLACE_STRUCTURED_COMPOSER_POST_FAILURE";
            case 2899:
                return "MARKETPLACE_HOME_PAGINATION_ADS_THEMED_HEAD_LOAD_WWW_GRAPHQL";
            case 3441:
                return "MARKETPLACE_HOMEFEED_FIRST_SCROLL";
            case 3545:
                return "MARKETPLACE_MARKETPLACE_JOBS_SUBTAB_TTRC";
            case 3572:
                return "MARKETPLACE_ORDER_MANAGEMENT";
            case 3674:
                return "MARKETPLACE_HOME_TTRC_FIRE_DRILL";
            case 3751:
                return "MARKETPLACE_LOCAL_PAGINATION_HEAD_LOAD_WWW_GRAPHQL_V2";
            case 3912:
                return "MARKETPLACE_HOME_LIGHTNING_FEED_WWW_GRAPHQL";
            case 4095:
                return "MARKETPLACE_HOME_PAGINATION_THEMED_TAIL_LOAD_WWW_GRAPHQL";
            case 4102:
                return "MARKETPLACE_LOCAL_HOME_TTRC";
            case 4209:
                return "MARKETPLACE_HOME_PAGINATION_BOOSTED_LISTING_ADS_HEAD_LOAD_WWW_GRAPHQL";
            case 4870:
                return "MARKETPLACE_HOME_PAGINATION_ADS_THEMED_TAIL_LOAD_WWW_GRAPHQL";
            case 5013:
                return "MARKETPLACE_STRUCTURED_COMPOSER_POST_DISCARD";
            case 5099:
                return "MARKETPLACE_HOME_AUTO_REFRESH_TTRC";
            case 5162:
                return "MARKETPLACE_HOME_REFRESH_TTRC";
            case 5668:
                return "MARKETPLACE_LOCAL_REFRESH_TTRC";
            case 5753:
                return "MARKETPLACE_PDP_TTRC_FIRE_DRILL";
            case 7099:
                return "MARKETPLACE_COMPOSER_TTRC";
            case 7479:
                return "MARKETPLACE_LOCAL_PAGINATION_ADS_THEMED_HEAD_LOAD_WWW_GRAPHQL";
            case 8354:
                return "MARKETPLACE_SEARCH_RESULT_WWW_GRAPHQL";
            case 9571:
                return "MARKETPLACE_BUY_SELL_GROUP_HOME_TTRC";
            case 9897:
                return "MARKETPLACE_PARTNER_SELECTOR_BOTTOMSHEET_TTRC";
            case 9981:
                return "MARKETPLACE_HOME_PAGINATION_ADS_TAIL_LOAD_WWW_GRAPHQL";
            case 10206:
                return "MARKETPLACE_LOCAL_PAGINATION_ADS_TAIL_LOAD_WWW_GRAPHQL";
            case 11177:
                return "MARKETPLACE_RELAY_FETCH";
            case 11715:
                return "MARKETPLACE_LOCAL_PAGINATION_THEMED_HEAD_LOAD_WWW_GRAPHQL";
            case 11798:
                return "MARKETPLACE_MARKETPLACE_JOBS_SUBTAB_FCRT";
            case 11960:
                return "MARKETPLACE_HOME_PAGINATION_HEAD_LOAD_WWW_GRAPHQL";
            case 12139:
                return "MARKETPLACE_PRE_MARKETPLACE_JOURNEY";
            case 12436:
                return "MARKETPLACE_MAKING_A_PURCHASE_FLOW";
            case 12748:
                return "MARKETPLACE_HOME_PAGINATION_TTRC";
            case 12954:
                return "MARKETPLACE_HOME_PAGINATION_THEMED_HEAD_LOAD_WWW_GRAPHQL";
            case 13104:
                return "MARKETPLACE_LIST_AN_ITEM_FLOW";
            case 13168:
                return "MARKETPLACE_HOME_PAGINATION_FUNNEL_LOGGING";
            case 13224:
                return "MARKETPLACE_HOME_PTR_TTRC";
            case 13761:
                return "MARKETPLACE_LOCAL_PAGINATION_BOOSTED_LISTING_ADS_TAIL_LOAD_WWW_GRAPHQL";
            case 14524:
                return "MARKETPLACE_HOME_PAGINATION_FCRT";
            case 14666:
                return "MARKETPLACE_MARKETPLACE_PDP_ADS_WWW_GRAPHQL";
            case 14890:
                return "MARKETPLACE_HOME_PAGINATION_ADS_HEAD_LOAD_WWW_GRAPHQL";
            case 15100:
                return "MARKETPLACE_LOCAL_PAGINATION_TAIL_LOAD_WWW_GRAPHQL_V2";
            case 15814:
                return "MARKETPLACE_SELLER_HUB_TTRC";
            case 16139:
                return "MARKETPLACE_HOME_PAGINATION_BOOSTED_LISTING_ADS_TAIL_LOAD_WWW_GRAPHQL";
            case 23669:
                return "MARKETPLACE_CATEGORY_FEED_TTRC";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
