package X;

/* JADX INFO: renamed from: X.4qi, reason: invalid class name and case insensitive filesystem */
/* JADX INFO: loaded from: classes4.dex */
public abstract class AbstractC106714qi {
    public static String A00(int i) {
        switch (i) {
            case 1006:
                return "TEST_NAVIGATION_DIRECT_INBOX";
            case 1017:
                return "TEST_NAVIGATION_TAGS_LIST";
            case 1057:
                return "TEST_INTERACTION_SUNDIAL_SEE_ALL_TRIALS_PAGE";
            case 1094:
                return "TEST_INTERACTION_SELF_FOLLOWING";
            case 1219:
                return "TEST_INTERACTION_USAGE_INSIGHTS_BLOCKING";
            case 1225:
                return "TEST_DWELL_CLIPS_PRECAPTURE_CAMERA";
            case 1232:
                return "TEST_NAVIGATION_SEARCH_TYPEAHEAD";
            case 1268:
                return "TEST_DWELL_REEL_MULTIEDIT_COMPOSER";
            case 1312:
                return "TEST_DWELL_FEED_CONTEXTUAL_SELF_PROFILE";
            case 1316:
                return "TEST_NAVIGATION_REEL_MULTIEDIT_COMPOSER";
            case 1334:
                return "TEST_DWELL_CLIPS_GALLERY";
            case 1348:
                return "TEST_NAVIGATION_DIRECT_AVATAR_STICKER_PICKER_GRID";
            case 1350:
                return "TEST_INTERACTION_DIRECT_INBOX";
            case 1361:
                return "TEST_NAVIGATION_DIRECT_REPLY_TO_AUTHOR";
            case 1403:
                return "TEST_NAVIGATION_ARCHIVE_STORIES";
            case 1428:
                return "TEST_DWELL_DIRECT_THREAD_DETAILS_REDESIGN";
            case 1453:
                return "TEST_INTERACTION_COMMENTS_V2_CLIPS_VIEWER_FEED_TIMELINE_MIXED_UNCONNECTED";
            case 1465:
                return "TEST_NAVIGATION_AUDIENCE_SELECTION";
            case 1519:
                return "TEST_DWELL_IG_SAVED_MEDIA_VIEW_CONTROLLER";
            case 1541:
                return "TEST_DWELL_FOANATIVE_IG_BASE_VIEW_CONTROLLER_IDENTITY_SWITCHER";
            case 1667:
                return "TEST_INTERACTION_ACTIVITY_FEED_CONTAINER";
            case 1771:
                return "TEST_NAVIGATION_STORY_EMOJI_PICKER";
            case 1799:
                return "TEST_NAVIGATION_HIGHLIGHTS_ADD_SHEET";
            case 1861:
                return "TEST_NAVIGATION_CLIPS_VIEWER_CLIPS_BLEND";
            case 1865:
                return "TEST_INTERACTION_CUSTOM_ALERT";
            case 1914:
                return "TEST_INTERACTION_SAVE_TO_COLLECTIONS_VIEW_CONTROLLER";
            case 1929:
                return "TEST_DWELL_SERP_USERS";
            case 1935:
                return "TEST_INTERACTION_COM_INSTAGRAM_PRIVACY_ACTIVITY_CENTER_LIKED_MEDIA_SCREEN";
            case 1979:
                return "TEST_INTERACTION_AUDIO_BROWSER_TABBED_SEARCH_RESULTS_VC";
            case 2151:
                return "TEST_INTERACTION_ANYTIME_MENTIONS_SEARCH";
            case 2166:
                return "TEST_DWELL_SELF_COMMENTS_V2";
            case 2183:
                return "TEST_INTERACTION_COMMENTS_V2_CLIPS_VIEWER_PUSH_NOTIF";
            case 2222:
                return "TEST_DWELL_PENDING_TABS";
            case 2249:
                return "TEST_NAVIGATION_STORY_STICKERS_TRAY";
            case 2288:
                return "TEST_INTERACTION_DIRECT_THREAD_PRESENTER";
            case 2290:
                return "TEST_INTERACTION_CLIPS_VIEWER_HOMECOMING_FYP";
            case 2312:
                return "TEST_NAVIGATION_DIRECT_STORY_AUDIENCE_PICKER";
            case 2325:
                return "TEST_INTERACTION_DIRECT_AGGREGATED_MEDIA";
            case 2400:
                return "TEST_INTERACTION_DIRECT_PENDING_INBOX";
            case 2416:
                return "TEST_INTERACTION_AUDIO_BROWSER_V2_TRENDING";
            case 2455:
                return "TEST_INTERACTION_DIRECT_RICH_REACTIONS_LIST";
            case 2493:
                return "TEST_NAVIGATION_DIRECT_RESHARE_SHEET";
            case 2498:
                return "TEST_DWELL_UNIFIED_FOLLOW_LISTS";
            case 2548:
                return "TEST_DWELL_FEED_CONTEXTUAL_PROFILE";
            case 2558:
                return "TEST_NAVIGATION_MUTUAL";
            case 2578:
                return "TEST_NAVIGATION_MEDIA_CROP_VIEW";
            case 2607:
                return "TEST_DWELL_FEED_TIMELINE";
            case 2613:
                return "TEST_INTERACTION_FEED_POST_STICKER";
            case 2660:
                return "TEST_INTERACTION_IG_QUICK_SNAP_CREATION";
            case 2698:
                return "TEST_INTERACTION_COM_BLOKS_WWW_CAA_LOGIN_LOGIN_HOMEPAGE";
            case 2703:
                return "TEST_DWELL_DIRECT_MEDIA_PICKER_WATERFALL";
            case 2784:
                return "TEST_NAVIGATION_LINKS_SHEET";
            case 2799:
                return "TEST_DWELL_EDIT_PROFILE";
            case 2825:
                return "TEST_DWELL_FRIENDING_CENTER";
            case 2864:
                return "TEST_NAVIGATION_CLIPS_GALLERY";
            case 2930:
                return "TEST_NAVIGATION_AUDIO_BROWSER_V2_SAVED";
            case 2942:
                return "TEST_DWELL_DIRECT_MESSAGE_ACTIONS_VIEW_CONTROLLER";
            case 2998:
                return "TEST_NAVIGATION_COMMENT_LIKERS";
            case 3005:
                return "TEST_DWELL_INAPP_APP_STORE";
            case 3060:
                return "TEST_NAVIGATION_DIRECT_MEDIA_PICKER_WATERFALL";
            case 3112:
                return "TEST_INTERACTION_DIRECT_MESSAGE_LIST";
            case 3113:
                return "TEST_NAVIGATION_COM_BLOKS_WWW_FX_COMPANY_IDENTITY_SWITCHER_ADD_ACCOUNT_SCREEN_QUERY";
            case 3143:
                return "TEST_INTERACTION_PROFILE_PICTURE_PREVIEW";
            case 3153:
                return "TEST_INTERACTION_NEWSFEED_YOU";
            case 3183:
                return "TEST_DWELL_REEL_HIGHLIGHTS_GALLERY";
            case 3242:
                return "TEST_INTERACTION_EDIT_PROFILE";
            case 3280:
                return "TEST_DWELL_SERP_TOP";
            case 3287:
                return "TEST_DWELL_PROFILE_SOCIAL_CONTEXT";
            case 3327:
                return "TEST_NAVIGATION_COM_INSTAGRAM_INSIGHTS_MEDIA_REFRESH_STORIES_CORE";
            case 3365:
                return "TEST_NAVIGATION_CLIPS_POSTCAPTURE_CAMERA";
            case 3381:
                return "TEST_INTERACTION_COMMENTS_V2_CLIPS_VIEWER_CLIPS_TAB";
            case 3497:
                return "TEST_NAVIGATION_FOLLOWING_SHEET";
            case 3530:
                return "TEST_INTERACTION_LOCATION_PICKER";
            case 3547:
                return "TEST_INTERACTION_SELF_COMMENTS_V2_CLIPS_VIEWER_NEWSFEED_YOU";
            case 3584:
                return "TEST_DWELL_FEED_CONTEXTUAL_FROM_MEMORIES_NOTIFICATION";
            case 3697:
                return "TEST_INTERACTION_DIRECT_THREAD_GALLERY";
            case 3809:
                return "TEST_NAVIGATION_LIKERS";
            case 3910:
                return "TEST_DWELL_DIRECT_NOTES_COMPOSER";
            case 3942:
                return "TEST_DWELL_IG_DIRECT_NOTES_SELF_SHEET";
            case 3991:
                return "TEST_DWELL_SEARCH_TYPEAHEAD";
            case 3992:
                return "TEST_DWELL_BROADCAST_CHAT_THREAD";
            case 4004:
                return "TEST_DWELL_DIRECT_THREAD";
            case 4055:
                return "TEST_INTERACTION_FEED_CONTEXTUAL_PROFILE";
            case 4115:
                return "TEST_DWELL_FEED_CONTEXTUAL_SAVED_COLLECTIONS";
            case 4141:
                return "TEST_NAVIGATION_SELF_FOLLOWING";
            case 4206:
                return "TEST_NAVIGATION_CLIPS_PRECAPTURE_CAMERA";
            case 4309:
                return "TEST_NAVIGATION_DIRECT_FORWARDING_SHEET";
            case 4455:
                return "TEST_NAVIGATION_DIRECT_GIF";
            case 4466:
                return "TEST_INTERACTION_STORIES_GALLERY";
            case 4488:
                return "TEST_DWELL_FEED_POST_STICKER";
            case 4527:
                return "TEST_DWELL_PROFILE_PICTURE_PREVIEW";
            case 4545:
                return "TEST_NAVIGATION_IG_DIRECT_NOTES_COMPOSER_AUDIENCE_SELECTOR";
            case 4567:
                return "TEST_NAVIGATION_DIRECT_THREAD_GALLERY";
            case 4628:
                return "TEST_INTERACTION_QUICK_SNAP_VIEWER";
            case 4653:
                return "TEST_NAVIGATION_FOLLOWING";
            case 4656:
                return "TEST_DWELL_AUDIENCE_SELECTION";
            case 4666:
                return "TEST_DWELL_LIVE_VIEWER";
            case 4719:
                return "TEST_INTERACTION_COM_BLOKS_WWW_FX_SETTINGS_SECURITY_CHANGE_PASSWORD";
            case 4722:
                return "TEST_DWELL_FEED_TIMELINE_ALL";
            case 4729:
                return "TEST_DWELL_COM_INSTAGRAM_PRIVACY_ACTIVITY_CENTER_LIKED_MEDIA_SCREEN";
            case 4742:
                return "TEST_INTERACTION_FEED_SAVED_COLLECTIONS_CLIPS";
            case 4757:
                return "TEST_DWELL_SELF_TAGGED_PROFILE";
            case 4762:
                return "TEST_DWELL_AUDIO_PAGE";
            case 4763:
                return "TEST_INTERACTION_AUDIO_BROWSER_V2_FOR_YOU";
            case 4855:
                return "TEST_NAVIGATION_BUG_REPORTING";
            case 4886:
                return "TEST_INTERACTION_SERP_TOP";
            case 4902:
                return "TEST_NAVIGATION_COMMENTS_V2";
            case 4904:
                return "TEST_INTERACTION_BROADCAST_CHAT_THREAD";
            case 4946:
                return "TEST_NAVIGATION_SAVE_TO_COLLECTIONS_VIEW_CONTROLLER";
            case 4952:
                return "TEST_INTERACTION_DPA_SHOWCASE_PAGE";
            case 4961:
                return "TEST_DWELL_COM_INSTAGRAM_PRIVACY_ACTIVITY_CENTER_ACTIVITY_CENTER_ENTRY_BUSINESS_SCREEN";
            case 5009:
                return "TEST_DWELL_FEED_TIMELINE_FOLLOWING";
            case 5055:
                return "TEST_INTERACTION_STORIES_PRECAPTURE_CAMERA";
            case 5085:
                return "TEST_DWELL_ACTIVITY_FEED_CONTAINER";
            case 5089:
                return "TEST_NAVIGATION_LOCATION_PICKER";
            case 5152:
                return "TEST_DWELL_DIRECT_AGGREGATED_MEDIA";
            case 5179:
                return "TEST_DWELL_FEED_SAVED_COLLECTIONS";
            case 5198:
                return "TEST_INTERACTION_DIRECT_LOCATION_SHARING";
            case 5327:
                return "TEST_INTERACTION_COMMENTS_V2_CLIPS_VIEWER_DIRECT";
            case 5429:
                return "TEST_INTERACTION_IG_STORY_PEEK";
            case 5532:
                return "TEST_DWELL_REEL_COMPOSER_CAMERA";
            case 5539:
                return "TEST_DWELL_SAVED_MEDIA_ALL_CONTENT";
            case 5588:
                return "TEST_NAVIGATION_FEED_POST_STICKER";
            case 5657:
                return "TEST_NAVIGATION_PROFILE_SOCIAL_CONTEXT";
            case 5680:
                return "TEST_NAVIGATION_REEL_DASHBOARD";
            case 5683:
                return "TEST_NAVIGATION_ACTION_LIST_VIEW_CONTROLLER";
            case 5689:
                return "TEST_NAVIGATION_FEED_SAVED_COLLECTIONS";
            case 5708:
                return "TEST_INTERACTION_TAGS_LIST";
            case 5731:
                return "TEST_NAVIGATION_SINGLE_FEED_NOTIFICATION";
            case 5787:
                return "TEST_INTERACTION_CALENDAR_ARCHIVE";
            case 5827:
                return "TEST_DWELL_SINGLE_FEED_ARCHIVE_FEED";
            case 5835:
                return "TEST_INTERACTION_IG_DIRECT_NOTES_SELF_SHEET";
            case 5857:
                return "TEST_DWELL_MUTUAL_FULL_LIST";
            case 5867:
                return "TEST_NAVIGATION_FOANATIVE_IG_BASE_VIEW_CONTROLLER_IDENTITY_SWITCHER";
            case 5875:
                return "TEST_NAVIGATION_FEED_CONTEXTUAL_CHAIN";
            case 5914:
                return "TEST_DWELL_SAVE_TO_COLLECTIONS_VIEW_CONTROLLER";
            case 5923:
                return "TEST_INTERACTION_DIRECT_REACTION_SELECTION";
            case 5937:
                return "TEST_NAVIGATION_COM_INSTAGRAM_PRIVACY_ACTIVITY_CENTER_ACTIVITY_CENTER_ENTRY_BUSINESS_SCREEN";
            case 5970:
                return "TEST_NAVIGATION_VIDEO_CALL";
            case 6026:
                return "TEST_NAVIGATION_STORIES_VIEWER";
            case 6054:
                return "TEST_INTERACTION_FRIENDS";
            case 6070:
                return "TEST_INTERACTION_LEAD_ADS";
            case 6094:
                return "TEST_NAVIGATION_NEWSFEED_YOU";
            case 6103:
                return "TEST_DWELL_ARCHIVE_HOME";
            case 6127:
                return "TEST_DWELL_DIRECT_MULTIEDIT_COMPOSER";
            case 6146:
                return "TEST_INTERACTION_AUDIO_BROWSER_V2_SAVED";
            case 6252:
                return "TEST_NAVIGATION_MULTIBLOCK_VIEW_CONTROLLER";
            case 6269:
                return "TEST_INTERACTION_VIDEO_CALL";
            case 6273:
                return "TEST_INTERACTION_QUICK_SNAP_IMMERSIVE_VIEWER_CONSUMPTION_VC";
            case 6309:
                return "TEST_DWELL_IG_QUICK_SNAP_CREATION";
            case 6311:
                return "TEST_NAVIGATION_STORIES_GALLERY";
            case 6342:
                return "TEST_INTERACTION_MUTUAL";
            case 6363:
                return "TEST_DWELL_DIRECT_REPLY_TO_AUTHOR";
            case 6418:
                return "TEST_DWELL_CLIPS_VIEWER";
            case 6538:
                return "TEST_DWELL_DIRECT_STORY_AUDIENCE_PICKER";
            case 6597:
                return "TEST_INTERACTION_BUG_REPORTING";
            case 6607:
                return "TEST_INTERACTION_VIDEO_VIEW_COUNT_USER_LIST";
            case 6656:
                return "TEST_INTERACTION_EDIT_PROFILE_USERNAME";
            case 6657:
                return "TEST_INTERACTION_LIVE_VIEWER";
            case 6661:
                return "TEST_INTERACTION_SINGLE_FEED_NOTIFICATION";
            case 6776:
                return "TEST_INTERACTION_SERP";
            case 6799:
                return "TEST_INTERACTION_FEED_CONTEXTUAL_SAVED_COLLECTIONS";
            case 6807:
                return "TEST_INTERACTION_FEED_TIMELINE";
            case 6825:
                return "TEST_NAVIGATION_EXPLORE_POPULAR";
            case 6828:
                return "TEST_DWELL_DIRECT_AGGREGATED_MEDIA_VIEWER";
            case 6845:
                return "TEST_DWELL_CLIPS_PROFILE";
            case 6877:
                return "TEST_DWELL_BLOCK_LIST_VIEW";
            case 6955:
                return "TEST_INTERACTION_MAIN_SETTINGS_SCREEN";
            case 6968:
                return "TEST_INTERACTION_COMMENTS_V2_CLIPS_VIEWER_EXPLORE_POPULAR_DEFAULT_UNIT";
            case 6973:
                return "TEST_INTERACTION_INAPP_APP_STORE";
            case 7034:
                return "TEST_NAVIGATION_LIVE_VIEWER";
            case 7039:
                return "TEST_NAVIGATION_DIRECT_POSTCAPTURE_CAMERA";
            case 7056:
                return "TEST_DWELL_AUDIO_BROWSER_TABBED_VC";
            case 7170:
                return "TEST_DWELL_SELF_PROFILE";
            case 7232:
                return "TEST_INTERACTION_DIRECT_THREAD_DETAILS_REDESIGN";
            case 7257:
                return "TEST_NAVIGATION_PRIVATE_STORIES_SHARE_SHEET";
            case 7262:
                return "TEST_DWELL_FEED_CONTEXTUAL_CHAIN";
            case 7271:
                return "TEST_INTERACTION_REEL_MULTIEDIT_COMPOSER";
            case 7286:
                return "TEST_DWELL_DIRECT_INBOX";
            case 7348:
                return "TEST_NAVIGATION_STORIES_POSTCAPTURE_CAMERA";
            case 7361:
                return "TEST_INTERACTION_COMMENTS_V2_FEED_TIMELINE";
            case 7379:
                return "TEST_INTERACTION_IG_FRIENDS_MAP";
            case 7399:
                return "TEST_INTERACTION_PROFILE";
            case 7401:
                return "TEST_NAVIGATION_DIRECT_AGGREGATED_MEDIA_VIEWER";
            case 7433:
                return "TEST_DWELL_DIRECT_GIF";
            case 7473:
                return "TEST_DWELL_CAROUSEL_GALLERY";
            case 7547:
                return "TEST_DWELL_AUDIO_BROWSER_V2_TRENDING";
            case 7679:
                return "TEST_INTERACTION_COMMENTS_V2_CLIPS_VIEWER_EXPLORE_POPULAR_MINOR_UNIT";
            case 7737:
                return "TEST_INTERACTION_STORY_STICKERS_TRAY";
            case 7765:
                return "TEST_INTERACTION_IG_PUBLISH_SCREEN_CAPTION";
            case 7776:
                return "TEST_INTERACTION_CLIPS_PRECAPTURE_CAMERA";
            case 7778:
                return "TEST_INTERACTION_CLIPS_TAB_HOME";
            case 7823:
                return "TEST_DWELL_MUTUAL";
            case 7836:
                return "TEST_INTERACTION_STORY_GIFS";
            case 7856:
                return "TEST_INTERACTION_AUDIENCE_SELECTION";
            case 7864:
                return "TEST_NAVIGATION_FEED_TIMELINE";
            case 7872:
                return "TEST_INTERACTION_MUSIC_IN_FEED";
            case 7956:
                return "TEST_NAVIGATION_DIRECT_MESSAGE_ACTIONS_VIEW_CONTROLLER";
            case 7974:
                return "TEST_INTERACTION_SELF_FOLLOWERS";
            case 7998:
                return "TEST_INTERACTION_FOANATIVE_IG_BASE_VIEW_CONTROLLER_IDENTITY_SWITCHER";
            case 8045:
                return "TEST_DWELL_CLIPS_VIEWER_CLIPS_BLEND";
            case 8071:
                return "TEST_NAVIGATION_QUICK_SNAP_IMMERSIVE_VIEWER_CONSUMPTION_VC";
            case 8081:
                return "TEST_INTERACTION_COMMENTS_V2_CLIPS_VIEWER_CLIPS_PROFILE";
            case 8094:
                return "TEST_INTERACTION_EXPLORE_POPULAR";
            case 8097:
                return "TEST_INTERACTION_FEED_GALLERY";
            case 8185:
                return "TEST_INTERACTION_COMMENTS_V2_CLIPS_VIEWER_FEED_CONTEXTUAL_PROFILE";
            case 8228:
                return "TEST_INTERACTION_COMMENTS_V2_CLIPS_VIEWER_CLIPS_NETEGO";
            case 8233:
                return "TEST_DWELL_IG_CREATION_GENAI_RESTYLE";
            case 8257:
                return "TEST_INTERACTION_EDIT_REEL_HIGHLIGHTS";
            case 8283:
                return "TEST_NAVIGATION_ANYTIME_MENTIONS_LIST";
            case 8288:
                return "TEST_INTERACTION_CLIPS_VIEWER_EXPLORE_POPULAR_DEFAULT_UNIT";
            case 8306:
                return "IG_SLATE_TEST_APP_START";
            case 8382:
                return "TEST_DWELL_REEL_DASHBOARD";
            case 8434:
                return "TEST_DWELL_COMMENTS_V2";
            case 8516:
                return "TEST_NAVIGATION_CLIPS_VIEWER";
            case 8604:
                return "TEST_INTERACTION_DIRECT_NOTES_COMPOSER";
            case 8625:
                return "TEST_DWELL_SUNDIAL_STACKED_TIMELINE_VC";
            case 8679:
                return "TEST_DWELL_NEWSFEED_YOU";
            case 8874:
                return "TEST_INTERACTION_CLIPS_VIEWER_CLIPS_BLEND";
            case 8891:
                return "TEST_NAVIGATION_DIRECT_THREAD_DETAILS_REDESIGN";
            case 8942:
                return "TEST_NAVIGATION_PEEK_MEDIA";
            case 9007:
                return "TEST_INTERACTION_FEED_SAVED_COLLECTIONS";
            case 9012:
                return "TEST_INTERACTION_CLIPS_VIEWER_CLIPS_PROFILE";
            case 9029:
                return "TEST_NAVIGATION_IG_DIRECT_NOTES_SELF_SHEET";
            case 9058:
                return "TEST_INTERACTION_FEED_CONTEXTUAL_SELF_PROFILE";
            case 9127:
                return "TEST_INTERACTION_CLIPS_VIEWER_FRIENDS_LANE";
            case 9149:
                return "TEST_INTERACTION_MEDIA_CROP_VIEW";
            case 9171:
                return "TEST_INTERACTION_FOLLOWERS";
            case 9209:
                return "TEST_INTERACTION_DIRECT_THREAD";
            case 9225:
                return "TEST_DWELL_STORY_DRAFTS_BROWSER";
            case 9327:
                return "TEST_INTERACTION_DIRECT_SUNDIAL_FEED";
            case 9333:
                return "TEST_NAVIGATION_DIRECT_AGGREGATED_MEDIA";
            case 9350:
                return "TEST_NAVIGATION_EDIT_REEL_HIGHLIGHTS";
            case 9396:
                return "TEST_NAVIGATION_MEDIA_BROADCAST_SHARE";
            case 9451:
                return "TEST_NAVIGATION_STORY_DRAFTS_BROWSER";
            case 9487:
                return "TEST_INTERACTION_SELF_UNIFIED_FOLLOW_LISTS";
            case 9500:
                return "TEST_INTERACTION_IG_CREATION_GENAI_RESTYLE";
            case 9520:
                return "TEST_INTERACTION_PHOTO_FILTER";
            case 9531:
                return "TEST_DWELL_ARCHIVE_STORIES";
            case 9542:
                return "TEST_DWELL_IG_DIRECT_NOTES_COMPOSER_AUDIENCE_SELECTOR";
            case 9587:
                return "TEST_NAVIGATION_PROFILE_CREATION_SHEET";
            case 9595:
                return "TEST_NAVIGATION_INAPP_APP_STORE";
            case 9624:
                return "TEST_NAVIGATION_PROFILE_PICTURE_PREVIEW";
            case 9653:
                return "TEST_INTERACTION_DIRECT_PRECAPTURE_CAMERA";
            case 9662:
                return "TEST_DWELL_DIRECT_PENDING_INBOX";
            case 9664:
                return "TEST_NAVIGATION_SELF_COMMENTS_V2";
            case 9700:
                return "TEST_INTERACTION_COMMENTS_V2_CLIPS_VIEWER_REEL_FEED_TIMELINE";
            case 9720:
                return "TEST_DWELL_STORY_STICKERS_TRAY";
            case 9814:
                return "TEST_INTERACTION_INSTAGRAM_CLICKTODIRECT";
            case 9856:
                return "TEST_NAVIGATION_IGSUNDIAL_SHARE_SHEET_V2_VIEW_CONTROLLER";
            case 9859:
                return "TEST_DWELL_MEDIA_BROADCAST_SHARE";
            case 9877:
                return "TEST_INTERACTION_COMMENTS_V2";
            case 9938:
                return "TEST_INTERACTION_FOLLOW_REQUESTS";
            case 9969:
                return "TEST_DWELL_CLIPS_POSTCAPTURE_CAMERA";
            case 9990:
                return "TEST_DWELL_CLIPS_VIEWER_CLIPS_TAB";
            case 10004:
                return "TEST_INTERACTION_QUICK_SNAP_IMMERSIVE_VIEWER";
            case 10124:
                return "TEST_INTERACTION_FEED_CONTEXTUAL_CHAIN";
            case 10277:
                return "TEST_NAVIGATION_MSH_SHOTS_DETAIL";
            case 10292:
                return "TEST_DWELL_LIKERS";
            case 10308:
                return "TEST_INTERACTION_CLIPS_VIEWER_SERP_TOP_MINOR_UNIT";
            case 10348:
                return "TEST_INTERACTION_PEEK_MEDIA";
            case 10399:
                return "TEST_NAVIGATION_FEED_CONTEXTUAL_SAVED_COLLECTIONS";
            case 10439:
                return "TEST_NAVIGATION_EDIT_PROFILE";
            case 10554:
                return "TEST_DWELL_QUICK_SNAP_IMMERSIVE_VIEWER_CONSUMPTION_VC";
            case 10555:
                return "TEST_NAVIGATION_SELF_FOLLOWERS";
            case 10612:
                return "TEST_INTERACTION_ZOOM";
            case 10632:
                return "TEST_INTERACTION_FEED_CONTEXTUAL_FROM_MEMORIES_NOTIFICATION";
            case 10671:
                return "TEST_INTERACTION_SELF_CLIPS_PROFILE";
            case 10685:
                return "TEST_INTERACTION_TAGGED_PROFILE";
            case 10729:
                return "TEST_DWELL_TAGS_LIST";
            case 10733:
                return "TEST_INTERACTION_STORY_EMOJI_PICKER";
            case 10830:
                return "TEST_INTERACTION_STORIES_VIEWER";
            case 10851:
                return "TEST_INTERACTION_DIRECT_MESSAGE_ACTIONS_VIEW_CONTROLLER";
            case 10862:
                return "TEST_DWELL_VIDEO_VIEW_COUNT_USER_LIST";
            case 10886:
                return "TEST_DWELL_BROWSER_VIEW_CONTROLLER";
            case 10893:
                return "TEST_DWELL_AUDIO_BROWSER_TABBED_SEARCH_RESULTS_VC";
            case 10948:
                return "TEST_INTERACTION_CLIPS_PROFILE";
            case 10975:
                return "TEST_INTERACTION_DIRECT_RESHARE_SHEET";
            case 10993:
                return "TEST_INTERACTION_IGSTORY_TEXT_TOOL_VIEW_CONTROLLER";
            case 11035:
                return "TEST_INTERACTION_LIKERS";
            case 11042:
                return "TEST_NAVIGATION_DIRECT_PRECAPTURE_CAMERA";
            case 11092:
                return "TEST_DWELL_STORIES_GALLERY";
            case 11135:
                return "TEST_DWELL_MAIN_SETTINGS_SCREEN";
            case 11144:
                return "TEST_NAVIGATION_FRIENDING_CENTER";
            case 11170:
                return "TEST_NAVIGATION_THREAD_THEME_PICKER";
            case 11301:
                return "TEST_INTERACTION_STORIES_POSTCAPTURE_CAMERA";
            case 11319:
                return "TEST_INTERACTION_DIRECT_AGGREGATED_MEDIA_VIEWER";
            case 11370:
                return "TEST_NAVIGATION_AUDIO_BROWSER_TABBED_SEARCH_RESULTS_VC";
            case 11414:
                return "TEST_NAVIGATION_SERP_TOP";
            case 11497:
                return "TEST_INTERACTION_REEL_HIGHLIGHTS_GALLERY";
            case 11585:
                return "TEST_INTERACTION_COM_BLOKS_WWW_FX_SETTINGS_ACTIVITY_MANAGEMENT_SEARCH_HISTORY";
            case 11586:
                return "TEST_DWELL_SUNDIAL_CONTENT_NOTES_FEED";
            case 11605:
                return "TEST_INTERACTION_CLIPS_VIEWER_EXPLORE_POPULAR_MINOR_UNIT";
            case 11623:
                return "TEST_DWELL_DIRECT_SUNDIAL_FEED";
            case 11716:
                return "TEST_DWELL_CUSTOM_ALERT";
            case 11770:
                return "TEST_NAVIGATION_AUDIO_PAGE";
            case 11815:
                return "IG_SLATE_TEST_INTERACTION";
            case 11824:
                return "TEST_INTERACTION_COM_INSTAGRAM_PRIVACY_ACTIVITY_CENTER_MEDIA_REPOST_SCREEN";
            case 11829:
                return "TEST_NAVIGATION_BLOKS_UNKNOWN";
            case 11859:
                return "TEST_INTERACTION_SAVED_MEDIA_ALL_CONTENT";
            case 11890:
                return "TEST_INTERACTION_FEED_TIMELINE_ALL";
            case 11916:
                return "TEST_INTERACTION_FOLLOWING";
            case 11989:
                return "TEST_DWELL_DIRECT_POSTCAPTURE_CAMERA";
            case 12087:
                return "TEST_DWELL_STORY_EXTENDED_GALLERY";
            case 12135:
                return "TEST_INTERACTION_FEED_TIMELINE_FOLLOWING";
            case 12144:
                return "TEST_NAVIGATION_BROWSER_VIEW_CONTROLLER";
            case 12175:
                return "TEST_NAVIGATION_ACTIVITY_FEED_CONTAINER";
            case 12212:
                return "TEST_INTERACTION_ACTION_LIST_VIEW_CONTROLLER";
            case 12284:
                return "TEST_DWELL_SERP";
            case 12313:
                return "TEST_INTERACTION_REEL_DASHBOARD";
            case 12380:
                return "TEST_NAVIGATION_PHOTO_FILTER";
            case 12436:
                return "TEST_NAVIGATION_COM_BLOKS_WWW_IG_ABOUT_THIS_ACCOUNT";
            case 12466:
                return "TEST_INTERACTION_DIRECT_REPLY_TO_AUTHOR";
            case 12534:
                return "TEST_DWELL_LOCATION_PICKER";
            case 12555:
                return "TEST_INTERACTION_CAROUSEL_GALLERY";
            case 12558:
                return "TEST_NAVIGATION_IG_PUBLISH_SCREEN_CAPTION";
            case 12583:
                return "TEST_INTERACTION_COM_BLOKS_WWW_INSTAGRAM_YOUR_ACTIVITY_BLOKS_YOUR_ACTIVITY_SEEN_CONTENT_SCREEN_QU";
            case 12614:
                return "TEST_DWELL_SELF_FOLLOWERS";
            case 12631:
                return "TEST_INTERACTION_SUNDIAL_CONTENT_NOTES_FEED";
            case 12737:
                return "TEST_DWELL_MEDIA_CROP_VIEW";
            case 12751:
                return "TEST_NAVIGATION_SAVED_MEDIA_ALL_CONTENT";
            case 12786:
                return "TEST_DWELL_STORIES_VIEWER";
            case 12796:
                return "TEST_DWELL_STORIES_PRECAPTURE_CAMERA";
            case 12881:
                return "TEST_NAVIGATION_STORY_EXTENDED_GALLERY";
            case 12893:
                return "TEST_NAVIGATION_FEED_CONTEXTUAL_SELF_PROFILE";
            case 12896:
                return "TEST_NAVIGATION_IG_FRIENDS_MAP";
            case 12903:
                return "TEST_INTERACTION_DIRECT_GIF";
            case 12917:
                return "TEST_DWELL_VIDEO_CALL";
            case 12940:
                return "TEST_DWELL_SELF_UNIFIED_FOLLOW_LISTS";
            case 12947:
                return "TEST_INTERACTION_DIRECT_CARD_GALLERY";
            case 12982:
                return "TEST_INTERACTION_BROWSER_VIEW_CONTROLLER";
            case 13063:
                return "TEST_INTERACTION_MUTUAL_FULL_LIST";
            case 13078:
                return "TEST_NAVIGATION_SELF_PROFILE";
            case 13132:
                return "TEST_DWELL_FOLLOWERS";
            case 13155:
                return "TEST_NAVIGATION_FOLLOWERS";
            case 13180:
                return "TEST_INTERACTION_IG_DIRECT_NOTES_COMPOSER_AUDIENCE_SELECTOR";
            case 13231:
                return "TEST_NAVIGATION_IGQUICKSNAPHISTORYVIEWCONTROLLER";
            case 13301:
                return "TEST_INTERACTION_ARCHIVE_STORIES";
            case 13515:
                return "TEST_INTERACTION_AUDIO_PAGE";
            case 13534:
                return "TEST_DWELL_FOLLOWING";
            case 13556:
                return "TEST_INTERACTION_IG_IXT_ACTIVITING_INDICATING";
            case 13607:
                return "TEST_DWELL_DIRECT_RESHARE_SHEET";
            case 13661:
                return "TEST_INTERACTION_DIRECT_POSTCAPTURE_CAMERA";
            case 13662:
                return "TEST_DWELL_PHOTO_FILTER";
            case 13682:
                return "TEST_NAVIGATION_CUSTOM_ALERT";
            case 13837:
                return "TEST_INTERACTION_STORY_MORE_OPTIONS";
            case 13881:
                return "TEST_NAVIGATION_MUTUAL_FULL_LIST";
            case 13948:
                return "TEST_INTERACTION_MEDIA_BROADCAST_SHARE";
            case 13983:
                return "TEST_DWELL_STORIES_POSTCAPTURE_CAMERA";
            case 14035:
                return "TEST_INTERACTION_STORY_VIEWER_REACTION_OVERLAY";
            case 14063:
                return "TEST_NAVIGATION_FRIENDS";
            case 14145:
                return "TEST_DWELL_EXPLORE_POPULAR";
            case 14200:
                return "TEST_INTERACTION_SELF_COMMENTS_V2_CLIPS_VIEWER_SELF_CLIPS_PROFILE";
            case 14257:
                return "TEST_NAVIGATION_SINGLE_FEED_DIRECT_XMA_MEDIA_SHARE";
            case 14322:
                return "TEST_INTERACTION_DIRECT_MEDIA_PICKER_WATERFALL";
            case 14477:
                return "TEST_INTERACTION_CLIPS_VIEWER";
            case 14492:
                return "TEST_INTERACTION_EDIT_POST";
            case 14576:
                return "TEST_INTERACTION_COMMENTS_V2_CLIPS_VIEWER_FEED_TIMELINE";
            case 14691:
                return "TEST_INTERACTION_CLIPS_VIEWER_CLIPS_TAB";
            case 14713:
                return "IG_SLATE_TEST_DWELL";
            case 14826:
                return "TEST_INTERACTION_CLIPS_GALLERY";
            case 14900:
                return "TEST_NAVIGATION_VIDEO_VIEW_COUNT_USER_LIST";
            case 14919:
                return "TEST_DWELL_SELF_FOLLOWING";
            case 14921:
                return "TEST_INTERACTION_SELF_COMMENTS_V2";
            case 15075:
                return "TEST_INTERACTION_CLIPS_AUDITION";
            case 15078:
                return "IG_SLATE_TEST_NAVIGATION";
            case 15081:
                return "TEST_DWELL_AUDIO_BROWSER_V2_FOR_YOU";
            case 15129:
                return "TEST_INTERACTION_SUNDIAL_STACKED_TIMELINE_VC";
            case 15170:
                return "TEST_NAVIGATION_PROFILE";
            case 15178:
                return "TEST_INTERACTION_CAMERA_NAV";
            case 15201:
                return "TEST_DWELL_USAGE_INSIGHTS_BLOCKING";
            case 15280:
                return "TEST_DWELL_AUDIO_BROWSER_V2_SAVED";
            case 15327:
                return "TEST_NAVIGATION_DIRECT_PENDING_INBOX";
            case 15349:
                return "TEST_NAVIGATION_DIRECT_THREAD";
            case 15384:
                return "TEST_INTERACTION_COMMENTS_V2_CLIPS_VIEWER_NEWSFEED_YOU";
            case 15460:
                return "TEST_DWELL_PROFILE";
            case 15511:
                return "TEST_DWELL_TAGGED_PROFILE";
            case 15620:
                return "TEST_INTERACTION_PANAVIDEO_SHARE_SHEET";
            case 15699:
                return "TEST_INTERACTION_FRIENDING_CENTER";
            case 15731:
                return "TEST_NAVIGATION_AUDIO_BROWSER_V2_FOR_YOU";
            case 15741:
                return "TEST_DWELL_SELF_CLIPS_PROFILE";
            case 15751:
                return "TEST_INTERACTION_DIRECT_AVATAR_STICKER_PICKER_GRID";
            case 15777:
                return "TEST_DWELL_AUDIO_BROWSER_PAGE_CONTENT_VC";
            case 15783:
                return "TEST_INTERACTION_CLIPS_POSTCAPTURE_CAMERA";
            case 15832:
                return "TEST_DWELL_ACTION_LIST_VIEW_CONTROLLER";
            case 15889:
                return "TEST_INTERACTION_IGQUICK_VIDEO_CUTOUT_VIEW_CONTROLLER";
            case 15902:
                return "TEST_NAVIGATION_BLOCK_LIST_TAB_VIEW";
            case 15915:
                return "TEST_DWELL_SINGLE_FEED_NOTIFICATION";
            case 15940:
                return "TEST_NAVIGATION_STORIES_PRECAPTURE_CAMERA";
            case 15946:
                return "TEST_INTERACTION_STORY_EXTENDED_GALLERY";
            case 15989:
                return "TEST_NAVIGATION_MAIN_SETTINGS_SCREEN";
            case 15999:
                return "TEST_NAVIGATION_IG_QUICK_SNAP_CREATION";
            case 16004:
                return "TEST_NAVIGATION_FEED_CONTEXTUAL_PROFILE";
            case 16007:
                return "TEST_INTERACTION_STORY_EMOJI";
            case 16017:
                return "TEST_INTERACTION_SELF_PROFILE";
            case 16130:
                return "TEST_INTERACTION_SEARCH_TYPEAHEAD";
            case 16148:
                return "TEST_NAVIGATION_QUICK_SNAP_VIEWER";
            case 16154:
                return "TEST_INTERACTION_DIRECT_FORWARDING_SHEET";
            case 16157:
                return "TEST_DWELL_DIRECT_PRECAPTURE_CAMERA";
            case 16188:
                return "TEST_DWELL_IG_PUBLISH_SCREEN_CAPTION";
            case 16191:
                return "TEST_DWELL_DIRECT_THREAD_GALLERY";
            case 16271:
                return "TEST_DWELL_HIGHLIGHTS_ADD_SHEET";
            case 16290:
                return "TEST_NAVIGATION_CLIPS_VIEWER_CLIPS_TAB";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
