package X;

/* JADX INFO: renamed from: X.50s, reason: invalid class name and case insensitive filesystem */
/* JADX INFO: loaded from: classes4.dex */
public abstract class AbstractC1117550s {
    public static String A00(int i) {
        switch (i) {
            case 1122:
                return "ZERO_ZERO_BALANCE_DIALOG";
            case 1325:
                return "ZERO_IG_ZERO_OPTIN_TRACE";
            case 1359:
                return "ZERO_CONTENT_DISPLAY_FLOW";
            case 1427:
                return "ZERO_CONTENT_DISPLAY_NON_FEED_FLOW_NT";
            case 1466:
                return "ZERO_FB_PRE_OPTIN_FLOW";
            case 1508:
                return "ZERO_SWITCH_MODE";
            case 1646:
                return "ZERO_FUP_IMAGE_LOADING";
            case 1667:
                return "ZERO_FB_OPTIN_SCREEN_FETCH";
            case 1703:
                return "ZERO_FBLITE_CONNECTION_ATTEMPT";
            case 2446:
                return "ZERO_FOS_DISCOVER_SIGNUP_FUNNEL";
            case 2615:
                return "ZERO_FREELS_END_CARD";
            case 2885:
                return "ZERO_ZERO_MESSENGER_NUX_ELIGIBILITY_CHECK";
            case 2919:
                return "ZERO_MESSAGING_PLACEHOLDER";
            case 2933:
                return "ZERO_ZERO_AUTO_MESSENGER_NUX_CLICK";
            case 3522:
                return "ZERO_PERIODIC_ZBD_UPSELL_INTERSTITIAL";
            case 3631:
                return "ZERO_ZERO_MESSENGER_NUX";
            case 4217:
                return "ZERO_FB_MINI_DISTRIBUTED_TESTS";
            case 4483:
                return "ZERO_IG_ZERO_SINGLE_OPTIN_FLOW";
            case 4538:
                return "ZERO_ZERO_MESSENGER_OPTIN_ACTION";
            case 4914:
                return "ZERO_IG_ZERO_FUNNELS_JOINED";
            case 5261:
                return "ZERO_UNKNOWN_STATE_RESOLVED";
            case 5455:
                return "ZERO_FREELS_SFUP_JEWEL_NOTIFICATION";
            case 5527:
                return "ZERO_IG_ZERO_OPTIN_FINAL";
            case 5551:
                return "ZERO_ZERO_MESSENGER_NUX_CLICK_CONTINUE";
            case 5653:
                return "ZERO_ZERO_MESSENGER_INTERSTITIAL";
            case 5750:
                return "ZERO_ZERO_ENROLMENT_NUX";
            case 5931:
                return "ZERO_IG_ZERO_BANNER";
            case 5969:
                return "ZERO_FREELS_IN_APP_NOTIFICATION";
            case 6078:
                return "ZERO_ZERO_MESSENGER_PLACEHOLDER";
            case 6089:
                return "ZERO_ZERO_UFAC_FLOW";
            case 6248:
                return "ZERO_FB_OPTIN_ACTION";
            case 6272:
                return "ZERO_FB_PUSH_REFRESH_TOKEN";
            case 6274:
                return "ZERO_ZERO_DATA_AVAILABILITY_MEASUREMENT";
            case 6309:
                return "ZERO_FB_REFRESH_ZERO_TOKEN";
            case 6374:
                return "ZERO_FREEMIUM_OPTIN";
            case 6559:
                return "ZERO_IG_ZERO_STARTUP";
            case 6754:
                return "ZERO_ZERO_AUTO_MESSENGER_NUX_SCREEN";
            case 6764:
                return "ZERO_FB_TOKEN_REFRESH_AFTER_OPTIN";
            case 6777:
                return "ZERO_ZERO_NATIVE_CARRIER_DETECTION";
            case 7012:
                return "ZERO_IG_ZERO_VIDEO";
            case 7038:
                return "ZERO_ZERO_SPLIT_FUP";
            case 7049:
                return "ZERO_ZERO_FREELS_MID_CARD";
            case 7054:
                return "ZERO_ZERO_BALANCE_DETECTION";
            case 7183:
                return "ZERO_ZORP_DECLINE_OPTIN";
            case 7819:
                return "ZERO_BACKGROUND_ZBD_NOTIF_PRE_SEND";
            case 8120:
                return "ZERO_IG_MINI_DISTRIBUTED_TESTS";
            case 8666:
                return "ZERO_ZERO_BALANCE_DETECTION_LID";
            case 9007:
                return "ZERO_FB4A_AUTOFLEX_ZBD_RESULT_FLOW";
            case 9294:
                return "ZERO_IG_ZERO_POST_OPTIN_FLOW";
            case 9417:
                return "ZERO_ZORP_TOKEN_REFRESH_AFTER_OPTIN";
            case 9556:
                return "ZERO_AUTOFLEX_OPTIN";
            case 9587:
                return "ZERO_IG_ZERO_MONETIZATION";
            case 9596:
                return "ZERO_ON_DEMAND_HEADERS";
            case 9694:
                return "ZERO_FUP";
            case 10043:
                return "ZERO_ZORP_OPTIN_SCREEN_FETCH";
            case 10130:
                return "ZERO_ZERO_LOGGED_OUT_REWRITE_RULES_REWRITE_RULES_RUN";
            case 10552:
                return "ZERO_IG_ZERO_BLOCKED_FLOWS";
            case 10653:
                return "ZERO_FB_OPTIN_FLOW";
            case 10657:
                return "ZERO_FREELS_NOTIFICATION";
            case 10667:
                return "ZERO_ZERO_UNEXPECTED_EVENT";
            case 10679:
                return "ZERO_IG_MOBILE_CENTER";
            case 10763:
                return "ZERO_FREELS_BOTTOM_SHEET_BUTTON_CLICKED";
            case 10773:
                return "ZERO_ZERO_BALANCE_DETECTED_UNTIL_SHOWN_FBLITE_SERVER";
            case 10829:
                return "ZERO_LOGOUT_REWRITE_RULES_TRIGGER";
            case 10885:
                return "ZERO_IG_ZERO_PRE_OPTIN_FLOW";
            case 11085:
                return "ZERO_FREELS_BOTTOM_SHEET_FETCH";
            case 11271:
                return "ZERO_ZERO_CAA_ZBD_TRIGGER";
            case 11543:
                return "ZERO_ZERO_ENROLMENT_NUX_INTERACTIONS";
            case 11644:
                return "ZERO_ZERO_ENROLMENT_NUX_FLOW";
            case 11693:
                return "ZERO_ZERO_ENROLMENT_NUX_COMPONENT";
            case 12221:
                return "ZERO_ZERO_MESSENGER_SETTINGS_SCREEN";
            case 12259:
                return "ZERO_FLEX_AUTOFLEX_TRANSITION";
            case 12580:
                return "ZERO_ZERO_MESSENGER_OPTOUT_ACTION";
            case 12788:
                return "ZERO_ZR_UI_PLACEHOLDER";
            case 12838:
                return "ZERO_ZERO_OPTIN_FLOW";
            case 12879:
                return "ZERO_IG_ZERO_NOTIF";
            case 12917:
                return "ZERO_ZERO_BALANCE_DETECTED_UNTIL_SHOWN";
            case 13308:
                return "ZERO_PLACEHOLDER_CLICK";
            case 13599:
                return "ZERO_FUP_INTERACTIONS";
            case 13650:
                return "ZERO_FB_DECLINE_OPTIN";
            case 14295:
                return "ZERO_IG_ZERO_OPTIN_FLOW";
            case 14436:
                return "ZERO_ZERO_MESSENGER_OPTIN_SCREEN";
            case 14448:
                return "ZERO_IG_ZERO_FREE_TO_PAID";
            case 14515:
                return "ZERO_ZERO_RATING_UI";
            case 14587:
                return "ZERO_FREELS_INTERACTIONS";
            case 14735:
                return "ZERO_FREELS_BUY_DATA";
            case 14750:
                return "ZERO_BACKGROUND_ZBD_NOTIF_POST_SEND";
            case 14775:
                return "ZERO_IG_ZERO_TIGON";
            case 15216:
                return "ZERO_IG_ZERO_OPTIN_PRE_FLOW";
            case 15494:
                return "ZERO_IG_ZERO_FUP_FLOW";
            case 15806:
                return "ZERO_FBLITE_OPTIN_SCREEN_FETCH";
            case 16216:
                return "ZERO_IG_ZERO_POST_ZBD";
            case 16304:
                return "ZERO_CAMPAIGN_API_REFRESH";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
