package X;

import com.google.protobuf.ByteString;
import com.whatsapp.calling.opengl.MediaCodecVideoEncoder;
import com.whatsapp.infra.tigon.WAHucClient;
import com.whatsapp.ui.coreui.base.WaTextView;
import java.util.ArrayList;
import java.util.Collections;
import java.util.LinkedHashMap;
import java.util.List;

/* JADX INFO: renamed from: X.0BQ, reason: invalid class name */
/* JADX INFO: loaded from: classes.dex */
public class C0BQ extends C0BP {
    public Boolean A00;
    public Boolean A01;
    public Boolean A02;
    public Boolean A03;
    public Boolean A04;
    public Boolean A05;
    public Boolean A06;
    public Boolean A07;
    public Boolean A08;
    public Boolean A09;
    public Boolean A0A;
    public Boolean A0B;
    public Boolean A0C;
    public Boolean A0D;
    public Boolean A0E;
    public Boolean A0F;
    public Boolean A0G;
    public Boolean A0H;
    public Boolean A0I;
    public Boolean A0J;
    public Boolean A0K;
    public Boolean A0L;
    public Boolean A0M;
    public Boolean A0N;
    public Boolean A0O;
    public Boolean A0P;
    public Boolean A0Q;
    public Boolean A0R;
    public Boolean A0S;
    public Boolean A0T;
    public Boolean A0U;
    public Boolean A0V;
    public Boolean A0W;
    public Boolean A0X;
    public Boolean A0Y;
    public Boolean A0Z;
    public Boolean A0a;
    public Boolean A0b;
    public Boolean A0c;
    public Boolean A0d;
    public Boolean A0e;
    public Boolean A0f;
    public Boolean A0g;
    public Boolean A0h;
    public Integer A0i;
    public Integer A0j;
    public Integer A0k;
    public Integer A0l;
    public Integer A0m;
    public Integer A0n;
    public Integer A0o;
    public Integer A0p;
    public Integer A0q;
    public Integer A0r;
    public Integer A0s;
    public Integer A0t;
    public Integer A0u;
    public Integer A0v;
    public Integer A0w;
    public Integer A0x;
    public Integer A0y;
    public Long A0z;
    public Long A10;
    public Long A11;
    public Long A12;
    public Long A13;
    public Long A14;
    public Long A15;
    public Long A16;
    public Long A17;
    public Long A18;
    public Long A19;
    public Long A1A;
    public Long A1B;
    public Long A1C;
    public Long A1D;
    public Long A1E;
    public Long A1F;
    public Long A1G;
    public Long A1H;
    public Long A1I;
    public Long A1J;
    public Long A1K;
    public Long A1L;
    public Long A1M;
    public Long A1N;
    public Long A1O;
    public Long A1P;
    public Long A1Q;
    public Long A1R;
    public Long A1S;
    public Long A1T;
    public Long A1U;
    public Long A1V;
    public Long A1W;
    public Long A1X;
    public Long A1Y;
    public Long A1Z;
    public Long A1a;
    public Long A1b;
    public Long A1c;
    public Long A1d;
    public Long A1e;
    public Long A1f;
    public Long A1g;
    public Long A1h;
    public Long A1i;
    public Long A1j;
    public Long A1k;
    public Long A1l;
    public Long A1m;
    public Long A1n;
    public Long A1o;
    public Long A1p;
    public Long A1q;
    public Long A1r;
    public Long A1s;
    public Long A1t;
    public Long A1u;
    public Long A1v;
    public Long A1w;
    public Long A1x;
    public Long A1y;
    public Long A1z;
    public Long A20;
    public Long A21;
    public Long A22;
    public Long A23;
    public Long A24;
    public Long A25;
    public Long A26;
    public Long A27;
    public Long A28;
    public Long A29;
    public String A2A;
    public String A2B;
    public String A2C;
    public String A2D;
    public String A2E;
    public String A2F;
    public String A2G;
    public String A2H;
    public String A2I;
    public String A2J;
    public String A2K;
    public String A2L;
    public String A2M;
    public String A2N;
    public String A2O;
    public String A2P;
    public String A2Q;
    public String A2R;
    public String A2S;
    public String A2T;
    public String A2U;
    public String A2V;
    public Long traceIdInt;

    public C0BQ() {
        super(1158, new C001800w(1, 1, 1, false), 0, -1);
    }

    @Override // X.C0BP
    public List validate() {
        C002401f c002401f = C002401f.A00;
        List listSingletonList = Collections.singletonList("ai_widget_installed");
        C000700h.A06(listSingletonList);
        ArrayList arrayListA06 = C01d.A06(new FPS("daily", ".nonnull", c002401f, listSingletonList));
        if (this.A0J == null) {
            List listSingletonList2 = Collections.singletonList("default_after_read_enabled");
            C000700h.A06(listSingletonList2);
            arrayListA06.add(new FPS("daily", ".nonnull", c002401f, listSingletonList2));
        }
        return arrayListA06;
    }

    @Override // X.C0BP
    public java.util.Map getFieldsMap() {
        LinkedHashMap linkedHashMap = new LinkedHashMap();
        linkedHashMap.put(Integer.valueOf(C26698BmO.NEWSLETTER_FOLLOWER_INVITE_MESSAGE_FIELD_NUMBER), null);
        linkedHashMap.put(11, this.A0z);
        linkedHashMap.put(12, this.A10);
        linkedHashMap.put(223, null);
        linkedHashMap.put(210, null);
        linkedHashMap.put(135, this.A2A);
        linkedHashMap.put(37, this.A11);
        linkedHashMap.put(39, this.A00);
        linkedHashMap.put(42, this.A01);
        linkedHashMap.put(41, this.A02);
        linkedHashMap.put(40, this.A03);
        linkedHashMap.put(139, this.A0i);
        linkedHashMap.put(230, this.A12);
        linkedHashMap.put(98, this.A04);
        linkedHashMap.put(49, null);
        linkedHashMap.put(167, this.A13);
        linkedHashMap.put(Integer.valueOf(C26698BmO.GROUP_STATUS_MESSAGE_V2_FIELD_NUMBER), this.A2B);
        linkedHashMap.put(212, this.A14);
        linkedHashMap.put(Integer.valueOf(C26698BmO.POLL_ADD_OPTION_MESSAGE_FIELD_NUMBER), this.A15);
        linkedHashMap.put(48, this.A05);
        linkedHashMap.put(90, this.A06);
        linkedHashMap.put(91, this.A07);
        linkedHashMap.put(89, this.A08);
        linkedHashMap.put(96, this.A09);
        linkedHashMap.put(97, this.A0A);
        linkedHashMap.put(95, this.A0B);
        linkedHashMap.put(87, this.A0C);
        linkedHashMap.put(88, this.A0D);
        linkedHashMap.put(86, this.A0E);
        linkedHashMap.put(93, this.A0F);
        linkedHashMap.put(94, this.A0G);
        linkedHashMap.put(92, this.A0H);
        linkedHashMap.put(Integer.valueOf(C26698BmO.NEWSLETTER_ADMIN_PROFILE_STATUS_MESSAGE_FIELD_NUMBER), this.A0I);
        linkedHashMap.put(231, this.A0j);
        linkedHashMap.put(10, this.A0k);
        linkedHashMap.put(138, this.A16);
        linkedHashMap.put(64, null);
        linkedHashMap.put(9, this.A0l);
        linkedHashMap.put(128, this.A0m);
        linkedHashMap.put(241, null);
        linkedHashMap.put(186, this.A17);
        linkedHashMap.put(19, this.A18);
        linkedHashMap.put(168, this.A19);
        linkedHashMap.put(35, null);
        linkedHashMap.put(36, null);
        linkedHashMap.put(161, this.A2C);
        linkedHashMap.put(200, this.A1A);
        linkedHashMap.put(201, this.A0n);
        linkedHashMap.put(238, this.A1B);
        linkedHashMap.put(216, null);
        linkedHashMap.put(181, this.A1C);
        linkedHashMap.put(182, this.A1D);
        linkedHashMap.put(217, null);
        linkedHashMap.put(218, null);
        linkedHashMap.put(219, null);
        linkedHashMap.put(85, this.A2D);
        linkedHashMap.put(247, this.A1E);
        linkedHashMap.put(68, null);
        linkedHashMap.put(67, null);
        linkedHashMap.put(65, null);
        linkedHashMap.put(66, null);
        linkedHashMap.put(206, this.A1F);
        linkedHashMap.put(248, this.A1G);
        linkedHashMap.put(249, this.A0J);
        linkedHashMap.put(140, this.A1H);
        linkedHashMap.put(214, this.A1I);
        linkedHashMap.put(228, this.A1J);
        linkedHashMap.put(153, this.A2E);
        linkedHashMap.put(174, this.A0o);
        linkedHashMap.put(134, null);
        linkedHashMap.put(166, this.A1K);
        linkedHashMap.put(Integer.valueOf(C26698BmO.STATUS_QUOTED_MESSAGE_FIELD_NUMBER), this.A1L);
        linkedHashMap.put(Integer.valueOf(C26698BmO.STATUS_STICKER_INTERACTION_MESSAGE_FIELD_NUMBER), this.A1M);
        linkedHashMap.put(Integer.valueOf(C26698BmO.NEWSLETTER_FOLLOWER_INVITE_MESSAGE_V2_FIELD_NUMBER), null);
        linkedHashMap.put(112, this.A1N);
        linkedHashMap.put(Integer.valueOf(C26698BmO.POLL_CREATION_MESSAGE_V5_FIELD_NUMBER), this.A1O);
        linkedHashMap.put(Integer.valueOf(C26698BmO.POLL_CREATION_MESSAGE_V6_FIELD_NUMBER), this.A0K);
        linkedHashMap.put(164, this.A0p);
        linkedHashMap.put(62, this.A1P);
        linkedHashMap.put(43, this.A0L);
        linkedHashMap.put(79, this.A1Q);
        linkedHashMap.put(175, null);
        linkedHashMap.put(Integer.valueOf(MediaCodecVideoEncoder.MIN_ENCODER_WIDTH), null);
        linkedHashMap.put(177, null);
        linkedHashMap.put(187, this.A0M);
        linkedHashMap.put(222, this.A0N);
        linkedHashMap.put(190, this.A1R);
        linkedHashMap.put(120, this.A2F);
        linkedHashMap.put(Integer.valueOf(C26698BmO.NEWSLETTER_ADMIN_PROFILE_MESSAGE_FIELD_NUMBER), null);
        linkedHashMap.put(137, this.A1S);
        linkedHashMap.put(Integer.valueOf(C26698BmO.POLL_RESULT_SNAPSHOT_MESSAGE_V3_FIELD_NUMBER), this.A1T);
        linkedHashMap.put(114, this.A1U);
        linkedHashMap.put(260, this.A1V);
        linkedHashMap.put(261, this.A2G);
        linkedHashMap.put(234, this.A0O);
        linkedHashMap.put(202, this.A0P);
        linkedHashMap.put(183, this.A0Q);
        linkedHashMap.put(184, this.A0R);
        linkedHashMap.put(46, this.A0S);
        linkedHashMap.put(47, null);
        linkedHashMap.put(78, this.A0T);
        linkedHashMap.put(195, null);
        linkedHashMap.put(60, this.A0U);
        linkedHashMap.put(61, this.A0V);
        linkedHashMap.put(38, this.A0W);
        linkedHashMap.put(154, this.A2H);
        linkedHashMap.put(82, null);
        linkedHashMap.put(84, null);
        linkedHashMap.put(83, null);
        linkedHashMap.put(5, this.A2I);
        linkedHashMap.put(63, this.A1W);
        linkedHashMap.put(185, this.A1X);
        linkedHashMap.put(44, this.A0X);
        linkedHashMap.put(258, null);
        linkedHashMap.put(253, this.A1Y);
        linkedHashMap.put(254, this.A1Z);
        linkedHashMap.put(6, this.A2J);
        linkedHashMap.put(171, this.A0Y);
        linkedHashMap.put(160, this.A1a);
        linkedHashMap.put(Integer.valueOf(C26698BmO.PAYMENT_REMINDER_MESSAGE_FIELD_NUMBER), null);
        linkedHashMap.put(244, this.A0q);
        linkedHashMap.put(21, this.A1b);
        linkedHashMap.put(20, this.A1c);
        linkedHashMap.put(188, this.A0r);
        linkedHashMap.put(239, null);
        linkedHashMap.put(198, this.A0s);
        linkedHashMap.put(199, this.A0t);
        linkedHashMap.put(220, this.A0Z);
        linkedHashMap.put(221, this.A2K);
        linkedHashMap.put(155, this.A0a);
        linkedHashMap.put(205, this.A0b);
        linkedHashMap.put(7, this.A0c);
        linkedHashMap.put(159, null);
        linkedHashMap.put(163, this.A1d);
        linkedHashMap.put(178, null);
        linkedHashMap.put(179, null);
        linkedHashMap.put(180, null);
        linkedHashMap.put(250, this.A1e);
        linkedHashMap.put(4, this.A2L);
        linkedHashMap.put(Integer.valueOf(C26698BmO.SPOILER_MESSAGE_FIELD_NUMBER), this.A0u);
        linkedHashMap.put(191, this.A1f);
        linkedHashMap.put(Integer.valueOf(C26698BmO.MESSAGE_HISTORY_NOTICE_FIELD_NUMBER), this.A2M);
        linkedHashMap.put(Integer.valueOf(WAHucClient.HTTP_STATUS_NO_CONTENT), this.A2N);
        linkedHashMap.put(165, this.A0d);
        linkedHashMap.put(100, this.A0e);
        linkedHashMap.put(Integer.valueOf(C26698BmO.MUSIC_MESSAGE_FIELD_NUMBER), null);
        linkedHashMap.put(209, null);
        linkedHashMap.put(Integer.valueOf(ByteString.UNSIGNED_BYTE_MASK), this.A0v);
        linkedHashMap.put(229, this.A2O);
        linkedHashMap.put(57, this.A1g);
        linkedHashMap.put(58, this.A1h);
        linkedHashMap.put(56, this.A1i);
        linkedHashMap.put(Integer.valueOf(C26698BmO.BOT_FORWARDED_MESSAGE_FIELD_NUMBER), null);
        linkedHashMap.put(52, this.A1j);
        linkedHashMap.put(50, this.A1k);
        linkedHashMap.put(53, this.A1l);
        linkedHashMap.put(252, this.A1m);
        linkedHashMap.put(59, this.A1n);
        linkedHashMap.put(55, this.A1o);
        linkedHashMap.put(51, this.A1p);
        linkedHashMap.put(54, this.A1q);
        linkedHashMap.put(156, this.A1r);
        linkedHashMap.put(251, null);
        linkedHashMap.put(162, this.A2P);
        linkedHashMap.put(224, this.A2Q);
        linkedHashMap.put(227, this.A2R);
        linkedHashMap.put(141, null);
        linkedHashMap.put(142, null);
        linkedHashMap.put(235, null);
        linkedHashMap.put(143, null);
        linkedHashMap.put(Integer.valueOf(MediaCodecVideoEncoder.MIN_ENCODER_HEIGHT), null);
        linkedHashMap.put(145, null);
        linkedHashMap.put(146, null);
        linkedHashMap.put(225, this.A0w);
        linkedHashMap.put(226, this.A0x);
        linkedHashMap.put(147, null);
        linkedHashMap.put(148, null);
        linkedHashMap.put(Integer.valueOf(WaTextView.ONE_LINE_DISPLAY_TEXT_LENGTH_LIMIT), null);
        linkedHashMap.put(151, null);
        linkedHashMap.put(152, null);
        linkedHashMap.put(211, this.A1s);
        linkedHashMap.put(8, this.A0f);
        linkedHashMap.put(262, this.A2S);
        linkedHashMap.put(70, null);
        linkedHashMap.put(69, null);
        linkedHashMap.put(172, this.A0g);
        linkedHashMap.put(173, this.A0h);
        linkedHashMap.put(77, this.A2T);
        linkedHashMap.put(2, null);
        linkedHashMap.put(3, null);
        linkedHashMap.put(243, this.A1t);
        linkedHashMap.put(256, null);
        linkedHashMap.put(257, null);
        linkedHashMap.put(31, this.A1u);
        linkedHashMap.put(136, this.A1v);
        linkedHashMap.put(32, this.A1w);
        linkedHashMap.put(169, this.A2U);
        linkedHashMap.put(170, this.A2V);
        linkedHashMap.put(192, this.A1x);
        linkedHashMap.put(259, null);
        linkedHashMap.put(127, this.A1y);
        linkedHashMap.put(193, this.A1z);
        linkedHashMap.put(194, this.A20);
        linkedHashMap.put(232, this.A21);
        linkedHashMap.put(233, this.A22);
        linkedHashMap.put(240, this.traceIdInt);
        linkedHashMap.put(215, null);
        linkedHashMap.put(236, this.A23);
        linkedHashMap.put(213, this.A24);
        linkedHashMap.put(245, this.A25);
        linkedHashMap.put(237, this.A26);
        linkedHashMap.put(242, this.A0y);
        linkedHashMap.put(246, this.A27);
        linkedHashMap.put(23, this.A28);
        linkedHashMap.put(22, this.A29);
        linkedHashMap.put(207, null);
        linkedHashMap.put(208, null);
        return linkedHashMap;
    }

    @Override // X.C0BP
    public java.util.Map getFieldsMapForFalco() {
        LinkedHashMap linkedHashMap = new LinkedHashMap();
        linkedHashMap.put("accessibility_voiceover", null);
        linkedHashMap.put("addressbook_size", this.A0z);
        linkedHashMap.put("addressbook_whatsapp_size", this.A10);
        linkedHashMap.put("ai_memory_saved_cnt", null);
        linkedHashMap.put("ai_widget_installed", null);
        linkedHashMap.put("android_advertising_id", this.A2A);
        linkedHashMap.put("android_api_level", this.A11);
        linkedHashMap.put("android_has_sd_card", this.A00);
        linkedHashMap.put("android_is_jid_google_drive_capable", this.A01);
        linkedHashMap.put("android_is_jid_google_drive_eligible", this.A02);
        linkedHashMap.put("android_is_sd_card_removable", this.A03);
        Integer num = this.A0i;
        if (num != null && num.intValue() != 0) {
            linkedHashMap.put("android_keystore_state", num);
        }
        linkedHashMap.put("android_main_thread_post_count", this.A12);
        linkedHashMap.put("android_ram_low", this.A04);
        linkedHashMap.put("android_video_transcode_supported", null);
        linkedHashMap.put("android_xmpp_workers_runtime", this.A13);
        linkedHashMap.put("app_code_hash", this.A2B);
        linkedHashMap.put("app_last_open_timestamp", this.A14);
        linkedHashMap.put("app_standby_bucket", this.A15);
        linkedHashMap.put("app_using_forced_locale", this.A05);
        linkedHashMap.put("auto_dl_audio_cellular", this.A06);
        linkedHashMap.put("auto_dl_audio_roaming", this.A07);
        linkedHashMap.put("auto_dl_audio_wifi", this.A08);
        linkedHashMap.put("auto_dl_doc_cellular", this.A09);
        linkedHashMap.put("auto_dl_doc_roaming", this.A0A);
        linkedHashMap.put("auto_dl_doc_wifi", this.A0B);
        linkedHashMap.put("auto_dl_image_cellular", this.A0C);
        linkedHashMap.put("auto_dl_image_roaming", this.A0D);
        linkedHashMap.put("auto_dl_image_wifi", this.A0E);
        linkedHashMap.put("auto_dl_video_cellular", this.A0F);
        linkedHashMap.put("auto_dl_video_roaming", this.A0G);
        linkedHashMap.put("auto_dl_video_wifi", this.A0H);
        linkedHashMap.put("background_restricted", this.A0I);
        Integer num2 = this.A0j;
        if (num2 != null && num2.intValue() != 0) {
            linkedHashMap.put("backup_encryption_method", num2);
        }
        linkedHashMap.put("backup_network_setting", this.A0k);
        linkedHashMap.put("backup_restore_encryption_version", this.A16);
        linkedHashMap.put("backup_schedule", this.A0l);
        Integer num3 = this.A0m;
        if (num3 != null && num3.intValue() != 0) {
            linkedHashMap.put("bg_data_restriction", num3);
        }
        linkedHashMap.put("canonical_ent_last_validation_ts_ms", null);
        linkedHashMap.put("channels_media_folder_size", this.A17);
        linkedHashMap.put("chat_database_size", this.A18);
        linkedHashMap.put("chat_lock_folder_count", this.A19);
        linkedHashMap.put("class_count", null);
        linkedHashMap.put("class_names", null);
        linkedHashMap.put("classpath_hash", this.A2C);
        linkedHashMap.put("contacts_created_on_whatsapp_size", this.A1A);
        Integer num4 = this.A0n;
        if (num4 != null && num4.intValue() != 0) {
            linkedHashMap.put("contacts_permission_authorization_status", num4);
        }
        linkedHashMap.put("contacts_requiring_sync_before_display_size", this.A1B);
        linkedHashMap.put("count_1on1_threads", null);
        linkedHashMap.put("count_ephemeral_threads", this.A1C);
        linkedHashMap.put("count_ephemeral_threads_enabled_by_me", this.A1D);
        linkedHashMap.put("count_group_threads", null);
        linkedHashMap.put("count_limit_sharing_1on1_threads", null);
        linkedHashMap.put("count_limit_sharing_group_threads", null);
        linkedHashMap.put("cpu_abi", this.A2D);
        linkedHashMap.put("daily_passkey_count", this.A1E);
        linkedHashMap.put("database_dump_and_restore_after_reindex_result", null);
        linkedHashMap.put("database_integrity_check_result", null);
        linkedHashMap.put("database_restore_succeeded_eventually", null);
        linkedHashMap.put("database_restore_succeeded_on_first_backup_file", null);
        linkedHashMap.put("db_addressbook_table_size", this.A1F);
        linkedHashMap.put("default_after_read_duration", this.A1G);
        linkedHashMap.put("default_after_read_enabled", this.A0J);
        linkedHashMap.put("default_disappearing_duration", this.A1H);
        linkedHashMap.put("defense_mode", this.A1I);
        linkedHashMap.put("deprecated_contacts_size", this.A1J);
        linkedHashMap.put("device_language", this.A2E);
        Integer num5 = this.A0o;
        if (num5 != null && num5.intValue() != 0) {
            linkedHashMap.put("email_state", num5);
        }
        linkedHashMap.put("ent_security_notifications_enabled", null);
        linkedHashMap.put("experiment_tmo_preload_group_daily", this.A1K);
        linkedHashMap.put("external_storage_avail_size", this.A1L);
        linkedHashMap.put("external_storage_total_size", this.A1M);
        linkedHashMap.put("favorited_animated_sticker_count", null);
        linkedHashMap.put("favorited_first_party_sticker_count", this.A1N);
        linkedHashMap.put("favorited_total_sticker_count", this.A1O);
        linkedHashMap.put("fingerprint_lock_enabled", this.A0K);
        Integer num6 = this.A0p;
        if (num6 != null && num6.intValue() != 0) {
            linkedHashMap.put("gallery_permission", num6);
        }
        linkedHashMap.put("google_account_count", this.A1P);
        linkedHashMap.put("google_play_services_available", this.A0L);
        linkedHashMap.put("google_play_services_version", this.A1Q);
        linkedHashMap.put("has_textstatus_emoji_modified_24h", null);
        linkedHashMap.put("has_textstatus_modified_24h", null);
        linkedHashMap.put("has_textstatus_text_modified_24h", null);
        linkedHashMap.put("has_username", this.A0M);
        linkedHashMap.put("has_username_pin", this.A0N);
        linkedHashMap.put("in_network_contacts_size", this.A1R);
        linkedHashMap.put("install_source", this.A2F);
        linkedHashMap.put("installed_animated_sticker_pack_count", null);
        linkedHashMap.put("installed_animated_third_party_sticker_pack_count", this.A1S);
        linkedHashMap.put("installed_first_party_sticker_pack_count", this.A1T);
        linkedHashMap.put("installed_total_sticker_pack_count", this.A1U);
        linkedHashMap.put("interop_contacts_size", this.A1V);
        linkedHashMap.put("interop_contacts_size_per_integrator", this.A2G);
        linkedHashMap.put("is_canonical_ent_present", this.A0O);
        linkedHashMap.put("is_contact_sync_to_os_default_on", this.A0P);
        linkedHashMap.put("is_default_disappearing_messaging_user", this.A0Q);
        linkedHashMap.put("is_ephemeral_messaging_user", this.A0R);
        linkedHashMap.put("is_genymotion", this.A0S);
        linkedHashMap.put("is_group_create_banner_shown", null);
        linkedHashMap.put("is_monkeyrunner_running", this.A0T);
        linkedHashMap.put("is_profile_photo_set", null);
        linkedHashMap.put("is_rooted", this.A0U);
        linkedHashMap.put("is_using_custom_rom", this.A0V);
        linkedHashMap.put("is_whatsapp_plus_user", this.A0W);
        linkedHashMap.put("keyboard_language", this.A2H);
        linkedHashMap.put("labels_table_label_count", null);
        linkedHashMap.put("labels_table_labeled_contacts_count", null);
        linkedHashMap.put("labels_table_labeled_messages_count", null);
        linkedHashMap.put("language_code", this.A2I);
        linkedHashMap.put("last_backup_timestamp", this.A1W);
        linkedHashMap.put("last_cloud_backup_size", this.A1X);
        linkedHashMap.put("libc_qemu_present", this.A0X);
        linkedHashMap.put("lid_raw_contact_id", null);
        linkedHashMap.put("lid_to_pn_mapping_count", this.A1Y);
        linkedHashMap.put("lid_to_username_mapping_count", this.A1Z);
        linkedHashMap.put("location_code", this.A2J);
        linkedHashMap.put("lock_folder_hidden", this.A0Y);
        linkedHashMap.put("lowest_app_standby_bucket", this.A1a);
        linkedHashMap.put("md_pair_time", null);
        linkedHashMap.put("media_auto_download_quality_setting", this.A0q);
        linkedHashMap.put("media_folder_file_count", this.A1b);
        linkedHashMap.put("media_folder_size", this.A1c);
        linkedHashMap.put("media_quality_setting", this.A0r);
        linkedHashMap.put("media_size_cache_age_seconds", null);
        linkedHashMap.put("meta_ai_model_actual", this.A0s);
        linkedHashMap.put("meta_ai_model_selected", this.A0t);
        linkedHashMap.put("meta_ai_voice_default_on", this.A0Z);
        linkedHashMap.put("meta_ai_voice_selection", this.A2K);
        linkedHashMap.put("modified_internal_props", this.A0a);
        linkedHashMap.put("native_contacts_global_setting_enabled", this.A0b);
        linkedHashMap.put("network_is_roaming", this.A0c);
        linkedHashMap.put("network_operator_name", null);
        linkedHashMap.put("num_accounts", this.A1d);
        linkedHashMap.put("num_contacts_with_textstatus_24h", null);
        linkedHashMap.put("num_contacts_with_textstatus_emoji_24h", null);
        linkedHashMap.put("num_contacts_with_textstatus_text_24h", null);
        linkedHashMap.put("number_of_sim", this.A1e);
        linkedHashMap.put("os_build_number", this.A2L);
        Integer num7 = this.A0u;
        if (num7 != null && num7.intValue() != 0) {
            linkedHashMap.put("os_notification_setting", num7);
        }
        linkedHashMap.put("out_of_network_contacts_size", this.A1f);
        linkedHashMap.put("package_name", this.A2M);
        linkedHashMap.put("package_source", this.A2N);
        linkedHashMap.put("passkey_exists", this.A0d);
        linkedHashMap.put("payments_is_enabled", this.A0e);
        linkedHashMap.put("percent_contact_with_prekeys", null);
        linkedHashMap.put("peripheral_connected", null);
        linkedHashMap.put("peripheral_display_connectivity_type", this.A0v);
        linkedHashMap.put("peripheral_linked_product_line", this.A2O);
        linkedHashMap.put("permission_access_coarse_location", this.A1g);
        linkedHashMap.put("permission_access_fine_location", this.A1h);
        linkedHashMap.put("permission_camera", this.A1i);
        linkedHashMap.put("permission_contacts", null);
        linkedHashMap.put("permission_get_accounts", this.A1j);
        linkedHashMap.put("permission_read_contacts", this.A1k);
        linkedHashMap.put("permission_read_external_storage", this.A1l);
        linkedHashMap.put("permission_read_media_audio", this.A1m);
        linkedHashMap.put("permission_receive_sms", this.A1n);
        linkedHashMap.put("permission_record_audio", this.A1o);
        linkedHashMap.put("permission_write_contacts", this.A1p);
        linkedHashMap.put("permission_write_external_storage", this.A1q);
        linkedHashMap.put("phone_cores", this.A1r);
        linkedHashMap.put("phone_number_hint_available_count", null);
        linkedHashMap.put("phoneyid", this.A2P);
        linkedHashMap.put("preloads_app_manager_id", this.A2Q);
        linkedHashMap.put("preloads_attribution_json", this.A2R);
        Integer num8 = this.A0w;
        if (num8 != null && num8.intValue() != 0) {
            linkedHashMap.put("privacy_settings_profile_links", num8);
        }
        Integer num9 = this.A0x;
        if (num9 != null && num9.intValue() != 0) {
            linkedHashMap.put("privacy_settings_profile_links_except_num", num9);
        }
        linkedHashMap.put("profile_links_count", this.A1s);
        linkedHashMap.put("receipts_enabled", this.A0f);
        linkedHashMap.put("received_experience_ids", this.A2S);
        linkedHashMap.put("restore_screen_load_time", null);
        linkedHashMap.put("restore_time_backup_files_count", null);
        linkedHashMap.put("secret_code_active", this.A0g);
        linkedHashMap.put("show_meta_ai_button_setting", this.A0h);
        linkedHashMap.put("signature_hash", this.A2T);
        linkedHashMap.put("sim_mcc", null);
        linkedHashMap.put("sim_mnc", null);
        linkedHashMap.put("sim_phone_number_matched", this.A1t);
        linkedHashMap.put("stickers_folder_file_count", null);
        linkedHashMap.put("stickers_folder_size", null);
        linkedHashMap.put("storage_avail_size", this.A1u);
        linkedHashMap.put("storage_avail_size_with_cache", this.A1v);
        linkedHashMap.put("storage_total_size", this.A1w);
        linkedHashMap.put("supported_decoders", this.A2U);
        linkedHashMap.put("supported_encoders", this.A2V);
        linkedHashMap.put("synced_in_network_contacts_size", this.A1x);
        linkedHashMap.put("text_message_animation_enabled", null);
        linkedHashMap.put("time_delta_since_last_event", this.A1y);
        linkedHashMap.put("total_count_in_network_unique_phone_number", this.A1z);
        linkedHashMap.put("total_count_synced_in_network_unique_phone_number", this.A20);
        linkedHashMap.put("total_missed_calls", this.A21);
        linkedHashMap.put("total_unread_messages", this.A22);
        linkedHashMap.put("trace_id_int", this.traceIdInt);
        linkedHashMap.put("traffic_anonymization", null);
        linkedHashMap.put("unique_phone_number_contacts_size_with_username", this.A23);
        linkedHashMap.put("unread_badge_frequency", this.A24);
        linkedHashMap.put("unverified_profile_links_count", this.A25);
        linkedHashMap.put("username_only_contacts_size", this.A26);
        Integer num10 = this.A0y;
        if (num10 != null && num10.intValue() != 0) {
            linkedHashMap.put("username_state", num10);
        }
        linkedHashMap.put("verified_profile_links_count", this.A27);
        linkedHashMap.put("video_folder_file_count", this.A28);
        linkedHashMap.put("video_folder_size", this.A29);
        linkedHashMap.put("webc_contacts_table_size", null);
        linkedHashMap.put("webc_filtered_contacts_size", null);
        return linkedHashMap;
    }

    @Override // X.C0BP
    public java.util.Map getFieldsMapForLogging() {
        return null;
    }

    @Override // X.C0BP
    public int internalFalcoMigrationBatchNumber() {
        return 12;
    }

    @Override // X.C0BP
    public void serialize(InterfaceC79783iN interfaceC79783iN) {
        throw new NullPointerException("serialize");
    }

    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("WamDaily {");
        C0BR.A00(this.A0z, "addressbookSize", sb);
        C0BR.A00(this.A10, "addressbookWhatsappSize", sb);
        C0BR.A00(this.A2A, "androidAdvertisingId", sb);
        C0BR.A00(this.A11, "androidApiLevel", sb);
        C0BR.A00(this.A00, "androidHasSdCard", sb);
        C0BR.A00(this.A01, "androidIsJidGoogleDriveCapable", sb);
        C0BR.A00(this.A02, "androidIsJidGoogleDriveEligible", sb);
        C0BR.A00(this.A03, "androidIsSdCardRemovable", sb);
        Integer num = this.A0i;
        C0BR.A00(num == null ? null : num.toString(), "androidKeystoreState", sb);
        C0BR.A00(this.A12, "androidMainThreadPostCount", sb);
        C0BR.A00(this.A04, "androidRamLow", sb);
        C0BR.A00(this.A13, "androidXmppWorkersRuntime", sb);
        C0BR.A00(this.A2B, "appCodeHash", sb);
        C0BR.A00(this.A14, "appLastOpenTimestamp", sb);
        C0BR.A00(this.A15, "appStandbyBucket", sb);
        C0BR.A00(this.A05, "appUsingForcedLocale", sb);
        C0BR.A00(this.A06, "autoDlAudioCellular", sb);
        C0BR.A00(this.A07, "autoDlAudioRoaming", sb);
        C0BR.A00(this.A08, "autoDlAudioWifi", sb);
        C0BR.A00(this.A09, "autoDlDocCellular", sb);
        C0BR.A00(this.A0A, "autoDlDocRoaming", sb);
        C0BR.A00(this.A0B, "autoDlDocWifi", sb);
        C0BR.A00(this.A0C, "autoDlImageCellular", sb);
        C0BR.A00(this.A0D, "autoDlImageRoaming", sb);
        C0BR.A00(this.A0E, "autoDlImageWifi", sb);
        C0BR.A00(this.A0F, "autoDlVideoCellular", sb);
        C0BR.A00(this.A0G, "autoDlVideoRoaming", sb);
        C0BR.A00(this.A0H, "autoDlVideoWifi", sb);
        C0BR.A00(this.A0I, "backgroundRestricted", sb);
        Integer num2 = this.A0j;
        C0BR.A00(num2 == null ? null : num2.toString(), "backupEncryptionMethod", sb);
        Integer num3 = this.A0k;
        C0BR.A00(num3 == null ? null : num3.toString(), "backupNetworkSetting", sb);
        C0BR.A00(this.A16, "backupRestoreEncryptionVersion", sb);
        Integer num4 = this.A0l;
        C0BR.A00(num4 == null ? null : num4.toString(), "backupSchedule", sb);
        Integer num5 = this.A0m;
        C0BR.A00(num5 == null ? null : num5.toString(), "bgDataRestriction", sb);
        C0BR.A00(this.A17, "channelsMediaFolderSize", sb);
        C0BR.A00(this.A18, "chatDatabaseSize", sb);
        C0BR.A00(this.A19, "chatLockFolderCount", sb);
        C0BR.A00(this.A2C, "classpathHash", sb);
        C0BR.A00(this.A1A, "contactsCreatedOnWhatsappSize", sb);
        Integer num6 = this.A0n;
        C0BR.A00(num6 == null ? null : num6.toString(), "contactsPermissionAuthorizationStatus", sb);
        C0BR.A00(this.A1B, "contactsRequiringSyncBeforeDisplaySize", sb);
        C0BR.A00(this.A1C, "countEphemeralThreads", sb);
        C0BR.A00(this.A1D, "countEphemeralThreadsEnabledByMe", sb);
        C0BR.A00(this.A2D, "cpuAbi", sb);
        C0BR.A00(this.A1E, "dailyPasskeyCount", sb);
        C0BR.A00(this.A1F, "dbAddressbookTableSize", sb);
        C0BR.A00(this.A1G, "defaultAfterReadDuration", sb);
        C0BR.A00(this.A0J, "defaultAfterReadEnabled", sb);
        C0BR.A00(this.A1H, "defaultDisappearingDuration", sb);
        C0BR.A00(this.A1I, "defenseMode", sb);
        C0BR.A00(this.A1J, "deprecatedContactsSize", sb);
        C0BR.A00(this.A2E, "deviceLanguage", sb);
        Integer num7 = this.A0o;
        C0BR.A00(num7 == null ? null : num7.toString(), "emailState", sb);
        C0BR.A00(this.A1K, "experimentTmoPreloadGroupDaily", sb);
        C0BR.A00(this.A1L, "externalStorageAvailSize", sb);
        C0BR.A00(this.A1M, "externalStorageTotalSize", sb);
        C0BR.A00(this.A1N, "favoritedFirstPartyStickerCount", sb);
        C0BR.A00(this.A1O, "favoritedTotalStickerCount", sb);
        C0BR.A00(this.A0K, "fingerprintLockEnabled", sb);
        Integer num8 = this.A0p;
        C0BR.A00(num8 == null ? null : num8.toString(), "galleryPermission", sb);
        C0BR.A00(this.A1P, "googleAccountCount", sb);
        C0BR.A00(this.A0L, "googlePlayServicesAvailable", sb);
        C0BR.A00(this.A1Q, "googlePlayServicesVersion", sb);
        C0BR.A00(this.A0M, "hasUsername", sb);
        C0BR.A00(this.A0N, "hasUsernamePin", sb);
        C0BR.A00(this.A1R, "inNetworkContactsSize", sb);
        C0BR.A00(this.A2F, "installSource", sb);
        C0BR.A00(this.A1S, "installedAnimatedThirdPartyStickerPackCount", sb);
        C0BR.A00(this.A1T, "installedFirstPartyStickerPackCount", sb);
        C0BR.A00(this.A1U, "installedTotalStickerPackCount", sb);
        C0BR.A00(this.A1V, "interopContactsSize", sb);
        C0BR.A00(this.A2G, "interopContactsSizePerIntegrator", sb);
        C0BR.A00(this.A0O, "isCanonicalEntPresent", sb);
        C0BR.A00(this.A0P, "isContactSyncToOsDefaultOn", sb);
        C0BR.A00(this.A0Q, "isDefaultDisappearingMessagingUser", sb);
        C0BR.A00(this.A0R, "isEphemeralMessagingUser", sb);
        C0BR.A00(this.A0S, "isGenymotion", sb);
        C0BR.A00(this.A0T, "isMonkeyrunnerRunning", sb);
        C0BR.A00(this.A0U, "isRooted", sb);
        C0BR.A00(this.A0V, "isUsingCustomRom", sb);
        C0BR.A00(this.A0W, "isWhatsappPlusUser", sb);
        C0BR.A00(this.A2H, "keyboardLanguage", sb);
        C0BR.A00(this.A2I, "languageCode", sb);
        C0BR.A00(this.A1W, "lastBackupTimestamp", sb);
        C0BR.A00(this.A1X, "lastCloudBackupSize", sb);
        C0BR.A00(this.A0X, "libcQemuPresent", sb);
        C0BR.A00(this.A1Y, "lidToPnMappingCount", sb);
        C0BR.A00(this.A1Z, "lidToUsernameMappingCount", sb);
        C0BR.A00(this.A2J, "locationCode", sb);
        C0BR.A00(this.A0Y, "lockFolderHidden", sb);
        C0BR.A00(this.A1a, "lowestAppStandbyBucket", sb);
        Integer num9 = this.A0q;
        C0BR.A00(num9 == null ? null : num9.toString(), "mediaAutoDownloadQualitySetting", sb);
        C0BR.A00(this.A1b, "mediaFolderFileCount", sb);
        C0BR.A00(this.A1c, "mediaFolderSize", sb);
        Integer num10 = this.A0r;
        C0BR.A00(num10 == null ? null : num10.toString(), "mediaQualitySetting", sb);
        Integer num11 = this.A0s;
        C0BR.A00(num11 == null ? null : num11.toString(), "metaAiModelActual", sb);
        Integer num12 = this.A0t;
        C0BR.A00(num12 == null ? null : num12.toString(), "metaAiModelSelected", sb);
        C0BR.A00(this.A0Z, "metaAiVoiceDefaultOn", sb);
        C0BR.A00(this.A2K, "metaAiVoiceSelection", sb);
        C0BR.A00(this.A0a, "modifiedInternalProps", sb);
        C0BR.A00(this.A0b, "nativeContactsGlobalSettingEnabled", sb);
        C0BR.A00(this.A0c, "networkIsRoaming", sb);
        C0BR.A00(this.A1d, "numAccounts", sb);
        C0BR.A00(this.A1e, "numberOfSim", sb);
        C0BR.A00(this.A2L, "osBuildNumber", sb);
        Integer num13 = this.A0u;
        C0BR.A00(num13 == null ? null : num13.toString(), "osNotificationSetting", sb);
        C0BR.A00(this.A1f, "outOfNetworkContactsSize", sb);
        C0BR.A00(this.A2M, "packageName", sb);
        C0BR.A00(this.A2N, "packageSource", sb);
        C0BR.A00(this.A0d, "passkeyExists", sb);
        C0BR.A00(this.A0e, "paymentsIsEnabled", sb);
        Integer num14 = this.A0v;
        C0BR.A00(num14 == null ? null : num14.toString(), "peripheralDisplayConnectivityType", sb);
        C0BR.A00(this.A2O, "peripheralLinkedProductLine", sb);
        C0BR.A00(this.A1g, "permissionAccessCoarseLocation", sb);
        C0BR.A00(this.A1h, "permissionAccessFineLocation", sb);
        C0BR.A00(this.A1i, "permissionCamera", sb);
        C0BR.A00(this.A1j, "permissionGetAccounts", sb);
        C0BR.A00(this.A1k, "permissionReadContacts", sb);
        C0BR.A00(this.A1l, "permissionReadExternalStorage", sb);
        C0BR.A00(this.A1m, "permissionReadMediaAudio", sb);
        C0BR.A00(this.A1n, "permissionReceiveSms", sb);
        C0BR.A00(this.A1o, "permissionRecordAudio", sb);
        C0BR.A00(this.A1p, "permissionWriteContacts", sb);
        C0BR.A00(this.A1q, "permissionWriteExternalStorage", sb);
        C0BR.A00(this.A1r, "phoneCores", sb);
        C0BR.A00(this.A2P, "phoneyid", sb);
        C0BR.A00(this.A2Q, "preloadsAppManagerId", sb);
        C0BR.A00(this.A2R, "preloadsAttributionJson", sb);
        Integer num15 = this.A0w;
        C0BR.A00(num15 == null ? null : num15.toString(), "privacySettingsProfileLinks", sb);
        Integer num16 = this.A0x;
        C0BR.A00(num16 == null ? null : num16.toString(), "privacySettingsProfileLinksExceptNum", sb);
        C0BR.A00(this.A1s, "profileLinksCount", sb);
        C0BR.A00(this.A0f, "receiptsEnabled", sb);
        C0BR.A00(this.A2S, "receivedExperienceIds", sb);
        C0BR.A00(this.A0g, "secretCodeActive", sb);
        C0BR.A00(this.A0h, "showMetaAiButtonSetting", sb);
        C0BR.A00(this.A2T, "signatureHash", sb);
        C0BR.A00(this.A1t, "simPhoneNumberMatched", sb);
        C0BR.A00(this.A1u, "storageAvailSize", sb);
        C0BR.A00(this.A1v, "storageAvailSizeWithCache", sb);
        C0BR.A00(this.A1w, "storageTotalSize", sb);
        C0BR.A00(this.A2U, "supportedDecoders", sb);
        C0BR.A00(this.A2V, "supportedEncoders", sb);
        C0BR.A00(this.A1x, "syncedInNetworkContactsSize", sb);
        C0BR.A00(this.A1y, "timeDeltaSinceLastEvent", sb);
        C0BR.A00(this.A1z, "totalCountInNetworkUniquePhoneNumber", sb);
        C0BR.A00(this.A20, "totalCountSyncedInNetworkUniquePhoneNumber", sb);
        C0BR.A00(this.A21, "totalMissedCalls", sb);
        C0BR.A00(this.A22, "totalUnreadMessages", sb);
        C0BR.A00(this.traceIdInt, "traceIdInt", sb);
        C0BR.A00(this.A23, "uniquePhoneNumberContactsSizeWithUsername", sb);
        C0BR.A00(this.A24, "unreadBadgeFrequency", sb);
        C0BR.A00(this.A25, "unverifiedProfileLinksCount", sb);
        C0BR.A00(this.A26, "usernameOnlyContactsSize", sb);
        Integer num17 = this.A0y;
        C0BR.A00(num17 == null ? null : num17.toString(), "usernameState", sb);
        C0BR.A00(this.A27, "verifiedProfileLinksCount", sb);
        C0BR.A00(this.A28, "videoFolderFileCount", sb);
        C0BR.A00(this.A29, "videoFolderSize", sb);
        sb.append("}");
        String string = sb.toString();
        C000700h.A06(string);
        return string;
    }

    @Override // X.C0BP
    public String getEventNameForFalco() {
        return "wam_daily";
    }
}
