package X;

import android.content.res.ColorStateList;
import android.graphics.Typeface;
import android.text.TextUtils;

/* JADX INFO: renamed from: X.6Ae, reason: invalid class name and case insensitive filesystem */
/* JADX INFO: loaded from: classes4.dex */
public final class C138866Ae implements Cloneable {
    public float A00;
    public float A01;
    public float A02;
    public float A03;
    public float A06;
    public float A07;
    public float A08;
    public float A09;
    public float A0A;
    public int A0D;
    public int A0E;
    public int A0F;
    public int A0G;
    public int A0H;
    public int A0Q;
    public int A0R;
    public ColorStateList A0V;
    public Typeface A0W;
    public TextUtils.TruncateAt A0X;
    public InterfaceC05670Pa A0Y;
    public C117875Pd A0a;
    public CharSequence A0c;
    public String A0e;
    public boolean A0h;
    public boolean A0i;
    public boolean A0j;
    public boolean A0k;
    public boolean A0l;
    public boolean A0g = true;
    public int A0P = Integer.MIN_VALUE;
    public int A0M = Integer.MAX_VALUE;
    public int A0O = -1;
    public int A0L = -1;
    public int A0N = Integer.MAX_VALUE;
    public int A0S = -7829368;
    public int A0I = -16776961;
    public int A0T = -1;
    public float A04 = Float.MAX_VALUE;
    public float A05 = 1.0f;
    public int A0U = Typeface.DEFAULT.getStyle();
    public EnumC96684aK A0Z = EnumC96684aK.A07;
    public int A0C = -1;
    public boolean A0f = true;
    public C4ZI A0b = C4ZI.A03;
    public int A0J = Integer.MIN_VALUE;
    public int A0K = Integer.MIN_VALUE;
    public Integer A0d = C02S.A01;
    public int A0B = -16777216;

    public final C138866Ae A00() {
        try {
            Object objClone = super.clone();
            C000700h.A0D(objClone, "null cannot be cast to non-null type com.facebook.rendercore.text.TextStyle");
            return (C138866Ae) objClone;
        } catch (CloneNotSupportedException e) {
            throw AbstractC81763lf.A0u(e);
        }
    }

    public Object clone() {
        return super.clone();
    }

    public String toString() {
        StringBuilder sbA08 = AnonymousClass000.A08();
        sbA08.append("TextStyle(");
        sbA08.append("ellipsize=");
        sbA08.append(this.A0X);
        sbA08.append(", ");
        sbA08.append("customEllipsisText=");
        sbA08.append(this.A0c);
        sbA08.append(", ");
        sbA08.append("includeFontPadding=");
        sbA08.append(this.A0g);
        sbA08.append(", ");
        sbA08.append("minLines=");
        sbA08.append(this.A0P);
        sbA08.append(", ");
        sbA08.append("maxLines=");
        sbA08.append(this.A0M);
        sbA08.append(", ");
        sbA08.append("minEms=");
        sbA08.append(this.A0O);
        sbA08.append(", ");
        sbA08.append("maxEms=");
        sbA08.append(this.A0L);
        sbA08.append(", ");
        sbA08.append("minTextWidth=");
        sbA08.append(this.A0Q);
        sbA08.append(", ");
        sbA08.append("maxTextWidth=");
        sbA08.append(this.A0N);
        sbA08.append(", ");
        sbA08.append("shadowRadius=");
        sbA08.append(this.A0A);
        sbA08.append(", ");
        sbA08.append("shadowDx=");
        sbA08.append(this.A08);
        sbA08.append(", ");
        sbA08.append("shadowDy=");
        sbA08.append(this.A09);
        sbA08.append(", ");
        sbA08.append("shadowColor=");
        sbA08.append(this.A0S);
        sbA08.append(", ");
        sbA08.append("isSingleLine=");
        sbA08.append(this.A0h);
        sbA08.append(", ");
        sbA08.append("linkColor=");
        sbA08.append(this.A0I);
        sbA08.append(", ");
        sbA08.append("textSize=");
        sbA08.append(this.A0T);
        sbA08.append(", ");
        sbA08.append("shouldAddSpacingExtraToFirstLine=");
        sbA08.append(this.A0j);
        sbA08.append(", ");
        sbA08.append("lineSpacingExtra=");
        sbA08.append(this.A06);
        sbA08.append(", ");
        sbA08.append("lineHeight=");
        sbA08.append(this.A04);
        sbA08.append(", ");
        sbA08.append("lineHeightMultiplier=");
        sbA08.append(this.A05);
        sbA08.append(", ");
        sbA08.append("letterSpacing=");
        sbA08.append(this.A03);
        sbA08.append(", ");
        sbA08.append("textStyle=");
        sbA08.append(this.A0U);
        sbA08.append(", ");
        sbA08.append("typeface=");
        sbA08.append(this.A0W);
        sbA08.append(", ");
        sbA08.append("alignment=");
        sbA08.append(this.A0Z);
        sbA08.append(", ");
        sbA08.append("breakStrategy=");
        sbA08.append(this.A0C);
        sbA08.append(", ");
        sbA08.append("hyphenationFrequency=");
        sbA08.append(this.A0F);
        sbA08.append(", ");
        sbA08.append("justificationMode=");
        sbA08.append(this.A0G);
        sbA08.append(", ");
        sbA08.append("textDirection=");
        sbA08.append(this.A0Y);
        sbA08.append(", ");
        sbA08.append("clipToBounds=");
        sbA08.append(this.A0f);
        sbA08.append(", ");
        sbA08.append("verticalGravity=");
        sbA08.append(this.A0b);
        sbA08.append(", ");
        sbA08.append("highlightColor=");
        sbA08.append(this.A0D);
        sbA08.append(", ");
        sbA08.append("keyboardHighlightColor=");
        sbA08.append(this.A0H);
        sbA08.append(", ");
        sbA08.append("highlightStartOffset=");
        sbA08.append(-1);
        sbA08.append(", ");
        sbA08.append("highlightEndOffset=");
        sbA08.append(-1);
        sbA08.append(", ");
        sbA08.append("highlightCornerRadius=");
        sbA08.append(this.A0E);
        sbA08.append(", ");
        sbA08.append("shouldLayoutEmptyText=");
        sbA08.append(this.A0k);
        sbA08.append(", ");
        sbA08.append("minimallyWide=");
        sbA08.append(false);
        sbA08.append(", ");
        sbA08.append("minimallyWideThreshold=");
        sbA08.append(0);
        sbA08.append(", ");
        sbA08.append("clickableSpanExpandedOffset=");
        sbA08.append(this.A00);
        sbA08.append(", ");
        sbA08.append("shouldTruncateTextUsingConstraints=");
        sbA08.append(this.A0l);
        sbA08.append(", ");
        sbA08.append("manualBaselineSpacing=");
        sbA08.append(this.A0J);
        sbA08.append(", ");
        sbA08.append("manualCapSpacing=");
        sbA08.append(this.A0K);
        sbA08.append(", ");
        sbA08.append("extraSpacingLeft=");
        sbA08.append(this.A01);
        sbA08.append(", ");
        sbA08.append("extraSpacingRight=");
        sbA08.append(this.A02);
        sbA08.append(", ");
        sbA08.append("outlineWidth=");
        sbA08.append(this.A07);
        sbA08.append(", ");
        sbA08.append("outlineColor=");
        sbA08.append(0);
        sbA08.append(", ");
        sbA08.append("roundedBackgroundProps=");
        sbA08.append(this.A0a);
        sbA08.append(", ");
        sbA08.append("accessibilityLabel=");
        sbA08.append(this.A0e);
        sbA08.append(", ");
        sbA08.append("isTextSelectable=");
        sbA08.append(this.A0i);
        sbA08.append(", ");
        sbA08.append("selectionHandleColor=");
        sbA08.append(this.A0R);
        sbA08.append(", ");
        sbA08.append("truncationStyle=");
        sbA08.append(this.A0d.intValue() != 0 ? "USE_MAX_LINES" : "FORCE_INLINE_TRUNCATION");
        sbA08.append(", ");
        sbA08.append("textColor=");
        sbA08.append(this.A0B);
        sbA08.append(", ");
        sbA08.append("textColorStateList=");
        sbA08.append(this.A0V);
        return AnonymousClass000.A06(")", sbA08);
    }
}
