package X;

import com.whatsapp.accountlinking.ipc.api.models.TriggerSilentUnpauseOperation;
import com.whatsapp.calling.camera.VoipLiteCamera;
import com.whatsapp.calling.voipcalling.Voip;
import com.whatsapp.ui.coreui.base.WaTextView;
import java.io.Serializable;

/* JADX INFO: renamed from: X.J2m, reason: case insensitive filesystem */
/* JADX INFO: loaded from: classes10.dex */
public class C43321J2m implements Serializable {
    public static final long serialVersionUID = -4616824299921458702L;
    public C43343J3l adsRationalGamblerConfig;
    public boolean enableAdsTuningSidnee;
    public boolean enableAudioManifestBasedABRTuning;
    public boolean enableManifestBasedABRQualityRewardCurveTuning;
    public boolean enableManifestBasedABRTuning;
    public boolean enableMosOverride;
    public boolean enableMosOverrideLive;
    public boolean enableOverallAudioMOSBasedRewardSidnee;
    public boolean enableOverallMOSBasedRewardSidnee;
    public boolean enableQoERationalGamblerABR;
    public boolean enableQoERationalGamblerABRForAudio;
    public boolean enableSmartCacheOverride;
    public boolean enableSmartCachePrefetchOverride;
    public boolean enableWifiBasedSidneeRewardTuning;
    public long liveAbrDurationForIntentional;
    public double liveMaxAlphaLowPassEMABwDown;
    public double liveMaxAlphaLowPassEMABwUp;
    public double liveMaxAlphaLowPassEMATtfbDown;
    public double liveMaxAlphaLowPassEMATtfbUp;
    public float liveRiskRewardRatioUpperBound;
    public boolean liveShouldUseLowPassEMAAsymmetryForBWEstimation;
    public boolean liveShouldUseLowPassWithWeightedEMAForBWEstimation;
    public boolean liveUpdateFormatsWithIntentionChange;
    public boolean liveUseMaxBitrateForABRIfLower;
    public boolean liveUseMaxBitrateForAOCIfLower;
    public boolean liveUsePersonalizedVirtualBuffer;
    public boolean liveUseRiskRewardRatio;
    public double maxAlphaLowPassEMABwDown;
    public double maxAlphaLowPassEMABwUp;
    public double maxAlphaLowPassEMABwVol;
    public double maxAlphaLowPassEMATtfbDown;
    public double maxAlphaLowPassEMATtfbUp;
    public double maxAlphaLowPassEMATtfbVol;
    public final int maxWidthInlinePlayer;
    public final int maxWidthToPrefetchAbr;
    public final int maxWidthToPrefetchAbrCell;
    public boolean overrideCacheWhenHighMos;
    public boolean overrideCacheWhenHighMosForPrefetch;
    public C43343J3l rationalGamblerConfig;
    public float riskRewardRatioUpperBoundSfv;
    public boolean shouldUseFreshAbrEvaluatorPerLivePrefetch;
    public boolean shouldUseLowPassEMAAsymmetryForBWEstimation;
    public boolean shouldUseLowPassEMAForBWEstimation;
    public boolean shouldUseLowPassWithWeightedEMAForBWEstimation;
    public K8G viewportAwareAbrConfig;
    public boolean systemicRiskEnableForPrefetch = true;
    public double systemicRiskLowMosFactor = 1.2d;
    public double systemicRiskFactor = 2.0d;
    public double systemicRiskLowMosFactorForBgPrefetch = 0.0d;
    public int systemicRiskAvgSegmentDurationMs = 2000;
    public boolean liveSystemicRiskEnable = false;
    public int liveSystemicRiskAvgSegmentDurationMs = 2000;
    public double liveSystemicRiskFactor = 2.0d;
    public double liveSystemicRiskLowMosFactor = 1.2d;
    public int liveSystemicRiskMaxLookaheadDurationMs = 0;
    public double systemicRiskModMosFactor = 1.0d;
    public int modBwRiskConfPct = 65;
    public int modWatchableMos = 0;
    public float bwWeightLimitForBWEDampening = 800.0f;
    public float ttfbWeightLimitForBWEDampening = 300.0f;
    public boolean enableDynamicClientSignalBasedABRTuning = false;
    public boolean enableDynamicSignalBasedRiskRewardRoundDigitTuning = false;
    public double signalBasedStallRiskFactorUpperBound = 100.0d;
    public double stallRiskFactorForCongestionOnCell = 0.0d;
    public double stallRiskFactorForCongestionOnWifi = 0.0d;
    public boolean shouldLogCongestion = false;
    public double stallRiskFactorForFwaOrTetheredConnection = 0.0d;
    public boolean checkNetworkProperties = false;
    public String audioAbrForceLane = Voip.REJECT_REASON_DECLINED;
    public boolean systemicRiskAudioEnableABR = false;
    public boolean systemicRiskAudioEnableDynOtherBitrate = true;
    public double systemicRiskAudioFactor = 4.0d;
    public double systemicRiskAudioLowMosFactor = 1.2d;
    public double systemicRiskAudioBitrateBoostFactor = 6.0d;
    public int systemicRiskAudioOtherBitrate = 0;
    public boolean liveSystemicRiskAudioEnableABR = false;
    public double liveSystemicRiskAudioFactor = 4.0d;
    public double liveSystemicRiskAudioLowMosFactor = 1.2d;
    public double liveSystemicRiskAudioBitrateBoostFactor = 6.0d;
    public int liveSystemicRiskAudioOtherBitrate = 0;
    public double virtualBufferPercent = 0.0d;
    public double liveVirtualBufferPercent = 0.0d;
    public double liveLSBVirtualBufferPercent = 0.0d;
    public double liveULSBVirtualBufferPercent = 0.0d;
    public double audioRiskAdjFactor = 0.0d;
    public double liveRiskAdjFactor = 0.0d;
    public double liveAudioRiskAdjFactor = 0.0d;
    public double liveUserLowLatencySystemicRiskFactor = 0.0d;
    public double liveUserUltraLowLatencyRiskAdjFactor = 0.0d;
    public double liveUserUltraLowLatencySystemicRiskFactor = 0.0d;
    public int ultraLowLatencyAdjustedLowestQualityIndex = -1;
    public double personalizedVirtualBufferPercent = 0.0d;
    public double personalizedRiskMultiplierVeryConservative = 1.0d;
    public double personalizedRiskMultiplierConservative = 1.0d;
    public double personalizedRiskMultiplierAggressive = 1.0d;
    public double personalizedRiskMultiplierVeryAggressive = 1.0d;
    public int personalizedBWRiskConfPctNormal = 75;
    public long personalizedAggressiveStallDuration = 120000;
    public long personalizedVeryAggressiveStallDuration = 300000;
    public long personalizedConservativeStallDuration = TriggerSilentUnpauseOperation.TRIGGER_SILENT_UNPAUSE_TIMEOUT_MS;
    public boolean shouldLogInbandTelemetryBweDebugString = false;
    public double livePersonalizedVirtualBufferPercent = 0.0d;
    public double livePersonalizedRiskMultiplierVeryConservative = 1.0d;
    public double livePersonalizedRiskMultiplierConservative = 1.0d;
    public double livePersonalizedRiskMultiplierAggressive = 1.0d;
    public double livePersonalizedRiskMultiplierVeryAggressive = 1.0d;
    public int livePersonalizedBWRiskConfPctNormal = 75;
    public int liveDefaultBwRiskConfPct = 50;
    public int defaultBwRiskConfPct = 50;
    public int liveHighBwRiskConfPct = 75;
    public int liveHighBwRiskConfPctUltraLowLatency = 75;
    public int highBwRiskConfPct = 75;
    public int adHighBwRiskConfPct = 0;
    public int adHighBwRiskConfPctOnScreen = 0;
    public int adHighBwRiskConfPctPrefetch = 0;
    public int backgroundPrefetchHighBwRiskConfPct = 0;
    public boolean enableConfRiskBwCache = false;
    public boolean shouldDeprecateLiveInitialABR = false;
    public boolean shouldCountFirstChunkOnly = false;
    public boolean honorDefaultBandwidthSR = false;
    public boolean bypassWidthLimitsSponsoredVerticalVideos = true;
    public int maxNumberSmallBwSamplesIgnored = 0;
    public boolean enableInitialBWStdDevFix = false;
    public boolean disableLiveDefaultDataSourceBwSamples = false;
    public boolean shouldDeleteNonSR = false;
    public double smartCacheOverrideThreshold = 0.0d;
    public double smartCacheOverridePrefetchThreshold = 0.0d;
    public double highOrBetterMosThreshold = 0.0d;
    public boolean enableDelayedPrefetchQualitySelection = false;
    public boolean useUnifiedUploadMos = false;
    public boolean usePlaybackCsvqm = false;
    public boolean useOverallMosForABR = false;
    public double minOverallMosForABR = 0.0d;
    public double modOverallMosForABR = 0.0d;
    public boolean usePlaybackMosForLowMosABR = true;
    public boolean enableXPlatBweParity = false;
    public boolean enableAndroidAPIBitrate = false;
    public int androidBandwidthFallbackNumberOfSamples = -1;
    public boolean xplatUseLowPassFilter = true;
    public double xplatLowPassFilterAlphaMultiplier = 1.0d;
    public long xplatWindowSizeSeconds = 20;
    public long xplatWindowMinSamples = 10;
    public double xplatAlphaBitrate = 0.1d;
    public double xplatAlphaLatency = 0.25d;
    public long xplatMaxNumSmallSamplesIgnored = -1;
    public double minRationalGamblerMultiplier = 0.5d;
    public double maxRationalGamblerMultiplier = 2.0d;
    public long minBufferDurationMsRationalGambler = 5000;
    public long maxRationalGamblerABREvaluationDurationMs = TriggerSilentUnpauseOperation.TRIGGER_SILENT_UNPAUSE_TIMEOUT_MS;
    public boolean honorDefaultBandwidthWhenNoEstimate = false;
    public long defaultInitialBitrateWhenNoEstimate = 0;
    public boolean enableCdnDebugHeadersDecisionDetails = false;
    public boolean enableCdnDebugHeadersExtended = false;
    public boolean enableCdnDebugHeadersAudioMos = false;
    public boolean enableCdnDebugHeadersSsbwe = false;
    public boolean enableCdnDebugHeadersPrefetch = false;
    public boolean includeExactSegmentSizesInAbrDecisionInfo = true;
    public final int maxWidthCell = 480;
    public final int maxWidthSphericalVideo = 0;
    public final int maxInitialBitrate = 50000;
    public final int prefetchLongQueueBandwidthConfidencePct = -1;
    public final int prefetchShortQueueBandwidthConfidencePct = -1;
    public final float maxBandwidthMultiplier = 2.0f;
    public final float maxTTFBMultiplier = 3.0f;
    public final float minTTFBMultiplier = 0.5f;
    public final float storiesMinTTFBMultiplier = 0.5f;
    public final int latencyBasedTargetBufferSizeMs = WaTextView.LONG_TEXT_LOGGING_LIMIT;
    public final boolean enableAvoidOnCellular = false;
    public final int minMosConstraintLimit = 0;
    public final boolean bypassWidthLimitsStories = false;
    public final boolean bypassWidthLimitsStoriesPrefetch = false;
    public final boolean enableSegmentBitrate = false;
    public final boolean shouldFilterHardwareCapabilities = false;
    public final float minPartiallyCachedSpan = 1.0f;
    public final boolean hashUrlForUnique = false;
    public final float screenWidthMultiplierLandscapeVideo = 1.2f;
    public final float screenWidthMultiplierPortraitVideo = 1.2f;
    public final boolean enablePhysicalDisplaySize = false;
    public final boolean clampPhysicalDisplaySizeToRenderSurface = false;
    public final boolean enableLandscapeDisplayFix = false;
    public final boolean enableMultiAudioSupport = false;
    public final boolean enableAudioIbrEvaluator = false;
    public final boolean enableAudioPrefetchAoc = false;
    public final boolean enableUseLastPreCacheAudioFormat = false;
    public final boolean enableAudioIbrCache = false;
    public int minWatchableMos = 0;
    public boolean treatShortFormAsStories = false;
    public final boolean treatCurrentNullAsLowBuffer = false;
    public final boolean useDefaultFormatAsBackupForScreenWidthConstraints = false;
    public final boolean useMosAwareCachedSelection = false;
    public final int storiesMinMosForCachedQuality = 0;
    public int minMosForCachedQuality = 0;
    public final int mosDiffPctForCachedQuality = 0;
    public final float dropRenderFrameRatioForPreventAbrUp = 1.0f;
    public final int minFramesDropForPreventAbrUp = 0;
    public final int minFramesRenderedForPreventAbrUp = 0;
    public final float minWidthMultiplierFrameDrop = 0.0f;
    public final boolean forceUpdateFormatListIfFormatSizeChanged = false;
    public final boolean bypassPrefetchWidthLimits = false;
    public final boolean shouldEnableAvoidOnABR = false;
    public final boolean useRiskRewardRatio = false;
    public final float riskRewardRatioUpperBound = 0.0f;
    public final boolean useLogarithmicRisk = false;
    public final int liveMaxWidthCell = VoipLiteCamera.DEFAULT_SUPERNOVA_HEIGHT;
    public final int liveMaxWidthInlinePlayer = 1000;
    public final int liveAbrLatencyBasedAbrTargetBufferSizeMs = WaTextView.LONG_TEXT_LOGGING_LIMIT;
    public final int livePrefetchLongQueueBandwidthConfidencePct = -1;
    public final int livePrefetchShortQueueBandwidthConfidencePct = -1;
    public final float liveMinBandwidthMultiplier = 0.3f;
    public final float liveMaxBandwidthMultiplier = 2.0f;
    public final float liveMaxTTFBMultiplier = 3.0f;
    public final float liveMinTTFBMultiplier = 0.5f;
    public final boolean liveShouldAvoidOnCellular = false;
    public final int liveMaxWidthToPrefetchCell = 396;
    public final int liveMaxWidthToPrefetchWifi = 504;
    public final boolean liveShouldFilterHardwareCapabilities = false;
    public final int liveInitialBitrate = 50000;
    public final float liveScreenWidthMultiplierLandscapeVideo = 1.2f;
    public final float liveScreenWidthMultiplierPortraitVideo = 1.2f;
    public final boolean liveTreatCurrentNullAsLowBuffer = false;
    public final long liveAocDefaultLimitIntentionalKbps = 0;
    public final long liveAocDefaultLimitUnintentionalKbps = 0;
    public final boolean alwaysPlayLiveCachedData = false;
    public final int initSegmentBandwidthExclusionLimitBytes = 0;
    public final boolean liveEnableAudioIbrEvaluator = false;
    public final boolean liveEnableAudioIbrCache = false;
    public final long initialCachedBwSizeBytes = 0;

    public C43321J2m(MLJ mlj) {
        this.maxWidthToPrefetchAbr = mlj.A01;
        this.maxWidthToPrefetchAbrCell = mlj.A02;
        this.maxWidthInlinePlayer = mlj.A00;
    }
}
