package X;

import com.google.protobuf.ByteString;
import com.whatsapp.calling.opengl.MediaCodecVideoEncoder;
import com.whatsapp.infra.tigon.WAHucClient;
import com.whatsapp.ui.coreui.base.WaTextView;
import java.util.LinkedHashMap;

/* JADX INFO: renamed from: X.Mve, reason: case insensitive filesystem */
/* JADX INFO: loaded from: classes11.dex */
public final class C49981Mve extends C0BP {
    public Boolean A00;
    public Boolean A01;
    public Boolean A02;
    public Boolean A03;
    public Boolean A04;
    public Boolean A05;
    public Boolean A06;
    public Boolean A07;
    public Boolean A08;
    public Boolean A09;
    public Boolean A0A;
    public Boolean A0B;
    public Boolean A0C;
    public Boolean A0D;
    public Boolean A0E;
    public Boolean A0F;
    public Boolean A0G;
    public Boolean A0H;
    public Boolean A0I;
    public Boolean A0J;
    public Boolean A0K;
    public Boolean A0L;
    public Boolean A0M;
    public Boolean A0N;
    public Boolean A0O;
    public Boolean A0P;
    public Boolean A0Q;
    public Boolean A0R;
    public Boolean A0S;
    public Boolean A0T;
    public Boolean A0U;
    public Boolean A0V;
    public Boolean A0W;
    public Boolean A0X;
    public Boolean A0Y;
    public Boolean A0Z;
    public Boolean A0a;
    public Boolean A0b;
    public Boolean A0c;
    public Boolean A0d;
    public Boolean A0e;
    public Integer A0f;
    public Integer A0g;
    public Integer A0h;
    public Integer A0i;
    public Integer A0j;
    public Integer A0k;
    public Integer A0l;
    public Integer A0m;
    public Integer A0n;
    public Integer A0o;
    public Integer A0p;
    public Long A0q;
    public Long A0r;
    public Long A0s;
    public Long A0t;
    public Long A0u;
    public Long A0v;
    public Long A0w;
    public Long A0x;
    public Long A0y;
    public Long A0z;
    public Long A10;
    public Long A11;
    public Long A12;
    public Long A13;
    public Long A14;
    public Long A15;
    public Long A16;
    public Long A17;
    public Long A18;
    public Long A19;
    public Long A1A;
    public Long A1B;
    public Long A1C;
    public Long A1D;
    public Long A1E;
    public Long A1F;
    public Long A1G;
    public Long A1H;
    public Long A1I;
    public Long A1J;
    public Long A1K;
    public Long A1L;
    public Long A1M;
    public Long A1N;
    public Long A1O;
    public Long A1P;
    public Long A1Q;
    public Long A1R;
    public Long A1S;
    public Long A1T;
    public Long A1U;
    public Long A1V;
    public Long A1W;
    public Long A1X;
    public Long A1Y;
    public Long A1Z;
    public Long A1a;
    public Long A1b;
    public Long A1c;
    public Long A1d;
    public Long A1e;
    public Long A1f;
    public Long A1g;
    public Long A1h;
    public Long A1i;
    public Long A1j;
    public Long A1k;
    public Long A1l;
    public Long A1m;
    public Long A1n;
    public Long A1o;
    public Long A1p;
    public Long A1q;
    public Long A1r;
    public Long A1s;
    public Long A1t;
    public Long A1u;
    public Long A1v;
    public Long A1w;
    public Long A1x;
    public Long A1y;
    public Long A1z;
    public Long A20;
    public Long A21;
    public Long A22;
    public Long A23;
    public Long A24;
    public Long A25;
    public Long A26;
    public Long A27;
    public Long A28;
    public Long A29;
    public Long A2A;
    public Long A2B;
    public Long A2C;
    public Long A2D;
    public Long A2E;
    public Long A2F;
    public Long A2G;
    public Long A2H;
    public Long A2I;
    public Long A2J;
    public Long A2K;
    public Long A2L;
    public Long A2M;
    public Long A2N;
    public Long A2O;
    public Long A2P;
    public Long A2Q;
    public Long A2R;
    public Long A2S;
    public Long A2T;
    public Long A2U;
    public Long A2V;
    public Long A2W;
    public Long A2X;
    public Long A2Y;
    public Long A2Z;
    public Long A2a;
    public Long A2b;
    public Long A2c;
    public Long A2d;
    public Long A2e;
    public Long A2f;
    public Long A2g;
    public Long A2h;
    public Long A2i;
    public Long A2j;
    public Long A2k;
    public Long A2l;
    public Long A2m;
    public Long A2n;
    public Long A2o;
    public Long A2p;
    public Long A2q;
    public Long A2r;
    public Long A2s;
    public Long A2t;
    public Long A2u;
    public Long A2v;
    public Long A2w;
    public Long A2x;
    public Long A2y;
    public Long A2z;
    public Long A30;
    public Long A31;
    public Long A32;
    public Long A33;
    public Long A34;
    public Long A35;
    public Long A36;
    public Long A37;
    public Long A38;
    public Long A39;
    public Long A3A;
    public Long A3B;
    public Long A3C;
    public Long A3D;
    public Long A3E;
    public Long A3F;
    public Long A3G;
    public Long A3H;
    public Long A3I;
    public String A3J;
    public String A3K;
    public String A3L;
    public String A3M;
    public String A3N;
    public String A3O;
    public String A3P;
    public String A3Q;
    public String A3R;

    public C49981Mve() {
        super(1644, AbstractC465925m.A0y(1), 0, -1);
    }

    @Override // X.C0BP
    public String getEventNameForFalco() {
        return "wam_chat_message_counts";
    }

    @Override // X.C0BP
    public java.util.Map getFieldsMapForLogging() {
        return null;
    }

    @Override // X.C0BP
    public int internalFalcoMigrationBatchNumber() {
        return 13;
    }

    @Override // X.C0BP
    public java.util.Map getFieldsMap() {
        LinkedHashMap linkedHashMapA1E = AbstractC465925m.A1E();
        Object objA0f = BA1.A0f(linkedHashMapA1E, 224);
        AbstractC466525s.A1S(objA0f, linkedHashMapA1E, 195);
        AbstractC466525s.A1S(objA0f, linkedHashMapA1E, 212);
        linkedHashMapA1E.put(149, this.A0q);
        linkedHashMapA1E.put(Integer.valueOf(WaTextView.ONE_LINE_DISPLAY_TEXT_LENGTH_LIMIT), this.A0r);
        AbstractC466825v.A0t(190, linkedHashMapA1E);
        linkedHashMapA1E.put(MJp.A0r(56, this.A0s, linkedHashMapA1E), this.A0f);
        linkedHashMapA1E.put(MJp.A0V(65, this.A0t, linkedHashMapA1E), this.A0g);
        linkedHashMapA1E.put(206, this.A0u);
        linkedHashMapA1E.put(207, this.A0v);
        linkedHashMapA1E.put(208, this.A0w);
        AbstractC466525s.A1S(BA1.A0f(linkedHashMapA1E, 196), linkedHashMapA1E, 209);
        linkedHashMapA1E.put(197, this.A0x);
        AbstractC466825v.A0t(220, linkedHashMapA1E);
        linkedHashMapA1E.put(221, this.A0y);
        linkedHashMapA1E.put(222, this.A0z);
        AbstractC466525s.A1S(BA1.A0f(linkedHashMapA1E, 198), linkedHashMapA1E, 199);
        linkedHashMapA1E.put(200, this.A10);
        linkedHashMapA1E.put(201, this.A11);
        linkedHashMapA1E.put(AbstractC148896gB.A0r(AbstractC148896gB.A0s(AbstractC202198ro.A0k(AbstractC148896gB.A0t(210, this.A12, linkedHashMapA1E), this.A13, linkedHashMapA1E), this.A14, linkedHashMapA1E), this.A15, linkedHashMapA1E), this.A16);
        linkedHashMapA1E.put(70, this.A17);
        linkedHashMapA1E.put(71, this.A18);
        linkedHashMapA1E.put(72, this.A19);
        linkedHashMapA1E.put(78, this.A1A);
        linkedHashMapA1E.put(73, this.A1B);
        linkedHashMapA1E.put(74, this.A1C);
        linkedHashMapA1E.put(88, this.A00);
        linkedHashMapA1E.put(AbstractC466325q.A0p(AbstractC148896gB.A0h(86, this.A1D, linkedHashMapA1E), this.A1E, linkedHashMapA1E), this.A0h);
        AbstractC466825v.A0t(179, linkedHashMapA1E);
        linkedHashMapA1E.put(MJp.A0f(AbstractC466825v.A0d(79, this.A1F, linkedHashMapA1E), this.A0i, linkedHashMapA1E), this.A1G);
        linkedHashMapA1E.put(174, this.A1H);
        linkedHashMapA1E.put(MJp.A0b(MJp.A0c(Integer.valueOf(C26698BmO.NEWSLETTER_ADMIN_PROFILE_STATUS_MESSAGE_FIELD_NUMBER), this.A1I, linkedHashMapA1E), this.A1J, linkedHashMapA1E), this.A1K);
        linkedHashMapA1E.put(219, this.A3J);
        linkedHashMapA1E.put(59, this.A0j);
        linkedHashMapA1E.put(151, this.A1L);
        linkedHashMapA1E.put(152, this.A1M);
        linkedHashMapA1E.put(100, this.A1N);
        Object objA0f2 = BA1.A0f(linkedHashMapA1E, 184);
        AbstractC466525s.A1S(objA0f2, linkedHashMapA1E, 182);
        AbstractC466525s.A1S(objA0f2, linkedHashMapA1E, 183);
        linkedHashMapA1E.put(MJp.A0h(AbstractC31894DxJ.A19(), this.A3K, linkedHashMapA1E), this.A3L);
        linkedHashMapA1E.put(AbstractC466825v.A0g(AbstractC148896gB.A0g(248, this.A1O, linkedHashMapA1E), this.A1P, linkedHashMapA1E), this.A1Q);
        linkedHashMapA1E.put(69, this.A1R);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.STATUS_QUOTED_MESSAGE_FIELD_NUMBER), this.A0k);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.STATUS_STICKER_INTERACTION_MESSAGE_FIELD_NUMBER), this.A0l);
        linkedHashMapA1E.put(142, this.A1S);
        linkedHashMapA1E.put(143, this.A1T);
        linkedHashMapA1E.put(Integer.valueOf(MediaCodecVideoEncoder.MIN_ENCODER_HEIGHT), this.A1U);
        linkedHashMapA1E.put(145, this.A1V);
        AbstractC466825v.A0t(45, linkedHashMapA1E);
        linkedHashMapA1E.put(25, this.A1W);
        linkedHashMapA1E.put(234, this.A1X);
        linkedHashMapA1E.put(235, this.A1Y);
        linkedHashMapA1E.put(236, this.A1Z);
        linkedHashMapA1E.put(237, this.A1a);
        linkedHashMapA1E.put(238, this.A1b);
        linkedHashMapA1E.put(229, this.A1c);
        linkedHashMapA1E.put(153, this.A1d);
        linkedHashMapA1E.put(154, this.A1e);
        linkedHashMapA1E.put(155, this.A1f);
        linkedHashMapA1E.put(156, this.A1g);
        linkedHashMapA1E.put(157, this.A1h);
        linkedHashMapA1E.put(158, this.A1i);
        linkedHashMapA1E.put(89, this.A1j);
        linkedHashMapA1E.put(90, this.A1k);
        linkedHashMapA1E.put(128, this.A1l);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.MUSIC_MESSAGE_FIELD_NUMBER), this.A1m);
        Object objA0f3 = BA1.A0f(linkedHashMapA1E, 159);
        AbstractC466525s.A1S(objA0f3, linkedHashMapA1E, 160);
        AbstractC466525s.A1S(objA0f3, linkedHashMapA1E, 161);
        AbstractC466525s.A1S(objA0f3, linkedHashMapA1E, 162);
        linkedHashMapA1E.put(163, this.A1n);
        linkedHashMapA1E.put(164, this.A1o);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.STATUS_LINK_PREVIEW_METADATA_FIELD_NUMBER), this.A1p);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.BOT_PLATFORM_REGISTRATION_SUCCESS_MESSAGE_FIELD_NUMBER), this.A1q);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.NEWSLETTER_SCHEDULED_MESSAGE_FIELD_NUMBER), this.A1r);
        linkedHashMapA1E.put(133, this.A1s);
        linkedHashMapA1E.put(165, this.A1t);
        linkedHashMapA1E.put(AbstractC148896gB.A0o(166, this.A1u, linkedHashMapA1E), this.A0m);
        linkedHashMapA1E.put(167, this.A1v);
        linkedHashMapA1E.put(168, this.A1w);
        AbstractC466525s.A1S(BA1.A0f(linkedHashMapA1E, 214), linkedHashMapA1E, 215);
        linkedHashMapA1E.put(57, this.A1x);
        linkedHashMapA1E.put(75, this.A01);
        linkedHashMapA1E.put(87, this.A0n);
        AbstractC466825v.A0t(225, linkedHashMapA1E);
        linkedHashMapA1E.put(AbstractC148896gB.A0l(MJp.A0k(AbstractC31894DxJ.A1A(), this.A1y, linkedHashMapA1E), this.A1z, linkedHashMapA1E), this.A20);
        linkedHashMapA1E.put(249, this.A21);
        linkedHashMapA1E.put(250, this.A22);
        linkedHashMapA1E.put(251, this.A23);
        linkedHashMapA1E.put(252, this.A24);
        linkedHashMapA1E.put(253, this.A25);
        linkedHashMapA1E.put(254, this.A26);
        linkedHashMapA1E.put(Integer.valueOf(ByteString.UNSIGNED_BYTE_MASK), this.A27);
        linkedHashMapA1E.put(256, this.A28);
        linkedHashMapA1E.put(216, this.A02);
        linkedHashMapA1E.put(180, this.A03);
        linkedHashMapA1E.put(228, this.A04);
        linkedHashMapA1E.put(175, this.A29);
        linkedHashMapA1E.put(202, this.A2A);
        linkedHashMapA1E.put(203, this.A2B);
        linkedHashMapA1E.put(AbstractC466325q.A0n(Integer.valueOf(MediaCodecVideoEncoder.MIN_ENCODER_WIDTH), BA1.A0f(linkedHashMapA1E, 146), linkedHashMapA1E), this.A05);
        linkedHashMapA1E.put(AbstractC466325q.A0r(AbstractC466325q.A0m(213, this.A06, linkedHashMapA1E), this.A07, linkedHashMapA1E), this.A08);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.NEWSLETTER_FOLLOWER_INVITE_MESSAGE_FIELD_NUMBER), this.A09);
        linkedHashMapA1E.put(BA0.A0i(MJp.A0X(MJp.A0Y(MJp.A0U(230, this.A0A, linkedHashMapA1E), this.A0B, linkedHashMapA1E), this.A0C, linkedHashMapA1E), this.A0D, linkedHashMapA1E), this.A0E);
        linkedHashMapA1E.put(185, this.A0F);
        linkedHashMapA1E.put(257, this.A0G);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.QUESTION_REPLY_MESSAGE_FIELD_NUMBER), this.A0H);
        AbstractC466825v.A0t(54, linkedHashMapA1E);
        linkedHashMapA1E.put(260, this.A0I);
        linkedHashMapA1E.put(91, this.A0J);
        AbstractC466825v.A0t(211, linkedHashMapA1E);
        linkedHashMapA1E.put(261, this.A0K);
        linkedHashMapA1E.put(62, this.A0L);
        AbstractC466825v.A0t(239, linkedHashMapA1E);
        linkedHashMapA1E.put(9, this.A0M);
        linkedHashMapA1E.put(92, this.A0N);
        linkedHashMapA1E.put(186, this.A0O);
        linkedHashMapA1E.put(141, this.A0P);
        AbstractC466825v.A0t(140, linkedHashMapA1E);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.POLL_CREATION_MESSAGE_V5_FIELD_NUMBER), this.A0Q);
        AbstractC466825v.A0t(C26698BmO.GROUP_ROOT_KEY_SHARE_FIELD_NUMBER, linkedHashMapA1E);
        linkedHashMapA1E.put(258, this.A0R);
        linkedHashMapA1E.put(259, this.A0S);
        AbstractC466825v.A0t(81, linkedHashMapA1E);
        linkedHashMapA1E.put(55, this.A2C);
        linkedHashMapA1E.put(226, this.A0T);
        linkedHashMapA1E.put(96, this.A2D);
        linkedHashMapA1E.put(193, this.A2E);
        linkedHashMapA1E.put(194, this.A2F);
        AbstractC466825v.A0t(241, linkedHashMapA1E);
        linkedHashMapA1E.put(246, this.A3M);
        AbstractC466825v.A0t(242, linkedHashMapA1E);
        linkedHashMapA1E.put(247, this.A3N);
        AbstractC466825v.A0t(243, linkedHashMapA1E);
        linkedHashMapA1E.put(127, this.A2G);
        AbstractC466825v.A0t(244, linkedHashMapA1E);
        linkedHashMapA1E.put(AbstractC466125o.A15(), this.A2H);
        linkedHashMapA1E.put(AbstractC466825v.A0e(AbstractC466825v.A0f(AbstractC466325q.A0k(245, this.A2I, linkedHashMapA1E), this.A2J, linkedHashMapA1E), this.A2K, linkedHashMapA1E), this.A2L);
        linkedHashMapA1E.put(147, this.A2M);
        linkedHashMapA1E.put(148, this.A2N);
        linkedHashMapA1E.put(68, this.A0U);
        linkedHashMapA1E.put(231, this.A2O);
        AbstractC466825v.A0t(82, linkedHashMapA1E);
        linkedHashMapA1E.put(240, this.A0V);
        linkedHashMapA1E.put(Integer.valueOf(WAHucClient.HTTP_STATUS_NO_CONTENT), this.A0W);
        linkedHashMapA1E.put(217, this.A0X);
        linkedHashMapA1E.put(227, this.A0Y);
        linkedHashMapA1E.put(MJp.A0Z(181, this.A0o, linkedHashMapA1E), this.A2P);
        AbstractC466525s.A1S(BA1.A0f(linkedHashMapA1E, 83), linkedHashMapA1E, 84);
        linkedHashMapA1E.put(MJp.A0s(MJp.A0d(39, this.A2Q, linkedHashMapA1E), this.A2R, linkedHashMapA1E), this.A2S);
        linkedHashMapA1E.put(134, this.A2T);
        linkedHashMapA1E.put(135, this.A2U);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.POLL_RESULT_SNAPSHOT_MESSAGE_V3_FIELD_NUMBER), this.A2V);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.NEWSLETTER_ADMIN_PROFILE_MESSAGE_FIELD_NUMBER), this.A2W);
        linkedHashMapA1E.put(117, this.A2X);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.SPOILER_MESSAGE_FIELD_NUMBER), this.A2Y);
        linkedHashMapA1E.put(64, this.A2Z);
        linkedHashMapA1E.put(63, this.A2a);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.POLL_CREATION_MESSAGE_V6_FIELD_NUMBER), this.A2b);
        linkedHashMapA1E.put(120, this.A2c);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.POLL_ADD_OPTION_MESSAGE_FIELD_NUMBER), this.A2d);
        linkedHashMapA1E.put(MJp.A0q(Integer.valueOf(C26698BmO.EVENT_INVITE_MESSAGE_FIELD_NUMBER), this.A2e, linkedHashMapA1E), this.A2f);
        linkedHashMapA1E.put(97, this.A2g);
        linkedHashMapA1E.put(AbstractC148896gB.A0n(98, this.A2h, linkedHashMapA1E), this.A2i);
        linkedHashMapA1E.put(80, this.A2j);
        linkedHashMapA1E.put(93, this.A0Z);
        linkedHashMapA1E.put(AbstractC148896gB.A0m(94, this.A0a, linkedHashMapA1E), this.A2k);
        linkedHashMapA1E.put(99, this.A0b);
        linkedHashMapA1E.put(218, this.A0c);
        linkedHashMapA1E.put(101, this.A2l);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.MESSAGE_HISTORY_NOTICE_FIELD_NUMBER), this.A2m);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.GROUP_STATUS_MESSAGE_V2_FIELD_NUMBER), this.A2n);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.BOT_FORWARDED_MESSAGE_FIELD_NUMBER), this.A2o);
        linkedHashMapA1E.put(AbstractC466325q.A0o(MJp.A0T(Integer.valueOf(C26698BmO.STATUS_QUESTION_ANSWER_MESSAGE_FIELD_NUMBER), this.A2p, linkedHashMapA1E), this.A2q, linkedHashMapA1E), this.A2r);
        linkedHashMapA1E.put(191, this.A2s);
        linkedHashMapA1E.put(MJp.A0j(192, this.A2t, linkedHashMapA1E), this.A2u);
        linkedHashMapA1E.put(MJp.A0i(169, this.A2v, linkedHashMapA1E), this.A2w);
        linkedHashMapA1E.put(170, this.A2x);
        linkedHashMapA1E.put(171, this.A2y);
        AbstractC466825v.A0t(43, linkedHashMapA1E);
        linkedHashMapA1E.put(177, this.A2z);
        linkedHashMapA1E.put(178, this.A30);
        linkedHashMapA1E.put(136, this.A31);
        linkedHashMapA1E.put(137, this.A32);
        AbstractC466825v.A0t(C26698BmO.PAYMENT_REMINDER_MESSAGE_FIELD_NUMBER, linkedHashMapA1E);
        linkedHashMapA1E.put(189, this.A3O);
        linkedHashMapA1E.put(66, this.A3P);
        linkedHashMapA1E.put(67, this.A3Q);
        linkedHashMapA1E.put(223, this.A3R);
        linkedHashMapA1E.put(264, this.A33);
        linkedHashMapA1E.put(262, this.A34);
        linkedHashMapA1E.put(BA0.A0h(263, this.A35, linkedHashMapA1E), this.A36);
        linkedHashMapA1E.put(112, this.A37);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.NEWSLETTER_FOLLOWER_INVITE_MESSAGE_V2_FIELD_NUMBER), this.A38);
        linkedHashMapA1E.put(114, this.A39);
        AbstractC466825v.A0t(C26698BmO.SPLIT_PAYMENT_MESSAGE_FIELD_NUMBER, linkedHashMapA1E);
        linkedHashMapA1E.put(85, this.A0p);
        linkedHashMapA1E.put(138, this.A3A);
        linkedHashMapA1E.put(139, this.A3B);
        linkedHashMapA1E.put(205, this.A0d);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.QUESTION_RESPONSE_MESSAGE_FIELD_NUMBER), this.A0e);
        linkedHashMapA1E.put(76, this.A3C);
        linkedHashMapA1E.put(172, this.A3D);
        linkedHashMapA1E.put(AbstractC148896gB.A0i(AbstractC148896gB.A0j(AbstractC148896gB.A0k(173, this.A3E, linkedHashMapA1E), this.A3F, linkedHashMapA1E), this.A3G, linkedHashMapA1E), this.A3H);
        linkedHashMapA1E.put(77, this.A3I);
        return linkedHashMapA1E;
    }

    @Override // X.C0BP
    public java.util.Map getFieldsMapForFalco() {
        LinkedHashMap linkedHashMapA1E = AbstractC465925m.A1E();
        linkedHashMapA1E.put("ai_chat_origins", null);
        linkedHashMapA1E.put("ai_discovery_tab", null);
        linkedHashMapA1E.put("apt_test_id", null);
        linkedHashMapA1E.put("audio_messages_received", this.A0q);
        linkedHashMapA1E.put("audio_messages_sent", this.A0r);
        linkedHashMapA1E.put("auto_reply_from_icebreaker_sent", null);
        linkedHashMapA1E.put("away_msgs_sent", this.A0s);
        linkedHashMapA1E.put("biz_catalog_type", this.A0f);
        linkedHashMapA1E.put("biz_conversation_depth", this.A0t);
        linkedHashMapA1E.put("block_reason", this.A0g);
        linkedHashMapA1E.put("bottom_sheet_animated_sent", this.A0u);
        linkedHashMapA1E.put("bottom_sheet_edited_animated_sent", this.A0v);
        linkedHashMapA1E.put("bottom_sheet_edited_sent", this.A0w);
        linkedHashMapA1E.put("bottom_sheet_forward_messages_sent", null);
        linkedHashMapA1E.put("bottom_sheet_images_edited", null);
        linkedHashMapA1E.put("bottom_sheet_images_generated", this.A0x);
        linkedHashMapA1E.put("bottom_sheet_memu_images_generated", null);
        linkedHashMapA1E.put("bottom_sheet_memu_initiated", this.A0y);
        linkedHashMapA1E.put("bottom_sheet_memu_messages_sent", this.A0z);
        linkedHashMapA1E.put("bottom_sheet_messages_downloaded", null);
        linkedHashMapA1E.put("bottom_sheet_messages_received", null);
        linkedHashMapA1E.put("bottom_sheet_messages_sent", this.A10);
        linkedHashMapA1E.put("bottom_sheet_prompts_initiated", this.A11);
        linkedHashMapA1E.put("bottom_sheet_regenerated_sent", this.A12);
        linkedHashMapA1E.put("broadcast_msgs_received", this.A13);
        linkedHashMapA1E.put("broadcast_msgs_sent", this.A14);
        linkedHashMapA1E.put("call_offers_received", this.A15);
        linkedHashMapA1E.put("call_offers_sent", this.A16);
        linkedHashMapA1E.put("calls_result_busy", this.A17);
        linkedHashMapA1E.put("calls_result_cancelled", this.A18);
        linkedHashMapA1E.put("calls_result_connected", this.A19);
        linkedHashMapA1E.put("calls_result_error", this.A1A);
        linkedHashMapA1E.put("calls_result_missed", this.A1B);
        linkedHashMapA1E.put("calls_result_rejected", this.A1C);
        linkedHashMapA1E.put("can_edit_dm_settings", this.A00);
        linkedHashMapA1E.put("cart_views", this.A1D);
        linkedHashMapA1E.put("chat_ephemerality_duration", this.A1E);
        Integer num = this.A0h;
        if (num != null && num.intValue() != 0) {
            linkedHashMapA1E.put("chat_muted", num);
        }
        linkedHashMapA1E.put("chat_overflow_clicks", this.A1F);
        Integer num2 = this.A0i;
        if (num2 != null && num2.intValue() != 0) {
            linkedHashMapA1E.put("chat_type_ind", num2);
        }
        linkedHashMapA1E.put("collection_inquiries_sent", this.A1G);
        linkedHashMapA1E.put("command_sheet_show", this.A1H);
        linkedHashMapA1E.put("comments_received", this.A1I);
        linkedHashMapA1E.put("commerce_msgs_received", this.A1J);
        linkedHashMapA1E.put("commerce_msgs_sent", this.A1K);
        linkedHashMapA1E.put("device_language", this.A3J);
        Integer num3 = this.A0j;
        if (num3 != null && num3.intValue() != 0) {
            linkedHashMapA1E.put("disappearing_chat_initiator", num3);
        }
        linkedHashMapA1E.put("document_messages_received", this.A1L);
        linkedHashMapA1E.put("document_messages_sent", this.A1M);
        linkedHashMapA1E.put("edited_msgs_sent", this.A1N);
        linkedHashMapA1E.put("emu_flash_playbacks", null);
        linkedHashMapA1E.put("emu_flash_preview_show", null);
        linkedHashMapA1E.put("emu_flash_sent", null);
        linkedHashMapA1E.put("entry_point_conversion_app", this.A3K);
        linkedHashMapA1E.put("entry_point_conversion_source", this.A3L);
        linkedHashMapA1E.put("ephemeral_messages_expired", this.A1O);
        linkedHashMapA1E.put("ephemeral_messages_received", this.A1P);
        linkedHashMapA1E.put("ephemeral_messages_sent", this.A1Q);
        linkedHashMapA1E.put("ephemeral_messages_unread_expired", this.A1R);
        Integer num4 = this.A0k;
        if (num4 != null && num4.intValue() != 0) {
            linkedHashMapA1E.put("ephemerality_initiator", num4);
        }
        linkedHashMapA1E.put("ephemerality_trigger_action", this.A0l);
        linkedHashMapA1E.put("event_creation_messages_received", this.A1S);
        linkedHashMapA1E.put("event_creation_messages_sent", this.A1T);
        linkedHashMapA1E.put("event_response_messages_received", this.A1U);
        linkedHashMapA1E.put("event_response_messages_sent", this.A1V);
        linkedHashMapA1E.put("fb_cta_inquiries_sent", null);
        linkedHashMapA1E.put("first_response_time", this.A1W);
        linkedHashMapA1E.put("fmx_not_mv_bottom_sheet_dismissed_count", this.A1X);
        linkedHashMapA1E.put("fmx_not_mv_bottom_sheet_get_mv_button_clicks", this.A1Y);
        linkedHashMapA1E.put("fmx_not_mv_bottom_sheet_get_mv_button_impressions", this.A1Z);
        linkedHashMapA1E.put("fmx_not_mv_bottom_sheet_impressions", this.A1a);
        linkedHashMapA1E.put("fmx_not_mv_bottom_sheet_learn_more_button_clicks", this.A1b);
        linkedHashMapA1E.put("fmx_not_mv_clicks", this.A1c);
        linkedHashMapA1E.put("forward_audio_messages_received", this.A1d);
        linkedHashMapA1E.put("forward_audio_messages_sent", this.A1e);
        linkedHashMapA1E.put("forward_document_messages_received", this.A1f);
        linkedHashMapA1E.put("forward_document_messages_sent", this.A1g);
        linkedHashMapA1E.put("forward_gif_messages_received", this.A1h);
        linkedHashMapA1E.put("forward_gif_messages_sent", this.A1i);
        linkedHashMapA1E.put("forward_messages_received", this.A1j);
        linkedHashMapA1E.put("forward_messages_sent", this.A1k);
        linkedHashMapA1E.put("forward_photo_messages_received", this.A1l);
        linkedHashMapA1E.put("forward_photo_messages_sent", this.A1m);
        linkedHashMapA1E.put("forward_ptv_messages_received", null);
        linkedHashMapA1E.put("forward_ptv_messages_sent", null);
        linkedHashMapA1E.put("forward_status_reply_messages_received", null);
        linkedHashMapA1E.put("forward_status_reply_messages_sent", null);
        linkedHashMapA1E.put("forward_sticker_messages_received", this.A1n);
        linkedHashMapA1E.put("forward_sticker_messages_sent", this.A1o);
        linkedHashMapA1E.put("forward_text_messages_received", this.A1p);
        linkedHashMapA1E.put("forward_text_messages_sent", this.A1q);
        linkedHashMapA1E.put("forward_url_messages_received", this.A1r);
        linkedHashMapA1E.put("forward_url_messages_sent", this.A1s);
        linkedHashMapA1E.put("forward_video_messages_received", this.A1t);
        linkedHashMapA1E.put("forward_video_messages_sent", this.A1u);
        linkedHashMapA1E.put("ga_status", this.A0m);
        linkedHashMapA1E.put("gif_messages_received", this.A1v);
        linkedHashMapA1E.put("gif_messages_sent", this.A1w);
        linkedHashMapA1E.put("google_search_click", null);
        linkedHashMapA1E.put("google_search_show", null);
        linkedHashMapA1E.put("greeting_msgs_sent", this.A1x);
        linkedHashMapA1E.put("group_contains_biz", this.A01);
        Integer num5 = this.A0n;
        if (num5 != null && num5.intValue() != 0) {
            linkedHashMapA1E.put("group_info_setting", num5);
        }
        linkedHashMapA1E.put("group_limit_sharing_on_cnt", null);
        linkedHashMapA1E.put("group_membership_replies", this.A1y);
        linkedHashMapA1E.put("group_private_replies", this.A1z);
        linkedHashMapA1E.put("group_size", this.A20);
        linkedHashMapA1E.put("group_status_likes_others_to_others", this.A21);
        linkedHashMapA1E.put("group_status_likes_others_to_own", this.A22);
        linkedHashMapA1E.put("group_status_likes_own_to_others", this.A23);
        linkedHashMapA1E.put("group_status_likes_own_to_own", this.A24);
        linkedHashMapA1E.put("group_status_replies_others_to_others", this.A25);
        linkedHashMapA1E.put("group_status_replies_others_to_own", this.A26);
        linkedHashMapA1E.put("group_status_replies_own_to_others", this.A27);
        linkedHashMapA1E.put("group_status_replies_own_to_own", this.A28);
        linkedHashMapA1E.put("has_replied_1_on_1", this.A02);
        linkedHashMapA1E.put("has_username", this.A03);
        linkedHashMapA1E.put("has_username_pin", this.A04);
        linkedHashMapA1E.put("imagine_command_click", this.A29);
        linkedHashMapA1E.put("imagine_me_messages_sent", this.A2A);
        linkedHashMapA1E.put("imagine_me_prompts_initiated_count", this.A2B);
        linkedHashMapA1E.put("imagine_mention_click", null);
        linkedHashMapA1E.put("imagine_mention_show", null);
        linkedHashMapA1E.put("is_a_contact", this.A05);
        linkedHashMapA1E.put("is_a_contact_at_thread_creation", this.A06);
        linkedHashMapA1E.put("is_a_group", this.A07);
        linkedHashMapA1E.put("is_archived", this.A08);
        linkedHashMapA1E.put("is_auto_muted", this.A09);
        linkedHashMapA1E.put("is_biz_mv_friction_eligible", this.A0A);
        linkedHashMapA1E.put("is_blocked", this.A0B);
        linkedHashMapA1E.put("is_cart_add_clicked", this.A0C);
        linkedHashMapA1E.put("is_commerce_viewed", this.A0D);
        linkedHashMapA1E.put("is_cta_on_pdp_clicked", this.A0E);
        linkedHashMapA1E.put("is_deleted", this.A0F);
        linkedHashMapA1E.put("is_guest_thread", this.A0G);
        linkedHashMapA1E.put("is_invite_created_thread", this.A0H);
        linkedHashMapA1E.put("is_labelled", null);
        linkedHashMapA1E.put("is_managed_account", this.A0I);
        linkedHashMapA1E.put("is_message_yourself", this.A0J);
        linkedHashMapA1E.put("is_meta_ai_assistant", null);
        linkedHashMapA1E.put("is_new_managed_account_em_ignored", this.A0K);
        linkedHashMapA1E.put("is_opposite_party_initiated", this.A0L);
        linkedHashMapA1E.put("is_opposite_party_mv_biz", null);
        linkedHashMapA1E.put("is_pinned", this.A0M);
        linkedHashMapA1E.put("is_pnh_enabled_chat", this.A0N);
        linkedHashMapA1E.put("is_reported", this.A0O);
        linkedHashMapA1E.put("is_user_1p_biz_bot_chat", this.A0P);
        linkedHashMapA1E.put("is_user_3p_bot_chat", null);
        linkedHashMapA1E.put("is_user_agent", this.A0Q);
        linkedHashMapA1E.put("is_user_created_agent", null);
        linkedHashMapA1E.put("is_username_thread", this.A0R);
        linkedHashMapA1E.put("is_username_thread_at_creation", this.A0S);
        linkedHashMapA1E.put("is_wa_pay_registered", null);
        linkedHashMapA1E.put("labelled_msgs", this.A2C);
        linkedHashMapA1E.put("limit_sharing_option", this.A0T);
        linkedHashMapA1E.put("locations_sent", this.A2D);
        linkedHashMapA1E.put("marked_read_cnt", this.A2E);
        linkedHashMapA1E.put("marked_read_message_cnt", this.A2F);
        linkedHashMapA1E.put("matched_messages_marked_as_read", null);
        linkedHashMapA1E.put("matched_messages_marked_as_read_with_delta_time", this.A3M);
        linkedHashMapA1E.put("matched_messages_read", null);
        linkedHashMapA1E.put("matched_messages_read_with_delta_time", this.A3N);
        linkedHashMapA1E.put("messages_marked_as_read_delta_time", null);
        linkedHashMapA1E.put("messages_read", this.A2G);
        linkedHashMapA1E.put("messages_read_delta_time", null);
        linkedHashMapA1E.put("messages_received", this.A2H);
        linkedHashMapA1E.put("messages_received_with_enabled_read_receipt", this.A2I);
        linkedHashMapA1E.put("messages_sent", this.A2J);
        linkedHashMapA1E.put("messages_starred", this.A2K);
        linkedHashMapA1E.put("messages_unread", this.A2L);
        linkedHashMapA1E.put("meta_ai_mention_click", this.A2M);
        linkedHashMapA1E.put("meta_ai_mention_show", this.A2N);
        linkedHashMapA1E.put("new_thread", this.A0U);
        linkedHashMapA1E.put("not_mv_impressions", this.A2O);
        linkedHashMapA1E.put("od_received", null);
        linkedHashMapA1E.put("opposite_party_has_badge", this.A0V);
        linkedHashMapA1E.put("opposite_party_has_business_intent", this.A0W);
        linkedHashMapA1E.put("opposite_party_has_profile_photo", this.A0X);
        linkedHashMapA1E.put("opposite_party_limit_sharing_option", this.A0Y);
        Integer num6 = this.A0o;
        if (num6 != null && num6.intValue() != 0) {
            linkedHashMapA1E.put("opposite_visible_identification", num6);
        }
        linkedHashMapA1E.put("orders_sent", this.A2P);
        linkedHashMapA1E.put("p2m_od_nnp_transactions_sent", null);
        linkedHashMapA1E.put("p2m_od_np_transactions_sent", null);
        linkedHashMapA1E.put("payments_sent", this.A2Q);
        linkedHashMapA1E.put("pdp_inquiries_sent", this.A2R);
        linkedHashMapA1E.put("pdp_views", this.A2S);
        linkedHashMapA1E.put("photo_messages_received", this.A2T);
        linkedHashMapA1E.put("photo_messages_sent", this.A2U);
        linkedHashMapA1E.put("poll_creation_messages_received", this.A2V);
        linkedHashMapA1E.put("poll_creation_messages_sent", this.A2W);
        linkedHashMapA1E.put("poll_update_messages_received", this.A2X);
        linkedHashMapA1E.put("poll_update_messages_sent", this.A2Y);
        linkedHashMapA1E.put("profile_replies", this.A2Z);
        linkedHashMapA1E.put("profile_views", this.A2a);
        linkedHashMapA1E.put("ptt_messages_received", this.A2b);
        linkedHashMapA1E.put("ptt_messages_sent", this.A2c);
        linkedHashMapA1E.put("ptv_messages_received", this.A2d);
        linkedHashMapA1E.put("ptv_messages_sent", this.A2e);
        linkedHashMapA1E.put("quick_replies_sent", this.A2f);
        linkedHashMapA1E.put("reactions_received", this.A2g);
        linkedHashMapA1E.put("reactions_sent", this.A2h);
        linkedHashMapA1E.put("receiver_default_disappearing_duration", this.A2i);
        linkedHashMapA1E.put("replies_sent", this.A2j);
        linkedHashMapA1E.put("requested_phone_number", this.A0Z);
        linkedHashMapA1E.put("seen_masked_phone_number", this.A0a);
        linkedHashMapA1E.put("sender_default_disappearing_duration", this.A2k);
        linkedHashMapA1E.put("shared_phone_number", this.A0b);
        linkedHashMapA1E.put("shares_common_group", this.A0c);
        linkedHashMapA1E.put("smb_marketing_messages_reactions_sent", this.A2l);
        linkedHashMapA1E.put("smb_marketing_messages_replies_sent", this.A2m);
        linkedHashMapA1E.put("smb_marketing_messages_spam_reports", this.A2n);
        linkedHashMapA1E.put("smb_marketing_msgs_received", this.A2o);
        linkedHashMapA1E.put("smb_marketing_msgs_sent", this.A2p);
        linkedHashMapA1E.put("spam_reports", this.A2q);
        linkedHashMapA1E.put("start_time", this.A2r);
        linkedHashMapA1E.put("status_reactions_received", this.A2s);
        linkedHashMapA1E.put("status_reactions_sent", this.A2t);
        linkedHashMapA1E.put("status_replies", this.A2u);
        linkedHashMapA1E.put("status_reply_messages_received", this.A2v);
        linkedHashMapA1E.put("status_views", this.A2w);
        linkedHashMapA1E.put("sticker_messages_received", this.A2x);
        linkedHashMapA1E.put("sticker_messages_sent", this.A2y);
        linkedHashMapA1E.put("storefront_inquiries_sent", null);
        linkedHashMapA1E.put("suggestion_prompts_click", this.A2z);
        linkedHashMapA1E.put("suggestion_prompts_show", this.A30);
        linkedHashMapA1E.put("text_messages_received", this.A31);
        linkedHashMapA1E.put("text_messages_sent", this.A32);
        linkedHashMapA1E.put("text_messages_to_user_created_agent_cnt", null);
        linkedHashMapA1E.put("thread_creation_date", this.A3O);
        linkedHashMapA1E.put("thread_ds", this.A3P);
        linkedHashMapA1E.put("thread_id", this.A3Q);
        linkedHashMapA1E.put("thread_id_monthly", this.A3R);
        linkedHashMapA1E.put("tombstone_ai_futureproofed_messages_received", this.A33);
        linkedHashMapA1E.put("tombstone_ephemeral_messages_received", this.A34);
        linkedHashMapA1E.put("tombstone_view_once_messages_received", this.A35);
        linkedHashMapA1E.put("total_call_duration", this.A36);
        linkedHashMapA1E.put("total_message_edits_from_agent_cnt", this.A37);
        linkedHashMapA1E.put("total_message_from_agent_cnt", this.A38);
        linkedHashMapA1E.put("total_message_to_agent_cnt", this.A39);
        linkedHashMapA1E.put("total_messages_to_user_created_agent_cnt", null);
        BA2.A0x(this.A0p, linkedHashMapA1E);
        linkedHashMapA1E.put("url_messages_received", this.A3A);
        linkedHashMapA1E.put("url_messages_sent", this.A3B);
        linkedHashMapA1E.put("user_has_business_intent", this.A0d);
        linkedHashMapA1E.put("via_contactless_chats", this.A0e);
        linkedHashMapA1E.put("video_calls_offered", this.A3C);
        linkedHashMapA1E.put("video_messages_received", this.A3D);
        linkedHashMapA1E.put("video_messages_sent", this.A3E);
        linkedHashMapA1E.put("view_once_messages_opened", this.A3F);
        linkedHashMapA1E.put("view_once_messages_received", this.A3G);
        linkedHashMapA1E.put("view_once_messages_sent", this.A3H);
        linkedHashMapA1E.put("voice_calls_offered", this.A3I);
        return linkedHashMapA1E;
    }

    @Override // X.C0BP
    public void serialize(InterfaceC79783iN interfaceC79783iN) {
        throw AbstractC466525s.A0m();
    }

    public String toString() {
        StringBuilder sbA08 = AnonymousClass000.A08();
        sbA08.append("WamChatMessageCounts {");
        C0BR.A00(this.A0q, "audioMessagesReceived", sbA08);
        C0BR.A00(this.A0r, "audioMessagesSent", sbA08);
        C0BR.A00(this.A0s, "awayMsgsSent", sbA08);
        C0BR.A00(AbstractC32971bt.A0P(this.A0f), "bizCatalogType", sbA08);
        C0BR.A00(this.A0t, "bizConversationDepth", sbA08);
        C0BR.A00(AbstractC32971bt.A0P(this.A0g), "blockReason", sbA08);
        C0BR.A00(this.A0u, "bottomSheetAnimatedSent", sbA08);
        C0BR.A00(this.A0v, "bottomSheetEditedAnimatedSent", sbA08);
        C0BR.A00(this.A0w, "bottomSheetEditedSent", sbA08);
        C0BR.A00(this.A0x, "bottomSheetImagesGenerated", sbA08);
        C0BR.A00(this.A0y, "bottomSheetMemuInitiated", sbA08);
        C0BR.A00(this.A0z, "bottomSheetMemuMessagesSent", sbA08);
        C0BR.A00(this.A10, "bottomSheetMessagesSent", sbA08);
        C0BR.A00(this.A11, "bottomSheetPromptsInitiated", sbA08);
        C0BR.A00(this.A12, "bottomSheetRegeneratedSent", sbA08);
        C0BR.A00(this.A13, "broadcastMsgsReceived", sbA08);
        C0BR.A00(this.A14, "broadcastMsgsSent", sbA08);
        C0BR.A00(this.A15, "callOffersReceived", sbA08);
        C0BR.A00(this.A16, "callOffersSent", sbA08);
        C0BR.A00(this.A17, "callsResultBusy", sbA08);
        C0BR.A00(this.A18, "callsResultCancelled", sbA08);
        C0BR.A00(this.A19, "callsResultConnected", sbA08);
        C0BR.A00(this.A1A, "callsResultError", sbA08);
        C0BR.A00(this.A1B, "callsResultMissed", sbA08);
        C0BR.A00(this.A1C, "callsResultRejected", sbA08);
        C0BR.A00(this.A00, "canEditDmSettings", sbA08);
        C0BR.A00(this.A1D, "cartViews", sbA08);
        C0BR.A00(this.A1E, "chatEphemeralityDuration", sbA08);
        C0BR.A00(AbstractC32971bt.A0P(this.A0h), "chatMuted", sbA08);
        C0BR.A00(this.A1F, "chatOverflowClicks", sbA08);
        C0BR.A00(AbstractC32971bt.A0P(this.A0i), "chatTypeInd", sbA08);
        C0BR.A00(this.A1G, "collectionInquiriesSent", sbA08);
        C0BR.A00(this.A1H, "commandSheetShow", sbA08);
        C0BR.A00(this.A1I, "commentsReceived", sbA08);
        C0BR.A00(this.A1J, "commerceMsgsReceived", sbA08);
        C0BR.A00(this.A1K, "commerceMsgsSent", sbA08);
        C0BR.A00(this.A3J, "deviceLanguage", sbA08);
        C0BR.A00(AbstractC32971bt.A0P(this.A0j), "disappearingChatInitiator", sbA08);
        C0BR.A00(this.A1L, "documentMessagesReceived", sbA08);
        C0BR.A00(this.A1M, "documentMessagesSent", sbA08);
        C0BR.A00(this.A1N, "editedMsgsSent", sbA08);
        C0BR.A00(this.A3K, "entryPointConversionApp", sbA08);
        C0BR.A00(this.A3L, "entryPointConversionSource", sbA08);
        C0BR.A00(this.A1O, "ephemeralMessagesExpired", sbA08);
        C0BR.A00(this.A1P, "ephemeralMessagesReceived", sbA08);
        C0BR.A00(this.A1Q, "ephemeralMessagesSent", sbA08);
        C0BR.A00(this.A1R, "ephemeralMessagesUnreadExpired", sbA08);
        C0BR.A00(AbstractC32971bt.A0P(this.A0k), "ephemeralityInitiator", sbA08);
        C0BR.A00(AbstractC32971bt.A0P(this.A0l), "ephemeralityTriggerAction", sbA08);
        C0BR.A00(this.A1S, "eventCreationMessagesReceived", sbA08);
        C0BR.A00(this.A1T, "eventCreationMessagesSent", sbA08);
        C0BR.A00(this.A1U, "eventResponseMessagesReceived", sbA08);
        C0BR.A00(this.A1V, "eventResponseMessagesSent", sbA08);
        C0BR.A00(this.A1W, "firstResponseTime", sbA08);
        C0BR.A00(this.A1X, "fmxNotMvBottomSheetDismissedCount", sbA08);
        C0BR.A00(this.A1Y, "fmxNotMvBottomSheetGetMvButtonClicks", sbA08);
        C0BR.A00(this.A1Z, "fmxNotMvBottomSheetGetMvButtonImpressions", sbA08);
        C0BR.A00(this.A1a, "fmxNotMvBottomSheetImpressions", sbA08);
        C0BR.A00(this.A1b, "fmxNotMvBottomSheetLearnMoreButtonClicks", sbA08);
        C0BR.A00(this.A1c, "fmxNotMvClicks", sbA08);
        C0BR.A00(this.A1d, "forwardAudioMessagesReceived", sbA08);
        C0BR.A00(this.A1e, "forwardAudioMessagesSent", sbA08);
        C0BR.A00(this.A1f, "forwardDocumentMessagesReceived", sbA08);
        C0BR.A00(this.A1g, "forwardDocumentMessagesSent", sbA08);
        C0BR.A00(this.A1h, "forwardGifMessagesReceived", sbA08);
        C0BR.A00(this.A1i, "forwardGifMessagesSent", sbA08);
        C0BR.A00(this.A1j, "forwardMessagesReceived", sbA08);
        C0BR.A00(this.A1k, "forwardMessagesSent", sbA08);
        C0BR.A00(this.A1l, "forwardPhotoMessagesReceived", sbA08);
        C0BR.A00(this.A1m, "forwardPhotoMessagesSent", sbA08);
        C0BR.A00(this.A1n, "forwardStickerMessagesReceived", sbA08);
        C0BR.A00(this.A1o, "forwardStickerMessagesSent", sbA08);
        C0BR.A00(this.A1p, "forwardTextMessagesReceived", sbA08);
        C0BR.A00(this.A1q, "forwardTextMessagesSent", sbA08);
        C0BR.A00(this.A1r, "forwardUrlMessagesReceived", sbA08);
        C0BR.A00(this.A1s, "forwardUrlMessagesSent", sbA08);
        C0BR.A00(this.A1t, "forwardVideoMessagesReceived", sbA08);
        C0BR.A00(this.A1u, "forwardVideoMessagesSent", sbA08);
        C0BR.A00(AbstractC32971bt.A0P(this.A0m), "gaStatus", sbA08);
        C0BR.A00(this.A1v, "gifMessagesReceived", sbA08);
        C0BR.A00(this.A1w, "gifMessagesSent", sbA08);
        C0BR.A00(this.A1x, "greetingMsgsSent", sbA08);
        C0BR.A00(this.A01, "groupContainsBiz", sbA08);
        C0BR.A00(AbstractC32971bt.A0P(this.A0n), "groupInfoSetting", sbA08);
        C0BR.A00(this.A1y, "groupMembershipReplies", sbA08);
        C0BR.A00(this.A1z, "groupPrivateReplies", sbA08);
        C0BR.A00(this.A20, "groupSize", sbA08);
        C0BR.A00(this.A21, "groupStatusLikesOthersToOthers", sbA08);
        C0BR.A00(this.A22, "groupStatusLikesOthersToOwn", sbA08);
        C0BR.A00(this.A23, "groupStatusLikesOwnToOthers", sbA08);
        C0BR.A00(this.A24, "groupStatusLikesOwnToOwn", sbA08);
        C0BR.A00(this.A25, "groupStatusRepliesOthersToOthers", sbA08);
        C0BR.A00(this.A26, "groupStatusRepliesOthersToOwn", sbA08);
        C0BR.A00(this.A27, "groupStatusRepliesOwnToOthers", sbA08);
        C0BR.A00(this.A28, "groupStatusRepliesOwnToOwn", sbA08);
        C0BR.A00(this.A02, "hasReplied1On1", sbA08);
        C0BR.A00(this.A03, "hasUsername", sbA08);
        C0BR.A00(this.A04, "hasUsernamePin", sbA08);
        C0BR.A00(this.A29, "imagineCommandClick", sbA08);
        C0BR.A00(this.A2A, "imagineMeMessagesSent", sbA08);
        C0BR.A00(this.A2B, "imagineMePromptsInitiatedCount", sbA08);
        C0BR.A00(this.A05, "isAContact", sbA08);
        C0BR.A00(this.A06, "isAContactAtThreadCreation", sbA08);
        C0BR.A00(this.A07, "isAGroup", sbA08);
        C0BR.A00(this.A08, "isArchived", sbA08);
        C0BR.A00(this.A09, "isAutoMuted", sbA08);
        C0BR.A00(this.A0A, "isBizMvFrictionEligible", sbA08);
        C0BR.A00(this.A0B, "isBlocked", sbA08);
        C0BR.A00(this.A0C, "isCartAddClicked", sbA08);
        C0BR.A00(this.A0D, "isCommerceViewed", sbA08);
        C0BR.A00(this.A0E, "isCtaOnPdpClicked", sbA08);
        C0BR.A00(this.A0F, "isDeleted", sbA08);
        C0BR.A00(this.A0G, "isGuestThread", sbA08);
        C0BR.A00(this.A0H, "isInviteCreatedThread", sbA08);
        C0BR.A00(this.A0I, "isManagedAccount", sbA08);
        C0BR.A00(this.A0J, "isMessageYourself", sbA08);
        C0BR.A00(this.A0K, "isNewManagedAccountEmIgnored", sbA08);
        C0BR.A00(this.A0L, "isOppositePartyInitiated", sbA08);
        C0BR.A00(this.A0M, "isPinned", sbA08);
        C0BR.A00(this.A0N, "isPnhEnabledChat", sbA08);
        C0BR.A00(this.A0O, "isReported", sbA08);
        C0BR.A00(this.A0P, "isUser1pBizBotChat", sbA08);
        C0BR.A00(this.A0Q, "isUserAgent", sbA08);
        C0BR.A00(this.A0R, "isUsernameThread", sbA08);
        C0BR.A00(this.A0S, "isUsernameThreadAtCreation", sbA08);
        C0BR.A00(this.A2C, "labelledMsgs", sbA08);
        C0BR.A00(this.A0T, "limitSharingOption", sbA08);
        C0BR.A00(this.A2D, "locationsSent", sbA08);
        C0BR.A00(this.A2E, "markedReadCnt", sbA08);
        C0BR.A00(this.A2F, "markedReadMessageCnt", sbA08);
        C0BR.A00(this.A3M, "matchedMessagesMarkedAsReadWithDeltaTime", sbA08);
        C0BR.A00(this.A3N, "matchedMessagesReadWithDeltaTime", sbA08);
        C0BR.A00(this.A2G, "messagesRead", sbA08);
        C0BR.A00(this.A2H, "messagesReceived", sbA08);
        C0BR.A00(this.A2I, "messagesReceivedWithEnabledReadReceipt", sbA08);
        C0BR.A00(this.A2J, "messagesSent", sbA08);
        C0BR.A00(this.A2K, "messagesStarred", sbA08);
        C0BR.A00(this.A2L, "messagesUnread", sbA08);
        C0BR.A00(this.A2M, "metaAiMentionClick", sbA08);
        C0BR.A00(this.A2N, "metaAiMentionShow", sbA08);
        C0BR.A00(this.A0U, "newThread", sbA08);
        C0BR.A00(this.A2O, "notMvImpressions", sbA08);
        C0BR.A00(this.A0V, "oppositePartyHasBadge", sbA08);
        C0BR.A00(this.A0W, "oppositePartyHasBusinessIntent", sbA08);
        C0BR.A00(this.A0X, "oppositePartyHasProfilePhoto", sbA08);
        C0BR.A00(this.A0Y, "oppositePartyLimitSharingOption", sbA08);
        C0BR.A00(AbstractC32971bt.A0P(this.A0o), "oppositeVisibleIdentification", sbA08);
        C0BR.A00(this.A2P, "ordersSent", sbA08);
        C0BR.A00(this.A2Q, "paymentsSent", sbA08);
        C0BR.A00(this.A2R, "pdpInquiriesSent", sbA08);
        C0BR.A00(this.A2S, "pdpViews", sbA08);
        C0BR.A00(this.A2T, "photoMessagesReceived", sbA08);
        C0BR.A00(this.A2U, "photoMessagesSent", sbA08);
        C0BR.A00(this.A2V, "pollCreationMessagesReceived", sbA08);
        C0BR.A00(this.A2W, "pollCreationMessagesSent", sbA08);
        C0BR.A00(this.A2X, "pollUpdateMessagesReceived", sbA08);
        C0BR.A00(this.A2Y, "pollUpdateMessagesSent", sbA08);
        C0BR.A00(this.A2Z, "profileReplies", sbA08);
        C0BR.A00(this.A2a, "profileViews", sbA08);
        C0BR.A00(this.A2b, "pttMessagesReceived", sbA08);
        C0BR.A00(this.A2c, "pttMessagesSent", sbA08);
        C0BR.A00(this.A2d, "ptvMessagesReceived", sbA08);
        C0BR.A00(this.A2e, "ptvMessagesSent", sbA08);
        C0BR.A00(this.A2f, "quickRepliesSent", sbA08);
        C0BR.A00(this.A2g, "reactionsReceived", sbA08);
        C0BR.A00(this.A2h, "reactionsSent", sbA08);
        C0BR.A00(this.A2i, "receiverDefaultDisappearingDuration", sbA08);
        C0BR.A00(this.A2j, "repliesSent", sbA08);
        C0BR.A00(this.A0Z, "requestedPhoneNumber", sbA08);
        C0BR.A00(this.A0a, "seenMaskedPhoneNumber", sbA08);
        C0BR.A00(this.A2k, "senderDefaultDisappearingDuration", sbA08);
        C0BR.A00(this.A0b, "sharedPhoneNumber", sbA08);
        C0BR.A00(this.A0c, "sharesCommonGroup", sbA08);
        C0BR.A00(this.A2l, "smbMarketingMessagesReactionsSent", sbA08);
        C0BR.A00(this.A2m, "smbMarketingMessagesRepliesSent", sbA08);
        C0BR.A00(this.A2n, "smbMarketingMessagesSpamReports", sbA08);
        C0BR.A00(this.A2o, "smbMarketingMsgsReceived", sbA08);
        C0BR.A00(this.A2p, "smbMarketingMsgsSent", sbA08);
        C0BR.A00(this.A2q, "spamReports", sbA08);
        C0BR.A00(this.A2r, "startTime", sbA08);
        C0BR.A00(this.A2s, "statusReactionsReceived", sbA08);
        C0BR.A00(this.A2t, "statusReactionsSent", sbA08);
        C0BR.A00(this.A2u, "statusReplies", sbA08);
        C0BR.A00(this.A2v, "statusReplyMessagesReceived", sbA08);
        C0BR.A00(this.A2w, "statusViews", sbA08);
        C0BR.A00(this.A2x, "stickerMessagesReceived", sbA08);
        C0BR.A00(this.A2y, "stickerMessagesSent", sbA08);
        C0BR.A00(this.A2z, "suggestionPromptsClick", sbA08);
        C0BR.A00(this.A30, "suggestionPromptsShow", sbA08);
        C0BR.A00(this.A31, "textMessagesReceived", sbA08);
        C0BR.A00(this.A32, "textMessagesSent", sbA08);
        C0BR.A00(this.A3O, "threadCreationDate", sbA08);
        C0BR.A00(this.A3P, "threadDs", sbA08);
        C0BR.A00(this.A3Q, "threadId", sbA08);
        C0BR.A00(this.A3R, "threadIdMonthly", sbA08);
        C0BR.A00(this.A33, "tombstoneAiFutureproofedMessagesReceived", sbA08);
        C0BR.A00(this.A34, "tombstoneEphemeralMessagesReceived", sbA08);
        C0BR.A00(this.A35, "tombstoneViewOnceMessagesReceived", sbA08);
        C0BR.A00(this.A36, "totalCallDuration", sbA08);
        C0BR.A00(this.A37, "totalMessageEditsFromAgentCnt", sbA08);
        C0BR.A00(this.A38, "totalMessageFromAgentCnt", sbA08);
        C0BR.A00(this.A39, "totalMessageToAgentCnt", sbA08);
        C0BR.A00(AbstractC32971bt.A0P(this.A0p), "typeOfGroup", sbA08);
        C0BR.A00(this.A3A, "urlMessagesReceived", sbA08);
        C0BR.A00(this.A3B, "urlMessagesSent", sbA08);
        C0BR.A00(this.A0d, "userHasBusinessIntent", sbA08);
        C0BR.A00(this.A0e, "viaContactlessChats", sbA08);
        C0BR.A00(this.A3C, "videoCallsOffered", sbA08);
        C0BR.A00(this.A3D, "videoMessagesReceived", sbA08);
        C0BR.A00(this.A3E, "videoMessagesSent", sbA08);
        C0BR.A00(this.A3F, "viewOnceMessagesOpened", sbA08);
        C0BR.A00(this.A3G, "viewOnceMessagesReceived", sbA08);
        C0BR.A00(this.A3H, "viewOnceMessagesSent", sbA08);
        return AbstractC32971bt.A0Q(this.A3I, "voiceCallsOffered", sbA08);
    }
}
