package X;

import com.whatsapp.calling.opengl.MediaCodecVideoEncoder;
import com.whatsapp.ui.coreui.base.WaTextView;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

/* JADX INFO: renamed from: X.Mvo, reason: case insensitive filesystem */
/* JADX INFO: loaded from: classes11.dex */
public final class C49991Mvo extends C0BP {
    public Boolean A00;
    public Boolean A01;
    public Boolean A02;
    public Boolean A03;
    public Boolean A04;
    public Boolean A05;
    public Boolean A06;
    public Boolean A07;
    public Boolean A08;
    public Boolean A09;
    public Boolean A0A;
    public Boolean A0B;
    public Boolean A0C;
    public Boolean A0D;
    public Boolean A0E;
    public Boolean A0F;
    public Boolean A0G;
    public Boolean A0H;
    public Boolean A0I;
    public Boolean A0J;
    public Boolean A0K;
    public Boolean A0L;
    public Boolean A0M;
    public Boolean A0N;
    public Boolean A0O;
    public Integer A0P;
    public Integer A0Q;
    public Integer A0R;
    public Integer A0S;
    public Integer A0T;
    public Long A0U;
    public Long A0V;
    public Long A0W;
    public Long A0X;
    public Long A0Y;
    public Long A0Z;
    public Long A0a;
    public Long A0b;
    public Long A0c;
    public Long A0d;
    public Long A0e;
    public Long A0f;
    public Long A0g;
    public Long A0h;
    public Long A0i;
    public Long A0j;
    public Long A0k;
    public Long A0l;
    public Long A0m;
    public Long A0n;
    public Long A0o;
    public Long A0p;
    public Long A0q;
    public Long A0r;
    public Long A0s;
    public Long A0t;
    public Long A0u;
    public Long A0v;
    public Long A0w;
    public Long A0x;
    public Long A0y;
    public Long A0z;
    public Long A10;
    public Long A11;
    public Long A12;
    public Long A13;
    public Long A14;
    public Long A15;
    public Long A16;
    public Long A17;
    public Long A18;
    public Long A19;
    public Long A1A;
    public Long A1B;
    public Long A1C;
    public Long A1D;
    public Long A1E;
    public Long A1F;
    public Long A1G;
    public Long A1H;
    public Long A1I;
    public Long A1J;
    public Long A1K;
    public Long A1L;
    public Long A1M;
    public Long A1N;
    public Long A1O;
    public Long A1P;
    public Long A1Q;
    public Long A1R;
    public Long A1S;
    public Long A1T;
    public Long A1U;
    public Long A1V;
    public Long A1W;
    public Long A1X;
    public Long A1Y;
    public Long A1Z;
    public Long A1a;
    public Long A1b;
    public Long A1c;
    public Long A1d;
    public Long A1e;
    public Long A1f;
    public Long A1g;
    public Long A1h;
    public Long A1i;
    public Long A1j;
    public Long A1k;
    public Long A1l;
    public Long A1m;
    public Long A1n;
    public Long A1o;
    public Long A1p;
    public Long A1q;
    public Long A1r;
    public Long A1s;
    public Long A1t;
    public Long A1u;
    public Long A1v;
    public Long A1w;
    public Long A1x;
    public Long A1y;
    public Long A1z;
    public Long A20;
    public Long A21;
    public Long A22;
    public Long A23;
    public String A24;
    public String A25;
    public String A26;
    public String A27;
    public String A28;
    public String A29;

    public C49991Mvo() {
        super(6466, AbstractC465925m.A0y(1), 0, -1);
    }

    @Override // X.C0BP
    public String getEventNameForFalco() {
        return "wam_thread_interaction_data_core_consumer";
    }

    @Override // X.C0BP
    public java.util.Map getFieldsMapForLogging() {
        return null;
    }

    @Override // X.C0BP
    public int internalFalcoMigrationBatchNumber() {
        return 12;
    }

    /* JADX WARN: Code duplicated, block: B:13:0x002a  */
    @Override // X.C0BP
    public List validate() {
        ArrayList arrayListA1H = this.A27 == null ? AbstractC466125o.A1H(AbstractC466325q.A0M("thread_ds", "thread_interaction_data_core_consumer", C002401f.A00)) : null;
        if (this.A28 == null) {
            FPS fpsA0M = AbstractC466325q.A0M("thread_id", "thread_interaction_data_core_consumer", C002401f.A00);
            if (arrayListA1H != null) {
                arrayListA1H.add(fpsA0M);
            } else {
                arrayListA1H = AbstractC466125o.A1H(fpsA0M);
                if (arrayListA1H == null) {
                    return C002401f.A00;
                }
            }
        } else if (arrayListA1H == null) {
            return C002401f.A00;
        }
        return arrayListA1H;
    }

    @Override // X.C0BP
    public java.util.Map getFieldsMap() {
        LinkedHashMap linkedHashMapA1E = AbstractC465925m.A1E();
        linkedHashMapA1E.put(138, this.A0U);
        linkedHashMapA1E.put(139, this.A0V);
        linkedHashMapA1E.put(Integer.valueOf(MediaCodecVideoEncoder.MIN_ENCODER_HEIGHT), this.A0W);
        linkedHashMapA1E.put(140, this.A0X);
        linkedHashMapA1E.put(141, this.A0Y);
        linkedHashMapA1E.put(142, this.A00);
        linkedHashMapA1E.put(AbstractC148896gB.A0h(AbstractC148896gB.A0g(AbstractC466825v.A0g(AbstractC466325q.A0r(AbstractC466325q.A0q(AbstractC466325q.A0p(AbstractC466325q.A0o(AbstractC466325q.A0n(AbstractC466325q.A0l(AbstractC466325q.A0k(AbstractC466825v.A0d(AbstractC466825v.A0c(143, this.A01, linkedHashMapA1E), this.A0Z, linkedHashMapA1E), this.A0a, linkedHashMapA1E), this.A0b, linkedHashMapA1E), this.A0c, linkedHashMapA1E), this.A0d, linkedHashMapA1E), this.A0P, linkedHashMapA1E), this.A0e, linkedHashMapA1E), this.A0Q, linkedHashMapA1E), this.A0f, linkedHashMapA1E), this.A0g, linkedHashMapA1E), this.A0h, linkedHashMapA1E), this.A0i);
        linkedHashMapA1E.put(MJp.A0W(MJp.A0V(MJp.A0U(MJp.A0T(AbstractC148896gB.A0t(AbstractC202198ro.A0k(BA0.A0h(AbstractC148896gB.A0s(AbstractC148896gB.A0r(AbstractC148896gB.A0q(AbstractC202198ro.A0j(AbstractC148896gB.A0p(AbstractC148896gB.A0o(AbstractC148896gB.A0n(AbstractC148896gB.A0k(AbstractC148896gB.A0j(AbstractC148896gB.A0i(Integer.valueOf(C26698BmO.STATUS_STICKER_INTERACTION_MESSAGE_FIELD_NUMBER), this.A0j, linkedHashMapA1E), this.A0k, linkedHashMapA1E), this.A0l, linkedHashMapA1E), this.A0m, linkedHashMapA1E), this.A0n, linkedHashMapA1E), this.A0o, linkedHashMapA1E), this.A0p, linkedHashMapA1E), this.A0q, linkedHashMapA1E), this.A0r, linkedHashMapA1E), this.A0s, linkedHashMapA1E), this.A0t, linkedHashMapA1E), this.A0u, linkedHashMapA1E), this.A0v, linkedHashMapA1E), this.A0w, linkedHashMapA1E), this.A0x, linkedHashMapA1E), this.A0y, linkedHashMapA1E), this.A0z, linkedHashMapA1E), this.A10);
        AbstractC466525s.A1S(BA1.A0f(linkedHashMapA1E, 134), linkedHashMapA1E, 135);
        linkedHashMapA1E.put(MJp.A0g(MJp.A0f(MJp.A0e(MJp.A0d(MJp.A0c(MJp.A0b(MJp.A0a(MJp.A0Z(BA0.A0i(MJp.A0Y(35, this.A11, linkedHashMapA1E), this.A12, linkedHashMapA1E), this.A13, linkedHashMapA1E), this.A14, linkedHashMapA1E), this.A15, linkedHashMapA1E), this.A16, linkedHashMapA1E), this.A17, linkedHashMapA1E), this.A18, linkedHashMapA1E), this.A0R, linkedHashMapA1E), this.A19, linkedHashMapA1E), this.A1A);
        linkedHashMapA1E.put(AbstractC31894DxJ.A19(), this.A1B);
        linkedHashMapA1E.put(MJp.A0i(48, this.A1C, linkedHashMapA1E), this.A1D);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.NEWSLETTER_FOLLOWER_INVITE_MESSAGE_V2_FIELD_NUMBER), this.A1E);
        linkedHashMapA1E.put(114, this.A1F);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.POLL_RESULT_SNAPSHOT_MESSAGE_V3_FIELD_NUMBER), this.A1G);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.NEWSLETTER_ADMIN_PROFILE_MESSAGE_FIELD_NUMBER), this.A1H);
        linkedHashMapA1E.put(117, this.A1I);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.SPOILER_MESSAGE_FIELD_NUMBER), this.A1J);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.POLL_CREATION_MESSAGE_V6_FIELD_NUMBER), this.A1K);
        linkedHashMapA1E.put(120, this.A1L);
        AbstractC466825v.A0t(145, linkedHashMapA1E);
        linkedHashMapA1E.put(50, this.A02);
        linkedHashMapA1E.put(MJp.A0p(MJp.A0n(MJp.A0m(MJp.A0l(MJp.A0k(AbstractC31894DxJ.A1A(), this.A03, linkedHashMapA1E), this.A04, linkedHashMapA1E), this.A05, linkedHashMapA1E), this.A06, linkedHashMapA1E), this.A07, linkedHashMapA1E), this.A08);
        linkedHashMapA1E.put(MJp.A0q(112, this.A09, linkedHashMapA1E), this.A0A);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.POLL_ADD_OPTION_MESSAGE_FIELD_NUMBER), this.A0B);
        linkedHashMapA1E.put(136, this.A0C);
        linkedHashMapA1E.put(59, this.A0D);
        linkedHashMapA1E.put(MJp.A0s(MJp.A0r(Integer.valueOf(C26698BmO.EVENT_INVITE_MESSAGE_FIELD_NUMBER), this.A0E, linkedHashMapA1E), this.A0F, linkedHashMapA1E), this.A0G);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.GROUP_ROOT_KEY_SHARE_FIELD_NUMBER), this.A0H);
        linkedHashMapA1E.put(137, this.A0I);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.PAYMENT_REMINDER_MESSAGE_FIELD_NUMBER), this.A0J);
        linkedHashMapA1E.put(62, this.A1M);
        linkedHashMapA1E.put(63, this.A1N);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.BOT_PLATFORM_REGISTRATION_SUCCESS_MESSAGE_FIELD_NUMBER), this.A24);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.NEWSLETTER_SCHEDULED_MESSAGE_FIELD_NUMBER), this.A25);
        linkedHashMapA1E.put(64, this.A1O);
        linkedHashMapA1E.put(65, this.A1P);
        linkedHashMapA1E.put(133, this.A1Q);
        linkedHashMapA1E.put(66, this.A1R);
        linkedHashMapA1E.put(68, this.A1S);
        AbstractC466825v.A0t(146, linkedHashMapA1E);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.SPLIT_PAYMENT_MESSAGE_FIELD_NUMBER), this.A0K);
        linkedHashMapA1E.put(69, this.A0S);
        linkedHashMapA1E.put(70, this.A1T);
        linkedHashMapA1E.put(71, this.A1U);
        linkedHashMapA1E.put(72, this.A1V);
        linkedHashMapA1E.put(73, this.A1W);
        linkedHashMapA1E.put(74, this.A1X);
        linkedHashMapA1E.put(75, this.A1Y);
        linkedHashMapA1E.put(76, this.A1Z);
        linkedHashMapA1E.put(77, this.A1a);
        linkedHashMapA1E.put(78, this.A1b);
        linkedHashMapA1E.put(79, this.A1c);
        linkedHashMapA1E.put(80, this.A1d);
        linkedHashMapA1E.put(81, this.A1e);
        linkedHashMapA1E.put(82, this.A1f);
        linkedHashMapA1E.put(83, this.A1g);
        linkedHashMapA1E.put(85, this.A1h);
        linkedHashMapA1E.put(86, this.A0L);
        linkedHashMapA1E.put(87, this.A0M);
        linkedHashMapA1E.put(89, this.A0N);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.QUESTION_RESPONSE_MESSAGE_FIELD_NUMBER), this.A0O);
        linkedHashMapA1E.put(90, this.A1i);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.NEWSLETTER_ADMIN_PROFILE_STATUS_MESSAGE_FIELD_NUMBER), this.A1j);
        linkedHashMapA1E.put(91, this.A1k);
        linkedHashMapA1E.put(127, this.A1l);
        linkedHashMapA1E.put(92, this.A1m);
        linkedHashMapA1E.put(93, this.A1n);
        linkedHashMapA1E.put(94, this.A1o);
        linkedHashMapA1E.put(95, this.A1p);
        linkedHashMapA1E.put(96, this.A1q);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.POLL_CREATION_MESSAGE_V5_FIELD_NUMBER), this.A26);
        linkedHashMapA1E.put(97, this.A27);
        linkedHashMapA1E.put(98, this.A28);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.STATUS_QUOTED_MESSAGE_FIELD_NUMBER), this.A29);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.STATUS_LINK_PREVIEW_METADATA_FIELD_NUMBER), this.A1r);
        linkedHashMapA1E.put(128, this.A1s);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.MUSIC_MESSAGE_FIELD_NUMBER), this.A1t);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.NEWSLETTER_FOLLOWER_INVITE_MESSAGE_FIELD_NUMBER), this.A0T);
        linkedHashMapA1E.put(99, this.A1u);
        linkedHashMapA1E.put(100, this.A1v);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.MESSAGE_HISTORY_NOTICE_FIELD_NUMBER), this.A1w);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.GROUP_STATUS_MESSAGE_V2_FIELD_NUMBER), this.A1x);
        Object objA0f = BA1.A0f(linkedHashMapA1E, WaTextView.ONE_LINE_DISPLAY_TEXT_LENGTH_LIMIT);
        AbstractC466525s.A1S(objA0f, linkedHashMapA1E, 151);
        AbstractC466525s.A1S(objA0f, linkedHashMapA1E, 152);
        AbstractC466525s.A1S(objA0f, linkedHashMapA1E, 153);
        AbstractC466525s.A1S(objA0f, linkedHashMapA1E, 154);
        AbstractC466525s.A1S(objA0f, linkedHashMapA1E, 155);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.BOT_FORWARDED_MESSAGE_FIELD_NUMBER), this.A1y);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.STATUS_QUESTION_ANSWER_MESSAGE_FIELD_NUMBER), this.A1z);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.QUESTION_REPLY_MESSAGE_FIELD_NUMBER), this.A20);
        linkedHashMapA1E.put(147, this.A21);
        linkedHashMapA1E.put(148, this.A22);
        linkedHashMapA1E.put(149, this.A23);
        Object objA0f2 = BA1.A0f(linkedHashMapA1E, 156);
        AbstractC466525s.A1S(objA0f2, linkedHashMapA1E, 157);
        AbstractC466525s.A1S(objA0f2, linkedHashMapA1E, 158);
        return linkedHashMapA1E;
    }

    @Override // X.C0BP
    public java.util.Map getFieldsMapForFalco() {
        LinkedHashMap linkedHashMapA1E = AbstractC465925m.A1E();
        linkedHashMapA1E.put("after_read_duration", this.A0U);
        linkedHashMapA1E.put("after_read_messages_expired", this.A0V);
        linkedHashMapA1E.put("after_read_messages_received", this.A0W);
        linkedHashMapA1E.put("after_read_messages_sent", this.A0X);
        linkedHashMapA1E.put("after_read_messages_unread_expired", this.A0Y);
        linkedHashMapA1E.put("after_read_turned_off", this.A00);
        linkedHashMapA1E.put("after_read_turned_on", this.A01);
        linkedHashMapA1E.put("audio_messages_received", this.A0Z);
        linkedHashMapA1E.put("audio_messages_sent", this.A0a);
        linkedHashMapA1E.put("broadcast_msgs_received", this.A0b);
        linkedHashMapA1E.put("broadcast_msgs_sent", this.A0c);
        linkedHashMapA1E.put("chat_ephemerality_duration", this.A0d);
        Integer num = this.A0P;
        if (num != null && num.intValue() != 0) {
            linkedHashMapA1E.put("chat_muted", num);
        }
        linkedHashMapA1E.put("chat_overflow_clicks", this.A0e);
        Integer num2 = this.A0Q;
        if (num2 != null && num2.intValue() != 0) {
            linkedHashMapA1E.put("chat_type_ind", num2);
        }
        linkedHashMapA1E.put("comments_received", this.A0f);
        linkedHashMapA1E.put("document_messages_received", this.A0g);
        linkedHashMapA1E.put("document_messages_sent", this.A0h);
        linkedHashMapA1E.put("edited_msgs_sent", this.A0i);
        linkedHashMapA1E.put("ephemeral_messages_expired", this.A0j);
        linkedHashMapA1E.put("ephemeral_messages_received", this.A0k);
        linkedHashMapA1E.put("ephemeral_messages_sent", this.A0l);
        linkedHashMapA1E.put("ephemeral_messages_unread_expired", this.A0m);
        linkedHashMapA1E.put("event_creation_messages_received", this.A0n);
        linkedHashMapA1E.put("event_creation_messages_sent", this.A0o);
        linkedHashMapA1E.put("event_response_messages_received", this.A0p);
        linkedHashMapA1E.put("event_response_messages_sent", this.A0q);
        linkedHashMapA1E.put("forward_audio_messages_received", this.A0r);
        linkedHashMapA1E.put("forward_audio_messages_sent", this.A0s);
        linkedHashMapA1E.put("forward_document_messages_received", this.A0t);
        linkedHashMapA1E.put("forward_document_messages_sent", this.A0u);
        linkedHashMapA1E.put("forward_gif_messages_received", this.A0v);
        linkedHashMapA1E.put("forward_gif_messages_sent", this.A0w);
        linkedHashMapA1E.put("forward_messages_received", this.A0x);
        linkedHashMapA1E.put("forward_messages_sent", this.A0y);
        linkedHashMapA1E.put("forward_photo_messages_received", this.A0z);
        linkedHashMapA1E.put("forward_photo_messages_sent", this.A10);
        linkedHashMapA1E.put("forward_ptv_messages_received", null);
        linkedHashMapA1E.put("forward_ptv_messages_sent", null);
        linkedHashMapA1E.put("forward_sticker_messages_received", this.A11);
        linkedHashMapA1E.put("forward_sticker_messages_sent", this.A12);
        linkedHashMapA1E.put("forward_text_messages_received", this.A13);
        linkedHashMapA1E.put("forward_text_messages_sent", this.A14);
        linkedHashMapA1E.put("forward_url_messages_received", this.A15);
        linkedHashMapA1E.put("forward_url_messages_sent", this.A16);
        linkedHashMapA1E.put("forward_video_messages_received", this.A17);
        linkedHashMapA1E.put("forward_video_messages_sent", this.A18);
        linkedHashMapA1E.put("ga_status", this.A0R);
        linkedHashMapA1E.put("gif_messages_received", this.A19);
        linkedHashMapA1E.put("gif_messages_sent", this.A1A);
        linkedHashMapA1E.put("group_membership_replies", this.A1B);
        linkedHashMapA1E.put("group_private_replies", this.A1C);
        linkedHashMapA1E.put("group_size", this.A1D);
        linkedHashMapA1E.put("group_status_likes_others_to_others", this.A1E);
        linkedHashMapA1E.put("group_status_likes_others_to_own", this.A1F);
        linkedHashMapA1E.put("group_status_likes_own_to_others", this.A1G);
        linkedHashMapA1E.put("group_status_likes_own_to_own", this.A1H);
        linkedHashMapA1E.put("group_status_replies_others_to_others", this.A1I);
        linkedHashMapA1E.put("group_status_replies_others_to_own", this.A1J);
        linkedHashMapA1E.put("group_status_replies_own_to_others", this.A1K);
        linkedHashMapA1E.put("group_status_replies_own_to_own", this.A1L);
        linkedHashMapA1E.put("has_replied_1_on_1", null);
        linkedHashMapA1E.put("has_username", this.A02);
        linkedHashMapA1E.put("has_username_pin", this.A03);
        linkedHashMapA1E.put("is_a_contact", this.A04);
        linkedHashMapA1E.put("is_a_contact_at_thread_creation", this.A05);
        linkedHashMapA1E.put("is_a_group", this.A06);
        linkedHashMapA1E.put("is_archived", this.A07);
        linkedHashMapA1E.put("is_deleted", this.A08);
        linkedHashMapA1E.put("is_guest_thread", this.A09);
        linkedHashMapA1E.put("is_invite_created_thread", this.A0A);
        linkedHashMapA1E.put("is_managed_account", this.A0B);
        linkedHashMapA1E.put("is_message_yourself", this.A0C);
        linkedHashMapA1E.put("is_meta_ai_assistant", this.A0D);
        linkedHashMapA1E.put("is_new_managed_account_em_ignored", this.A0E);
        linkedHashMapA1E.put("is_pinned", this.A0F);
        linkedHashMapA1E.put("is_pnh_enabled_chat", this.A0G);
        linkedHashMapA1E.put("is_username_thread", this.A0H);
        linkedHashMapA1E.put("is_username_thread_at_creation", this.A0I);
        linkedHashMapA1E.put("limit_sharing_option", this.A0J);
        linkedHashMapA1E.put("marked_read_cnt", this.A1M);
        linkedHashMapA1E.put("marked_read_message_cnt", this.A1N);
        linkedHashMapA1E.put("matched_messages_marked_as_read_with_delta_time", this.A24);
        linkedHashMapA1E.put("matched_messages_read_with_delta_time", this.A25);
        linkedHashMapA1E.put("messages_read", this.A1O);
        linkedHashMapA1E.put("messages_received", this.A1P);
        linkedHashMapA1E.put("messages_received_with_enabled_read_receipt", this.A1Q);
        linkedHashMapA1E.put("messages_sent", this.A1R);
        linkedHashMapA1E.put("messages_unread", this.A1S);
        linkedHashMapA1E.put("opposite_party_has_profile_photo", null);
        linkedHashMapA1E.put("opposite_party_limit_sharing_option", this.A0K);
        Integer num3 = this.A0S;
        if (num3 != null && num3.intValue() != 0) {
            linkedHashMapA1E.put("opposite_visible_identification", num3);
        }
        linkedHashMapA1E.put("photo_messages_received", this.A1T);
        linkedHashMapA1E.put("photo_messages_sent", this.A1U);
        linkedHashMapA1E.put("poll_creation_messages_received", this.A1V);
        linkedHashMapA1E.put("poll_creation_messages_sent", this.A1W);
        linkedHashMapA1E.put("poll_update_messages_received", this.A1X);
        linkedHashMapA1E.put("poll_update_messages_sent", this.A1Y);
        linkedHashMapA1E.put("profile_replies", this.A1Z);
        linkedHashMapA1E.put("profile_views", this.A1a);
        linkedHashMapA1E.put("ptt_messages_received", this.A1b);
        linkedHashMapA1E.put("ptt_messages_sent", this.A1c);
        linkedHashMapA1E.put("ptv_messages_received", this.A1d);
        linkedHashMapA1E.put("ptv_messages_sent", this.A1e);
        linkedHashMapA1E.put("reactions_received", this.A1f);
        linkedHashMapA1E.put("reactions_sent", this.A1g);
        linkedHashMapA1E.put("replies_sent", this.A1h);
        linkedHashMapA1E.put("requested_phone_number", this.A0L);
        linkedHashMapA1E.put("seen_masked_phone_number", this.A0M);
        linkedHashMapA1E.put("shared_phone_number", this.A0N);
        linkedHashMapA1E.put("shares_common_group", this.A0O);
        linkedHashMapA1E.put("status_reactions_received", this.A1i);
        linkedHashMapA1E.put("status_reactions_sent", this.A1j);
        linkedHashMapA1E.put("status_replies", this.A1k);
        linkedHashMapA1E.put("status_reply_messages_received", this.A1l);
        linkedHashMapA1E.put("status_views", this.A1m);
        linkedHashMapA1E.put("sticker_messages_received", this.A1n);
        linkedHashMapA1E.put("sticker_messages_sent", this.A1o);
        linkedHashMapA1E.put("text_messages_received", this.A1p);
        linkedHashMapA1E.put("text_messages_sent", this.A1q);
        linkedHashMapA1E.put("thread_creation_date", this.A26);
        linkedHashMapA1E.put("thread_ds", this.A27);
        linkedHashMapA1E.put("thread_id", this.A28);
        linkedHashMapA1E.put("thread_id_by_lid", this.A29);
        linkedHashMapA1E.put("tombstone_ai_futureproofed_messages_received", this.A1r);
        linkedHashMapA1E.put("tombstone_ephemeral_messages_received", this.A1s);
        linkedHashMapA1E.put("tombstone_view_once_messages_received", this.A1t);
        BA2.A0x(this.A0T, linkedHashMapA1E);
        linkedHashMapA1E.put("url_messages_received", this.A1u);
        linkedHashMapA1E.put("url_messages_sent", this.A1v);
        linkedHashMapA1E.put("video_messages_received", this.A1w);
        linkedHashMapA1E.put("video_messages_sent", this.A1x);
        linkedHashMapA1E.put("view_once_audio_messages_opened", null);
        linkedHashMapA1E.put("view_once_audio_messages_received", null);
        linkedHashMapA1E.put("view_once_audio_messages_sent", null);
        linkedHashMapA1E.put("view_once_image_messages_opened", null);
        linkedHashMapA1E.put("view_once_image_messages_received", null);
        linkedHashMapA1E.put("view_once_image_messages_sent", null);
        linkedHashMapA1E.put("view_once_messages_opened", this.A1y);
        linkedHashMapA1E.put("view_once_messages_received", this.A1z);
        linkedHashMapA1E.put("view_once_messages_sent", this.A20);
        linkedHashMapA1E.put("view_once_text_messages_opened", this.A21);
        linkedHashMapA1E.put("view_once_text_messages_received", this.A22);
        linkedHashMapA1E.put("view_once_text_messages_sent", this.A23);
        linkedHashMapA1E.put("view_once_video_messages_opened", null);
        linkedHashMapA1E.put("view_once_video_messages_received", null);
        linkedHashMapA1E.put("view_once_video_messages_sent", null);
        return linkedHashMapA1E;
    }

    @Override // X.C0BP
    public void serialize(InterfaceC79783iN interfaceC79783iN) {
        throw AbstractC466525s.A0m();
    }

    public String toString() {
        StringBuilder sbA08 = AnonymousClass000.A08();
        sbA08.append("WamThreadInteractionDataCoreConsumer {");
        C0BR.A00(this.A0U, "afterReadDuration", sbA08);
        C0BR.A00(this.A0V, "afterReadMessagesExpired", sbA08);
        C0BR.A00(this.A0W, "afterReadMessagesReceived", sbA08);
        C0BR.A00(this.A0X, "afterReadMessagesSent", sbA08);
        C0BR.A00(this.A0Y, "afterReadMessagesUnreadExpired", sbA08);
        C0BR.A00(this.A00, "afterReadTurnedOff", sbA08);
        C0BR.A00(this.A01, "afterReadTurnedOn", sbA08);
        C0BR.A00(this.A0Z, "audioMessagesReceived", sbA08);
        C0BR.A00(this.A0a, "audioMessagesSent", sbA08);
        C0BR.A00(this.A0b, "broadcastMsgsReceived", sbA08);
        C0BR.A00(this.A0c, "broadcastMsgsSent", sbA08);
        C0BR.A00(this.A0d, "chatEphemeralityDuration", sbA08);
        C0BR.A00(AbstractC32971bt.A0P(this.A0P), "chatMuted", sbA08);
        C0BR.A00(this.A0e, "chatOverflowClicks", sbA08);
        C0BR.A00(AbstractC32971bt.A0P(this.A0Q), "chatTypeInd", sbA08);
        C0BR.A00(this.A0f, "commentsReceived", sbA08);
        C0BR.A00(this.A0g, "documentMessagesReceived", sbA08);
        C0BR.A00(this.A0h, "documentMessagesSent", sbA08);
        C0BR.A00(this.A0i, "editedMsgsSent", sbA08);
        C0BR.A00(this.A0j, "ephemeralMessagesExpired", sbA08);
        C0BR.A00(this.A0k, "ephemeralMessagesReceived", sbA08);
        C0BR.A00(this.A0l, "ephemeralMessagesSent", sbA08);
        C0BR.A00(this.A0m, "ephemeralMessagesUnreadExpired", sbA08);
        C0BR.A00(this.A0n, "eventCreationMessagesReceived", sbA08);
        C0BR.A00(this.A0o, "eventCreationMessagesSent", sbA08);
        C0BR.A00(this.A0p, "eventResponseMessagesReceived", sbA08);
        C0BR.A00(this.A0q, "eventResponseMessagesSent", sbA08);
        C0BR.A00(this.A0r, "forwardAudioMessagesReceived", sbA08);
        C0BR.A00(this.A0s, "forwardAudioMessagesSent", sbA08);
        C0BR.A00(this.A0t, "forwardDocumentMessagesReceived", sbA08);
        C0BR.A00(this.A0u, "forwardDocumentMessagesSent", sbA08);
        C0BR.A00(this.A0v, "forwardGifMessagesReceived", sbA08);
        C0BR.A00(this.A0w, "forwardGifMessagesSent", sbA08);
        C0BR.A00(this.A0x, "forwardMessagesReceived", sbA08);
        C0BR.A00(this.A0y, "forwardMessagesSent", sbA08);
        C0BR.A00(this.A0z, "forwardPhotoMessagesReceived", sbA08);
        C0BR.A00(this.A10, "forwardPhotoMessagesSent", sbA08);
        C0BR.A00(this.A11, "forwardStickerMessagesReceived", sbA08);
        C0BR.A00(this.A12, "forwardStickerMessagesSent", sbA08);
        C0BR.A00(this.A13, "forwardTextMessagesReceived", sbA08);
        C0BR.A00(this.A14, "forwardTextMessagesSent", sbA08);
        C0BR.A00(this.A15, "forwardUrlMessagesReceived", sbA08);
        C0BR.A00(this.A16, "forwardUrlMessagesSent", sbA08);
        C0BR.A00(this.A17, "forwardVideoMessagesReceived", sbA08);
        C0BR.A00(this.A18, "forwardVideoMessagesSent", sbA08);
        C0BR.A00(AbstractC32971bt.A0P(this.A0R), "gaStatus", sbA08);
        C0BR.A00(this.A19, "gifMessagesReceived", sbA08);
        C0BR.A00(this.A1A, "gifMessagesSent", sbA08);
        C0BR.A00(this.A1B, "groupMembershipReplies", sbA08);
        C0BR.A00(this.A1C, "groupPrivateReplies", sbA08);
        C0BR.A00(this.A1D, "groupSize", sbA08);
        C0BR.A00(this.A1E, "groupStatusLikesOthersToOthers", sbA08);
        C0BR.A00(this.A1F, "groupStatusLikesOthersToOwn", sbA08);
        C0BR.A00(this.A1G, "groupStatusLikesOwnToOthers", sbA08);
        C0BR.A00(this.A1H, "groupStatusLikesOwnToOwn", sbA08);
        C0BR.A00(this.A1I, "groupStatusRepliesOthersToOthers", sbA08);
        C0BR.A00(this.A1J, "groupStatusRepliesOthersToOwn", sbA08);
        C0BR.A00(this.A1K, "groupStatusRepliesOwnToOthers", sbA08);
        C0BR.A00(this.A1L, "groupStatusRepliesOwnToOwn", sbA08);
        C0BR.A00(this.A02, "hasUsername", sbA08);
        C0BR.A00(this.A03, "hasUsernamePin", sbA08);
        C0BR.A00(this.A04, "isAContact", sbA08);
        C0BR.A00(this.A05, "isAContactAtThreadCreation", sbA08);
        C0BR.A00(this.A06, "isAGroup", sbA08);
        C0BR.A00(this.A07, "isArchived", sbA08);
        C0BR.A00(this.A08, "isDeleted", sbA08);
        C0BR.A00(this.A09, "isGuestThread", sbA08);
        C0BR.A00(this.A0A, "isInviteCreatedThread", sbA08);
        C0BR.A00(this.A0B, "isManagedAccount", sbA08);
        C0BR.A00(this.A0C, "isMessageYourself", sbA08);
        C0BR.A00(this.A0D, "isMetaAiAssistant", sbA08);
        C0BR.A00(this.A0E, "isNewManagedAccountEmIgnored", sbA08);
        C0BR.A00(this.A0F, "isPinned", sbA08);
        C0BR.A00(this.A0G, "isPnhEnabledChat", sbA08);
        C0BR.A00(this.A0H, "isUsernameThread", sbA08);
        C0BR.A00(this.A0I, "isUsernameThreadAtCreation", sbA08);
        C0BR.A00(this.A0J, "limitSharingOption", sbA08);
        C0BR.A00(this.A1M, "markedReadCnt", sbA08);
        C0BR.A00(this.A1N, "markedReadMessageCnt", sbA08);
        C0BR.A00(this.A24, "matchedMessagesMarkedAsReadWithDeltaTime", sbA08);
        C0BR.A00(this.A25, "matchedMessagesReadWithDeltaTime", sbA08);
        C0BR.A00(this.A1O, "messagesRead", sbA08);
        C0BR.A00(this.A1P, "messagesReceived", sbA08);
        C0BR.A00(this.A1Q, "messagesReceivedWithEnabledReadReceipt", sbA08);
        C0BR.A00(this.A1R, "messagesSent", sbA08);
        C0BR.A00(this.A1S, "messagesUnread", sbA08);
        C0BR.A00(this.A0K, "oppositePartyLimitSharingOption", sbA08);
        C0BR.A00(AbstractC32971bt.A0P(this.A0S), "oppositeVisibleIdentification", sbA08);
        C0BR.A00(this.A1T, "photoMessagesReceived", sbA08);
        C0BR.A00(this.A1U, "photoMessagesSent", sbA08);
        C0BR.A00(this.A1V, "pollCreationMessagesReceived", sbA08);
        C0BR.A00(this.A1W, "pollCreationMessagesSent", sbA08);
        C0BR.A00(this.A1X, "pollUpdateMessagesReceived", sbA08);
        C0BR.A00(this.A1Y, "pollUpdateMessagesSent", sbA08);
        C0BR.A00(this.A1Z, "profileReplies", sbA08);
        C0BR.A00(this.A1a, "profileViews", sbA08);
        C0BR.A00(this.A1b, "pttMessagesReceived", sbA08);
        C0BR.A00(this.A1c, "pttMessagesSent", sbA08);
        C0BR.A00(this.A1d, "ptvMessagesReceived", sbA08);
        C0BR.A00(this.A1e, "ptvMessagesSent", sbA08);
        C0BR.A00(this.A1f, "reactionsReceived", sbA08);
        C0BR.A00(this.A1g, "reactionsSent", sbA08);
        C0BR.A00(this.A1h, "repliesSent", sbA08);
        C0BR.A00(this.A0L, "requestedPhoneNumber", sbA08);
        C0BR.A00(this.A0M, "seenMaskedPhoneNumber", sbA08);
        C0BR.A00(this.A0N, "sharedPhoneNumber", sbA08);
        C0BR.A00(this.A0O, "sharesCommonGroup", sbA08);
        C0BR.A00(this.A1i, "statusReactionsReceived", sbA08);
        C0BR.A00(this.A1j, "statusReactionsSent", sbA08);
        C0BR.A00(this.A1k, "statusReplies", sbA08);
        C0BR.A00(this.A1l, "statusReplyMessagesReceived", sbA08);
        C0BR.A00(this.A1m, "statusViews", sbA08);
        C0BR.A00(this.A1n, "stickerMessagesReceived", sbA08);
        C0BR.A00(this.A1o, "stickerMessagesSent", sbA08);
        C0BR.A00(this.A1p, "textMessagesReceived", sbA08);
        C0BR.A00(this.A1q, "textMessagesSent", sbA08);
        C0BR.A00(this.A26, "threadCreationDate", sbA08);
        C0BR.A00(this.A27, "threadDs", sbA08);
        C0BR.A00(this.A28, "threadId", sbA08);
        C0BR.A00(this.A29, "threadIdByLid", sbA08);
        C0BR.A00(this.A1r, "tombstoneAiFutureproofedMessagesReceived", sbA08);
        C0BR.A00(this.A1s, "tombstoneEphemeralMessagesReceived", sbA08);
        C0BR.A00(this.A1t, "tombstoneViewOnceMessagesReceived", sbA08);
        C0BR.A00(AbstractC32971bt.A0P(this.A0T), "typeOfGroup", sbA08);
        C0BR.A00(this.A1u, "urlMessagesReceived", sbA08);
        C0BR.A00(this.A1v, "urlMessagesSent", sbA08);
        C0BR.A00(this.A1w, "videoMessagesReceived", sbA08);
        C0BR.A00(this.A1x, "videoMessagesSent", sbA08);
        C0BR.A00(this.A1y, "viewOnceMessagesOpened", sbA08);
        C0BR.A00(this.A1z, "viewOnceMessagesReceived", sbA08);
        C0BR.A00(this.A20, "viewOnceMessagesSent", sbA08);
        C0BR.A00(this.A21, "viewOnceTextMessagesOpened", sbA08);
        C0BR.A00(this.A22, "viewOnceTextMessagesReceived", sbA08);
        return AbstractC32971bt.A0Q(this.A23, "viewOnceTextMessagesSent", sbA08);
    }
}
