package X;

import java.util.LinkedHashMap;

/* JADX INFO: renamed from: X.Mvd, reason: case insensitive filesystem */
/* JADX INFO: loaded from: classes11.dex */
public final class C49980Mvd extends C0BP {
    public String A00;
    public String A01;
    public String A02;
    public String A03;
    public String A04;
    public String A05;
    public String A06;
    public String A07;
    public String A08;
    public String A09;
    public String A0A;
    public String A0B;
    public String A0C;
    public String A0D;
    public String A0E;
    public String A0F;
    public String A0G;
    public String A0H;
    public String A0I;
    public String A0J;
    public String A0K;
    public String A0L;
    public String A0M;
    public String A0N;
    public String A0O;
    public String A0P;
    public String A0Q;
    public String A0R;
    public String A0S;
    public String A0T;
    public String A0U;
    public String A0V;
    public String A0W;
    public String A0X;
    public String A0Y;
    public String A0Z;
    public String A0a;
    public String A0b;
    public String A0c;
    public String A0d;
    public String A0e;
    public String A0f;
    public String A0g;
    public String A0h;
    public String A0i;
    public String A0j;
    public String A0k;
    public String A0l;
    public String A0m;
    public String A0n;
    public String A0o;
    public String A0p;
    public String A0q;
    public String A0r;
    public String A0s;
    public String A0t;
    public String A0u;
    public String A0v;
    public String A0w;
    public String A0x;
    public String A0y;
    public String A0z;
    public String A10;
    public String A11;
    public String A12;
    public String A13;
    public String A14;
    public String A15;
    public String A16;
    public String A17;
    public String A18;
    public String A19;
    public String A1A;
    public String A1B;
    public String A1C;
    public String A1D;
    public String A1E;
    public String A1F;
    public String A1G;
    public String A1H;
    public String A1I;
    public String A1J;
    public String A1K;
    public String A1L;
    public String A1M;
    public String A1N;
    public String A1O;
    public String A1P;
    public String A1Q;
    public String A1R;
    public String A1S;
    public String A1T;
    public String A1U;
    public String A1V;
    public String A1W;
    public String A1X;
    public String A1Y;
    public String A1Z;
    public String A1a;
    public String A1b;
    public String A1c;
    public String A1d;
    public String A1e;
    public String A1f;
    public String A1g;
    public String A1h;
    public String A1i;
    public String A1j;
    public String A1k;
    public String A1l;

    public C49980Mvd() {
        super(6670, new C001800w(1, 20, 1000, false), 0, -1);
    }

    @Override // X.C0BP
    public String getEventNameForFalco() {
        return "wam_video_upload_logging";
    }

    @Override // X.C0BP
    public java.util.Map getFieldsMapForLogging() {
        return null;
    }

    @Override // X.C0BP
    public int internalFalcoMigrationBatchNumber() {
        return 9;
    }

    @Override // X.C0BP
    public java.util.Map getFieldsMap() {
        LinkedHashMap linkedHashMapA1E = AbstractC465925m.A1E();
        linkedHashMapA1E.put(MJp.A0h(MJp.A0g(MJp.A0f(MJp.A0e(MJp.A0d(MJp.A0c(MJp.A0b(MJp.A0a(MJp.A0Z(BA0.A0i(MJp.A0Y(MJp.A0X(MJp.A0W(MJp.A0V(MJp.A0U(MJp.A0T(AbstractC148896gB.A0t(AbstractC202198ro.A0k(BA0.A0h(AbstractC148896gB.A0s(AbstractC148896gB.A0r(AbstractC148896gB.A0q(AbstractC202198ro.A0j(AbstractC148896gB.A0p(AbstractC148896gB.A0o(AbstractC148896gB.A0n(AbstractC148896gB.A0m(AbstractC148896gB.A0l(AbstractC148896gB.A0k(AbstractC148896gB.A0j(AbstractC148896gB.A0i(AbstractC148896gB.A0h(AbstractC148896gB.A0g(AbstractC466825v.A0g(AbstractC466825v.A0f(AbstractC466825v.A0e(AbstractC466325q.A0r(AbstractC466325q.A0q(AbstractC466325q.A0p(AbstractC466325q.A0o(AbstractC466325q.A0n(AbstractC466325q.A0m(AbstractC466325q.A0l(AbstractC466325q.A0k(AbstractC466825v.A0d(AbstractC466025n.A1H(), this.A00, linkedHashMapA1E), this.A01, linkedHashMapA1E), this.A02, linkedHashMapA1E), this.A03, linkedHashMapA1E), this.A04, linkedHashMapA1E), this.A05, linkedHashMapA1E), this.A06, linkedHashMapA1E), this.A07, linkedHashMapA1E), this.A08, linkedHashMapA1E), this.A09, linkedHashMapA1E), this.A0A, linkedHashMapA1E), this.A0B, linkedHashMapA1E), this.A0C, linkedHashMapA1E), this.A0D, linkedHashMapA1E), this.A0E, linkedHashMapA1E), this.A0F, linkedHashMapA1E), this.A0G, linkedHashMapA1E), this.A0H, linkedHashMapA1E), this.A0I, linkedHashMapA1E), this.A0J, linkedHashMapA1E), this.A0K, linkedHashMapA1E), this.A0L, linkedHashMapA1E), this.A0M, linkedHashMapA1E), this.A0N, linkedHashMapA1E), this.A0O, linkedHashMapA1E), this.A0P, linkedHashMapA1E), this.A0Q, linkedHashMapA1E), this.A0R, linkedHashMapA1E), this.A0S, linkedHashMapA1E), this.A0T, linkedHashMapA1E), this.A0U, linkedHashMapA1E), this.A0V, linkedHashMapA1E), this.A0W, linkedHashMapA1E), this.A0X, linkedHashMapA1E), this.A0Y, linkedHashMapA1E), this.A0Z, linkedHashMapA1E), this.A0a, linkedHashMapA1E), this.A0b, linkedHashMapA1E), this.A0c, linkedHashMapA1E), this.A0d, linkedHashMapA1E), this.A0e, linkedHashMapA1E), this.A0f, linkedHashMapA1E), this.A0g, linkedHashMapA1E), this.A0h, linkedHashMapA1E), this.A0i, linkedHashMapA1E), this.A0j);
        linkedHashMapA1E.put(AbstractC31894DxJ.A19(), this.A0k);
        linkedHashMapA1E.put(MJp.A0j(MJp.A0i(48, this.A0l, linkedHashMapA1E), this.A0m, linkedHashMapA1E), this.A0n);
        linkedHashMapA1E.put(MJp.A0q(MJp.A0p(MJp.A0o(MJp.A0n(MJp.A0m(MJp.A0l(MJp.A0k(AbstractC31894DxJ.A1A(), this.A0o, linkedHashMapA1E), this.A0p, linkedHashMapA1E), this.A0q, linkedHashMapA1E), this.A0r, linkedHashMapA1E), this.A0s, linkedHashMapA1E), this.A0t, linkedHashMapA1E), this.A0u, linkedHashMapA1E), this.A0v);
        linkedHashMapA1E.put(MJp.A0s(MJp.A0r(59, this.A0w, linkedHashMapA1E), this.A0x, linkedHashMapA1E), this.A0y);
        linkedHashMapA1E.put(62, this.A0z);
        linkedHashMapA1E.put(63, this.A10);
        linkedHashMapA1E.put(64, this.A11);
        linkedHashMapA1E.put(65, this.A12);
        linkedHashMapA1E.put(66, this.A13);
        linkedHashMapA1E.put(67, this.A14);
        linkedHashMapA1E.put(68, this.A15);
        linkedHashMapA1E.put(69, this.A16);
        linkedHashMapA1E.put(70, this.A17);
        linkedHashMapA1E.put(71, this.A18);
        linkedHashMapA1E.put(72, this.A19);
        linkedHashMapA1E.put(73, this.A1A);
        linkedHashMapA1E.put(74, this.A1B);
        linkedHashMapA1E.put(75, this.A1C);
        linkedHashMapA1E.put(76, this.A1D);
        linkedHashMapA1E.put(77, this.A1E);
        linkedHashMapA1E.put(78, this.A1F);
        linkedHashMapA1E.put(79, this.A1G);
        linkedHashMapA1E.put(80, this.A1H);
        linkedHashMapA1E.put(81, this.A1I);
        linkedHashMapA1E.put(82, this.A1J);
        linkedHashMapA1E.put(83, this.A1K);
        linkedHashMapA1E.put(84, this.A1L);
        linkedHashMapA1E.put(85, this.A1M);
        linkedHashMapA1E.put(86, this.A1N);
        linkedHashMapA1E.put(87, this.A1O);
        linkedHashMapA1E.put(88, this.A1P);
        linkedHashMapA1E.put(89, this.A1Q);
        linkedHashMapA1E.put(90, this.A1R);
        linkedHashMapA1E.put(91, this.A1S);
        linkedHashMapA1E.put(92, this.A1T);
        linkedHashMapA1E.put(93, this.A1U);
        linkedHashMapA1E.put(94, this.A1V);
        linkedHashMapA1E.put(95, this.A1W);
        linkedHashMapA1E.put(96, this.A1X);
        linkedHashMapA1E.put(97, this.A1Y);
        linkedHashMapA1E.put(98, this.A1Z);
        linkedHashMapA1E.put(99, this.A1a);
        linkedHashMapA1E.put(100, this.A1b);
        linkedHashMapA1E.put(101, this.A1c);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.MESSAGE_HISTORY_NOTICE_FIELD_NUMBER), this.A1d);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.GROUP_STATUS_MESSAGE_V2_FIELD_NUMBER), this.A1e);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.BOT_FORWARDED_MESSAGE_FIELD_NUMBER), this.A1f);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.STATUS_QUESTION_ANSWER_MESSAGE_FIELD_NUMBER), this.A1g);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.QUESTION_REPLY_MESSAGE_FIELD_NUMBER), this.A1h);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.QUESTION_RESPONSE_MESSAGE_FIELD_NUMBER), this.A1i);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.NEWSLETTER_FOLLOWER_INVITE_MESSAGE_FIELD_NUMBER), this.A1j);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.STATUS_QUOTED_MESSAGE_FIELD_NUMBER), this.A1k);
        linkedHashMapA1E.put(Integer.valueOf(C26698BmO.STATUS_STICKER_INTERACTION_MESSAGE_FIELD_NUMBER), this.A1l);
        return linkedHashMapA1E;
    }

    @Override // X.C0BP
    public java.util.Map getFieldsMapForFalco() {
        LinkedHashMap linkedHashMapA1E = AbstractC465925m.A1E();
        linkedHashMapA1E.put("wa_app_attribution", this.A00);
        linkedHashMapA1E.put("wa_application_state", this.A01);
        linkedHashMapA1E.put("wa_applied_filters", this.A02);
        linkedHashMapA1E.put("wa_asset_id", this.A03);
        linkedHashMapA1E.put("wa_asset_id_str", this.A04);
        linkedHashMapA1E.put("wa_asset_type", this.A05);
        linkedHashMapA1E.put("wa_async_job_id", this.A06);
        linkedHashMapA1E.put("wa_audio_bit_rate", this.A07);
        linkedHashMapA1E.put("wa_audio_channel_count", this.A08);
        linkedHashMapA1E.put("wa_audio_sample_rate", this.A09);
        linkedHashMapA1E.put("wa_auto_retries", this.A0A);
        linkedHashMapA1E.put("wa_channel_name", this.A0B);
        linkedHashMapA1E.put("wa_chunk_bandwidth", this.A0C);
        linkedHashMapA1E.put("wa_chunk_size", this.A0D);
        linkedHashMapA1E.put("wa_cluster_region", this.A0E);
        linkedHashMapA1E.put("wa_codec_features", this.A0F);
        linkedHashMapA1E.put("wa_composer_dialog_version", this.A0G);
        linkedHashMapA1E.put("wa_composer_entry_point_ref", this.A0H);
        linkedHashMapA1E.put("wa_composer_session_id", this.A0I);
        linkedHashMapA1E.put("wa_connection_class", this.A0J);
        linkedHashMapA1E.put("wa_creative_tools", this.A0K);
        linkedHashMapA1E.put("wa_current_auto_retry_count", this.A0L);
        linkedHashMapA1E.put("wa_destination_video_id", this.A0M);
        linkedHashMapA1E.put("wa_duration", this.A0N);
        linkedHashMapA1E.put("wa_elapsed_time", this.A0O);
        linkedHashMapA1E.put("wa_error", this.A0P);
        linkedHashMapA1E.put("wa_error_code", this.A0Q);
        linkedHashMapA1E.put("wa_error_description", this.A0R);
        linkedHashMapA1E.put("wa_error_domain", this.A0S);
        linkedHashMapA1E.put("wa_error_inner", this.A0T);
        linkedHashMapA1E.put("wa_error_inner_code", this.A0U);
        linkedHashMapA1E.put("wa_error_inner_description", this.A0V);
        linkedHashMapA1E.put("wa_error_level", this.A0W);
        linkedHashMapA1E.put("wa_error_trace", this.A0X);
        linkedHashMapA1E.put("wa_estimated_resized_file_size", this.A0Y);
        linkedHashMapA1E.put("wa_event", this.A0Z);
        linkedHashMapA1E.put("wa_extra_data", this.A0a);
        linkedHashMapA1E.put("wa_extra_hash", this.A0b);
        linkedHashMapA1E.put("wa_features", this.A0c);
        linkedHashMapA1E.put("wa_file_can_read", this.A0d);
        linkedHashMapA1E.put("wa_file_exists", this.A0e);
        linkedHashMapA1E.put("wa_file_fetch_success", this.A0f);
        linkedHashMapA1E.put("wa_file_handle", this.A0g);
        linkedHashMapA1E.put("wa_file_size", this.A0h);
        linkedHashMapA1E.put("wa_flow_context", this.A0i);
        linkedHashMapA1E.put("wa_free_space_in_device", this.A0j);
        linkedHashMapA1E.put("wa_has_file_been_replaced", this.A0k);
        linkedHashMapA1E.put("wa_hash_file_size", this.A0l);
        linkedHashMapA1E.put("wa_hash_time", this.A0m);
        linkedHashMapA1E.put("wa_internet_status", this.A0n);
        linkedHashMapA1E.put("wa_media_accuracy_validation_codes", this.A0o);
        linkedHashMapA1E.put("wa_media_metadata", this.A0p);
        linkedHashMapA1E.put("wa_media_source_attribution", this.A0q);
        linkedHashMapA1E.put("wa_original_file_size", this.A0r);
        linkedHashMapA1E.put("wa_owner_type", this.A0s);
        linkedHashMapA1E.put("wa_parallel_segment_count", this.A0t);
        linkedHashMapA1E.put("wa_pref_transcode_config", this.A0u);
        linkedHashMapA1E.put("wa_resize_status", this.A0v);
        linkedHashMapA1E.put("wa_retries", this.A0w);
        linkedHashMapA1E.put("wa_server_creative_tools", this.A0x);
        linkedHashMapA1E.put("wa_server_response", this.A0y);
        linkedHashMapA1E.put("wa_server_retries", this.A0z);
        linkedHashMapA1E.put("wa_show_video_type", this.A10);
        linkedHashMapA1E.put("wa_source_bit_rate", this.A11);
        linkedHashMapA1E.put("wa_source_color_space", this.A12);
        linkedHashMapA1E.put("wa_source_frame_rate", this.A13);
        linkedHashMapA1E.put("wa_source_height", this.A14);
        linkedHashMapA1E.put("wa_source_rotation_angle", this.A15);
        linkedHashMapA1E.put("wa_source_type", this.A16);
        linkedHashMapA1E.put("wa_source_video_codec", this.A17);
        linkedHashMapA1E.put("wa_source_width", this.A18);
        linkedHashMapA1E.put("wa_ssim_frames_to_compare", this.A19);
        linkedHashMapA1E.put("wa_ssim_is_valid", this.A1A);
        linkedHashMapA1E.put("wa_ssim_max_value", this.A1B);
        linkedHashMapA1E.put("wa_ssim_min_value", this.A1C);
        linkedHashMapA1E.put("wa_ssim_result_count", this.A1D);
        linkedHashMapA1E.put("wa_ssim_results", this.A1E);
        linkedHashMapA1E.put("wa_ssim_timestamps", this.A1F);
        linkedHashMapA1E.put("wa_ssim_uploads", this.A1G);
        linkedHashMapA1E.put("wa_ssim_value", this.A1H);
        linkedHashMapA1E.put("wa_starfox_media_composition", this.A1I);
        linkedHashMapA1E.put("wa_target_bit_rate", this.A1J);
        linkedHashMapA1E.put("wa_target_color_space", this.A1K);
        linkedHashMapA1E.put("wa_target_frame_rate", this.A1L);
        linkedHashMapA1E.put("wa_target_height", this.A1M);
        linkedHashMapA1E.put("wa_target_id", this.A1N);
        linkedHashMapA1E.put("wa_target_type", this.A1O);
        linkedHashMapA1E.put("wa_target_upload_settings_mode", this.A1P);
        linkedHashMapA1E.put("wa_target_video_codec", this.A1Q);
        linkedHashMapA1E.put("wa_target_width", this.A1R);
        linkedHashMapA1E.put("wa_time_to_fetch_file", this.A1S);
        linkedHashMapA1E.put("wa_total_bytes", this.A1T);
        linkedHashMapA1E.put("wa_total_space_in_device", this.A1U);
        linkedHashMapA1E.put("wa_trans_num_call_stack", this.A1V);
        linkedHashMapA1E.put("wa_transcode_settings", this.A1W);
        linkedHashMapA1E.put("wa_unified_upload_mos", this.A1X);
        linkedHashMapA1E.put("wa_unified_upload_mos_v2", this.A1Y);
        linkedHashMapA1E.put("wa_upload_domain", this.A1Z);
        linkedHashMapA1E.put("wa_upload_method", this.A1a);
        linkedHashMapA1E.put("wa_upload_session_id", this.A1b);
        linkedHashMapA1E.put("wa_uploaded_video_height", this.A1c);
        linkedHashMapA1E.put("wa_uploaded_video_ids", this.A1d);
        linkedHashMapA1E.put("wa_uploaded_video_width", this.A1e);
        linkedHashMapA1E.put("wa_usable_space_in_device", this.A1f);
        linkedHashMapA1E.put("wa_video_asset_id_list", this.A1g);
        linkedHashMapA1E.put("wa_video_contains_location_data", this.A1h);
        linkedHashMapA1E.put("wa_video_id", this.A1i);
        linkedHashMapA1E.put("wa_video_original_file_path", this.A1j);
        linkedHashMapA1E.put("wa_waterfall_id", this.A1k);
        linkedHashMapA1E.put("wa_web_server_name", this.A1l);
        return linkedHashMapA1E;
    }

    @Override // X.C0BP
    public void serialize(InterfaceC79783iN interfaceC79783iN) {
        throw AbstractC466525s.A0m();
    }

    public String toString() {
        StringBuilder sbA08 = AnonymousClass000.A08();
        sbA08.append("WamVideoUploadLogging {");
        C0BR.A00(this.A00, "waAppAttribution", sbA08);
        C0BR.A00(this.A01, "waApplicationState", sbA08);
        C0BR.A00(this.A02, "waAppliedFilters", sbA08);
        C0BR.A00(this.A03, "waAssetId", sbA08);
        C0BR.A00(this.A04, "waAssetIdStr", sbA08);
        C0BR.A00(this.A05, "waAssetType", sbA08);
        C0BR.A00(this.A06, "waAsyncJobId", sbA08);
        C0BR.A00(this.A07, "waAudioBitRate", sbA08);
        C0BR.A00(this.A08, "waAudioChannelCount", sbA08);
        C0BR.A00(this.A09, "waAudioSampleRate", sbA08);
        C0BR.A00(this.A0A, "waAutoRetries", sbA08);
        C0BR.A00(this.A0B, "waChannelName", sbA08);
        C0BR.A00(this.A0C, "waChunkBandwidth", sbA08);
        C0BR.A00(this.A0D, "waChunkSize", sbA08);
        C0BR.A00(this.A0E, "waClusterRegion", sbA08);
        C0BR.A00(this.A0F, "waCodecFeatures", sbA08);
        C0BR.A00(this.A0G, "waComposerDialogVersion", sbA08);
        C0BR.A00(this.A0H, "waComposerEntryPointRef", sbA08);
        C0BR.A00(this.A0I, "waComposerSessionId", sbA08);
        C0BR.A00(this.A0J, "waConnectionClass", sbA08);
        C0BR.A00(this.A0K, "waCreativeTools", sbA08);
        C0BR.A00(this.A0L, "waCurrentAutoRetryCount", sbA08);
        C0BR.A00(this.A0M, "waDestinationVideoId", sbA08);
        C0BR.A00(this.A0N, "waDuration", sbA08);
        C0BR.A00(this.A0O, "waElapsedTime", sbA08);
        C0BR.A00(this.A0P, "waError", sbA08);
        C0BR.A00(this.A0Q, "waErrorCode", sbA08);
        C0BR.A00(this.A0R, "waErrorDescription", sbA08);
        C0BR.A00(this.A0S, "waErrorDomain", sbA08);
        C0BR.A00(this.A0T, "waErrorInner", sbA08);
        C0BR.A00(this.A0U, "waErrorInnerCode", sbA08);
        C0BR.A00(this.A0V, "waErrorInnerDescription", sbA08);
        C0BR.A00(this.A0W, "waErrorLevel", sbA08);
        C0BR.A00(this.A0X, "waErrorTrace", sbA08);
        C0BR.A00(this.A0Y, "waEstimatedResizedFileSize", sbA08);
        C0BR.A00(this.A0Z, "waEvent", sbA08);
        C0BR.A00(this.A0a, "waExtraData", sbA08);
        C0BR.A00(this.A0b, "waExtraHash", sbA08);
        C0BR.A00(this.A0c, "waFeatures", sbA08);
        C0BR.A00(this.A0d, "waFileCanRead", sbA08);
        C0BR.A00(this.A0e, "waFileExists", sbA08);
        C0BR.A00(this.A0f, "waFileFetchSuccess", sbA08);
        C0BR.A00(this.A0g, "waFileHandle", sbA08);
        C0BR.A00(this.A0h, "waFileSize", sbA08);
        C0BR.A00(this.A0i, "waFlowContext", sbA08);
        C0BR.A00(this.A0j, "waFreeSpaceInDevice", sbA08);
        C0BR.A00(this.A0k, "waHasFileBeenReplaced", sbA08);
        C0BR.A00(this.A0l, "waHashFileSize", sbA08);
        C0BR.A00(this.A0m, "waHashTime", sbA08);
        C0BR.A00(this.A0n, "waInternetStatus", sbA08);
        C0BR.A00(this.A0o, "waMediaAccuracyValidationCodes", sbA08);
        C0BR.A00(this.A0p, "waMediaMetadata", sbA08);
        C0BR.A00(this.A0q, "waMediaSourceAttribution", sbA08);
        C0BR.A00(this.A0r, "waOriginalFileSize", sbA08);
        C0BR.A00(this.A0s, "waOwnerType", sbA08);
        C0BR.A00(this.A0t, "waParallelSegmentCount", sbA08);
        C0BR.A00(this.A0u, "waPrefTranscodeConfig", sbA08);
        C0BR.A00(this.A0v, "waResizeStatus", sbA08);
        C0BR.A00(this.A0w, "waRetries", sbA08);
        C0BR.A00(this.A0x, "waServerCreativeTools", sbA08);
        C0BR.A00(this.A0y, "waServerResponse", sbA08);
        C0BR.A00(this.A0z, "waServerRetries", sbA08);
        C0BR.A00(this.A10, "waShowVideoType", sbA08);
        C0BR.A00(this.A11, "waSourceBitRate", sbA08);
        C0BR.A00(this.A12, "waSourceColorSpace", sbA08);
        C0BR.A00(this.A13, "waSourceFrameRate", sbA08);
        C0BR.A00(this.A14, "waSourceHeight", sbA08);
        C0BR.A00(this.A15, "waSourceRotationAngle", sbA08);
        C0BR.A00(this.A16, "waSourceType", sbA08);
        C0BR.A00(this.A17, "waSourceVideoCodec", sbA08);
        C0BR.A00(this.A18, "waSourceWidth", sbA08);
        C0BR.A00(this.A19, "waSsimFramesToCompare", sbA08);
        C0BR.A00(this.A1A, "waSsimIsValid", sbA08);
        C0BR.A00(this.A1B, "waSsimMaxValue", sbA08);
        C0BR.A00(this.A1C, "waSsimMinValue", sbA08);
        C0BR.A00(this.A1D, "waSsimResultCount", sbA08);
        C0BR.A00(this.A1E, "waSsimResults", sbA08);
        C0BR.A00(this.A1F, "waSsimTimestamps", sbA08);
        C0BR.A00(this.A1G, "waSsimUploads", sbA08);
        C0BR.A00(this.A1H, "waSsimValue", sbA08);
        C0BR.A00(this.A1I, "waStarfoxMediaComposition", sbA08);
        C0BR.A00(this.A1J, "waTargetBitRate", sbA08);
        C0BR.A00(this.A1K, "waTargetColorSpace", sbA08);
        C0BR.A00(this.A1L, "waTargetFrameRate", sbA08);
        C0BR.A00(this.A1M, "waTargetHeight", sbA08);
        C0BR.A00(this.A1N, "waTargetId", sbA08);
        C0BR.A00(this.A1O, "waTargetType", sbA08);
        C0BR.A00(this.A1P, "waTargetUploadSettingsMode", sbA08);
        C0BR.A00(this.A1Q, "waTargetVideoCodec", sbA08);
        C0BR.A00(this.A1R, "waTargetWidth", sbA08);
        C0BR.A00(this.A1S, "waTimeToFetchFile", sbA08);
        C0BR.A00(this.A1T, "waTotalBytes", sbA08);
        C0BR.A00(this.A1U, "waTotalSpaceInDevice", sbA08);
        C0BR.A00(this.A1V, "waTransNumCallStack", sbA08);
        C0BR.A00(this.A1W, "waTranscodeSettings", sbA08);
        C0BR.A00(this.A1X, "waUnifiedUploadMos", sbA08);
        C0BR.A00(this.A1Y, "waUnifiedUploadMosV2", sbA08);
        C0BR.A00(this.A1Z, "waUploadDomain", sbA08);
        C0BR.A00(this.A1a, "waUploadMethod", sbA08);
        C0BR.A00(this.A1b, "waUploadSessionId", sbA08);
        C0BR.A00(this.A1c, "waUploadedVideoHeight", sbA08);
        C0BR.A00(this.A1d, "waUploadedVideoIds", sbA08);
        C0BR.A00(this.A1e, "waUploadedVideoWidth", sbA08);
        C0BR.A00(this.A1f, "waUsableSpaceInDevice", sbA08);
        C0BR.A00(this.A1g, "waVideoAssetIdList", sbA08);
        C0BR.A00(this.A1h, "waVideoContainsLocationData", sbA08);
        C0BR.A00(this.A1i, "waVideoId", sbA08);
        C0BR.A00(this.A1j, "waVideoOriginalFilePath", sbA08);
        C0BR.A00(this.A1k, "waWaterfallId", sbA08);
        return AbstractC32971bt.A0Q(this.A1l, "waWebServerName", sbA08);
    }
}
