package X;

/* JADX INFO: renamed from: X.4xZ, reason: invalid class name */
/* JADX INFO: loaded from: classes4.dex */
public abstract class C4xZ {
    public static String A00(int i) {
        switch (i) {
            case 1:
                return "TH_PERFORMANCE_SCROLL";
            case 1573:
                return "SCROLL_IG_TEXT_FEED_FOLLOW_LIST_SELF_FOLLOWING";
            case 1678:
                return "SCROLL_IG_TEXT_FEED_TIMELINE_FOLLOWING";
            case 2075:
                return "SCROLL_IG_TEXT_SEARCH_SERP_WITH_FILTERS_TOP";
            case 2461:
                return "SCROLL_STORY_EMOJI_PICKER";
            case 2935:
                return "SCROLL_IG_TEXT_FEED_SAVED_FEED";
            case 2983:
                return "SCROLL_IG_TEXT_FEED_SLIDE_INBOX_REQUESTS";
            case 3130:
                return "SCROLL_IG_TEXT_FEED_SELF_PROFILE_REPLIES";
            case 3167:
                return "SCROLL_IG_TEXT_NEWSFEED_YOU_REPOSTS";
            case 3249:
                return "SCROLL_BCN_POST_PICKER_LIKED";
            case 3543:
                return "SCROLL_IG_TEXT_FEED_PROFILE_REPOSTS";
            case 3657:
                return "SCROLL_IG_TEXT_NEWSFEED_YOU_ALL";
            case 3883:
                return "SCROLL_IG_TEXT_FEED_SLIDE_INBOX";
            case 3896:
                return "SCROLL_IG_TEXT_NEWSFEED_YOU_MENTIONS";
            case 4240:
                return "SCROLL_IG_TEXT_FEED_HIDDEN_REPLIES_VC";
            case 4258:
                return "SCROLL_ACTIVITY_FEED";
            case 4322:
                return "SCROLL_IG_TEXT_SEARCH_SERP_COMMUNITY_FEED_RECENT";
            case 4635:
                return "SCROLL_IG_TEXT_FEED_SHARED_CONTENT";
            case 4656:
                return "SCROLL_IG_TEXT_FEED_CUSTOM_RECENT_FEED";
            case 5452:
                return "SCROLL_IG_TEXT_FEED_PROFILE_REPLIES";
            case 5606:
                return "SCROLL_IG_TEXT_NEWSFEED_YOU_FOLLOWS";
            case 5788:
                return "SCROLL_BCN_POST_PICKER_SAVED";
            case 5912:
                return "SCROLL_IG_TEXT_FEED_PROFILE_THREADS";
            case 5922:
                return "SCROLL_IG_TEXT_FEED_SLIDE_LIVE_CHAT";
            case 5928:
                return "SCROLL_IG_TEXT_FEED_TIMELINE_FOR_YOU";
            case 6512:
                return "SCROLL_IG_TEXT_FEED_SELF_PROFILE";
            case 6524:
                return "SCROLL_IG_TEXT_SEARCH_NULLSTATE";
            case 6562:
                return "SCROLL_IG_TEXT_FEED_LIKES_FEED";
            case 6615:
                return "SCROLL_IG_TEXT_FEED_SLIDE_INBOX_HIDDEN";
            case 6828:
                return "SCROLL_IG_TEXT_FEED_FOLLOW_LIST_MUTUALS";
            case 7164:
                return "SCROLL_IG_TEXT_SEARCH_SERP_WITH_FILTERS_RECENT";
            case 7190:
                return "SCROLL_IG_TEXT_MEDIA_SEARCH";
            case 7215:
                return "SCROLL_IG_TEXT_FEED_PROFILE_MEDIA";
            case 7379:
                return "SCROLL_IG_TEXT_FEED_TIMELINE_RECENTLY_VIEWED";
            case 7549:
                return "SCROLL_IG_TEXT_SEARCH_SERP_COMMUNITY_FEED_TOP";
            case 7582:
                return "SCROLL_IG_TEXT_FEED_SLIDE_CHAT";
            case 7631:
                return "SCROLL_IG_TEXT_FEED_SLIDE_CHAT_HIDDEN";
            case 7665:
                return "SCROLL_BCN_POST_PICKER_YOUR_POSTS";
            case 8028:
                return "SCROLL_IG_TEXT_SEARCH_SERP_TOP_PROFILES";
            case 8133:
                return "SCROLL_IG_TEXT_FEED_ADD_TO_LIST_TYPEAHEAD_SHEET";
            case 8484:
                return "SCROLL_IG_TEXT_NEWSFEED_YOU_REQUESTS";
            case 8757:
                return "SCROLL_IG_TEXT_FEED_SELF_PROFILE_MEDIA";
            case 8810:
                return "SCROLL_IG_TEXT_COMMUNITY_FEED";
            case 8940:
                return "SCROLL_IG_TEXT_FEED_FOLLOW_LIST_SELF_PENDING";
            case 9040:
                return "SCROLL_MUSIC_PICKER_VIEW_CONTROLLER";
            case 9154:
                return "SCROLL_IG_TEXT_FEED_FOLLOW_LIST_SELF_FOLLOWERS";
            case 9210:
                return "SCROLL_IG_TEXT_SEARCH_SERP_PROFILES";
            case 9215:
                return "SCROLL_IG_TEXT_FEED_SLIDE_CHAT_REQUEST";
            case 9261:
                return "SCROLL_IG_TEXT_FEED_FOLLOW_LIST_FOLLOWING";
            case 9316:
                return "SCROLL_IG_TEXT_SEARCH_TOPIC_MEMBERS";
            case 9478:
                return "SCROLL_BCN_FEED_DRAFTS";
            case 10084:
                return "SCROLL_IG_TEXT_FEED_FOLLOW_LIST_CORE";
            case 10451:
                return "SCROLL_IG_TEXT_NEWSFEED_YOU_FOLLOWING";
            case 10578:
                return "SCROLL_IG_TEXT_FEED_COMPOSER";
            case 10655:
                return "SCROLL_IG_TEXT_POST_FEEDBACK_HUB";
            case 11113:
                return "SCROLL_IG_TEXT_POST_PERMALINK";
            case 11413:
                return "SCROLL_IG_TEXT_FEED_SELF_PROFILE_THREADS";
            case 11523:
                return "SCROLL_IG_TEXT_FEED_TIMELINE";
            case 11696:
                return "SCROLL_IG_TEXT_FEED_SELF_PROFILE_REPOSTS";
            case 11798:
                return "SCROLL_IG_TEXT_FEED_GHOST_POSTS_FEED";
            case 12276:
                return "SCROLL_BCN_PHOTO_TAGGING_SEARCH";
            case 13114:
                return "SCROLL_IG_TEXT_SEARCH_TYPEAHEAD";
            case 13222:
                return "SCROLL_IG_TEXT_SEARCH_SERP";
            case 13346:
                return "SCROLL_IG_TEXT_FEED_SEARCH";
            case 13753:
                return "SCROLL_IG_TEXT_FEED_BIO_INTERESTS_EDIT";
            case 13892:
                return "SCROLL_IG_TEXT_FEED_EDIT_LIST_SHEET";
            case 14314:
                return "SCROLL_IG_TEXT_FEED_PROFILE";
            case 14361:
                return "SCROLL_IG_TEXT_NEWSFEED_YOU_CONVERSATIONS";
            case 14516:
                return "SCROLL_BCN_PENDING_REPLIES";
            case 14791:
                return "SCROLL_IG_TEXT_SEARCH_USERS";
            case 14943:
                return "SCROLL_IG_TEXT_SEARCH_SERP_RECENT";
            case 15127:
                return "SCROLL_IG_TEXT_FEED_BLOCKED_PROFILES";
            case 15185:
                return "SCROLL_IG_TEXT_FEED_SEARCH_NULLSTATE";
            case 15216:
                return "SCROLL_MEDIA_VIEWER";
            case 15385:
                return "SCROLL_IG_TEXT_FEED_FOLLOW_LIST_FOLLOWERS";
            case 15421:
                return "SCROLL_IG_TEXT_FEED_ARCHIVED_FEED";
            case 15509:
                return "SCROLL_IG_TEXT_SEARCH_SERP_TOP";
            case 15809:
                return "SCROLL_IG_TEXT_SEARCH_COMMUNITY_DISCOVERY";
            case 16030:
                return "SCROLL_IG_TEXT_NEWSFEED_YOU";
            case 16126:
                return "SCROLL_IG_TEXT_APP_SIDE_MENU";
            case 16283:
                return "SCROLL_TEXT_FEED_SHARE_SHEET";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
