package X;

import com.whatsapp.calling.voipcalling.Voip;

/* JADX INFO: renamed from: X.Nwp, reason: case insensitive filesystem */
/* JADX INFO: loaded from: classes11.dex */
public final class C52362Nwp {
    public final C016207r A00;
    public final C49458MlT A01;

    public boolean equals(Object obj) {
        return this == obj || ((obj instanceof C52362Nwp) && C000700h.areEqual(this.A00, ((C52362Nwp) obj).A00));
    }

    public static int A00(int i) {
        return ((((((((((((((i * 31) + 1237) * 31) + 1237) * 31) + 1237) * 31) + 1237) * 31) + 1237) * 31) + 1237) * 31) + 1237) * 31;
    }

    public int hashCode() {
        int iA00 = (AbstractC466925w.A00(-1L, (A00(((((A00(A00(A00(AbstractC202188rn.A00((A00(((AbstractC202188rn.A00(AbstractC81763lf.A04((AbstractC202188rn.A00((((((AbstractC202188rn.A00((((AbstractC202188rn.A00(AbstractC466425r.A02(this.A00), 1231) + 1237) * 31) + 1) * 31, 1237) + 1237) * 31) + 5) * 31) + 1237) * 31, 1231) + 1231) * 31, 1237), 1237) + 1237) * 31) + 1231) + 1237) * 31, 1237) + 1231) + 1237) + 1237) - 1) * 31) - 1) * 31) + 48) + 1237) * 31) + 1237) * 31;
        int iA07 = AbstractC81783lh.A07(0L);
        return ((((((AbstractC202188rn.A00(AbstractC202188rn.A00((A00(A00(AbstractC32971bt.A04(10L, (A00(A00(A00(((iA00 + iA07) * 31) + iA07) + 1237) + 2500) + 1237) * 31)) + 1237) + 1237) * 31, 1237), 1237) - 1) * 31) - 1) * 31) + 1237) * 31) + 1237;
    }

    public String toString() {
        C016207r c016207r = this.A00;
        StringBuilder sbA08 = AnonymousClass000.A08();
        sbA08.append("ExperimentConfiguration(abProps=");
        sbA08.append(c016207r);
        sbA08.append(", isRealTimeDisplayEncoderWarmUpDisabled=");
        sbA08.append(true);
        sbA08.append(", isSurfaceFrameTimeoutFixEnabled=");
        sbA08.append(true);
        sbA08.append(", shouldFetchTimeInPlayerThread=");
        sbA08.append(false);
        sbA08.append(", audioSinkBufferSizeMultiplier=");
        sbA08.append(1);
        sbA08.append(", useFbaAudioProcessor=");
        sbA08.append(false);
        sbA08.append(", useCTAudioProcessor=");
        sbA08.append(false);
        sbA08.append(", useCTVoiceEffectProcessor=");
        sbA08.append(false);
        sbA08.append(", audioEnhancementWarmupDurationSeconds=");
        sbA08.append(5);
        sbA08.append(", audioEnhancementEnableWarmup=");
        sbA08.append(false);
        sbA08.append(", audioEnhancementNREnabled=");
        sbA08.append(true);
        sbA08.append(", audioEnhancementAutoEQEnabled=");
        sbA08.append(true);
        sbA08.append(", audioEnhancementLevelerEnabled=");
        sbA08.append(true);
        sbA08.append(", audioEnhancementMLNoiseRemoverEnabled=");
        sbA08.append(false);
        sbA08.append(", audioEnhancementModelPath=");
        sbA08.append(Voip.REJECT_REASON_DECLINED);
        sbA08.append(", audioEnhancementVoltronLoaded=");
        sbA08.append(false);
        sbA08.append(", voiceOverEffectTrackEnabled=");
        sbA08.append(false);
        sbA08.append(", voiceLevelerOptimisationsEnabled=");
        sbA08.append(false);
        sbA08.append(", isHandleOutViewLifecycleEnabled=");
        sbA08.append(true);
        sbA08.append(", shouldEnableVideoTrackSegmentSplitForReverse=");
        sbA08.append(false);
        sbA08.append(", shouldSeekOnceWhenUpdateMediaComposition=");
        sbA08.append(false);
        sbA08.append(", enablePQHdrTonemap=");
        sbA08.append(false);
        sbA08.append(", enableHLGHdrTonemap=");
        sbA08.append(false);
        sbA08.append(", enableHLGHdrTranscode=");
        sbA08.append(false);
        sbA08.append(", enableHdr10PlusTonemap=");
        sbA08.append(false);
        sbA08.append(", enableHdr10PlusTonemapToHlg=");
        sbA08.append(false);
        sbA08.append(", isHLGHdrTranscodeEnabledForEffects=");
        sbA08.append(false);
        sbA08.append(", isEglCaveatConfigEnabled=");
        sbA08.append(false);
        sbA08.append(", enableHdrPreview=");
        sbA08.append(false);
        sbA08.append(", enableHdrEffectCheck=");
        sbA08.append(true);
        sbA08.append(", enableVerboseLogs=");
        sbA08.append(false);
        sbA08.append(", enableCancelBeforeRelease=");
        sbA08.append(false);
        sbA08.append(", enableReducedLookahead=");
        sbA08.append(false);
        sbA08.append(", enableLoopStylePreloading=");
        sbA08.append(false);
        sbA08.append(", enableProactiveReleasing=");
        sbA08.append(false);
        sbA08.append(", enableRefreshOnSeek=");
        sbA08.append(false);
        sbA08.append(", enableReleaseVideoInputResourcesOpt=");
        sbA08.append(false);
        sbA08.append(", enableRemoveOutputsOnRelease=");
        sbA08.append(false);
        sbA08.append(", enableAsyncSurfaceTexture=");
        sbA08.append(false);
        sbA08.append(", enableHandlerThreadInterruptOnRelease=");
        sbA08.append(false);
        sbA08.append(", enableUnsupportedMimeTypeForDemuxer=");
        sbA08.append(false);
        sbA08.append(", enableUseSupportedVideoTrackIfAvailable=");
        sbA08.append(false);
        sbA08.append(", enableUseSupportedAudioTrackIfAvailable=");
        sbA08.append(false);
        sbA08.append(", enableReusePlayerSessionIdOnRetry=");
        sbA08.append(false);
        sbA08.append(", enableMediaAccuracyCapture=");
        sbA08.append(false);
        sbA08.append(", enableMediaAccuracyDynamicSampling=");
        sbA08.append(false);
        sbA08.append(", isMediaAccuracyAsyncBetaChannelCall=");
        sbA08.append(false);
        sbA08.append(", enableMediaAccuracyAudioCapture=");
        sbA08.append(false);
        sbA08.append(", enableMediaAccuracyNonZeroTimestampSnapshot=");
        sbA08.append(false);
        sbA08.append(", enableRetryForDecoderStartFailure=");
        sbA08.append(false);
        sbA08.append(", enableNewPrepareDecoderWithRetry=");
        sbA08.append(false);
        sbA08.append(", checkSoftwareDecoding=");
        sbA08.append(false);
        sbA08.append(", enableSoftwareDecoder=");
        sbA08.append(false);
        sbA08.append(", getSoftwareDecodingWidth=");
        sbA08.append(-1);
        sbA08.append(", getSoftwareDecodingFrameRate=");
        sbA08.append(-1);
        sbA08.append(", mediaAccuracyCaptureTimestampsCsv=");
        sbA08.append("0");
        sbA08.append(", doNotRetainByteBuffer=");
        sbA08.append(false);
        sbA08.append(", enableExoPlayerMedia3Extractor=");
        sbA08.append(false);
        sbA08.append(", enableTraceLogs=");
        sbA08.append(false);
        sbA08.append(", enableExcludeLastPtsInTimeRange=");
        sbA08.append(false);
        sbA08.append(", enableCancelDecoderExtractFuture=");
        sbA08.append(false);
        sbA08.append(", enableVideoTranscoderReuse=");
        sbA08.append(false);
        sbA08.append(", enableTextureAvailableRaceConditionFix=");
        sbA08.append(false);
        sbA08.append(", enableDemuxerThreadLockSync=");
        sbA08.append(false);
        sbA08.append(", getDemuxerThreadTimeoutMs=");
        sbA08.append(-1L);
        sbA08.append(", enableRetryableMediaCompositionPlayer=");
        sbA08.append(false);
        sbA08.append(", retryableMediaCompositionPlayerMaxRetries=");
        sbA08.append(0L);
        sbA08.append(", retryableMediaCompositionPlayerErrorThresholdMs=");
        sbA08.append(0L);
        sbA08.append(", enableFirstFramePtsFix=");
        sbA08.append(false);
        sbA08.append(", enableRenderLockReleaseOnNoop=");
        sbA08.append(false);
        sbA08.append(", enableSkipAudioTrack=");
        sbA08.append(false);
        sbA08.append(", enableFrameRendererSyncRelease=");
        sbA08.append(false);
        sbA08.append(", enableExceptionThrownOnMuxerOperationCancellation=");
        sbA08.append(false);
        sbA08.append(", enableExceptionThrownOnOperationCancellation=");
        sbA08.append(false);
        sbA08.append(", shouldSynchronizeZoomCrop=");
        sbA08.append(false);
        sbA08.append(", enableOpenGlCleanup=");
        sbA08.append(false);
        sbA08.append(", disableAdjustingFrameInterval=");
        sbA08.append(false);
        sbA08.append(", enableAudioRawMimeTypeForBaseMediaDemuxer=");
        sbA08.append(false);
        sbA08.append(", shouldCacheLastPrepareSeekPositionNs=");
        sbA08.append(false);
        sbA08.append(", enableBitmapSyncFix=");
        sbA08.append(false);
        sbA08.append(", enableDeltaStuckTime=");
        sbA08.append(false);
        sbA08.append(", enableReleaseTimeoutCheckWarning=");
        sbA08.append(false);
        sbA08.append(", ignoreReleaseTimeoutError=");
        sbA08.append(false);
        sbA08.append(", splitReverseChunkDurationMs=");
        sbA08.append(2500);
        sbA08.append(", enableOnTheFlyGlobalVolumeUpdate=");
        sbA08.append(false);
        sbA08.append(", enablePTVFrameIntervalFix=");
        sbA08.append(false);
        sbA08.append(", enableHdrWindowSurfaceAttributes=");
        sbA08.append(false);
        sbA08.append(", enableAudioOnlyVVP=");
        sbA08.append(false);
        sbA08.append(", useSurfaceViewForVvp=");
        sbA08.append(false);
        sbA08.append(", logFileContentsOnExtractorFailure=");
        sbA08.append(false);
        sbA08.append(", isAsyncVideoDecoderEnabled=");
        sbA08.append(false);
        sbA08.append(", shouldRetryMediaCodecStopRelease=");
        sbA08.append(false);
        sbA08.append(", getMediaCodecRetryTimeoutMs=");
        sbA08.append(10L);
        sbA08.append(", enableQPLLoggingVVP=");
        sbA08.append(false);
        sbA08.append(", enableMediaAccuracySpecValidation=");
        sbA08.append(false);
        sbA08.append(", enableMediaAccuracyAssetValidation=");
        sbA08.append(false);
        sbA08.append(", shouldUseMediaReferenceTimeForSeekBoundsCheck=");
        sbA08.append(false);
        sbA08.append(", shouldPreserveEffectsOnUpdateTrim=");
        sbA08.append(false);
        sbA08.append(", enableGradualSeekOptimization=");
        sbA08.append(false);
        sbA08.append(", enableSeekInterrupt=");
        sbA08.append(false);
        sbA08.append(", enableTrackPreloadDuringClipSwitch=");
        sbA08.append(false);
        sbA08.append(", enableSpeedPitchMultiplier=");
        sbA08.append(false);
        sbA08.append(", enableRenderClockForAVSync=");
        sbA08.append(false);
        sbA08.append(", enableAudioTranscodePipelineCancel=");
        sbA08.append(false);
        sbA08.append(", enableSendRendererEventFix=");
        sbA08.append(false);
        sbA08.append(", enableFastSeekFlow=");
        sbA08.append(false);
        sbA08.append(", useHighPriorityDecoding=");
        sbA08.append(false);
        sbA08.append(", useMaxOperatingRateDecoding=");
        sbA08.append(false);
        sbA08.append(", useLowLatencyDecoding=");
        sbA08.append(false);
        sbA08.append(", enableNegativeFirstFrameTimeFix=");
        sbA08.append(false);
        sbA08.append(", shouldUpdateMediaCompositionOnlyIfNotEqual=");
        sbA08.append(false);
        sbA08.append(", enableDemuxerToIncludeLastTimestamp=");
        sbA08.append(false);
        sbA08.append(", enablePreciseDemuxerCorrection=");
        sbA08.append(false);
        sbA08.append(", getDecodingPriority=");
        sbA08.append(-1);
        sbA08.append(", getDecodingOperatingRate=");
        sbA08.append(-1);
        sbA08.append(", arFrameLiteRenderedMemLeakFix=");
        sbA08.append(false);
        return AbstractC32971bt.A0U(", enableUseCurrentDecodedBufferPts=", sbA08, false);
    }

    public /* synthetic */ C52362Nwp(C016207r c016207r) {
        this.A00 = c016207r;
        this.A01 = new C49458MlT(c016207r);
    }
}
