package X;

/* JADX INFO: renamed from: X.5QY, reason: invalid class name */
/* JADX INFO: loaded from: classes4.dex */
public final class C5QY {
    public final int A00;
    public final Object A01;
    public final Object A02;
    public final int A03;

    public boolean equals(Object obj) {
        if (this != obj) {
            if (obj == null || !AbstractC466825v.A1Z(this, obj)) {
                return false;
            }
            C5QY c5qy = (C5QY) obj;
            if (this.A00 != c5qy.A00 || !C000700h.areEqual(this.A02, c5qy.A02) || !C000700h.areEqual(this.A01, c5qy.A01)) {
                return false;
            }
        }
        return true;
    }

    public int hashCode() {
        return this.A03;
    }

    public C5QY(Object obj, int i, Object obj2) {
        this.A00 = i;
        this.A02 = obj;
        this.A01 = obj2;
        this.A03 = (AbstractC466425r.A02(obj) * 31) + ((obj2 != null ? obj2.hashCode() : 0) * 31) + i;
    }

    public String toString() {
        String str;
        StringBuilder sbA08 = AnonymousClass000.A08();
        sbA08.append("TransitionId{");
        sbA08.append("\"");
        sbA08.append(this.A02);
        sbA08.append("\", ");
        int i = this.A00;
        if (i == 1) {
            str = "GLOBAL";
        } else if (i != 2) {
            str = "AUTOGENERATED";
        } else {
            sbA08.append("SCOPED(");
            sbA08.append(this.A01);
            str = ")";
        }
        sbA08.append(str);
        String strA06 = AnonymousClass000.A06("}", sbA08);
        C000700h.A06(strA06);
        return strA06;
    }
}
