package X;

/* JADX INFO: loaded from: classes10.dex */
public enum K53 {
    CRONET_SOURCE_UNSPECIFIED,
    CRONET_SOURCE_STATICALLY_LINKED,
    CRONET_SOURCE_PLAY_SERVICES,
    CRONET_SOURCE_FALLBACK,
    CRONET_SOURCE_PLATFORM,
    CRONET_SOURCE_FAKE
}
