package X;

/* JADX INFO: loaded from: classes10.dex */
public abstract class KKF {
    public static String A00(Integer num) {
        switch (num.intValue()) {
            case 1:
                return "all_app_mem_info";
            case 2:
                return "portal_app";
            case 3:
                return "analytics";
            case 4:
                return "anr_data";
            case 5:
                return "application_thread_process_state";
            case 6:
                return "app_config_info";
            case 7:
                return "app_exit_info";
            case 8:
                return "app_info";
            case 9:
                return "app_state";
            case 10:
                return "black_box";
            case 11:
                return "bluetooth_traffic";
            case 12:
                return "composer_sessions";
            case 13:
                return "core_dump";
            case 14:
                return "custom";
            case 15:
                return "device_info";
            case 16:
                return "disk_info";
            case 17:
                return "extra_device_info";
            case 18:
                return "fury_traces";
            case 19:
                return "global_app_state";
            case 20:
                return "global_props";
            case 21:
                return "granular_exposures";
            case 22:
                return "lacrima_files";
            case 23:
                return "litho_debug_events";
            case 24:
                return "lmk_info";
            case 25:
                return "lmkd_info";
            case 26:
                return "logcat";
            case 27:
                return "logcat_intercept";
            case 28:
                return "mem_class_info";
            case 29:
                return "membench";
            case 30:
                return "memory";
            case 31:
                return "memory_stats";
            case 32:
                return "memory_timeline";
            case 33:
                return "memory_timeline_events";
            case 34:
                return "mobile_config";
            case 35:
                return "msys_crash_reporter";
            case 36:
                return "oom_score";
            case 37:
                return "private_dirty_memory";
            case 38:
                return "qpl";
            case 39:
                return "runtime_permissions";
            case 40:
                return "attachment";
            case 41:
                return "systems_health_report";
            case 42:
                return "app_connectivity_report";
            case 43:
                return "app_media_import_report";
            case 44:
                return "simple_memory";
            case 45:
                return "stack_traces";
            case 46:
                return "system_boot";
            case 47:
                return "system_health_stats";
            case 48:
                return "test_collector";
            case 49:
                return "thermal_info";
            case 50:
                return "time_info";
            case 51:
                return "user_info";
            case 52:
                return "watermark";
            case 53:
                return "component_version";
            case 54:
                return "parcelable";
            case 55:
                return "stall";
            case 56:
                return "litho_message";
            case 57:
                return "wearable_info";
            case 58:
                return "wearable_session";
            case 59:
                return "anr_timer";
            case 60:
                return "ota_resources_version";
            case 61:
                return "state_post_crash";
            case 62:
                return "lmk_importance";
            case 63:
                return "memory_and_importance";
            case 64:
                return "foreground_stats";
            case 65:
                return "custom_app_data";
            case 66:
                return "lifecycle_history";
            case 67:
                return "night_watch_resources";
            case 68:
                return "app_timeout";
            case 69:
                return "native_libraries";
            case 70:
                return "native_library_update";
            case 71:
                return "battery_info";
            case 72:
                return "memory_trim";
            case 73:
                return "native_memory";
            case 74:
                return "persistent_looper_history";
            case 75:
                return "anr_message_queue";
            case 76:
                return "jest_e2e";
            case 77:
                return "touch_event";
            case 78:
                return "app_start";
            case 79:
                return "thread_local_stats";
            case 80:
                return "allocator_type";
            case 81:
                return "gpu_info";
            case 82:
                return "vulkan_info";
            case 83:
                return "ux_session";
            case BmJ.SUBSCRIPTIONS_SYNC_V2_ACTION_FIELD_NUMBER /* 84 */:
                return "object_count";
            case 85:
                return "user_session_switch_count";
            case 86:
                return "ui_thread_priority";
            case 87:
                return "main_thread_watchdog";
            case 88:
                return "lionhead_fuzzing_metadata";
            case BmJ.WASA_ROOT_SECRET_ACTION_FIELD_NUMBER /* 89 */:
                return "detection_stages";
            case 90:
                return "pending_jobs";
            case 91:
                return "memory_pressure";
            case 92:
                return "family_device_id";
            default:
                return "add_mem_info";
        }
    }
}
