package X;

import java.util.Set;

/* JADX INFO: loaded from: classes10.dex */
public abstract class KPS {
    public static final Set A00;

    static {
        String[] strArr = new String[87];
        strArr[0] = "a2dp-sink.profile.action.AUDIO_CONFIG_CHANGED";
        strArr[1] = "a2dp-sink.profile.action.CONNECTION_STATE_CHANGED";
        strArr[2] = "a2dp-sink.profile.action.PLAYING_STATE_CHANGED";
        strArr[3] = "a2dp.profile.action.ACTIVE_DEVICE_CHANGED";
        strArr[4] = "a2dp.profile.action.CODEC_CONFIG_CHANGED";
        strArr[5] = "a2dp.profile.action.CONNECTION_STATE_CHANGED";
        strArr[6] = "a2dp.profile.action.PLAYING_STATE_CHANGED";
        strArr[7] = "action.CSIS_CONNECTION_STATE_CHANGED";
        strArr[8] = "action.CSIS_DEVICE_AVAILABLE";
        strArr[9] = "action.CSIS_SET_MEMBER_AVAILABLE";
        strArr[10] = "action.HAP_CONNECTION_STATE_CHANGED";
        strArr[11] = "action.LE_AUDIO_ACTIVE_DEVICE_CHANGED";
        strArr[12] = "action.LE_AUDIO_CONF_CHANGED";
        strArr[13] = "action.LE_AUDIO_CONNECTION_STATE_CHANGED";
        strArr[14] = "action.LE_AUDIO_GROUP_NODE_STATUS_CHANGED";
        strArr[15] = "action.LE_AUDIO_GROUP_STATUS_CHANGED";
        strArr[16] = "action.TETHERING_STATE_CHANGED";
        strArr[17] = "adapter.action.BLE_ACL_CONNECTED";
        strArr[18] = "adapter.action.BLE_ACL_DISCONNECTED";
        strArr[19] = "adapter.action.BLE_STATE_CHANGED";
        strArr[20] = "adapter.action.BLUETOOTH_ADDRESS_CHANGED";
        strArr[21] = "adapter.action.CONNECTION_STATE_CHANGED";
        strArr[22] = "adapter.action.DISCOVERY_FINISHED";
        strArr[23] = "adapter.action.DISCOVERY_STARTED";
        strArr[24] = "adapter.action.LOCAL_NAME_CHANGED";
        strArr[25] = "adapter.action.SCAN_MODE_CHANGED";
        strArr[26] = "adapter.action.STATE_CHANGED";
        strArr[27] = "avrcp-controller.profile.action.BROWSE_CONNECTION_STATE_CHANGED";
        strArr[28] = "avrcp-controller.profile.action.CONNECTION_STATE_CHANGED";
        strArr[29] = "avrcp-controller.profile.action.FOLDER_LIST";
        strArr[30] = "avrcp-controller.profile.action.TRACK_EVENT";
        strArr[31] = "device.action.ACL_CONNECTED";
        strArr[32] = "device.action.ACL_DISCONNECT_REQUESTED";
        strArr[33] = "device.action.ACL_DISCONNECTED";
        strArr[34] = "device.action.ALIAS_CHANGED";
        strArr[35] = "device.action.BATTERY_LEVEL_CHANGED";
        strArr[36] = "device.action.BOND_STATE_CHANGED";
        strArr[37] = "device.action.CLASS_CHANGED";
        strArr[38] = "device.action.CONNECTION_ACCESS_CANCEL";
        strArr[39] = "device.action.CONNECTION_ACCESS_REPLY";
        strArr[40] = "device.action.CONNECTION_ACCESS_REQUEST";
        strArr[41] = "device.action.FOUND";
        strArr[42] = "device.action.MAS_INSTANCE";
        strArr[43] = "device.action.NAME_CHANGED";
        strArr[44] = "device.action.NAME_FAILED";
        strArr[45] = "device.action.PAIRING_CANCEL";
        strArr[46] = "device.action.PAIRING_REQUEST";
        strArr[47] = "device.action.SDP_RECORD";
        strArr[48] = "device.action.UUID";
        strArr[49] = "devicepicker.action.DEVICE_SELECTED";
        strArr[50] = "devicepicker.action.LAUNCH";
        strArr[51] = "headset.action.HF_INDICATORS_VALUE_CHANGED";
        strArr[52] = "headset.action.VENDOR_SPECIFIC_HEADSET_EVENT";
        strArr[53] = "headset.profile.action.ACTIVE_DEVICE_CHANGED";
        strArr[54] = "headset.profile.action.AUDIO_STATE_CHANGED";
        strArr[55] = "headset.profile.action.CONNECTION_STATE_CHANGED";
        strArr[56] = "headsetclient.profile.action.AG_CALL_CHANGED";
        strArr[57] = "headsetclient.profile.action.AG_EVENT";
        strArr[58] = "headsetclient.profile.action.AUDIO_STATE_CHANGED";
        strArr[59] = "headsetclient.profile.action.CONNECTION_STATE_CHANGED";
        strArr[60] = "headsetclient.profile.action.LAST_VTAG";
        strArr[61] = "headsetclient.profile.action.NETWORK_SERVICE_STATE_CHANGED";
        strArr[62] = "headsetclient.profile.action.RESULT";
        strArr[63] = "hearingaid.profile.action.ACTIVE_DEVICE_CHANGED";
        strArr[64] = "hearingaid.profile.action.CONNECTION_STATE_CHANGED";
        strArr[65] = "hearingaid.profile.action.PLAYING_STATE_CHANGED";
        strArr[66] = "hiddevice.profile.action.CONNECTION_STATE_CHANGED";
        strArr[67] = "input.profile.action.CONNECTION_STATE_CHANGED";
        strArr[68] = "input.profile.action.HANDSHAKE";
        strArr[69] = "input.profile.action.IDLE_TIME_CHANGED";
        strArr[70] = "input.profile.action.PROTOCOL_MODE_CHANGED";
        strArr[71] = "input.profile.action.REPORT";
        strArr[72] = "input.profile.action.VIRTUAL_UNPLUG_STATUS";
        strArr[73] = "intent.DISCOVERABLE_TIMEOUT";
        strArr[74] = "map.profile.action.CONNECTION_STATE_CHANGED";
        strArr[75] = "mapmce.profile.action.CONNECTION_STATE_CHANGED";
        strArr[76] = "mapmce.profile.action.MESSAGE_DELETED_STATUS_CHANGED";
        strArr[77] = "mapmce.profile.action.MESSAGE_DELIVERED_SUCCESSFULLY";
        strArr[78] = "mapmce.profile.action.MESSAGE_READ_STATUS_CHANGED";
        strArr[79] = "mapmce.profile.action.MESSAGE_RECEIVED";
        strArr[80] = "mapmce.profile.action.MESSAGE_SENT_SUCCESSFULLY";
        strArr[81] = "mapmce.profile.action.WEARABLE_SYNC";
        strArr[82] = "pan.profile.action.CONNECTION_STATE_CHANGED";
        strArr[83] = "pbap.profile.action.CONNECTION_STATE_CHANGED";
        strArr[84] = "pbapclient.profile.action.CONNECTION_STATE_CHANGED";
        strArr[85] = "sap.profile.action.CONNECTION_STATE_CHANGED";
        A00 = AbstractC148856g7.A1H("volume-control.profile.action.CONNECTION_STATE_CHANGED", strArr, 86);
    }
}
