package X;

import android.R;

/* JADX INFO: loaded from: classes10.dex */
public abstract class KT9 {
    public static final int[] A00 = {R.attr.selectableItemBackground, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040737};
    public static final int[] A01 = {R.attr.summaryOn, R.attr.summaryOff, R.attr.disableDependentsState, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040261, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04082e, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04082f};
    public static final int[] A02 = {R.attr.dialogTitle, R.attr.dialogMessage, R.attr.dialogIcon, R.attr.positiveButtonText, R.attr.negativeButtonText, R.attr.dialogLayout, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040258, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040259, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04025a, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04025e, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04058c, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040617};
    public static final int[] A03 = {com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040917};
    public static final int[] A04 = {R.attr.entries, R.attr.entryValues, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f0402b8, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f0402b9, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040917};
    public static final int[] A05 = {R.attr.entries, R.attr.entryValues, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f0402b8, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f0402b9};
    public static final int[] A06 = {R.attr.icon, R.attr.persistent, R.attr.enabled, R.attr.layout, R.attr.title, R.attr.selectable, R.attr.key, R.attr.summary, R.attr.order, R.attr.widgetLayout, R.attr.dependency, R.attr.defaultValue, R.attr.shouldDisableView, R.attr.fragment, R.attr.singleLineTitle, R.attr.iconSpaceReserved, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040048, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04004a, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04024f, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040254, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f0402a6, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f0402a8, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040383, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f0403c9, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f0403d5, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040405, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040428, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04043f, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f0405a6, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f0405e9, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040736, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f0407aa, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f0407d4, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04082d, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f0408c7, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040a37};
    public static final int[] A07 = {R.attr.layout, R.attr.divider, R.attr.dividerHeight, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040049};
    public static final int[] A08 = {R.attr.orderingFromXml, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f0403f2, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f0405a8};
    public static final int[] A09 = {R.attr.maxWidth, R.attr.maxHeight, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040517, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04051d};
    public static final int[] A0A = {R.attr.layout, R.attr.max, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04003d, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04053d, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04072b, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f0407ba, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04090e};
    public static final int[] A0B = {R.attr.summaryOn, R.attr.summaryOff, R.attr.disableDependentsState, R.attr.switchTextOn, R.attr.switchTextOff, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040261, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04082e, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04082f, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040839, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04083a};
    public static final int[] A0C = {R.attr.summaryOn, R.attr.summaryOff, R.attr.disableDependentsState, R.attr.switchTextOn, R.attr.switchTextOff, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040261, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04082e, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04082f, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f040839, com.google.android.search.verification.client.R.attr._name_removed__res_0x7f04083a};
}
