package X;

import android.net.Uri;
import android.util.LruCache;
import com.facebook.video.heroplayer.setting.FbAutogeneratedSettings;
import com.facebook.video.heroplayer.setting.HeroPlayerSetting;
import com.whatsapp.calling.voipcalling.Voip;
import java.io.IOException;
import java.util.Collections;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;

/* JADX INFO: loaded from: classes10.dex */
public final class LIU implements MGZ {
    public static final String A0A;
    public long A00;
    public InterfaceC48547MGc A01;
    public final MGZ A02;
    public final C46432Ksy A03;
    public final HeroPlayerSetting A04;
    public final int A05;
    public final KUH A06;
    public final K5A A07;
    public final AtomicBoolean A08;
    public final AtomicBoolean A09;

    @Override // X.PAW
    public void A9T(ME8 me8) {
        C000700h.A0A(me8, 0);
        if (me8 instanceof InterfaceC48547MGc) {
            this.A01 = (InterfaceC48547MGc) me8;
        } else {
            this.A01 = new C47052LIb(me8);
        }
    }

    @Override // X.MGb, X.PAW
    public synchronized void close() {
        this.A02.close();
    }

    @Override // X.MGb, X.M9D
    public synchronized int read(byte[] bArr, int i, int i2) {
        C000700h.A0A(bArr, 0);
        long j = this.A00;
        if (j == 0) {
            return -1;
        }
        if (j != -1) {
            i2 = (int) Math.min(i2, j);
        }
        int i3 = this.A02.read(bArr, i, i2);
        if (i3 != -1) {
            this.A00 -= (long) i3;
        }
        return i3;
    }

    static {
        String name = LIU.class.getName();
        C000700h.A06(name);
        A0A = name;
    }

    @Override // X.MGb, X.PAW
    public java.util.Map Awy() {
        return this.A02.Awy();
    }

    @Override // X.PAW
    public Uri B61() {
        return this.A02.B61();
    }

    /* JADX WARN: Code duplicated, block: B:138:0x0237 A[Catch: all -> 0x03ff, TRY_LEAVE, TryCatch #3 {, blocks: (B:4:0x0003, B:6:0x0017, B:8:0x0023, B:32:0x008b, B:34:0x0095, B:29:0x0080, B:264:0x03f5, B:265:0x03fe, B:36:0x00a1, B:38:0x00a7, B:26:0x006d, B:28:0x0077, B:10:0x002f, B:12:0x0035, B:14:0x003d, B:16:0x0045, B:18:0x004d, B:20:0x0055, B:22:0x005d, B:24:0x0065, B:45:0x00b9, B:47:0x00c1, B:48:0x00c3, B:50:0x00cc, B:54:0x00d5, B:56:0x00dd, B:59:0x00e3, B:61:0x00eb, B:62:0x00ed, B:64:0x00fe, B:72:0x0119, B:74:0x011f, B:76:0x0129, B:78:0x012d, B:93:0x016d, B:96:0x0188, B:99:0x01ab, B:101:0x01c4, B:103:0x01ca, B:105:0x01ce, B:108:0x01d4, B:110:0x01d9, B:111:0x01df, B:113:0x01e4, B:109:0x01d7, B:114:0x01e7, B:116:0x01eb, B:118:0x01ef, B:119:0x01f4, B:125:0x0206, B:127:0x0209, B:129:0x020f, B:131:0x0219, B:133:0x021d, B:135:0x022c, B:136:0x0235, B:140:0x024e, B:147:0x0255, B:138:0x0237, B:148:0x0256, B:150:0x025a, B:151:0x025f, B:152:0x0265, B:154:0x026e, B:156:0x0276, B:158:0x027e, B:159:0x0281, B:164:0x0291, B:165:0x0295, B:167:0x0299, B:168:0x029c, B:170:0x02a7, B:175:0x02b0, B:176:0x02b4, B:177:0x02b7, B:179:0x02c2, B:184:0x02cb, B:185:0x02cf, B:186:0x02d2, B:188:0x02dd, B:193:0x02e6, B:194:0x02ea, B:195:0x02ed, B:197:0x02f8, B:202:0x0301, B:203:0x0305, B:204:0x0308, B:206:0x0313, B:211:0x031c, B:212:0x0320, B:213:0x0323, B:215:0x032e, B:220:0x0337, B:221:0x033b, B:222:0x033e, B:224:0x0349, B:229:0x0352, B:230:0x0356, B:231:0x0359, B:233:0x0364, B:236:0x036a, B:237:0x036e, B:238:0x0371, B:239:0x0375, B:241:0x037b, B:244:0x038d, B:246:0x0393, B:248:0x039b, B:250:0x039f, B:251:0x03a7, B:257:0x03c6, B:259:0x03ea, B:79:0x0135, B:81:0x0139, B:83:0x0142, B:84:0x0144, B:85:0x014a, B:86:0x014d, B:88:0x0151, B:90:0x015c, B:92:0x0166, B:66:0x0102, B:67:0x010a, B:69:0x0110), top: B:275:0x0003 }] */
    /* JADX WARN: Code duplicated, block: B:41:0x00b0  */
    /* JADX WARN: Code restructure failed: missing block: B:147:0x0255, code lost:
    
        throw r0;
     */
    @Override // X.MGb, X.PAW
    /*
        Code decompiled incorrectly, please refer to instructions dump.
    */
    public synchronized long C9F(C46619KxK c46619KxK) throws IOException {
        String str;
        String str2;
        boolean z;
        C46613KxC c46613KxC;
        long jMax;
        InterfaceC48547MGc interfaceC48547MGc;
        InterfaceC48547MGc interfaceC48547MGc2;
        InterfaceC48547MGc interfaceC48547MGc3;
        InterfaceC48547MGc interfaceC48547MGc4;
        InterfaceC48547MGc interfaceC48547MGc5;
        InterfaceC48547MGc interfaceC48547MGc6;
        InterfaceC48547MGc interfaceC48547MGc7;
        InterfaceC48547MGc interfaceC48547MGc8;
        InterfaceC48547MGc interfaceC48547MGc9;
        LruCache lruCache;
        boolean zA0t;
        String str3;
        K5A k5a;
        String str4;
        String host;
        long j;
        String host2;
        C000700h.A0A(c46619KxK, 0);
        Uri uri = c46619KxK.A06;
        C000700h.A05(uri);
        HeroPlayerSetting heroPlayerSetting = this.A04;
        if (heroPlayerSetting.enableCdnUrlExpiryCheck) {
            if ((("http".equalsIgnoreCase(uri.getScheme()) || "https".equalsIgnoreCase(uri.getScheme())) && (host = uri.getHost()) != null && (host.endsWith(".fbcdn.net") || host.endsWith(".cdninstagram.com") || (host.endsWith(".akamaihd.net") && (host.startsWith("fbcdn-") || host.startsWith("fbstatic-") || host.startsWith("fbexternal-") || host.startsWith("fb-"))))) || (("http".equalsIgnoreCase(uri.getScheme()) || "https".equalsIgnoreCase(uri.getScheme())) && (host2 = uri.getHost()) != null && AbstractC81793li.A1S(host2, AbstractC39542Hb1.A01))) {
                String queryParameter = uri.getQueryParameter("oe");
                if (queryParameter != null) {
                    j = Long.parseLong(queryParameter, 16) * 1000;
                } else {
                    j = -1;
                }
            } else {
                j = -1;
            }
            long jCurrentTimeMillis = System.currentTimeMillis();
            if (j != -1 && j < jCurrentTimeMillis) {
                throw new C43439JAh(c46619KxK, N8L.A0K.value, 1);
            }
        }
        C46693KzU c46693KzU = C46711Kzu.A00(c46619KxK).A0J;
        boolean z2 = c46693KzU != null ? c46693KzU.A02 : false;
        C46693KzU c46693KzU2 = C46711Kzu.A00(c46619KxK).A0J;
        if (c46693KzU2 == null || (str = c46693KzU2.A00) == null) {
            str = Voip.REJECT_REASON_DECLINED;
        }
        C46693KzU c46693KzU3 = C46711Kzu.A00(c46619KxK).A0J;
        if (c46693KzU3 == null || (str2 = c46693KzU3.A01) == null) {
            str2 = Voip.REJECT_REASON_DECLINED;
        }
        C46693KzU c46693KzU4 = C46711Kzu.A00(c46619KxK).A0J;
        if (c46693KzU4 != null) {
            z = c46693KzU4.A03;
        } else {
            AtomicBoolean atomicBoolean = this.A03.A08;
            z = atomicBoolean != null ? atomicBoolean.get() : false;
        }
        String str5 = this.A03.A07;
        C46693KzU c46693KzU5 = new C46693KzU(str, str2, z2, z);
        C46711Kzu c46711KzuA00 = C46711Kzu.A00(c46619KxK);
        if (c46711KzuA00 == null || (c46613KxC = c46711KzuA00.A0I) == null) {
            c46613KxC = K2k.A00.mHttpPriority;
            C000700h.A06(c46613KxC);
        }
        if (z2) {
            if (!heroPlayerSetting.gen.enable_http_priority_for_prefetch_fix || c46613KxC.equals(K2k.A02.mHttpPriority)) {
                c46613KxC = ((!heroPlayerSetting.useLowerHttpPriorityForUnimportantPrefetch || c46619KxK.A04 <= 50000) ? K2k.A05 : K2k.A06).mHttpPriority;
                C000700h.A09(c46613KxC);
            } else if (heroPlayerSetting.enableHttpPriorityForPrefetch) {
                c46613KxC = new C46613KxC(c46613KxC.A00, false);
            }
        } else if (heroPlayerSetting.enableHttpPriorityForStreaming) {
            c46613KxC = K2k.A04.mHttpPriority;
            C000700h.A06(c46613KxC);
            if (heroPlayerSetting.bufferedDurationBasedHttpPriorityUpperBoundMs > 0 && C46711Kzu.A00(c46619KxK).A02 > heroPlayerSetting.bufferedDurationBasedHttpPriorityUpperBoundMs) {
                c46613KxC = K2k.A07.mHttpPriority;
                C000700h.A06(c46613KxC);
            }
        }
        java.util.Map mapEmptyMap = Collections.emptyMap();
        byte[] bArr = c46619KxK.A0A;
        long j2 = c46619KxK.A02;
        long j3 = c46619KxK.A04;
        long j4 = j2 - j3;
        long j5 = c46619KxK.A03;
        if (j5 <= 0) {
            j5 = -1;
        }
        int i = c46619KxK.A00;
        C46711Kzu c46711Kzu = new C46711Kzu(c46613KxC, c46693KzU5, C46711Kzu.A00(c46619KxK), null, this.A05, -1, false);
        String str6 = c46619KxK.A08;
        C46619KxK c46619KxK2 = new C46619KxK(uri, c46711Kzu, str6 != null ? str6 : null, mapEmptyMap, bArr, 1, i, j4, j3, j5);
        if (heroPlayerSetting.enableVideoPlayerServerSideBweAnnotations && ((k5a = this.A07) == K5A.A04 || k5a == K5A.A0A || k5a == K5A.A09)) {
            switch ((z2 ? C02S.A01 : C02S.A0C).intValue()) {
                case 0:
                    str4 = "unknown";
                    break;
                case 1:
                    str4 = "android-prefetch-video";
                    break;
                default:
                    str4 = "android-playing-video";
                    break;
            }
            AbstractC46673Kyz.A01(c46619KxK2, "x-fb-ssbwe-annotation-request-type", str4);
        }
        FbAutogeneratedSettings fbAutogeneratedSettings = heroPlayerSetting.autogenSettings;
        if (fbAutogeneratedSettings != null && fbAutogeneratedSettings.enableSloHttpHeaderLogging) {
            C000700h.A06(str5);
            C46184KoL c46184KoL = C46184KoL.A01;
            synchronized (c46184KoL) {
                lruCache = c46184KoL.A00;
                zA0t = AbstractC32971bt.A0t(lruCache.get(str5));
            }
            if (!zA0t) {
                C46711Kzu c46711KzuA01 = C46711Kzu.A00(c46619KxK);
                if (c46711KzuA01 != null) {
                    str3 = "x-fb-qpl-ec";
                    if (!c46711KzuA01.A0R.containsKey("x-fb-qpl-ec")) {
                        str3 = "x-fb-qpl-ec";
                        AbstractC46673Kyz.A01(c46619KxK, "x-fb-qpl-ec", AnonymousClass000.A04(Km8.A00(), "video_uid=", AnonymousClass000.A08()));
                    }
                } else {
                    str3 = "x-fb-qpl-ec";
                    AbstractC46673Kyz.A01(c46619KxK, "x-fb-qpl-ec", AnonymousClass000.A04(Km8.A00(), "video_uid=", AnonymousClass000.A08()));
                }
                if (c46619KxK.A07 != null) {
                    C46711Kzu.A00(c46619KxK);
                    String strA0z = AbstractC466425r.A0z(str3, C46711Kzu.A00(c46619KxK).A0R);
                    if (strA0z != null) {
                        AbstractC46673Kyz.A02(c46619KxK2, C46711Kzu.A00(c46619KxK).A0R);
                        synchronized (c46184KoL) {
                            try {
                                lruCache.put(str5, strA0z);
                            } catch (Throwable th) {
                                throw th;
                            }
                        }
                    }
                }
            }
        }
        try {
            InterfaceC48547MGc interfaceC48547MGc10 = this.A01;
            if (interfaceC48547MGc10 != null) {
                interfaceC48547MGc10.C6R(c46619KxK2, K4W.A04);
            }
            MGZ mgz = this.A02;
            long jC9F = mgz.C9F(c46619KxK2);
            java.util.Map mapAwy = mgz.Awy();
            if (this.A01 != null) {
                List listA01 = AbstractC46501Kuu.A01("X-FB-Connection-Quality", mapAwy, true);
                if (listA01 != null) {
                    String strA12 = AbstractC81773lg.A12(listA01, 0);
                    InterfaceC48547MGc interfaceC48547MGc11 = this.A01;
                    if (interfaceC48547MGc11 != null) {
                        interfaceC48547MGc11.C6P("X-FB-Connection-Quality", strA12);
                    }
                }
                Object obj = mapAwy.get("x-fb-cec-video-limit");
                List list = (List) obj;
                if (obj != null) {
                    String strA13 = list != null ? AbstractC81773lg.A12(list, 0) : null;
                    InterfaceC48547MGc interfaceC48547MGc12 = this.A01;
                    if (interfaceC48547MGc12 != null) {
                        interfaceC48547MGc12.C6P("x-fb-cec-video-limit", strA13);
                    }
                }
                Object obj2 = mapAwy.get("up-ttfb");
                List list2 = (List) obj2;
                if (obj2 != null && (interfaceC48547MGc9 = this.A01) != null) {
                    interfaceC48547MGc9.C6P("up-ttfb", list2 != null ? AbstractC81773lg.A12(list2, 0) : null);
                }
                Object obj3 = mapAwy.get("x-fb-session-id");
                List list3 = (List) obj3;
                if (obj3 != null && (interfaceC48547MGc8 = this.A01) != null) {
                    interfaceC48547MGc8.C6P("x-fb-session-id", list3 != null ? AbstractC81773lg.A12(list3, 0) : null);
                }
                Object obj4 = mapAwy.get("x-fb-conn-uuid-client");
                List list4 = (List) obj4;
                if (obj4 != null && (interfaceC48547MGc7 = this.A01) != null) {
                    interfaceC48547MGc7.C6P("x-fb-conn-uuid-client", list4 != null ? AbstractC81773lg.A12(list4, 0) : null);
                }
                Object obj5 = mapAwy.get("x-fb-ptm-uuid");
                List list5 = (List) obj5;
                if (obj5 != null && (interfaceC48547MGc6 = this.A01) != null) {
                    interfaceC48547MGc6.C6P("x-fb-ptm-uuid", list5 != null ? AbstractC81773lg.A12(list5, 0) : null);
                }
                Object obj6 = mapAwy.get("x-fb-response-time-ms");
                List list6 = (List) obj6;
                if (obj6 != null && (interfaceC48547MGc5 = this.A01) != null) {
                    interfaceC48547MGc5.C6P("x-fb-response-time-ms", list6 != null ? AbstractC81773lg.A12(list6, 0) : null);
                }
                Object obj7 = mapAwy.get("x-bwe-mean");
                List list7 = (List) obj7;
                if (obj7 != null && (interfaceC48547MGc4 = this.A01) != null) {
                    interfaceC48547MGc4.C6P("x-bwe-mean", list7 != null ? AbstractC81773lg.A12(list7, 0) : null);
                }
                Object obj8 = mapAwy.get("x-bwe-std-dev");
                List list8 = (List) obj8;
                if (obj8 != null && (interfaceC48547MGc3 = this.A01) != null) {
                    interfaceC48547MGc3.C6P("x-bwe-std-dev", list8 != null ? AbstractC81773lg.A12(list8, 0) : null);
                }
                Object obj9 = mapAwy.get("x-fb-dynamic-predictive-response-chunk-size");
                List list9 = (List) obj9;
                if (obj9 != null && (interfaceC48547MGc2 = this.A01) != null) {
                    interfaceC48547MGc2.C6P("x-fb-dynamic-predictive-response-chunk-size", list9 != null ? AbstractC81773lg.A12(list9, 0) : null);
                }
                Iterator itA1F = AbstractC466625t.A1F(mapAwy);
                while (itA1F.hasNext()) {
                    java.util.Map.Entry entryA0Y = AbstractC32971bt.A0Y(itA1F);
                    String strA14 = AbstractC466425r.A12(entryA0Y);
                    List list10 = (List) entryA0Y.getValue();
                    if (strA14 != null && list10 != null && !list10.isEmpty() && AbstractC81773lg.A1Y("x-fb-ull-", 1, strA14) && (interfaceC48547MGc = this.A01) != null) {
                        interfaceC48547MGc.C6P(strA14, list10.get(0));
                    }
                }
            }
            C000700h.A0D(mapAwy, "null cannot be cast to non-null type kotlin.collections.Map<kotlin.String?, kotlin.collections.List<kotlin.String>?>");
            long jA00 = AbstractC46501Kuu.A00(mapAwy, true);
            long j6 = c46619KxK2.A04;
            jMax = (long) Math.max(0.0d, jA00 - j6);
            this.A00 = (jC9F == -1 || jC9F > jMax) ? jMax : jC9F;
            String str7 = A0A;
            Object[] objArrA1Y = J27.A1Y();
            AbstractC465925m.A1W(objArrA1Y, 0, j6);
            long j7 = c46619KxK2.A03;
            AbstractC465925m.A1W(objArrA1Y, 1, j7);
            AbstractC465925m.A1W(objArrA1Y, 2, jMax);
            objArrA1Y[3] = str5;
            objArrA1Y[4] = c46619KxK2.A08;
            AbstractC43332J2y.A01(str7, "Opening data spec Offset: %d, Length %d Open Length %d Videoid %s Key %s", objArrA1Y);
            if (j7 != -1) {
                jMax = (long) Math.min(jC9F, jMax);
            }
        } catch (IOException e) {
            throw e;
        }
        return jMax;
    }

    @Override // X.InterfaceC48546MGa
    public void cancel() {
    }

    public LIU(MGZ mgz, InterfaceC48547MGc interfaceC48547MGc, KUH kuh, C46432Ksy c46432Ksy, HeroPlayerSetting heroPlayerSetting, AtomicBoolean atomicBoolean, AtomicBoolean atomicBoolean2, int i, int i2) {
        this.A03 = c46432Ksy;
        this.A02 = mgz;
        this.A05 = i;
        this.A01 = interfaceC48547MGc;
        this.A08 = atomicBoolean;
        this.A09 = atomicBoolean2;
        this.A04 = heroPlayerSetting;
        this.A06 = kuh;
        for (K5A k5a : K5A.values()) {
            if (k5a.value == i2) {
                this.A07 = k5a;
            }
        }
        k5a = K5A.A0B;
        this.A07 = k5a;
    }
}
