package X;

import com.whatsapp.calling.voipcalling.Voip;

/* JADX INFO: loaded from: classes12.dex */
public class PG2 extends AbstractC47703LhK {
    public static final long serialVersionUID = -8217276541322337118L;
    public final String appNetSessionId;
    public final long avgBitrate;
    public final int bufferedDurationMs;
    public final int bufferedDurationMsAtDataSpecCreation;
    public final K4W cacheType;
    public final boolean cancelled;
    public final long cdnResponseTime;
    public final Long clientWallClockOffsetMs;
    public final String codec;
    public final long confidenceBasedBitrateEstimate;
    public final int confidencePctForBitrateEstimate;
    public final String connectionQuality;
    public final Long contentLength;
    public final String contentType;
    public final String dataSourceFactory;
    public final long dataSpecCreationTimeMs;
    public final String e2eTracingKey;
    public final String edgeHit;
    public final String exceptionMessage;
    public final int expectedPredictedNumber;
    public final int firstChunkSize;
    public final long firstChunkTransferDurationMs;
    public final boolean inRewoundState;
    public final boolean isChunkedTransfer;
    public final boolean isFBMS;
    public final boolean isFbPredictiveDASH;
    public final boolean isFirstTimePlay;
    public final boolean isInWarmup;
    public final boolean isLowestBitrate;
    public final boolean isManifestDynamic;
    public final boolean isOfflineCached;
    public final boolean isOfflinePlayback;
    public final boolean isPredictedURL;
    public final boolean isPrefetch;
    public final boolean isPreload;
    public final boolean isSkipAheadChunk;
    public final boolean isSpherical;
    public final boolean isSponsored;
    public final boolean isTemplatedManifest;
    public final int latestSegmentId;
    public final long manifestFirstSegmentStartTs;
    public final long manifestLastSegmentEndTs;
    public final long manifestNumSegments;
    public final int minimumLoadPositionMs;
    public final int networkPriority;
    public final String networkRequestConnectionId;
    public final String networkRequestHttpVersion;
    public final String networkRequestPtmUuid;
    public final long numSegmentsToEndOfManifest;
    public final String oneObserved;
    public final String oneReqWave;
    public final String oneResWave;
    public final String oneVariant;
    public final String originHit;
    public final String playOrigin;
    public final String playSubOrigin;
    public final String playbackSessionId;
    public final long playerId;
    public final String playerType;
    public final int positionInUnit;
    public final int predictedNumberMapping;
    public final String prefetchSource;
    public final String qualityLabel;
    public final int readBytesLength;
    public final long requestQueueDurationMs;
    public final EnumC43352J3u requestType;
    public final long requestedLength;
    public final int segmentDurationMs;
    public final long segmentStartMs;
    public final long startVideoBandwidth;
    public final long startVideoTTFB;
    public final long startingByteOffset;
    public final int streamType;
    public final String tigonSessionId;
    public final String tigonTransactionId;
    public final long timeMs;
    public final int trackType;
    public final long transferEndDurationMs;
    public final int transferSeqNum;
    public final long transferStartDurationMs;
    public final long upstreamTTFB;
    public final String url;
    public final String videoBandwidthEstimateStr;
    public final String videoId;
    public final long videoTimePositionUs;
    public final String vpSessionId;

    public String toString() {
        StringBuilder sbA08 = AnonymousClass000.A08();
        StringBuilder sbA09 = AnonymousClass000.A08();
        sbA09.append("timeMs=");
        StringBuilder sbA0M = AbstractC54852PDx.A0M(sbA09, sbA08, this.timeMs);
        sbA0M.append(", videoId=");
        StringBuilder sbA0K = AbstractC54852PDx.A0K(this.videoId, sbA0M, sbA08);
        sbA0K.append(", playerId=");
        StringBuilder sbA0M2 = AbstractC54852PDx.A0M(sbA0K, sbA08, this.playerId);
        sbA0M2.append(", url=");
        StringBuilder sbA0K2 = AbstractC54852PDx.A0K(this.url, sbA0M2, sbA08);
        sbA0K2.append(", exception=");
        StringBuilder sbA0K3 = AbstractC54852PDx.A0K(this.exceptionMessage, sbA0K2, sbA08);
        sbA0K3.append(", isPrefetch=");
        StringBuilder sbA0N = AbstractC54852PDx.A0N(sbA0K3, sbA08, this.isPrefetch);
        sbA0N.append(", prefetchSource=");
        StringBuilder sbA0K4 = AbstractC54852PDx.A0K(this.prefetchSource, sbA0N, sbA08);
        sbA0K4.append(", isPreload=");
        StringBuilder sbA0N2 = AbstractC54852PDx.A0N(sbA0K4, sbA08, this.isPreload);
        sbA0N2.append(", readBytes=");
        StringBuilder sbA0L = AbstractC54852PDx.A0L(sbA0N2, sbA08, this.readBytesLength);
        sbA0L.append(", queueDuration=");
        StringBuilder sbA0M3 = AbstractC54852PDx.A0M(sbA0L, sbA08, this.requestQueueDurationMs);
        sbA0M3.append(", startDuration=");
        StringBuilder sbA0M4 = AbstractC54852PDx.A0M(sbA0M3, sbA08, this.transferStartDurationMs);
        sbA0M4.append(", endDuration=");
        StringBuilder sbA0M5 = AbstractC54852PDx.A0M(sbA0M4, sbA08, this.transferEndDurationMs);
        sbA0M5.append(", seqNum=");
        StringBuilder sbA0L2 = AbstractC54852PDx.A0L(sbA0M5, sbA08, this.transferSeqNum);
        sbA0L2.append(", cacheType=");
        StringBuilder sbA0K5 = AbstractC54852PDx.A0K(this.cacheType.mName, sbA0L2, sbA08);
        sbA0K5.append(", isFirstPlay=");
        StringBuilder sbA0N3 = AbstractC54852PDx.A0N(sbA0K5, sbA08, this.isFirstTimePlay);
        sbA0N3.append(", playOrigin=");
        StringBuilder sbA0K6 = AbstractC54852PDx.A0K(this.playOrigin, sbA0N3, sbA08);
        sbA0K6.append(", startingByteOffset=");
        StringBuilder sbA0M6 = AbstractC54852PDx.A0M(sbA0K6, sbA08, this.startingByteOffset);
        sbA0M6.append(", requestedLength=");
        StringBuilder sbA0M7 = AbstractC54852PDx.A0M(sbA0M6, sbA08, this.requestedLength);
        sbA0M7.append(", streamType=");
        StringBuilder sbA0L3 = AbstractC54852PDx.A0L(sbA0M7, sbA08, this.streamType);
        sbA0L3.append(", segmentStart=");
        StringBuilder sbA0M8 = AbstractC54852PDx.A0M(sbA0L3, sbA08, this.segmentStartMs);
        sbA0M8.append(", segmentDuration=");
        StringBuilder sbA0L4 = AbstractC54852PDx.A0L(sbA0M8, sbA08, this.segmentDurationMs);
        sbA0L4.append(", dataSourceFactory=");
        StringBuilder sbA0K7 = AbstractC54852PDx.A0K(this.dataSourceFactory, sbA0L4, sbA08);
        sbA0K7.append(", qualityLabel=");
        StringBuilder sbA0K8 = AbstractC54852PDx.A0K(this.qualityLabel, sbA0K7, sbA08);
        sbA0K8.append(", connQual=");
        StringBuilder sbA0K9 = AbstractC54852PDx.A0K(this.connectionQuality, sbA0K8, sbA08);
        sbA0K9.append(", networkPriority=");
        StringBuilder sbA0L5 = AbstractC54852PDx.A0L(sbA0K9, sbA08, this.networkPriority);
        sbA0L5.append(", bufferedDurationMs=");
        StringBuilder sbA0L6 = AbstractC54852PDx.A0L(sbA0L5, sbA08, this.bufferedDurationMs);
        sbA0L6.append(", startVideoBandwidth=");
        StringBuilder sbA0M9 = AbstractC54852PDx.A0M(sbA0L6, sbA08, this.startVideoBandwidth);
        sbA0M9.append(", startVideoTTFB=");
        StringBuilder sbA0M10 = AbstractC54852PDx.A0M(sbA0M9, sbA08, this.startVideoTTFB);
        sbA0M10.append(", videoBandwidthEstimateStr=");
        StringBuilder sbA0K10 = AbstractC54852PDx.A0K(this.videoBandwidthEstimateStr, sbA0M10, sbA08);
        sbA0K10.append(", upstreamTTFB=");
        StringBuilder sbA0M11 = AbstractC54852PDx.A0M(sbA0K10, sbA08, this.upstreamTTFB);
        sbA0M11.append(", tigonSessionId=");
        StringBuilder sbA0K11 = AbstractC54852PDx.A0K(this.tigonSessionId, sbA0M11, sbA08);
        sbA0K11.append(", tigonTransactionId=");
        StringBuilder sbA0K12 = AbstractC54852PDx.A0K(this.tigonTransactionId, sbA0K11, sbA08);
        sbA0K12.append(", appNetSesssionId=");
        StringBuilder sbA0K13 = AbstractC54852PDx.A0K(this.appNetSessionId, sbA0K12, sbA08);
        sbA0K13.append(", networkRequestConnectionId=");
        StringBuilder sbA0K14 = AbstractC54852PDx.A0K(this.networkRequestConnectionId, sbA0K13, sbA08);
        sbA0K14.append(", networkRequestPtmUuid=");
        StringBuilder sbA0K15 = AbstractC54852PDx.A0K(this.networkRequestPtmUuid, sbA0K14, sbA08);
        sbA0K15.append(", networkRequestHttpVersion=");
        StringBuilder sbA0K16 = AbstractC54852PDx.A0K(this.networkRequestHttpVersion, sbA0K15, sbA08);
        sbA0K16.append(", manifestFirstSegmentStartTs=");
        StringBuilder sbA0M12 = AbstractC54852PDx.A0M(sbA0K16, sbA08, this.manifestFirstSegmentStartTs);
        sbA0M12.append(", manifestLastSegmentEndTs=");
        StringBuilder sbA0M13 = AbstractC54852PDx.A0M(sbA0M12, sbA08, this.manifestLastSegmentEndTs);
        sbA0M13.append(", manifestNumSegments=");
        StringBuilder sbA0M14 = AbstractC54852PDx.A0M(sbA0M13, sbA08, this.manifestNumSegments);
        sbA0M14.append(", cancelled=");
        StringBuilder sbA0N4 = AbstractC54852PDx.A0N(sbA0M14, sbA08, this.cancelled);
        sbA0N4.append(", bufferedDurationMsAtDataSpecCreation=");
        StringBuilder sbA0L7 = AbstractC54852PDx.A0L(sbA0N4, sbA08, this.bufferedDurationMsAtDataSpecCreation);
        sbA0L7.append(", dataSpecCreationTimeMs=");
        StringBuilder sbA0M15 = AbstractC54852PDx.A0M(sbA0L7, sbA08, this.dataSpecCreationTimeMs);
        sbA0M15.append(", playSubOrigin=");
        StringBuilder sbA0K17 = AbstractC54852PDx.A0K(this.playSubOrigin, sbA0M15, sbA08);
        sbA0K17.append(", isFBMS=");
        StringBuilder sbA0N5 = AbstractC54852PDx.A0N(sbA0K17, sbA08, this.isFBMS);
        sbA0N5.append(", isFbPredictiveDASH=");
        StringBuilder sbA0N6 = AbstractC54852PDx.A0N(sbA0N5, sbA08, this.isFbPredictiveDASH);
        sbA0N6.append(", isSkipAheadChunk=");
        StringBuilder sbA0N7 = AbstractC54852PDx.A0N(sbA0N6, sbA08, this.isSkipAheadChunk);
        sbA0N7.append(", inRewoundState=");
        StringBuilder sbA0N8 = AbstractC54852PDx.A0N(sbA0N7, sbA08, this.inRewoundState);
        sbA0N8.append(", isManifestDynamic=");
        StringBuilder sbA0N9 = AbstractC54852PDx.A0N(sbA0N8, sbA08, this.isManifestDynamic);
        sbA0N9.append(", isChunkedTransfer=");
        StringBuilder sbA0N10 = AbstractC54852PDx.A0N(sbA0N9, sbA08, this.isChunkedTransfer);
        sbA0N10.append(", isPredictedURL=");
        StringBuilder sbA0N11 = AbstractC54852PDx.A0N(sbA0N10, sbA08, this.isPredictedURL);
        sbA0N11.append(", expectedPredictedNumber=");
        StringBuilder sbA0L8 = AbstractC54852PDx.A0L(sbA0N11, sbA08, this.expectedPredictedNumber);
        sbA0L8.append(", predictedNumberMapping=");
        StringBuilder sbA0L9 = AbstractC54852PDx.A0L(sbA0L8, sbA08, this.predictedNumberMapping);
        sbA0L9.append(", numSegmentsToEndOfManifest= ");
        StringBuilder sbA0M16 = AbstractC54852PDx.A0M(sbA0L9, sbA08, this.numSegmentsToEndOfManifest);
        sbA0M16.append(", edgeHit= ");
        StringBuilder sbA0K18 = AbstractC54852PDx.A0K(this.edgeHit, sbA0M16, sbA08);
        sbA0K18.append(", originHit= ");
        StringBuilder sbA0K19 = AbstractC54852PDx.A0K(this.originHit, sbA0K18, sbA08);
        sbA0K19.append(", codec= ");
        StringBuilder sbA0K20 = AbstractC54852PDx.A0K(this.codec, sbA0K19, sbA08);
        sbA0K20.append(", cdnResponseTime= ");
        StringBuilder sbA0M17 = AbstractC54852PDx.A0M(sbA0K20, sbA08, this.cdnResponseTime);
        sbA0M17.append(", contentType= ");
        StringBuilder sbA0K21 = AbstractC54852PDx.A0K(this.contentType, sbA0M17, sbA08);
        sbA0K21.append(", latestSegmentId= ");
        StringBuilder sbA0L10 = AbstractC54852PDx.A0L(sbA0K21, sbA08, this.latestSegmentId);
        sbA0L10.append(", confidenceBasedBitrateEstimate=");
        StringBuilder sbA0M18 = AbstractC54852PDx.A0M(sbA0L10, sbA08, this.confidenceBasedBitrateEstimate);
        sbA0M18.append(", confidencePctForBitrateEstimate=");
        StringBuilder sbA0L11 = AbstractC54852PDx.A0L(sbA0M18, sbA08, this.confidencePctForBitrateEstimate);
        sbA0L11.append(", minimumLoadPositionMs=");
        StringBuilder sbA0L12 = AbstractC54852PDx.A0L(sbA0L11, sbA08, this.minimumLoadPositionMs);
        sbA0L12.append(", oneReqWave=");
        StringBuilder sbA0K22 = AbstractC54852PDx.A0K(this.oneReqWave, sbA0L12, sbA08);
        sbA0K22.append(", oneResWave=");
        StringBuilder sbA0K23 = AbstractC54852PDx.A0K(this.oneResWave, sbA0K22, sbA08);
        sbA0K23.append(", oneObserved=");
        StringBuilder sbA0K24 = AbstractC54852PDx.A0K(this.oneObserved, sbA0K23, sbA08);
        sbA0K24.append(", oneVariant=");
        StringBuilder sbA0K25 = AbstractC54852PDx.A0K(this.oneVariant, sbA0K24, sbA08);
        sbA0K25.append(", playerType=");
        StringBuilder sbA0K26 = AbstractC54852PDx.A0K(this.playerType, sbA0K25, sbA08);
        sbA0K26.append(", positionInUnit=");
        StringBuilder sbA0L13 = AbstractC54852PDx.A0L(sbA0K26, sbA08, this.positionInUnit);
        sbA0L13.append(", vpSessionId=");
        StringBuilder sbA0K27 = AbstractC54852PDx.A0K(this.vpSessionId, sbA0L13, sbA08);
        sbA0K27.append(", firstChunkSize=");
        StringBuilder sbA0L14 = AbstractC54852PDx.A0L(sbA0K27, sbA08, this.firstChunkSize);
        sbA0L14.append(", firstChunkTransferDurationMs=");
        StringBuilder sbA0M19 = AbstractC54852PDx.A0M(sbA0L14, sbA08, this.firstChunkTransferDurationMs);
        sbA0M19.append(", clientWallClockOffsetMs=");
        sbA0M19.append(this.clientWallClockOffsetMs);
        AbstractC81783lh.A1T(sbA0M19, sbA08);
        StringBuilder sbA010 = AnonymousClass000.A08();
        sbA010.append(", contentLength=");
        sbA010.append(this.contentLength);
        AbstractC81783lh.A1T(sbA010, sbA08);
        StringBuilder sbA011 = AnonymousClass000.A08();
        sbA011.append(", requestType=");
        sbA011.append(this.requestType);
        AbstractC81783lh.A1T(sbA011, sbA08);
        StringBuilder sbA012 = AnonymousClass000.A08();
        sbA012.append(", playbackSessionId=");
        StringBuilder sbA0K28 = AbstractC54852PDx.A0K(this.playbackSessionId, sbA012, sbA08);
        sbA0K28.append(", e2eTracingKey=");
        StringBuilder sbA0K29 = AbstractC54852PDx.A0K(this.e2eTracingKey, sbA0K28, sbA08);
        sbA0K29.append(", videoTimePositionUs=");
        StringBuilder sbA0M20 = AbstractC54852PDx.A0M(sbA0K29, sbA08, this.videoTimePositionUs);
        sbA0M20.append(", isOfflineCached=");
        StringBuilder sbA0N12 = AbstractC54852PDx.A0N(sbA0M20, sbA08, this.isOfflineCached);
        sbA0N12.append(", isOfflinePlayback=");
        sbA0N12.append(this.isOfflinePlayback);
        AbstractC81783lh.A1T(sbA0N12, sbA08);
        return sbA08.toString();
    }

    public PG2(K4W k4w, EnumC43352J3u enumC43352J3u, Long l, Long l2, String str, String str2, String str3, String str4, String str5, String str6, String str7, String str8, String str9, String str10, String str11, String str12, String str13, String str14, String str15, String str16, String str17, String str18, String str19, String str20, String str21, String str22, String str23, String str24, String str25, int i, int i2, int i3, int i4, int i5, int i6, int i7, int i8, int i9, int i10, int i11, int i12, int i13, int i14, long j, long j2, long j3, long j4, long j5, long j6, long j7, long j8, long j9, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10, boolean z11, boolean z12, boolean z13, boolean z14, boolean z15, boolean z16, boolean z17) {
        super(K55.A0F);
        this.timeMs = j;
        this.videoId = str;
        this.playerId = j2;
        String str26 = Voip.REJECT_REASON_DECLINED;
        this.url = str2 == null ? Voip.REJECT_REASON_DECLINED : str2;
        this.exceptionMessage = str3 == null ? Voip.REJECT_REASON_DECLINED : str3;
        this.isPrefetch = z;
        this.prefetchSource = str4;
        this.isPreload = z2;
        this.readBytesLength = i;
        this.requestQueueDurationMs = j3;
        this.transferStartDurationMs = j4;
        this.transferEndDurationMs = j5;
        this.transferSeqNum = i2;
        this.cacheType = k4w;
        this.isFirstTimePlay = z3;
        this.isInWarmup = z4;
        this.playOrigin = str5;
        this.playSubOrigin = str13;
        this.startingByteOffset = j6;
        this.requestedLength = j7;
        this.streamType = i3;
        this.trackType = i4;
        this.segmentStartMs = j8;
        this.segmentDurationMs = i5;
        this.dataSourceFactory = "Apache";
        this.qualityLabel = str6;
        this.connectionQuality = str7;
        this.networkPriority = i6;
        this.avgBitrate = j9;
        this.isLowestBitrate = z5;
        this.bufferedDurationMs = i7;
        this.startVideoBandwidth = j10;
        this.startVideoTTFB = j11;
        this.isSpherical = z6;
        this.isSponsored = z7;
        this.isTemplatedManifest = z8;
        this.videoBandwidthEstimateStr = str8;
        this.upstreamTTFB = j12;
        String str27 = Voip.REJECT_REASON_DECLINED;
        this.tigonSessionId = Voip.REJECT_REASON_DECLINED;
        this.tigonTransactionId = Voip.REJECT_REASON_DECLINED;
        this.appNetSessionId = str9;
        this.networkRequestConnectionId = str10;
        this.networkRequestPtmUuid = str11;
        this.networkRequestHttpVersion = str12;
        this.manifestFirstSegmentStartTs = j13;
        this.manifestLastSegmentEndTs = j14;
        this.manifestNumSegments = j15;
        this.cancelled = z9;
        this.bufferedDurationMsAtDataSpecCreation = i8;
        this.dataSpecCreationTimeMs = j16;
        this.isFBMS = z10;
        this.isFbPredictiveDASH = z11;
        this.isSkipAheadChunk = z12;
        this.inRewoundState = z13;
        this.isManifestDynamic = z14;
        this.isChunkedTransfer = z15;
        this.isPredictedURL = z16;
        this.expectedPredictedNumber = i10;
        this.predictedNumberMapping = i9;
        this.numSegmentsToEndOfManifest = j17;
        this.edgeHit = str14;
        this.originHit = str15;
        this.codec = str16 != null ? str16 : str27;
        this.cdnResponseTime = j18;
        this.contentType = str17;
        this.latestSegmentId = i11;
        this.confidenceBasedBitrateEstimate = j19;
        this.confidencePctForBitrateEstimate = i12;
        this.minimumLoadPositionMs = i13;
        this.oneReqWave = str18;
        this.oneResWave = str19;
        this.oneObserved = str20;
        this.oneVariant = str21;
        this.playerType = str22 != null ? str22 : str26;
        this.positionInUnit = -1;
        this.vpSessionId = str23;
        this.firstChunkSize = i14;
        this.firstChunkTransferDurationMs = j20;
        this.clientWallClockOffsetMs = l;
        this.contentLength = l2;
        this.requestType = enumC43352J3u;
        this.playbackSessionId = str24;
        this.e2eTracingKey = str25;
        this.videoTimePositionUs = j21;
        this.isOfflineCached = z17;
        this.isOfflinePlayback = false;
    }
}
