package X;

/* JADX INFO: loaded from: classes12.dex */
public abstract class PIH {
    public static String A00(int i) {
        switch (i) {
            case 1012:
                return "INTERACTION_DIRECT_MEDIA_PICKER_WATERFALL";
            case 1051:
                return "INTERACTION_COM_INSTAGRAM_PRIVACY_ACTIVITY_CENTER_FEED_MEDIA_SCREEN";
            case 1082:
                return "INTERACTION_COM_BLOKS_WWW_IG_ABOUT_THIS_ACCOUNT_FORMER_USERNAMES";
            case 1166:
                return "INTERACTION_FOLLOWERS";
            case 1225:
                return "INTERACTION_DIRECT_GIF_TRAY_FRAGMENT";
            case 1264:
                return "INTERACTION_MUSIC_OVERLAY_SEARCH_RESULTS";
            case 1460:
                return "INTERACTION_SELF_FOLLOWERS";
            case 1598:
                return "INTERACTION_BARCELONA_CUSTOM_INSTALL_FULLSCREEN";
            case 1642:
                return "INTERACTION_DIRECT_MESSAGE_LIST";
            case 1678:
                return "INTERACTION_TEST_FEED_CONTEXTUAL_SELF_PROFILE";
            case 1683:
                return "INTERACTION_CUSTOM_ALERT";
            case 1722:
                return "INTERACTION_ALBUM_PICKER";
            case 1872:
                return "INTERACTION_TEST_FEED_CONTEXTUAL_PROFILE";
            case 1959:
                return "INTERACTION_BLOCK_LIST_TAB_VIEW";
            case 1973:
                return "INTERACTION_COM_INSTAGRAM_SETTINGS_PRIVACY_COMMENTS_BLOCKED_COMMENTERS";
            case 2017:
                return "INTERACTION_COM_INSTAGRAM_PRIVACY_ACTIVITY_CENTER_LIKED_MEDIA_SCREEN";
            case 2136:
                return "INTERACTION_LIVE_VIEWER";
            case 2199:
                return "INTERACTION_REEL_FEED_POST_SHARE_FRAGMENT";
            case 2203:
                return "INTERACTION_IG_PUBLISH_SCREEN_CAPTION";
            case 2285:
                return "INTERACTION_DISCOVERY_MAP_LOCATION_LIST";
            case 2333:
                return "INTERACTION_PBIA_PROXY_PROFILE";
            case 2508:
                return "INTERACTION_DIRECT_AGGREGATED_MEDIA";
            case 2523:
                return "INTERACTION_DIRECT_THREAD_DETAILS_REDESIGN";
            case 2541:
                return "INTERACTION_TAGGED_PROFILE";
            case 2592:
                return "INTERACTION_REEL_DASHBOARD_ADD_TO_STORY_CAMERA_FRAGMENT";
            case 2684:
                return "INTERACTION_SEARCH_TYPEAHEAD";
            case 2720:
                return "INTERACTION_FRIEND_MAP";
            case 2792:
                return "INTERACTION_NAMETAG";
            case 2885:
                return "INTERACTION_IG_COMMENT_IMAGE_VIEWER";
            case 2891:
                return "INTERACTION_DIRECT_THREAD_SHARED_POSTS";
            case 2924:
                return "INTERACTION_ATTRIBUTION_QUICK_CAMERA_FRAGMENT";
            case 2926:
                return "INTERACTION_DIRECT_SHARESHEET_SEARCH_FRAGMENT";
            case 3037:
                return "INTERACTION_DIRECT_PUBLIC_CHAT_JOINFLOW_NUX";
            case 3075:
                return "INTERACTION_LIVE_BROADCAST";
            case 3128:
                return "INTERACTION_BLOKS_UNKNOWN";
            case 3150:
                return "INTERACTION_FEED_CONTEXTUAL_CHAIN";
            case 3254:
                return "INTERACTION_HIGHLIGHTS_ADD_SHEET";
            case 3304:
                return "INTERACTION_MEDIA_VIEW_STORY_STICKER";
            case 3314:
                return "INTERACTION_RTC_CALL";
            case 3395:
                return "INTERACTION_SAVED_MEDIA_ALL_CONTENT";
            case 3409:
                return "INTERACTION_LIKERS";
            case 3490:
                return "INTERACTION_AUDIO_BROWSER_TABBED_SEARCH_PAGE_VC";
            case 3491:
                return "INTERACTION_BLOCKED_LIST";
            case 3510:
                return "INTERACTION_SUNDIAL_CONTENT_NOTES_FEED";
            case 3614:
                return "INTERACTION_ACCOUNT_TRANSPARENCY_BLOKS";
            case 3622:
                return "INTERACTION_IG_DIRECT_EMOJI_PONG_EASTER_EGG";
            case 3710:
                return "INTERACTION_CLIPS_VIEWER_EXPLORE_POPULAR_MINOR_UNIT";
            case 3810:
                return "INTERACTION_FEED_CONTEXTUAL_SAVED_COLLECTIONS";
            case 3849:
                return "INTERACTION_DISCOVERY_MAP_LOCATION_DETAIL";
            case 3857:
                return "INTERACTION_DIRECT_INBOX";
            case 3890:
                return "INTERACTION_EXPLORE_POPULAR";
            case 3975:
                return "INTERACTION_UNIFIED_FOLLOW_LISTS";
            case 4040:
                return "INTERACTION_PROFILE_EDIT_USERNAME";
            case 4191:
                return "INTERACTION_CLIPS_GALLERY";
            case 4203:
                return "INTERACTION_COM_BLOKS_WWW_CAA_LOGIN_AYMH_MULTIPLE_PROFILES_SCREEN_ENTRY";
            case 4221:
                return "INTERACTION_DIRECT_PENDING_INBOX";
            case 4222:
                return "INTERACTION_BROADCAST_CHAT_THREAD";
            case 4229:
                return "INTERACTION_CLIPS_VIEWER_CLIPS_TAB";
            case 4240:
                return "INTERACTION_IG_DIRECT_NOTES_COMPOSER_AUDIENCE_SELECTOR";
            case 4250:
                return "INTERACTION_QUICK_SNAP_MEDIA_VIEWER_FRAGMENT";
            case 4420:
                return "INTERACTION_COMMENTS_V2";
            case 4634:
                return "INTERACTION_STORY_EMOJI";
            case 4672:
                return "INTERACTION_COM_BLOKS_WWW_FXCAL_SETTINGS";
            case 4708:
                return "INTERACTION_DIRECT_POSTCAPTURE_CAMERA";
            case 4824:
                return "INTERACTION_MEDIA_CROP_VIEW";
            case 4861:
                return "INTERACTION_AUDIENCE_SELECTION";
            case 4869:
                return "INTERACTION_EDIT_PROFILE_GRID_REORDER";
            case 4877:
                return "INTERACTION_SERP_USERS";
            case 4912:
                return "INTERACTION_COM_BLOKS_WWW_IG_RP_COWATCH_BROWSE_SURFACE_CONTAINER";
            case 4925:
                return "INTERACTION_COM_BLOKS_WWW_AVATAR_EDITOR_CDS_LAUNCHER";
            case 4954:
                return "INTERACTION_MUTUAL";
            case 4989:
                return "INTERACTION_PROFILE_EDIT_BIO";
            case 4992:
                return "INTERACTION_DIRECT_RECIPIENT_PICKER";
            case 5041:
                return "INTERACTION_SERP_TOP";
            case 5079:
                return "INTERACTION_CLIPS_TIMELINE_EDITOR";
            case 5133:
                return "INTERACTION_SELF_UNIFIED_FOLLOW_LISTS";
            case 5151:
                return "INTERACTION_REEL_MENTION_RESHARE_CAMERA_FRAGMENT";
            case 5177:
                return "INTERACTION_CLIPS_INTERACTION_REPLY_SHEET";
            case 5182:
                return "IG_APP_USER_INTERACTION_FLOWS_INTERACTION_TEST";
            case 5272:
                return "INTERACTION_DIRECT_REACTION_SELECTION";
            case 5302:
                return "INTERACTION_MAIN_SETTINGS_SCREEN";
            case 5349:
                return "INTERACTION_COM_BLOKS_WWW_INSTAGRAM_YOUR_ACTIVITY_BLOKS_YOUR_ACTIVITY_SEEN_CONTENT_SCREEN_QU";
            case 5360:
                return "INTERACTION_FOLLOWING";
            case 5441:
                return "INTERACTION_DIRECT_INDIVIDUAL_STACK_CARD_GALLERY_FRAGMENT";
            case 5709:
                return "INTERACTION_PROFILE_SOCIAL_CONTEXT";
            case 5730:
                return "INTERACTION_IG_QUICK_SNAP_CREATION";
            case 5775:
                return "INTERACTION_ARCHIVE_STORIES";
            case 5835:
                return "INTERACTION_COM_BLOKS_WWW_FX_SETTINGS_ADPROFILECENTER_ADS_DETAIL";
            case 5853:
                return "INTERACTION_CLIPS_PRECAPTURE_CAMERA";
            case 5912:
                return "INTERACTION_AUDIO_BROWSER_V2_TRENDING";
            case 5960:
                return "INTERACTION_FEED_CONTEXTUAL_KEYWORD";
            case 5967:
                return "INTERACTION_ACTIVITY_FEED_CONTAINER";
            case 6011:
                return "INTERACTION_QUICK_SNAP_CONSUMPTION_VIEWER";
            case 6037:
                return "INTERACTION_FEED_SAVED_COLLECTIONS";
            case 6118:
                return "INTERACTION_PHOTO_FILTER";
            case 6291:
                return "INTERACTION_SAVE_TO_COLLECTIONS_VIEW_CONTROLLER";
            case 6326:
                return "INTERACTION_PROFILE";
            case 6414:
                return "INTERACTION_STORIES_PRECAPTURE_CAMERA";
            case 6424:
                return "INTERACTION_DIRECT_STORY_AUDIENCE_PICKER";
            case 6461:
                return "INTERACTION_DIRECT_THREAD";
            case 6591:
                return "INTERACTION_REEL_MULTIEDIT_COMPOSER";
            case 6825:
                return "INTERACTION_TEST_BROWSER_VIEW_CONTROLLER";
            case 6837:
                return "INTERACTION_STORY_STICKERS_TRAY";
            case 6896:
                return "INTERACTION_CLIPS_PROFILE";
            case 6956:
                return "INTERACTION_REEL_VIEWER_SETTINGS";
            case 6994:
                return "INTERACTION_TEST_REEL_MULTIEDIT_COMPOSER";
            case 7002:
                return "INTERACTION_QUICK_SNAP_CAMERA";
            case 7067:
                return "INTERACTION_ANYTIME_MENTION_SEARCH_SHEET";
            case 7078:
                return "INTERACTION_COM_BLOKS_WWW_CAA_LOGIN_LOGIN_HOMEPAGE";
            case 7209:
                return "INTERACTION_MUSIC_OVERLAY_DETAIL";
            case 7394:
                return "INTERACTION_COM_BLOKS_WWW_BLOKS_IG_NDX_LS_ENTRY_SCREEN";
            case 7474:
                return "INTERACTION_IG_CREATION_GENAI_RESTYLE";
            case 7478:
                return "INTERACTION_REEL_PROMPT_SHARE_FRAGMENT";
            case 7568:
                return "INTERACTION_DIRECT_RESHARE_SHEET";
            case 7587:
                return "INTERACTION_AUDIO_BROWSER_TABBED_SEARCH_RESULTS_VC";
            case 7623:
                return "INTERACTION_COM_BLOKS_WWW_BLOKS_BROWSER_HISTORY_MAIN_SCREEN";
            case 7738:
                return "INTERACTION_MUSIC_NOTES_EDITOR_SHEET";
            case 7766:
                return "INTERACTION_STORY_EXTENDED_GALLERY";
            case 7791:
                return "INTERACTION_DISCOVER_PEOPLE";
            case 8085:
                return "INTERACTION_DIRECT_STICKER_TAB_TRAY_FRAGMENT";
            case 8089:
                return "INTERACTION_TAGS_LIST";
            case 8109:
                return "INTERACTION_TEST_FEED_TIMELINE";
            case 8200:
                return "INTERACTION_FEED_POST_STICKER";
            case 8266:
                return "INTERACTION_CLIPS_VIEWER_FEED_TIMELINE";
            case 8290:
                return "INTERACTION_MEDIA_VIEW";
            case 8352:
                return "INTERACTION_CLIPS_VIEWER_CLIPS_NETEGO";
            case 8384:
                return "INTERACTION_ACTION_LIST_VIEW_CONTROLLER";
            case 8411:
                return "INTERACTION_ACCOUNT_SWITCHER_SCREEN";
            case 8426:
                return "INTERACTION_FEED_CONTEXTUAL_PROFILE";
            case 8429:
                return "INTERACTION_DIRECT_FORWARDING_SHEET";
            case 8587:
                return "INTERACTION_REELS_CAMERA_SETTINGS";
            case 8597:
                return "INTERACTION_SERP";
            case 8608:
                return "INTERACTION_FOLLOW_FROM_OTHER_ACCOUNTS_FRAGMENT";
            case 8647:
                return "INTERACTION_QUICK_SNAP_IMMERSIVE_VIEWER";
            case 8649:
                return "INTERACTION_COM_BLOKS_WWW_IG_DIRECT_PRO_P2B_PRIVACY_DISCLOSURE";
            case 8668:
                return "INTERACTION_COM_BLOKS_WWW_FXCAL_SETTINGS_NAVIGATION";
            case 8684:
                return "INTERACTION_MEDIA_BROADCAST_SHARE";
            case 8686:
                return "INTERACTION_FRIEND_MAP_UPDATES_BOTTOM_SHEET_FRAGMENT";
            case 8709:
                return "INTERACTION_BLEND_FRAGMENT";
            case 8720:
                return "INTERACTION_CLIPS_VIEWER_EXPLORE_POPULAR_DEFAULT_UNIT";
            case 8898:
                return "INTERACTION_SAVED_AUDIO_LIST";
            case 8935:
                return "INTERACTION_AUDIO_BROWSER_TABBED_VC";
            case 8945:
                return "INTERACTION_FEED_TIMELINE_FOLLOWING";
            case 8957:
                return "INTERACTION_SINGLE_FEED";
            case 9123:
                return "INTERACTION_DIRECT_THREAD_SHARED_LINKS";
            case 9160:
                return "INTERACTION_CUTOUT_STICKER_CONTROLLER";
            case 9210:
                return "INTERACTION_BROWSER_VIEW_CONTROLLER";
            case 9221:
                return "INTERACTION_REEL_PROMPT_TEMPLATE_SHARE";
            case 9254:
                return "INTERACTION_CLIPS_VIEWER_CLIPS_BLEND";
            case 9313:
                return "INTERACTION_REPOSTS_SUBTAB";
            case 9384:
                return "INTERACTION_REEL_COMPOSER_CAMERA";
            case 9411:
                return "INTERACTION_TEST_CLIPS_VIEWER_CLIPS_TAB";
            case 9424:
                return "INTERACTION_SINGLE_FEED_DIRECT_XMA_MEDIA_SHARE";
            case 9474:
                return "INTERACTION_EDIT_PROFILE";
            case 9536:
                return "INTERACTION_NOTE_SELF_NOTE_BOTTOM_SHEET";
            case 9734:
                return "INTERACTION_TEST_STORY_EXTENDED_GALLERY";
            case 9802:
                return "INTERACTION_DIRECT_REPLY_TO_AUTHOR";
            case 9840:
                return "INTERACTION_FOLLOW_REQUESTS";
            case 9909:
                return "INTERACTION_STORIES_VIEWER";
            case 9970:
                return "INTERACTION_WEB_VIEW";
            case 10029:
                return "INTERACTION_DIRECT_THREAD_SHARED_MEDIA";
            case 10060:
                return "INTERACTION_STORIES_GALLERY";
            case 10072:
                return "INTERACTION_ARCHIVE_QUICK_SNAP_FRAGMENT";
            case 10087:
                return "INTERACTION_STORY_STICKER_GALLERY";
            case 10096:
                return "INTERACTION_FOLLOWING_SHEET";
            case 10278:
                return "INTERACTION_DIRECT_STORY_VIEWER_FRAGMENT";
            case 10303:
                return "INTERACTION_TEST_STORIES_VIEWER";
            case 10308:
                return "INTERACTION_REEL_CLPS_RESHARE_FRAGMENT";
            case 10364:
                return "INTERACTION_STORY_VIEWER_REACTION_OVERLAY";
            case 10372:
                return "INTERACTION_USER_LIST_GROUP_LEAST_INTERACTED_WITH";
            case 10402:
                return "INTERACTION_PENDING_INBOX";
            case 10430:
                return "INTERACTION_DIRECT_SUNDIAL_FEED";
            case 10467:
                return "INTERACTION_ARCHIVE_FEED";
            case 10482:
                return "INTERACTION_ARCHIVE_STORIES_TAB";
            case 10487:
                return "INTERACTION_RAGESHAKE_BOTTOM_SHEET";
            case 10488:
                return "INTERACTION_FRIENDS";
            case 10543:
                return "INTERACTION_QUICK_SNAP_VIEWER";
            case 10623:
                return "INTERACTION_IN_APP_BROWSER_V2";
            case 10663:
                return "INTERACTION_SELF_LIKERS";
            case 10696:
                return "INTERACTION_FEED_GALLERY";
            case 10753:
                return "INTERACTION_LINK_STICKER_CREATION";
            case 10832:
                return "INTERACTION_SELF_COMMENTS_V2";
            case 10935:
                return "INTERACTION_QUICK_SNAP_ARCHIVE";
            case 10945:
                return "INTERACTION_GALLERY_PICKER";
            case 11153:
                return "INTERACTION_QUICK_EDIT_FRAGMENT";
            case 11155:
                return "INTERACTION_AUDIO_PAGE";
            case 11167:
                return "INTERACTION_FEED_CONTEXTUAL_MAP";
            case 11206:
                return "INTERACTION_DIRECT_MESSAGE_ACTIONS_VIEW_CONTROLLER";
            case 11254:
                return "INTERACTION_MESSAGES";
            case 11255:
                return "INTERACTION_DIRECT_SEARCH_INBOX_FRAGMENT";
            case 11432:
                return "INTERACTION_CLIPS_MUSIC_EDITOR";
            case 11433:
                return "INTERACTION_AUDIO_BROWSER_V2_SAVED";
            case 11441:
                return "INTERACTION_FEED_TIMELINE_OLDER";
            case 11456:
                return "INTERACTION_TABBED_GALLERY_CAMERA";
            case 11483:
                return "INTERACTION_MSH_SHOTS_DETAIL";
            case 11491:
                return "INTERACTION_LIVE_PRECAPTURE_CAMERA";
            case 11547:
                return "INTERACTION_STORIES_POSTCAPTURE_CAMERA";
            case 11610:
                return "INTERACTION_DIRECT_GALLERY";
            case 11625:
                return "INTERACTION_SELF_PROFILE";
            case 11676:
                return "INTERACTION_IG_FRIENDS_MAP";
            case 11690:
                return "INTERACTION_SUBSCRIBED_CREATOR_LIST_FRAGMENT";
            case 11719:
                return "INTERACTION_QUICK_SNAP_ARCHIVE_DETAIL";
            case 11750:
                return "INTERACTION_QUICKSNAP_PRECAPTURE_CAMERA";
            case 11804:
                return "INTERACTION_IG_PUBLISH_SCREEN_CAROUSEL_CAPTION";
            case 11893:
                return "INTERACTION_DISCOVERY_MAP";
            case 11894:
                return "INTERACTION_SELF_FOLLOWING";
            case 11961:
                return "INTERACTION_FEED_SHORT_URL";
            case 12096:
                return "INTERACTION_THREAD_DETAIL_HOME_PAGE_FRAGMENT";
            case 12326:
                return "INTERACTION_SINGLE_FEED_ARCHIVE_FEED";
            case 12332:
                return "INTERACTION_AUDIO_BROWSER_V2_FOR_YOU";
            case 12528:
                return "INTERACTION_AUTOFILL_BLOKS_CONTACT_SOFT_KEYBOARD_FRAGMENT";
            case 12868:
                return "INTERACTION_NEWSFEED_YOU";
            case 12871:
                return "INTERACTION_DIRECT_AGGREGATED_MEDIA_VIEWER";
            case 12900:
                return "INTERACTION_MUTUAL_FULL_LIST";
            case 12957:
                return "INTERACTION_COLLABORATOR_SEARCH";
            case 12996:
                return "INTERACTION_PEEK_MEDIA";
            case 13146:
                return "INTERACTION_DIRECT_NOTES_COMPOSER";
            case 13211:
                return "INTERACTION_SELF_CLIPS_PROFILE";
            case 13225:
                return "INTERACTION_COM_INSTAGRAM_INSIGHTS_MEDIA_REFRESH_CLIPS_CORE";
            case 13292:
                return "INTERACTION_MULTI_BLOCK_BOTTOM_SHEET";
            case 13324:
                return "INTERACTION_EFFECT_LICENSING";
            case 13466:
                return "INTERACTION_REEL_HIGHLIGHTS_GALLERY";
            case 13501:
                return "INTERACTION_THREAD_DETAILS_NICKNAME_CHANGE_FRAGMENT";
            case 13503:
                return "INTERACTION_USER_LIST_GROUP_CREATORS_AND_BUSINESSES";
            case 13558:
                return "INTERACTION_THREAD_THEME_PICKER";
            case 13569:
                return "INTERACTION_CAMERA_NAV";
            case 13575:
                return "INTERACTION_DIRECT_REACTIONS_PICKER_FRAGMENT";
            case 13612:
                return "INTERACTION_COM_BLOKS_WWW_FX_SETTINGS_SECURITY_CHANGE_PASSWORD";
            case 13709:
                return "INTERACTION_SINGLE_FEED_NOTIFICATION";
            case 13777:
                return "INTERACTION_DIRECT_SAVE_TO_COLLECTION";
            case 13822:
                return "INTERACTION_QUICK_SNAP_IMMERSIVE_VIEWER_CONSUMPTION_VC";
            case 13861:
                return "IG_APP_USER_INTERACTION_FLOWS_INTERACTION";
            case 13887:
                return "INTERACTION_LEAD_AD_QUESTION_PAGE";
            case 13890:
                return "INTERACTION_STORY_TEMPLATE_DISCOVERY_SURFACE";
            case 13928:
                return "INTERACTION_CLIPS_VIEWER_CLIPS_PROFILE";
            case 14025:
                return "INTERACTION_CAROUSEL_GALLERY";
            case 14058:
                return "INTERACTION_EDIT_PROFILE_PICTURE_BOTTOM_SHEET";
            case 14097:
                return "INTERACTION_PRESET_BROWSER_ANALYTICS";
            case 14126:
                return "INTERACTION_CLIPS_VIEWER";
            case 14136:
                return "INTERACTION_SUNDIAL_STACKED_TIMELINE_VC";
            case 14268:
                return "INTERACTION_LOCATION_PICKER";
            case 14285:
                return "INTERACTION_CLIPS_POSTCAPTURE_CAMERA";
            case 14394:
                return "INTERACTION_FRIENDING_CENTER";
            case 14461:
                return "INTERACTION_DIRECT_PRECAPTURE_CAMERA";
            case 14614:
                return "INTERACTION_UGC_AGENT_THREAD";
            case 14646:
                return "INTERACTION_VIDEO_VIEW_COUNT_USER_LIST";
            case 14673:
                return "INTERACTION_AI_EDIT_FRAGMENT";
            case 14683:
                return "INTERACTION_DIRECT_AVATAR_STICKER_PICKER_GRID";
            case 14732:
                return "INTERACTION_DAILY_LIMIT";
            case 14735:
                return "INTERACTION_IG_CAMERA_MINI_GALLERY_CATEGORY_PAGE";
            case 14778:
                return "INTERACTION_REEL_FEED_TIMELINE";
            case 14929:
                return "INTERACTION_TEST_SERP_TOP";
            case 14933:
                return "INTERACTION_DISCOVERY_MAP_LOCATION_DETAIL_GRID";
            case 14967:
                return "INTERACTION_EFFECT_PAGE";
            case 14997:
                return "INTERACTION_TEXT_COMPOSER_FRAGMENT";
            case 15079:
                return "INTERACTION_MUSIC_SEARCH";
            case 15103:
                return "INTERACTION_CALENDAR_ARCHIVE";
            case 15125:
                return "INTERACTION_DIRECT_LIVE_LOCATION_MAP_FRAGMENT";
            case 15222:
                return "INTERACTION_STORY_EMOJI_PICKER";
            case 15246:
                return "INTERACTION_REEL_DASHBOARD";
            case 15319:
                return "INTERACTION_DIRECT_MEDIA_PICKER_PHOTOS_FRAGMENT";
            case 15349:
                return "INTERACTION_NOTE_QUICK_REPLY_SHEET";
            case 15368:
                return "INTERACTION_MUSIC_BROWSER_HOME_FRAGMENT";
            case 15418:
                return "INTERACTION_DIRECT_GIF";
            case 15462:
                return "INTERACTION_TEST_CLIPS_VIEWER";
            case 15473:
                return "INTERACTION_SUNDIAL_MUSIC_BROWSER";
            case 15490:
                return "INTERACTION_FEED_CONTEXTUAL";
            case 15541:
                return "INTERACTION_VIDEO_CALL";
            case 15545:
                return "INTERACTION_CLIPS_SHARE_SHEET";
            case 15614:
                return "INTERACTION_FEED_CONTEXTUAL_SELF_PROFILE";
            case 15635:
                return "INTERACTION_DIRECT_QUICK_REPLY_FRAGMENT";
            case 15890:
                return "INTERACTION_TEST_COMMENTS_V2";
            case 15981:
                return "INTERACTION_PROFILE_PICTURE_PREVIEW";
            case 15983:
                return "INTERACTION_NOTES_CREATION_SHEET";
            case 16297:
                return "INTERACTION_TEST_PROFILE";
            case 16301:
                return "INTERACTION_DIRECT_THREAD_GALLERY";
            case 16329:
                return "INTERACTION_FEED_TIMELINE";
            case 16343:
                return "INTERACTION_THREAD_DETAILS_PRIVACY_AND_SAFETY_FRAGMENT";
            default:
                return "UNDEFINED_QPL_EVENT";
        }
    }
}
