package X;

import java.util.Arrays;
import java.util.Collections;

/* JADX INFO: loaded from: classes12.dex */
public abstract class PN2 {
    public static final AnonymousClass017 A00;

    static {
        AnonymousClass017 anonymousClass017 = new AnonymousClass017(59);
        A00 = anonymousClass017;
        String[] strArr = new String[2];
        strArr[0] = "ZA";
        anonymousClass017.put("af", MJm.A0t("NA", strArr, 1));
        String[] strArr2 = new String[4];
        strArr2[0] = "EG";
        strArr2[1] = "SA";
        strArr2[2] = "SY";
        anonymousClass017.put("ar", MJm.A0t("IQ", strArr2, 3));
        String[] strArr3 = new String[5];
        strArr3[0] = "AL";
        strArr3[1] = "XK";
        strArr3[2] = "GR";
        strArr3[3] = "MK";
        anonymousClass017.put("sq", MJm.A0t("IT", strArr3, 4));
        anonymousClass017.put("az", Collections.singletonList("AZ"));
        String[] strArr4 = new String[2];
        strArr4[0] = "IN";
        anonymousClass017.put("bn", MJm.A0t("BD", strArr4, 1));
        anonymousClass017.put("bg", Collections.singletonList("BG"));
        String[] strArr5 = new String[2];
        strArr5[0] = "ES";
        anonymousClass017.put("ca", MJm.A0t("AD", strArr5, 1));
        String[] strArr6 = new String[4];
        strArr6[0] = "MY";
        strArr6[1] = "SG";
        strArr6[2] = "CN";
        anonymousClass017.put("zh-Hans", MJm.A0t("HK", strArr6, 3));
        String[] strArr7 = new String[4];
        strArr7[0] = "HK";
        strArr7[1] = "TW";
        strArr7[2] = "MY";
        anonymousClass017.put("zh-Hant", MJm.A0t("MO", strArr7, 3));
        String[] strArr8 = new String[2];
        strArr8[0] = "HR";
        anonymousClass017.put("hr", MJm.A0t("BA", strArr8, 1));
        anonymousClass017.put("cs", Collections.singletonList("CZ"));
        anonymousClass017.put("da", Collections.singletonList("DK"));
        String[] strArr9 = new String[3];
        strArr9[0] = "NL";
        strArr9[1] = "BE";
        anonymousClass017.put("nl", MJm.A0t("SR", strArr9, 2));
        String[] strArr10 = new String[5];
        strArr10[0] = "IN";
        strArr10[1] = "PK";
        strArr10[2] = "ZA";
        strArr10[3] = "GB";
        anonymousClass017.put("en", MJm.A0t("US", strArr10, 4));
        anonymousClass017.put("et", Collections.singletonList("EE"));
        anonymousClass017.put("fil", Collections.singletonList("PH"));
        anonymousClass017.put("fi", Collections.singletonList("FI"));
        anonymousClass017.put("fr", Collections.singletonList("FR"));
        String[] strArr11 = new String[3];
        strArr11[0] = "DE";
        strArr11[1] = "AT";
        anonymousClass017.put("de", MJm.A0t("CH", strArr11, 2));
        String[] strArr12 = new String[2];
        strArr12[0] = "GR";
        anonymousClass017.put("el", MJm.A0t("CY", strArr12, 1));
        A00(anonymousClass017, "IN", "gu");
        anonymousClass017.put("he", Collections.singletonList("IL"));
        A00(anonymousClass017, "IN", "hi");
        String[] strArr13 = new String[2];
        strArr13[0] = "HU";
        anonymousClass017.put("hu", MJm.A0t("RO", strArr13, 1));
        anonymousClass017.put("id", Collections.singletonList("ID"));
        String[] strArr14 = new String[2];
        strArr14[0] = "IE";
        anonymousClass017.put("ga", MJm.A0t("GB", strArr14, 1));
        anonymousClass017.put("it", Arrays.asList(AbstractC81763lf.A1b("IT", "CH", 2, 1)));
        anonymousClass017.put("ja", Collections.singletonList("JP"));
        A00(anonymousClass017, "IN", "kn");
        String[] strArr15 = new String[3];
        strArr15[0] = "KZ";
        strArr15[1] = "UZ";
        anonymousClass017.put("kk", MJm.A0t("MN", strArr15, 2));
        anonymousClass017.put("ko", Collections.singletonList("KR"));
        anonymousClass017.put("lo", Collections.singletonList("LA"));
        anonymousClass017.put("lv", Collections.singletonList("LV"));
        anonymousClass017.put("lt", Collections.singletonList("LT"));
        A00(anonymousClass017, "MK", "mk");
        A00(anonymousClass017, "MY", "ms");
        A00(anonymousClass017, "IN", "ml");
        A00(anonymousClass017, "IN", "mr");
        anonymousClass017.put("nb", Collections.singletonList("NO"));
        String[] strArr16 = new String[2];
        strArr16[0] = "IR";
        anonymousClass017.put("fa", MJm.A0t("AF", strArr16, 1));
        anonymousClass017.put("pl", Collections.singletonList("PL"));
        anonymousClass017.put("pt-BR", Collections.singletonList("BR"));
        String[] strArr17 = new String[4];
        strArr17[0] = "PT";
        strArr17[1] = "AO";
        strArr17[2] = "BR";
        anonymousClass017.put("pt-PT", MJm.A0t("MZ", strArr17, 3));
        A00(anonymousClass017, "IN", "pa");
        String[] strArr18 = new String[2];
        strArr18[0] = "RO";
        anonymousClass017.put("ro", MJm.A0t("MD", strArr18, 1));
        String[] strArr19 = new String[4];
        strArr19[0] = "RU";
        strArr19[1] = "KZ";
        strArr19[2] = "KG";
        anonymousClass017.put("ru", MJm.A0t("UA", strArr19, 3));
        String[] strArr20 = new String[3];
        strArr20[0] = "RS";
        strArr20[1] = "BA";
        anonymousClass017.put("sr", MJm.A0t("ME", strArr20, 2));
        anonymousClass017.put("sk", Collections.singletonList("SK"));
        anonymousClass017.put("sl", Collections.singletonList("SI"));
        String[] strArr21 = new String[6];
        strArr21[0] = "MX";
        strArr21[1] = "AR";
        strArr21[2] = "CL";
        strArr21[3] = "CO";
        strArr21[4] = "ES";
        anonymousClass017.put("es", MJm.A0t("PE", strArr21, 5));
        String[] strArr22 = new String[4];
        strArr22[0] = "TZ";
        strArr22[1] = "KE";
        strArr22[2] = "RW";
        anonymousClass017.put("sw", MJm.A0t("BI", strArr22, 3));
        String[] strArr23 = new String[2];
        strArr23[0] = "SE";
        anonymousClass017.put("sv", MJm.A0t("FI", strArr23, 1));
        String[] strArr24 = new String[4];
        strArr24[0] = "IN";
        strArr24[1] = "LK";
        strArr24[2] = "MY";
        anonymousClass017.put("ta", MJm.A0t("SG", strArr24, 3));
        A00(anonymousClass017, "IN", "te");
        String[] strArr25 = new String[2];
        strArr25[0] = "TH";
        anonymousClass017.put("th", MJm.A0t("LA", strArr25, 1));
        anonymousClass017.put("tr", Collections.singletonList("TR"));
        anonymousClass017.put("uk", Collections.singletonList("UA"));
        anonymousClass017.put("ur", Arrays.asList(AbstractC81763lf.A1b("PK", "IN", 2, 1)));
        String[] strArrA1b = AbstractC81763lf.A1b("UZ", "RU", 4, 1);
        strArrA1b[2] = "KZ";
        anonymousClass017.put("uz", MJm.A0t("KG", strArrA1b, 3));
        anonymousClass017.put("vi", Collections.singletonList("VN"));
    }

    public static void A00(AnonymousClass016 anonymousClass016, Object obj, Object obj2) {
        anonymousClass016.put(obj2, Collections.singletonList(obj));
    }
}
