package X;

import com.meta.wearable.warp.core.api.transport.socket.SocketClientTransport;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

/* JADX INFO: loaded from: classes12.dex */
public abstract class PNO {
    public static final GVO A00;
    public static final GVO A01;
    public static final GVO A02;
    public static final GVO A03;
    public static final GVO A04;
    public static final GVO A05;
    public static final GVO A06;
    public static final GVO A07;
    public static final GVO A08;
    public static final GVO A09;
    public static final GVO A0A;
    public static final GVO A0B;
    public static final GVO A0C;
    public static final GVO A0D;
    public static final GVO A0E;
    public static final GVO A0F;
    public static final GVO A0G;
    public static final GVO A0H;
    public static final GVO A0I;
    public static final GVO A0J;
    public static final GVO A0K;
    public static final GVO A0L;
    public static final GVO A0M;
    public static final GVO A0N;
    public static final GVO A0O;
    public static final GVO A0P;
    public static final GVO A0Q;
    public static final GVO A0R;
    public static final GVO A0S;
    public static final GVO A0T;
    public static final GVO A0U;
    public static final GVO A0V;
    public static final GVO A0W;
    public static final GVO A0X;
    public static final GVO A0Y;
    public static final GVO A0Z;
    public static final GVO A0a;
    public static final GVO A0b;
    public static final GVO A0c;
    public static final GVO A0d;
    public static final GVO A0e;
    public static final GVO A0f;
    public static final GVO A0g;
    public static final GVO A0h;
    public static final GVO A0i;
    public static final GVO A0j;
    public static final GVO A0k;
    public static final GVO A0l;
    public static final GVO A0m;
    public static final GVO A0n;
    public static final GVO A0o;
    public static final GVO A0p;
    public static final GVO A0q;
    public static final GVO A0r;
    public static final GVO A0s;
    public static final GVO A0t;
    public static final GVO A0u;
    public static final GVO A0v;
    public static final GVO A0w;
    public static final GVO A0x;
    public static final GVO A0y;
    public static final GVO A0z;
    public static final GVO A10;
    public static final GVO A11;
    public static final GVO A12;
    public static final GVO A13;
    public static final GVO A14;
    public static final GVO A15;
    public static final GVO A16;
    public static final GVO A17;
    public static final GVO A18;
    public static final GVO A19;
    public static final GVO A1A;
    public static final GVO A1B;
    public static final GVO A1C;
    public static final GVO A1D;
    public static final GVO A1E;
    public static final GVO A1F;
    public static final GVO A1G;
    public static final GVO A1H;
    public static final GVO A1I;
    public static final GVO A1J;
    public static final GVO A1K;
    public static final GVO A1L;
    public static final GVO A1M;
    public static final GVO A1N;
    public static final GVO A1O;
    public static final GVO A1P;
    public static final GVO A1Q;
    public static final GVO A1R;
    public static final GVO A1S;
    public static final GVO A1T;
    public static final GVO A1U;
    public static final GVO A1V;
    public static final GVO A1W;
    public static final GVO A1X;
    public static final GVO A1Y;
    public static final GVO A1Z;
    public static final GVO A1a;
    public static final GVO A1b;
    public static final GVO A1c;
    public static final GVO A1d;
    public static final GVO A1e;
    public static final GVO A1f;
    public static final GVO A1g;
    public static final GVO A1h;
    public static final GVO A1i;
    public static final GVO A1j;
    public static final GVO A1k;
    public static final GVO A1l;
    public static final GVO A1m;
    public static final GVO A1n;
    public static final GVO A1o;
    public static final GVO A1p;
    public static final GVO A1q;
    public static final GVO A1r;
    public static final GVO A1s;
    public static final GVO A1t;
    public static final GVO A1u;
    public static final GVO A1v;
    public static final GVO A1w;
    public static final GVO A1x;
    public static final GVO A1y;
    public static final GVO A1z;
    public static final GVO A20;
    public static final GVO A21;
    public static final GVO A22;
    public static final GVO A23;
    public static final GVO A24;
    public static final GVO A25;
    public static final GVO A26;
    public static final GVO A27;
    public static final GVO A28;
    public static final GVO A29;
    public static final GVO A2A;
    public static final GVO A2B;
    public static final GVO A2C;
    public static final GVO A2D;
    public static final GVO A2E;
    public static final GVO A2F;
    public static final GVO A2G;
    public static final GVO A2H;
    public static final GVO A2I;
    public static final GVO A2J;
    public static final GVO A2K;
    public static final GVO A2L;
    public static final GVO A2M;
    public static final GVO A2N;
    public static final GVO A2O;
    public static final GVO A2P;
    public static final GVO A2Q;
    public static final GVO A2R;
    public static final GVO A2S;
    public static final GVO A2T;
    public static final GVO A2U;
    public static final GVO A2V;
    public static final GVO A2W;
    public static final GVO A2X;
    public static final GVO A2Y;
    public static final GVO A2Z;
    public static final GVO A2a;
    public static final GVO A2b;
    public static final GVO A2c;
    public static final GVO A2d;
    public static final GVO A2e;
    public static final GVO A2f;
    public static final GVO A2g;
    public static final GVO A2h;
    public static final GVO A2i;
    public static final GVO A2j;
    public static final GVO A2k;
    public static final GVO A2l;
    public static final GVO A2m;
    public static final GVO A2n;
    public static final GVO A2o;
    public static final GVO A2p;
    public static final GVO A2q;
    public static final GVO A2r;
    public static final GVO A2s;
    public static final GVO A2t;
    public static final GVO A2u;
    public static final GVO A2v;
    public static final GVO A2w;
    public static final GVO A2x;
    public static final GVO A2y;
    public static final GVO A2z;
    public static final GVO A30;
    public static final GVO A31;
    public static final GVO A32;
    public static final GVO A33;
    public static final GVO A34;
    public static final GVO A35;
    public static final GVO A36;
    public static final GVO A37;
    public static final GVO A38;
    public static final GVO A39;
    public static final GVO A3A;
    public static final GVO A3B;
    public static final GVO A3C;
    public static final GVO A3D;
    public static final GVO A3E;
    public static final GVO A3F;
    public static final GVO A3G;
    public static final GVO A3H;
    public static final GVO A3I;
    public static final GVO A3J;
    public static final GVO A3K;
    public static final GVO A3L;
    public static final GVO A3M;
    public static final GVO A3N;
    public static final GVO A3O;
    public static final GVO A3P;
    public static final GVO A3Q;
    public static final GVO A3R;
    public static final GVO A3S;
    public static final GVO A3T;
    public static final GVO A3U;
    public static final GVO A3V;
    public static final GVO A3W;
    public static final GVO A3X;
    public static final GVO A3Y;
    public static final GVO A3Z;
    public static final GVO A3a;
    public static final GVO A3b;
    public static final GVO A3c;
    public static final GVO A3d;
    public static final GVO A3e;
    public static final GVO A3f;
    public static final GVO A3g;
    public static final GVO A3h;
    public static final GVO A3i;
    public static final GVO A3j;
    public static final GVO A3k;
    public static final GVO A3l;
    public static final GVO A3m;
    public static final GVO A3n;
    public static final GVO A3o;
    public static final GVO A3p;
    public static final GVO A3q;
    public static final GVO A3r;
    public static final GVO A3s;
    public static final GVO A3t;
    public static final GVO A3u;
    public static final GVO A3v;
    public static final GVO A3w;
    public static final GVO A3x;
    public static final GVO A3y;
    public static final GVO A3z;
    public static final GVO A40;
    public static final GVO A41;
    public static final GVO A42;
    public static final GVO A43;
    public static final GVO A44;
    public static final GVO A45;
    public static final GVO A46;
    public static final GVO A47;
    public static final GVO A48;
    public static final GVO A49;
    public static final GVO A4A;
    public static final GVO A4B;
    public static final GVO A4C;
    public static final GVO A4D;
    public static final GVO A4E;
    public static final GVO A4F;
    public static final GVO A4G;
    public static final GVO A4H;
    public static final GVO A4I;
    public static final GVO A4J;
    public static final GVO A4K;
    public static final GVO A4L;
    public static final GVO A4M;
    public static final GVO A4N;
    public static final GVO A4O;
    public static final GVO A4P;
    public static final GVO A4Q;
    public static final GVO A4R;
    public static final GVO A4S;
    public static final GVO A4T;
    public static final GVO A4U;
    public static final GVO A4V;
    public static final GVO A4W;
    public static final GVO A4X;
    public static final GVO A4Y;
    public static final GVO A4Z;
    public static final GVO A4a;
    public static final GVO A4b;
    public static final GVO A4c;
    public static final GVO A4d;
    public static final GVO A4e;
    public static final GVO A4f;
    public static final GVO A4g;
    public static final GVO A4h;
    public static final GVO A4i;
    public static final GVO A4j;
    public static final GVO A4k;
    public static final GVO A4l;
    public static final GVO A4m;
    public static final GVO A4n;
    public static final GVO A4o;
    public static final GVO A4p;
    public static final GVO A4q;
    public static final GVO A4r;
    public static final GVO A4s;
    public static final GVO A4t;
    public static final GVO A4u;
    public static final GVO A4v;
    public static final GVO A4w;
    public static final GVO A4x;
    public static final GVO A4y;
    public static final GVO A4z;
    public static final GVO A50;
    public static final GVO A51;
    public static final GVO A52;
    public static final GVO A53;
    public static final GVO A54;
    public static final GVO A55;
    public static final GVO A56;
    public static final GVO A57;
    public static final GVO A58;
    public static final GVO A59;
    public static final GVO A5A;
    public static final GVO A5B;
    public static final GVO A5C;
    public static final GVO A5D;
    public static final GVO A5E;
    public static final GVO A5F;
    public static final GVO A5G;
    public static final GVO A5H;
    public static final GVO A5I;
    public static final GVO A5J;
    public static final GVO A5K;
    public static final GVO A5L;
    public static final GVO A5M;
    public static final GVO A5N;
    public static final GVO A5O;
    public static final GVO A5P;
    public static final GVO A5Q;
    public static final GVO A5R;
    public static final GVO A5S;
    public static final GVO A5T;
    public static final GVO A5U;
    public static final GVO A5V;
    public static final GVO A5W;
    public static final GVO A5X;
    public static final GVO A5Y;
    public static final GVO A5Z;
    public static final GVO A5a;
    public static final GVO A5b;
    public static final GVO A5c;
    public static final GVO A5d;
    public static final GVO A5e;
    public static final GVO A5f;
    public static final GVO A5g;
    public static final GVO A5h;
    public static final GVO A5i;
    public static final GVO A5j;
    public static final GVO A5k;
    public static final GVO A5l;
    public static final GVO A5m;
    public static final GVO A5n;
    public static final GVO A5o;
    public static final GVO A5p;
    public static final GVO A5q;
    public static final GVO A5r;
    public static final GVO A5s;
    public static final GVO A5t;
    public static final GVO A5u;
    public static final GVO A5v;
    public static final GVO A5w;
    public static final GVO A5x;
    public static final GVO A5y;
    public static final GVO A5z;
    public static final GVO A60;
    public static final GVO A61;
    public static final GVO A62;
    public static final GVO A63;
    public static final GVO A64;
    public static final GVO A65;
    public static final GVO A66;
    public static final GVO A67;
    public static final GVO A68;
    public static final GVO A69;
    public static final GVO A6A;
    public static final GVO A6B;
    public static final GVO A6C;
    public static final GVO A6D;
    public static final GVO A6E;
    public static final GVO A6F;
    public static final GVO A6G;
    public static final GVO A6H;
    public static final GVO A6I;
    public static final GVO A6J;
    public static final GVO A6K;
    public static final GVO A6L;
    public static final GVO A6M;
    public static final GVO A6N;
    public static final GVO A6O;
    public static final GVO A6P;
    public static final GVO A6Q;
    public static final GVO A6R;
    public static final GVO A6S;
    public static final GVO A6T;
    public static final GVO A6U;
    public static final GVO A6V;
    public static final GVO A6W;
    public static final GVO A6X;
    public static final GVO A6Y;
    public static final GVO A6Z;
    public static final GVO A6a;
    public static final GVO A6b;
    public static final GVO A6c;
    public static final GVO A6d;
    public static final GVO A6e;
    public static final GVO A6f;
    public static final GVO A6g;
    public static final GVO A6h;
    public static final GVO A6i;
    public static final GVO A6j;
    public static final GVO A6k;
    public static final GVO A6l;
    public static final GVO A6m;
    public static final GVO A6n;
    public static final GVO A6o;
    public static final GVO A6p;
    public static final GVO A6q;
    public static final GVO A6r;
    public static final GVO A6s;
    public static final GVO A6t;
    public static final GVO A6u;
    public static final GVO A6v;
    public static final GVO A6w;
    public static final GVO A6x;
    public static final GVO A6y;
    public static final GVO A6z;
    public static final GVO A70;
    public static final GVO A71;
    public static final GVO A72;
    public static final GVO A73;
    public static final GVO A74;
    public static final GVO A75;
    public static final GVO A76;
    public static final GVO A77;
    public static final GVO A78;
    public static final GVO A79;
    public static final GVO A7A;
    public static final GVO A7B;
    public static final GVO A7C;
    public static final GVO A7D;
    public static final GVO A7E;
    public static final GVO A7F;
    public static final GVO A7G;
    public static final GVO A7H;
    public static final GVO A7I;
    public static final GVO A7J;
    public static final GVO A7K;
    public static final GVO A7L;
    public static final GVO A7M;
    public static final GVO A7N;
    public static final GVO A7O;
    public static final GVO A7P;
    public static final GVO A7Q;
    public static final GVO A7R;
    public static final GVO A7S;
    public static final GVO A7T;
    public static final GVO A7U;
    public static final GVO A7V;
    public static final GVO A7W;
    public static final GVO A7X;
    public static final GVO A7Y;
    public static final GVO A7Z;
    public static final GVO A7a;
    public static final GVO A7b;
    public static final GVO A7c;
    public static final GVO A7d;
    public static final GVO A7e;
    public static final GVO A7f;
    public static final GVO A7g;
    public static final GVO A7h;
    public static final GVO A7i;
    public static final GVO A7j;
    public static final GVO A7k;
    public static final GVO A7l;
    public static final GVO A7m;
    public static final GVO A7n;
    public static final GVO A7o;
    public static final GVO A7p;
    public static final GVO A7q;
    public static final GVO A7r;
    public static final GVO A7s;
    public static final GVO A7t;
    public static final GVO A7u;
    public static final GVO A7v;
    public static final GVO A7w;
    public static final GVO A7x;
    public static final GVO A7y;
    public static final GVO A7z;
    public static final GVO A80;
    public static final GVO A81;
    public static final GVO A82;
    public static final GVO A83;
    public static final GVO A84;
    public static final GVO A85;
    public static final GVO A86;
    public static final GVO A87;
    public static final GVO A88;
    public static final GVO A89;
    public static final GVO A8A;
    public static final GVO A8B;
    public static final GVO A8C;
    public static final GVO A8D;
    public static final GVO A8E;
    public static final GVO A8F;
    public static final GVO A8G;
    public static final GVO A8H;
    public static final GVO A8I;
    public static final GVO A8J;
    public static final GVO A8K;
    public static final GVO A8L;
    public static final GVO A8M;
    public static final GVO A8N;
    public static final GVO A8O;
    public static final GVO A8P;
    public static final GVO A8Q;
    public static final GVO A8R;
    public static final GVO A8S;
    public static final GVO A8T;
    public static final GVO A8U;
    public static final GVO A8V;
    public static final GVO A8W;
    public static final GVO A8X;
    public static final GVO A8Y;
    public static final GVO A8Z;
    public static final GVO A8a;
    public static final GVO A8b;
    public static final GVO A8c;
    public static final GVO A8d;
    public static final GVO A8e;
    public static final GVO A8f;
    public static final GVO A8g;
    public static final GVO A8h;
    public static final GVO A8i;
    public static final GVO A8j;
    public static final GVO A8k;
    public static final GVO A8l;
    public static final GVO A8m;
    public static final GVO A8n;
    public static final GVO A8o;
    public static final GVO A8p;
    public static final GVO A8q;
    public static final GVO A8r;
    public static final GVO A8s;
    public static final GVO A8t;
    public static final GVO A8u;
    public static final GVO A8v;
    public static final GVO A8w;
    public static final GVO A8x;
    public static final GVO A8y;
    public static final GVO A8z;
    public static final GVO A90;
    public static final GVO A91;
    public static final GVO A92;
    public static final GVO A93;
    public static final GVO A94;
    public static final GVO A95;
    public static final GVO A96;
    public static final GVO A97;
    public static final GVO A98;
    public static final GVO A99;
    public static final GVO A9A;
    public static final GVO A9B;
    public static final GVO A9C;
    public static final GVO A9D;
    public static final GVO A9E;
    public static final GVO A9F;
    public static final GVO A9G;
    public static final GVO A9H;
    public static final GVO A9I;
    public static final GVO A9J;
    public static final GVO A9K;
    public static final GVO A9L;
    public static final GVO A9M;
    public static final GVO A9N;
    public static final GVO A9O;
    public static final GVO A9P;
    public static final GVO A9Q;
    public static final GVO A9R;
    public static final GVO A9S;
    public static final GVO A9T;
    public static final GVO A9U;
    public static final GVO A9V;
    public static final GVO A9W;
    public static final GVO A9X;
    public static final GVO A9Y;
    public static final GVO A9Z;
    public static final GVO A9a;
    public static final GVO A9b;
    public static final GVO A9c;
    public static final GVO A9d;
    public static final GVO A9e;
    public static final GVO A9f;
    public static final GVO A9g;
    public static final GVO A9h;
    public static final GVO A9i;
    public static final GVO A9j;
    public static final GVO A9k;
    public static final GVO A9l;
    public static final GVO A9m;
    public static final GVO A9n;
    public static final GVO A9o;
    public static final GVO A9p;
    public static final GVO A9q;
    public static final GVO A9r;
    public static final GVO A9s;
    public static final GVO A9t;
    public static final GVO A9u;
    public static final GVO A9v;
    public static final GVO A9w;
    public static final GVO A9x;
    public static final GVO A9y;
    public static final GVO A9z;
    public static final GVO AA0;
    public static final GVO AA1;
    public static final GVO AA2;
    public static final GVO AA3;
    public static final GVO AA4;
    public static final GVO AA5;
    public static final GVO AA6;
    public static final GVO AA7;
    public static final GVO AA8;
    public static final GVO AA9;
    public static final GVO AAA;
    public static final GVO AAB;
    public static final GVO AAC;
    public static final GVO AAD;
    public static final GVO AAE;
    public static final GVO AAF;
    public static final GVO AAG;
    public static final GVO AAH;
    public static final GVO AAI;
    public static final GVO AAJ;
    public static final GVO AAK;
    public static final GVO AAL;
    public static final GVO AAM;
    public static final GVO AAN;
    public static final GVO AAO;
    public static final GVO AAP;
    public static final GVO AAQ;
    public static final GVO AAR;
    public static final GVO AAS;
    public static final GVO AAT;
    public static final GVO AAU;
    public static final GVO AAV;
    public static final GVO AAW;
    public static final GVO AAX;
    public static final GVO AAY;
    public static final GVO AAZ;
    public static final GVO AAa;
    public static final GVO AAb;
    public static final GVO AAc;
    public static final GVO AAd;
    public static final GVO AAe;
    public static final GVO AAf;
    public static final GVO AAg;
    public static final GVO AAh;
    public static final GVO AAi;
    public static final GVO AAj;
    public static final GVO AAk;
    public static final GVO AAl;
    public static final GVO AAm;
    public static final GVO AAn;
    public static final GVO AAo;
    public static final GVO AAp;
    public static final GVO AAq;
    public static final GVO AAr;
    public static final GVO AAs;
    public static final GVO AAt;
    public static final GVO AAu;
    public static final GVO AAv;
    public static final GVO AAw;
    public static final GVO AAx;
    public static final GVO AAy;
    public static final GVO AAz;
    public static final GVO AB0;
    public static final GVO AB1;
    public static final GVO AB2;
    public static final GVO AB3;
    public static final GVO AB4;
    public static final GVO AB5;
    public static final GVO AB6;
    public static final GVO AB7;
    public static final GVO AB8;
    public static final GVO AB9;
    public static final GVO ABA;
    public static final GVO ABB;
    public static final GVO ABC;
    public static final GVO ABD;
    public static final GVO ABE;
    public static final GVO ABF;
    public static final GVO ABG;
    public static final GVO ABH;
    public static final GVO ABI;
    public static final GVO ABJ;
    public static final GVO ABK;
    public static final GVO ABL;
    public static final GVO ABM;
    public static final GVO ABN;
    public static final GVO ABO;
    public static final GVO ABP;
    public static final GVO ABQ;
    public static final GVO ABR;
    public static final GVO ABS;
    public static final GVO ABT;
    public static final GVO ABU;
    public static final GVO ABV;
    public static final GVO ABW;
    public static final GVO ABX;
    public static final GVO ABY;
    public static final GVO ABZ;
    public static final GVO ABa;
    public static final GVO ABb;
    public static final GVO ABc;
    public static final GVO ABd;
    public static final GVO ABe;
    public static final GVO ABf;
    public static final GVO ABg;
    public static final GVO ABh;
    public static final GVO ABi;
    public static final GVO ABj;
    public static final GVO ABk;
    public static final GVO ABl;
    public static final GVO ABm;
    public static final GVO ABn;
    public static final GVO ABo;
    public static final GVO ABp;
    public static final GVO ABq;
    public static final GVO ABr;
    public static final GVO ABs;
    public static final GVO ABt;
    public static final GVO ABu;
    public static final GVO ABv;
    public static final GVO ABw;
    public static final GVO ABx;
    public static final GVO ABy;
    public static final GVO ABz;
    public static final GVO AC0;
    public static final GVO AC1;
    public static final GVO AC2;
    public static final GVO AC3;
    public static final GVO AC4;
    public static final GVO AC5;
    public static final GVO AC6;
    public static final GVO AC7;
    public static final GVO AC8;
    public static final GVO AC9;
    public static final GVO ACA;
    public static final GVO ACB;
    public static final GVO ACC;
    public static final GVO ACD;
    public static final GVO ACE;
    public static final GVO ACF;
    public static final GVO ACG;
    public static final GVO ACH;
    public static final GVO ACI;
    public static final GVO ACJ;
    public static final GVO ACK;
    public static final GVO ACL;
    public static final GVO ACM;
    public static final GVO ACN;
    public static final GVO ACO;
    public static final GVO ACP;
    public static final GVO ACQ;
    public static final GVO ACR;
    public static final GVO ACS;
    public static final GVO ACT;
    public static final GVO ACU;
    public static final GVO ACV;
    public static final GVO ACW;

    public static GVO A00(List list, Set set) {
        HashMap map = new HashMap();
        HashSet hashSet = new HashSet();
        Iterator it = list.iterator();
        while (it.hasNext()) {
            hashSet.addAll((Collection) it.next());
        }
        Iterator it2 = set.iterator();
        while (it2.hasNext()) {
            map.put(it2.next(), hashSet);
        }
        return new GVO(Collections.unmodifiableMap(map));
    }

    static {
        GVR[] gvrArr = new GVR[2];
        GVR gvr = PDz.A0o;
        gvrArr[0] = gvr;
        GVR gvr2 = PDz.A0p;
        A02 = GVN.A01("com.cfsample.coffeeshop", AbstractC148856g7.A1H(gvr2, gvrArr, 1));
        GVR gvr3 = PDz.A1F;
        A03 = GVN.A01("com.digitalliteracy.app", C08F.A00(gvr3));
        GVR[] gvrArr2 = new GVR[2];
        gvrArr2[0] = PDz.A0d;
        A04 = GVN.A01("com.discoverapp", AbstractC148856g7.A1H(PDz.A0e, gvrArr2, 1));
        GVR[] gvrArr3 = new GVR[2];
        GVR gvr4 = PDz.A0J;
        gvrArr3[0] = gvr4;
        GVR gvr5 = PDz.A0P;
        A05 = GVN.A01("com.dsi.ant.server", AbstractC148856g7.A1H(gvr5, gvrArr3, 1));
        A06 = GVN.A01("com.example.accountkitsample", AbstractC54852PDx.A0O(gvr, gvr2));
        GVR gvr6 = PDz.A0m;
        A30 = GVN.A01("com.facebook.Origami", C08F.A00(gvr6));
        GVR[] gvrArr4 = new GVR[3];
        GVR gvr7 = PDz.A0k;
        gvrArr4[0] = gvr7;
        gvrArr4[1] = gvr6;
        GVR gvr8 = PDz.A23;
        A07 = GVN.A01("com.facebook.adsmanager", AbstractC148856g7.A1H(gvr8, gvrArr4, 2));
        A08 = GVN.A01("com.facebook.adssdk.coffeeshop", C08F.A00(gvr));
        GVR[] gvrArrA0r = AbstractC54852PDx.A0r(gvr, gvr2, 3);
        GVR gvr9 = PDz.A1g;
        A09 = GVN.A01("com.facebook.aidemos", AbstractC148856g7.A1H(gvr9, gvrArrA0r, 2));
        GVR gvr10 = PDz.A08;
        A0A = GVN.A01("com.facebook.aloha", C08F.A00(gvr10));
        A0s = GVN.A01("com.facebook.aloha.app.asyncmessage", C08F.A00(gvr10));
        GVR gvr11 = PDz.A06;
        A0t = GVN.A01("com.facebook.aloha.app.audiodebug", C08F.A00(gvr11));
        A0u = GVN.A01("com.facebook.aloha.app.bdggallery", C08F.A00(gvr11));
        A0v = GVN.A01("com.facebook.aloha.app.bishop.keyboard", C08F.A00(gvr10));
        GVR gvr12 = PDz.A00;
        A0w = GVN.A01("com.facebook.aloha.app.bluetoothreceiver", C08F.A00(gvr12));
        GVR[] gvrArr5 = new GVR[2];
        gvrArr5[0] = gvr12;
        GVR gvr13 = PDz.A01;
        A0x = GVN.A01("com.facebook.aloha.app.butler", AbstractC148856g7.A1H(gvr13, gvrArr5, 1));
        A0y = GVN.A01("com.facebook.aloha.app.calendar", C08F.A00(gvr12));
        A0z = GVN.A01("com.facebook.aloha.app.cameraeditor", C08F.A00(gvr12));
        A10 = GVN.A01("com.facebook.aloha.app.cameraroll", AbstractC54852PDx.A0O(gvr12, gvr10));
        A11 = GVN.A01("com.facebook.aloha.app.communities", C08F.A00(gvr12));
        A12 = GVN.A01("com.facebook.aloha.app.companionservice", C08F.A00(gvr12));
        A13 = GVN.A01("com.facebook.aloha.app.contentreader", C08F.A00(gvr10));
        A14 = GVN.A01("com.facebook.aloha.app.dialservice", C08F.A00(gvr10));
        A15 = GVN.A01("com.facebook.aloha.app.experiencesample", AbstractC54852PDx.A0O(gvr, gvr2));
        A16 = GVN.A01("com.facebook.aloha.app.fbtv", AbstractC54852PDx.A0O(gvr12, gvr10));
        GVR gvr14 = PDz.A02;
        A17 = GVN.A01("com.facebook.aloha.app.fbtv4portal", C08F.A00(gvr14));
        A18 = GVN.A01("com.facebook.aloha.app.horizon", C08F.A00(gvr14));
        A19 = GVN.A01("com.facebook.aloha.app.instagram", C08F.A00(gvr10));
        A1A = GVN.A01("com.facebook.aloha.app.kokua", C08F.A00(gvr12));
        A1B = GVN.A01("com.facebook.aloha.app.live", C08F.A00(gvr10));
        A1C = GVN.A01("com.facebook.aloha.app.messenger", C08F.A00(gvr10));
        A1D = GVN.A01("com.facebook.aloha.app.monitorwarden", C08F.A00(gvr14));
        A1E = GVN.A01("com.facebook.aloha.app.ntidemo", C08F.A00(gvr11));
        A1F = GVN.A01("com.facebook.aloha.app.onboarding", C08F.A00(gvr14));
        A1G = GVN.A01("com.facebook.aloha.app.papaya", C08F.A00(gvr14));
        A1H = GVN.A01("com.facebook.aloha.app.pdsgallery", C08F.A00(gvr11));
        A1I = GVN.A01("com.facebook.aloha.app.photobooth", AbstractC54852PDx.A0O(gvr12, gvr10));
        A1J = GVN.A01("com.facebook.aloha.app.portalboilerroomtestapp2", C08F.A00(gvr11));
        A1K = GVN.A01("com.facebook.aloha.app.portalcatalysisdevapp", C08F.A00(gvr11));
        A1L = GVN.A01("com.facebook.aloha.app.portalcatalysistestapp", C08F.A00(gvr11));
        A1M = GVN.A01("com.facebook.aloha.app.portalfeed", C08F.A00(gvr12));
        A1N = GVN.A01("com.facebook.aloha.app.pxd", C08F.A00(gvr14));
        A1O = GVN.A01("com.facebook.aloha.app.rcbootflow", C08F.A00(gvr12));
        A1P = GVN.A01("com.facebook.aloha.app.referralhome", C08F.A00(gvr14));
        A1Q = GVN.A01("com.facebook.aloha.app.remotecontrol", C08F.A00(gvr13));
        A1R = GVN.A01("com.facebook.aloha.app.ripleycontacts", C08F.A00(gvr10));
        A1S = GVN.A01("com.facebook.aloha.app.shifts", C08F.A00(gvr14));
        A1T = GVN.A01("com.facebook.aloha.app.sip", C08F.A00(gvr14));
        A1U = GVN.A01("com.facebook.aloha.app.stories", C08F.A00(gvr14));
        A1V = GVN.A01("com.facebook.aloha.app.storytime", AbstractC54852PDx.A0O(gvr12, gvr10));
        A1W = GVN.A01("com.facebook.aloha.app.threephome", C08F.A00(gvr12));
        A1X = GVN.A01("com.facebook.aloha.app.ttsservice", C08F.A00(gvr12));
        A1Y = GVN.A01("com.facebook.aloha.app.voiceenrollment", AbstractC54852PDx.A0O(gvr12, gvr10));
        A1Z = GVN.A01("com.facebook.aloha.app.whatsapp", C08F.A00(PDz.A09));
        A1a = GVN.A01("com.facebook.aloha.app.workplacelive", C08F.A00(gvr14));
        A1b = GVN.A01("com.facebook.aloha.app.workrooms", C08F.A00(gvr14));
        A1c = GVN.A01("com.facebook.aloha.app.workrooms_dogfooding", AbstractC54852PDx.A0O(gvr14, gvr10));
        GVR gvr15 = PDz.A04;
        A0r = GVN.A01("com.facebook.aloha.appmanagerprefs", C08F.A00(gvr15));
        A1d = GVN.A01("com.facebook.aloha.assistantmodels", C08F.A00(gvr10));
        A1e = GVN.A01("com.facebook.aloha.calendar", C08F.A00(gvr14));
        A1f = GVN.A01("com.facebook.aloha.googlesync", C08F.A00(gvr12));
        A1g = GVN.A01("com.facebook.aloha.home.touch", C08F.A00(gvr12));
        A1h = GVN.A01("com.facebook.aloha.household", C08F.A00(gvr12));
        A1i = GVN.A01("com.facebook.aloha.location", AbstractC54852PDx.A0O(gvr12, gvr14));
        A1j = GVN.A01("com.facebook.aloha.miyagi", C08F.A00(gvr14));
        A1k = GVN.A01("com.facebook.aloha.mobileconfig", C08F.A00(gvr10));
        A1l = GVN.A01("com.facebook.aloha.munafa", C08F.A00(gvr12));
        A1m = GVN.A01("com.facebook.aloha.o365sync", C08F.A00(gvr12));
        A1n = GVN.A01("com.facebook.aloha.portalboilerroomtestapp", C08F.A00(gvr11));
        A1o = GVN.A01("com.facebook.aloha.push", C08F.A00(gvr10));
        A1p = GVN.A01("com.facebook.aloha.reminder", C08F.A00(gvr14));
        A1q = GVN.A01("com.facebook.aloha.sample.mobileconfigtest", C08F.A00(gvr11));
        A1r = GVN.A01("com.facebook.aloha.sample.portalapprollbacktestapp", C08F.A00(gvr11));
        A1s = GVN.A01("com.facebook.aloha.sample.portalboilerroomtestapp", C08F.A00(gvr11));
        GVR[] gvrArr6 = new GVR[3];
        gvrArr6[0] = PDz.A03;
        A1t = GVN.A01("com.facebook.aloha.sample.sdksamples", AbstractC54852PDx.A0P(gvr, gvr2, gvrArr6, 1, 2));
        A1u = GVN.A01("com.facebook.aloha.sample.skeleton.java.di", AbstractC54852PDx.A0O(gvr, gvr2));
        A1v = GVN.A01("com.facebook.aloha.sample.skeleton.java.nodi", AbstractC54852PDx.A0O(gvr, gvr2));
        A1w = GVN.A01("com.facebook.aloha.sample.skeleton.java.vanilla", AbstractC54852PDx.A0O(gvr, gvr2));
        A1x = GVN.A01("com.facebook.aloha.sample.skeleton.kotlin.di", AbstractC54852PDx.A0O(gvr, gvr2));
        A1y = GVN.A01("com.facebook.aloha.sample.skeleton.kotlin.nodi", AbstractC54852PDx.A0O(gvr, gvr2));
        A1z = GVN.A01("com.facebook.aloha.sample.skeleton.kotlin.vanilla", AbstractC54852PDx.A0O(gvr, gvr2));
        A20 = GVN.A01("com.facebook.aloha.spotifystandalone", C08F.A00(gvr14));
        A21 = GVN.A01("com.facebook.aloha.system.alexammsdkproxy", C08F.A00(gvr10));
        A22 = GVN.A01("com.facebook.aloha.system.camerafeedback", C08F.A00(gvr10));
        A23 = GVN.A01("com.facebook.aloha.system.device", C08F.A00(gvr10));
        A24 = GVN.A01("com.facebook.aloha.system.nativelibs", C08F.A00(gvr10));
        A25 = GVN.A01("com.facebook.aloha.system.rcbootflow", C08F.A00(gvr10));
        A26 = GVN.A01("com.facebook.aloha.system.ripleyhome", C08F.A00(gvr10));
        A27 = GVN.A01("com.facebook.aloha.system.services", C08F.A00(gvr10));
        A28 = GVN.A01("com.facebook.aloha.system.voiceactions", C08F.A00(gvr10));
        A29 = GVN.A01("com.facebook.aloha.system.work", C08F.A00(gvr10));
        A2A = GVN.A01("com.facebook.aloha.websafety", AbstractC54852PDx.A0O(gvr12, gvr10));
        A0B = GVN.A01("com.facebook.alohaappmanager", C08F.A00(gvr15));
        A0C = GVN.A01("com.facebook.alohaappmanagerprefs", C08F.A00(gvr15));
        A0D = GVN.A01("com.facebook.alohaapps.abilitycenter", C08F.A00(gvr10));
        A0E = GVN.A01("com.facebook.alohaapps.abilitydebugger", C08F.A00(gvr10));
        A0F = GVN.A01("com.facebook.alohaapps.abilityhost", C08F.A00(gvr10));
        A0G = GVN.A01("com.facebook.alohaapps.alarms", C08F.A00(gvr10));
        A0H = GVN.A01("com.facebook.alohaapps.bugreporter", C08F.A00(gvr10));
        A0I = GVN.A01("com.facebook.alohaapps.contacts", C08F.A00(gvr10));
        A0J = GVN.A01("com.facebook.alohaapps.controlcenter", C08F.A00(gvr10));
        A0K = GVN.A01("com.facebook.alohaapps.devicesetup", C08F.A00(gvr10));
        A0L = GVN.A01("com.facebook.alohaapps.dogfooding", C08F.A00(gvr10));
        A0M = GVN.A01("com.facebook.alohaapps.launcher", C08F.A00(gvr10));
        A0N = GVN.A01("com.facebook.alohaapps.notificationcenter", C08F.A00(gvr10));
        A0O = GVN.A01("com.facebook.alohaapps.personaluser", C08F.A00(gvr10));
        A0P = GVN.A01("com.facebook.alohaapps.recovery", C08F.A00(gvr10));
        A0Q = GVN.A01("com.facebook.alohaapps.retail", C08F.A00(gvr10));
        A0R = GVN.A01("com.facebook.alohaapps.settings", C08F.A00(gvr10));
        A0S = GVN.A01("com.facebook.alohaapps.superframe", C08F.A00(gvr10));
        A0T = GVN.A01("com.facebook.alohaapps.tutorial", C08F.A00(gvr10));
        A0U = GVN.A01("com.facebook.alohaapps.voice", C08F.A00(gvr10));
        A0V = GVN.A01("com.facebook.alohainstaller", C08F.A00(gvr15));
        A0W = GVN.A01("com.facebook.alohasdk.pushnotification", C08F.A00(gvr10));
        A0X = GVN.A01("com.facebook.alohaservices.abilities.about", C08F.A00(gvr10));
        A0Y = GVN.A01("com.facebook.alohaservices.abilities.albums", C08F.A00(gvr10));
        A0Z = GVN.A01("com.facebook.alohaservices.abilities.fbnews", C08F.A00(gvr10));
        A0a = GVN.A01("com.facebook.alohaservices.abilities.iheart", C08F.A00(gvr10));
        A0b = GVN.A01("com.facebook.alohaservices.abilities.javascript", C08F.A00(gvr10));
        A0c = GVN.A01("com.facebook.alohaservices.abilities.pages", C08F.A00(gvr10));
        A0d = GVN.A01("com.facebook.alohaservices.abilities.pandora", C08F.A00(gvr10));
        A0e = GVN.A01("com.facebook.alohaservices.abilities.radio", C08F.A00(gvr10));
        A0f = GVN.A01("com.facebook.alohaservices.abilities.spotify", C08F.A00(gvr10));
        A0g = GVN.A01("com.facebook.alohaservices.abilitymanager", C08F.A00(gvr10));
        A0h = GVN.A01("com.facebook.alohaservices.alohausers", C08F.A00(gvr10));
        A0i = GVN.A01("com.facebook.alohaservices.deviceadmin", C08F.A00(gvr10));
        A0j = GVN.A01("com.facebook.alohaservices.globalstates", C08F.A00(gvr10));
        A0k = GVN.A01("com.facebook.alohaservices.hotword", C08F.A00(gvr10));
        A0l = GVN.A01("com.facebook.alohaservices.keyboard", C08F.A00(gvr10));
        A0m = GVN.A01("com.facebook.alohaservices.keyguard", C08F.A00(gvr10));
        A0n = GVN.A01("com.facebook.alohaservices.player", C08F.A00(gvr10));
        A0o = GVN.A01("com.facebook.alohaservices.player2", C08F.A00(gvr10));
        A0p = GVN.A01("com.facebook.alohaservices.presence", C08F.A00(gvr10));
        A0q = GVN.A01("com.facebook.alohaworkvc", C08F.A00(gvr14));
        A2B = GVN.A01("com.facebook.apex", AbstractC54852PDx.A0O(gvr, gvr2));
        GVR[] gvrArr7 = new GVR[3];
        gvrArr7[0] = gvr6;
        GVR gvr16 = PDz.A21;
        gvrArr7[1] = gvr16;
        GVR gvr17 = PDz.A22;
        A2C = GVN.A01("com.facebook.appmanager", AbstractC148856g7.A1H(gvr17, gvrArr7, 2));
        GVR[] gvrArr8 = new GVR[3];
        gvrArr8[0] = gvr6;
        A2D = GVN.A01("com.facebook.appmanager.redirect", AbstractC54852PDx.A0P(gvr16, gvr17, gvrArr8, 1, 2));
        GVR gvr18 = PDz.A0z;
        A2E = GVN.A01("com.facebook.ariane", AbstractC54852PDx.A0P(gvr18, gvr8, new GVR[2], 0, 1));
        A2F = GVN.A01("com.facebook.ariane_external", C08F.A00(gvr18));
        GVR[] gvrArr9 = new GVR[2];
        gvrArr9[0] = gvr14;
        GVR gvr19 = PDz.A0i;
        A2G = GVN.A01("com.facebook.arstudio.player", AbstractC148856g7.A1H(gvr19, gvrArr9, 1));
        A2H = GVN.A01("com.facebook.assistantplayground", AbstractC54852PDx.A0O(gvr, gvr2));
        A2I = GVN.A01("com.facebook.aura", C08F.A00(PDz.A12));
        A2J = GVN.A01("com.facebook.biddingkitsample", AbstractC54852PDx.A0O(gvr, gvr2));
        GVR gvr20 = PDz.A24;
        A2K = GVN.A01("com.facebook.bishop", C08F.A00(gvr20));
        GVR gvr21 = PDz.A0l;
        A2L = GVN.A01("com.facebook.clio", C08F.A00(gvr21));
        A2M = GVN.A01("com.facebook.creatorstudio", C08F.A00(gvr19));
        A2N = GVN.A01("com.facebook.deviceinfo", C08F.A00(gvr17));
        A2O = GVN.A01("com.facebook.deviceinfo.redirect", C08F.A00(gvr17));
        A2P = GVN.A01("com.facebook.deviceowner", C08F.A00(gvr17));
        A2Q = GVN.A01("com.facebook.ember", AbstractC54852PDx.A0P(PDz.A0f, gvr6, new GVR[2], 0, 1));
        A2R = GVN.A01("com.facebook.faceclusteringdemo", AbstractC54852PDx.A0O(gvr, gvr2));
        A2S = GVN.A01("com.facebook.familycenter", C08F.A00(gvr21));
        A2T = GVN.A01("com.facebook.fig.app.uitestbed", AbstractC54852PDx.A0O(gvr, gvr2));
        A2U = GVN.A01("com.facebook.flex", C08F.A00(PDz.A0w));
        A2V = GVN.A01("com.facebook.gaming", C08F.A00(PDz.A0u));
        GVR[] gvrArr10 = new GVR[2];
        gvrArr10[0] = gvr6;
        A2W = GVN.A01("com.facebook.gizmo", AbstractC148856g7.A1H(PDz.A11, gvrArr10, 1));
        A2X = GVN.A01("com.facebook.gizmo_internal", C08F.A00(gvr21));
        A2Y = GVN.A01("com.facebook.groups", C08F.A00(gvr7));
        A2Z = GVN.A01("com.facebook.hackbook.internal.current", AbstractC54852PDx.A0O(gvr, gvr2));
        GVR gvr22 = PDz.A1U;
        A2a = GVN.A01("com.facebook.horizon", C08F.A00(gvr22));
        A2b = GVN.A01("com.facebook.ides", C08F.A00(gvr));
        A2c = GVN.A01("com.facebook.idverify.sample", AbstractC54852PDx.A0O(gvr, gvr2));
        A2d = GVN.A01("com.facebook.installshim", C08F.A00(gvr7));
        A2e = GVN.A01("com.facebook.iorg.carrier.toolkit", C08F.A00(gvr3));
        GVR[] gvrArr11 = new GVR[3];
        gvrArr11[0] = gvr7;
        A2f = GVN.A01("com.facebook.katana", AbstractC54852PDx.A0P(gvr6, gvr8, gvrArr11, 1, 2));
        A2g = GVN.A01("com.facebook.keyframes.app", AbstractC54852PDx.A0O(gvr, gvr2));
        A2h = GVN.A01("com.facebook.lite", AbstractC54852PDx.A0O(gvr6, gvr8));
        A2i = GVN.A01("com.facebook.liteqa", AbstractC54852PDx.A0O(gvr, gvr2));
        A2j = GVN.A01("com.facebook.livemaps.lens", AbstractC54852PDx.A0O(gvr, gvr2));
        A2k = GVN.A01("com.facebook.lmwayfinder", AbstractC54852PDx.A0O(gvr, gvr2));
        A2l = GVN.A01("com.facebook.loja", C08F.A00(PDz.A1H));
        A2m = GVN.A01("com.facebook.mappingcompanion", C08F.A00(PDz.A10));
        A2n = GVN.A01("com.facebook.mdmpolicyapp", C08F.A00(gvr4));
        A2o = GVN.A01("com.facebook.mediastreaming.sample.livestreaming", AbstractC54852PDx.A0O(gvr, gvr2));
        A2p = GVN.A01("com.facebook.metadeals", C08F.A00(PDz.A1J));
        A2q = GVN.A01("com.facebook.mlite", C08F.A00(gvr7));
        A2r = GVN.A01("com.facebook.mlite_inhouse", C08F.A00(gvr7));
        A2s = GVN.A01("com.facebook.mobilehome", AbstractC54852PDx.A0O(gvr6, gvr8));
        A2t = GVN.A01("com.facebook.moments", C08F.A00(gvr7));
        A2u = GVN.A01("com.facebook.mptshelper", C08F.A00(gvr17));
        GVR[] gvrArr12 = new GVR[3];
        gvrArr12[0] = gvr;
        A2v = GVN.A01("com.facebook.ocean.app.xrplayground.android", AbstractC54852PDx.A0P(gvr2, gvr8, gvrArr12, 1, 2));
        A2w = GVN.A01("com.facebook.ocean.app.xrplayground.oculus", C08F.A00(gvr9));
        A2x = GVN.A01("com.facebook.onecamera.yuvrecorder", AbstractC54852PDx.A0O(gvr, gvr2));
        GVR[] gvrArr13 = new GVR[3];
        gvrArr13[0] = gvr7;
        A2y = GVN.A01("com.facebook.orca", AbstractC54852PDx.A0P(gvr6, gvr8, gvrArr13, 1, 2));
        A2z = GVN.A01("com.facebook.origami", C08F.A00(gvr21));
        GVR gvr23 = PDz.A16;
        A31 = GVN.A01("com.facebook.origami.wearables", C08F.A00(gvr23));
        GVR[] gvrArr14 = new GVR[3];
        gvrArr14[0] = gvr7;
        A32 = GVN.A01("com.facebook.pages.app", AbstractC54852PDx.A0P(gvr6, gvr8, gvrArr14, 1, 2));
        A33 = GVN.A01("com.facebook.playground.apps.appinitplayground", AbstractC54852PDx.A0O(gvr, gvr2));
        A34 = GVN.A01("com.facebook.playground.apps.barebonesplayground", C08F.A00(gvr));
        A35 = GVN.A01("com.facebook.playground.apps.fb4aplayground", AbstractC54852PDx.A0O(gvr, gvr2));
        A36 = GVN.A01("com.facebook.playground.apps.fdsplayground", AbstractC54852PDx.A0O(gvr, gvr2));
        A37 = GVN.A01("com.facebook.playground.apps.workdsplayground", C08F.A00(gvr8));
        A38 = GVN.A01("com.facebook.portal.aiservice", C08F.A00(gvr10));
        GVR gvr24 = PDz.A07;
        A39 = GVN.A01("com.facebook.portal.sdk", C08F.A00(gvr24));
        A3A = GVN.A01("com.facebook.portal.thirdpartysdk", C08F.A00(gvr24));
        A3B = GVN.A01("com.facebook.portal.webview", C08F.A00(gvr24));
        A3C = GVN.A01("com.facebook.pwc.app", C08F.A00(gvr20));
        A3D = GVN.A01("com.facebook.react.uiapp", C08F.A00(gvr));
        A3E = GVN.A01("com.facebook.red", C08F.A00(gvr19));
        A3F = GVN.A01("com.facebook.rlr.solaris.companion", C08F.A00(gvr21));
        A3G = GVN.A01("com.facebook.rlr.solaris.shell", C08F.A00(gvr21));
        A3I = GVN.A01("com.facebook.samples.AdUnitsSample", C08F.A00(gvr7));
        A3R = GVN.A01("com.facebook.samples.MediationSample", C08F.A00(gvr7));
        A3T = GVN.A01("com.facebook.samples.NativeAdSample", C08F.A00(gvr7));
        A3H = GVN.A01("com.facebook.samples.adbiddingsample", AbstractC54852PDx.A0O(gvr, gvr2));
        A3J = GVN.A01("com.facebook.samples.arcas.helloar", AbstractC54852PDx.A0O(gvr, gvr2));
        A3K = GVN.A01("com.facebook.samples.ariane", AbstractC54852PDx.A0O(gvr, gvr2));
        A3L = GVN.A01("com.facebook.samples.assistantplayground", AbstractC54852PDx.A0O(gvr, gvr2));
        A3M = GVN.A01("com.facebook.samples.compphoto", AbstractC54852PDx.A0O(gvr, gvr2));
        A3N = GVN.A01("com.facebook.samples.cvatapp", AbstractC54852PDx.A0O(gvr, gvr8));
        A3O = GVN.A01("com.facebook.samples.hackvertising", AbstractC54852PDx.A0O(gvr, gvr2));
        A3P = GVN.A01("com.facebook.samples.indoordatarecorder.app", AbstractC54852PDx.A0O(gvr, gvr2));
        A3Q = GVN.A01("com.facebook.samples.litetestapp", AbstractC54852PDx.A0O(gvr, gvr2));
        A3S = GVN.A01("com.facebook.samples.memes", AbstractC54852PDx.A0O(gvr, gvr2));
        A3U = GVN.A01("com.facebook.samples.releasex_e2e_test_app", AbstractC54852PDx.A0O(gvr, gvr8));
        A3V = GVN.A01("com.facebook.samples.releng", C08F.A00(PDz.A26));
        A3W = GVN.A01("com.facebook.samples.releng.bundle.test_rsa_key_md5", C08F.A00(PDz.A2M));
        A3X = GVN.A01("com.facebook.samples.releng.bundle.test_rsa_key_one", C08F.A00(PDz.A2I));
        A3Y = GVN.A01("com.facebook.samples.releng.bundle.test_rsa_key_sha", C08F.A00(PDz.A2N));
        A3Z = GVN.A01("com.facebook.samples.releng.bundle.test_rsa_key_two", C08F.A00(PDz.A2K));
        A3a = GVN.A01("com.facebook.samples.releng_conveyor_android_app", C08F.A00(gvr));
        A3b = GVN.A01("com.facebook.samples.releng_example_android_app", C08F.A00(gvr));
        A3c = GVN.A01("com.facebook.samples.sampleadsapp", AbstractC54852PDx.A0O(gvr, gvr2));
        A3d = GVN.A01("com.facebook.samples.topnews", AbstractC54852PDx.A0O(gvr, gvr2));
        A3e = GVN.A01("com.facebook.samples.videouploadtest", AbstractC54852PDx.A0O(gvr, gvr2));
        A3f = GVN.A01("com.facebook.samples.voiceplatform", AbstractC54852PDx.A0O(gvr, gvr2));
        A3g = GVN.A01("com.facebook.samples.voltron", AbstractC148856g7.A1H(PDz.A0s, AbstractC54852PDx.A0r(gvr, gvr2, 3), 2));
        A3h = GVN.A01("com.facebook.samples.workassistant", AbstractC54852PDx.A0O(gvr, gvr2));
        A3i = GVN.A01("com.facebook.services", AbstractC54852PDx.A0O(gvr16, gvr17));
        A3j = GVN.A01("com.facebook.sparklabs", AbstractC54852PDx.A0O(gvr, gvr2));
        A3k = GVN.A01("com.facebook.sparklabs.inhouse", AbstractC54852PDx.A0O(gvr, gvr2));
        GVR gvr25 = PDz.A1V;
        A3l = GVN.A01("com.facebook.spatial_persistence_service", C08F.A00(gvr25));
        GVR[] gvrArr15 = new GVR[3];
        gvrArr15[0] = gvr8;
        GVR gvr26 = PDz.A2R;
        gvrArr15[1] = gvr26;
        A3m = GVN.A01(SocketClientTransport.SOCKET_SERVER_PACKAGE_PROD, AbstractC148856g7.A1H(PDz.A2S, gvrArr15, 2));
        A3n = GVN.A01("com.facebook.stella.hc", C08F.A00(gvr26));
        A3o = GVN.A01("com.facebook.study", C08F.A00(PDz.A0v));
        A3p = GVN.A01("com.facebook.stylesketch", C08F.A00(PDz.A2T));
        GVR[] gvrArr16 = new GVR[3];
        gvrArr16[0] = gvr6;
        A3q = GVN.A01("com.facebook.system", AbstractC54852PDx.A0P(gvr16, gvr17, gvrArr16, 1, 2));
        GVR[] gvrArr17 = new GVR[3];
        gvrArr17[0] = gvr7;
        A3r = GVN.A01("com.facebook.talk", AbstractC54852PDx.A0P(gvr6, gvr8, gvrArr17, 1, 2));
        A3s = GVN.A01("com.facebook.together.together.release_nightly", C08F.A00(gvr22));
        A3t = GVN.A01("com.facebook.together.together.stable", C08F.A00(gvr22));
        A3u = GVN.A01("com.facebook.tools.trimark", AbstractC54852PDx.A0O(gvr, gvr2));
        A3v = GVN.A01("com.facebook.tv", AbstractC54852PDx.A0O(gvr10, gvr19));
        A3w = GVN.A01("com.facebook.vibes", C08F.A00(PDz.A2W));
        GVR[] gvrArr18 = new GVR[4];
        gvrArr18[0] = PDz.A0B;
        gvrArr18[1] = PDz.A0C;
        A3x = GVN.A01("com.facebook.viewpoints", AbstractC54852PDx.A0P(gvr21, gvr8, gvrArr18, 2, 3));
        A3y = GVN.A01("com.facebook.vscamera.app", AbstractC54852PDx.A0O(gvr, gvr2));
        A3z = GVN.A01("com.facebook.wakizashi", C08F.A00(gvr7));
        A40 = GVN.A01("com.facebook.wallaby.arena", C08F.A00(gvr));
        GVR[] gvrArr19 = new GVR[2];
        gvrArr19[0] = gvr21;
        A41 = GVN.A01("com.facebook.wallaby.pulse", AbstractC148856g7.A1H(PDz.A25, gvrArr19, 1));
        A42 = GVN.A01("com.facebook.wallaby.stylesketch", C08F.A00(gvr));
        A43 = GVN.A01("com.facebook.wearable.alldaywear", C08F.A00(gvr4));
        GVR gvr27 = PDz.A1L;
        A44 = GVN.A01("com.facebook.wearable.apps.activities", C08F.A00(gvr27));
        A45 = GVN.A01("com.facebook.wearable.apps.activity_watchface", C08F.A00(gvr27));
        A46 = GVN.A01("com.facebook.wearable.apps.aihistory", C08F.A00(gvr27));
        A47 = GVN.A01("com.facebook.wearable.apps.assistant", C08F.A00(gvr27));
        A48 = GVN.A01("com.facebook.wearable.apps.avatar", C08F.A00(gvr27));
        A49 = GVN.A01("com.facebook.wearable.apps.breathe", C08F.A00(gvr27));
        A4A = GVN.A01("com.facebook.wearable.apps.calendar", C08F.A00(gvr27));
        A4B = GVN.A01("com.facebook.wearable.apps.camera", C08F.A00(gvr27));
        A4C = GVN.A01("com.facebook.wearable.apps.carousel_watchface", C08F.A00(gvr27));
        A4D = GVN.A01("com.facebook.wearable.apps.challenge", C08F.A00(gvr27));
        GVR gvr28 = PDz.A1M;
        A4E = GVN.A01("com.facebook.wearable.apps.clock", C08F.A00(gvr28));
        A4F = GVN.A01("com.facebook.wearable.apps.constellationplayground", C08F.A00(gvr27));
        GVR gvr29 = PDz.A1N;
        A4G = GVN.A01("com.facebook.wearable.apps.devicediagnostic", C08F.A00(gvr29));
        A4H = GVN.A01("com.facebook.wearable.apps.devoptions", C08F.A00(gvr27));
        A4I = GVN.A01("com.facebook.wearable.apps.digest_watchface", C08F.A00(gvr27));
        A4J = GVN.A01("com.facebook.wearable.apps.eq", C08F.A00(gvr29));
        A4K = GVN.A01("com.facebook.wearable.apps.feather", C08F.A00(gvr27));
        A4L = GVN.A01("com.facebook.wearable.apps.fuel", C08F.A00(gvr27));
        A4M = GVN.A01("com.facebook.wearable.apps.gallery", C08F.A00(gvr27));
        A4N = GVN.A01("com.facebook.wearable.apps.genai_watchface", C08F.A00(gvr27));
        A4O = GVN.A01("com.facebook.wearable.apps.health_dogfooder", C08F.A00(gvr27));
        A4P = GVN.A01("com.facebook.wearable.apps.heart", C08F.A00(gvr27));
        A4S = GVN.A01("com.facebook.wearable.apps.ig_stories_watchface", C08F.A00(gvr27));
        A4Q = GVN.A01("com.facebook.wearable.apps.igdirect", C08F.A00(gvr27));
        A4R = GVN.A01("com.facebook.wearable.apps.igdirectrtc", C08F.A00(gvr27));
        A4T = GVN.A01("com.facebook.wearable.apps.journal", C08F.A00(gvr27));
        A4U = GVN.A01("com.facebook.wearable.apps.lego", C08F.A00(gvr27));
        GVR[] gvrArr20 = new GVR[2];
        gvrArr20[0] = gvr27;
        GVR gvr30 = PDz.A1O;
        A4V = GVN.A01("com.facebook.wearable.apps.libremove", AbstractC148856g7.A1H(gvr30, gvrArr20, 1));
        A4W = GVN.A01("com.facebook.wearable.apps.mediacontroller", C08F.A00(gvr28));
        A4X = GVN.A01("com.facebook.wearable.apps.mediastore", C08F.A00(gvr27));
        A4Y = GVN.A01("com.facebook.wearable.apps.merlin", C08F.A00(gvr27));
        A4Z = GVN.A01("com.facebook.wearable.apps.messages", C08F.A00(gvr27));
        A4a = GVN.A01("com.facebook.wearable.apps.mirror", C08F.A00(gvr27));
        A4b = GVN.A01("com.facebook.wearable.apps.mockapplarge", C08F.A00(gvr28));
        A4c = GVN.A01("com.facebook.wearable.apps.mockappmedium", C08F.A00(gvr28));
        A4d = GVN.A01("com.facebook.wearable.apps.mockappsmall", C08F.A00(gvr28));
        A4e = GVN.A01("com.facebook.wearable.apps.mwear", C08F.A00(gvr27));
        A4f = GVN.A01("com.facebook.wearable.apps.mwearrtc", C08F.A00(gvr27));
        A4g = GVN.A01("com.facebook.wearable.apps.navigation", C08F.A00(gvr27));
        A4h = GVN.A01("com.facebook.wearable.apps.odyssey_watchface", C08F.A00(gvr27));
        A4i = GVN.A01("com.facebook.wearable.apps.peoplepicker", C08F.A00(gvr27));
        A4j = GVN.A01("com.facebook.wearable.apps.personalsafety", C08F.A00(gvr27));
        A4k = GVN.A01("com.facebook.wearable.apps.phone", AbstractC54852PDx.A0O(gvr27, gvr29));
        A4l = GVN.A01("com.facebook.wearable.apps.player", C08F.A00(gvr30));
        A4m = GVN.A01("com.facebook.wearable.apps.reminder", C08F.A00(gvr27));
        A4n = GVN.A01("com.facebook.wearable.apps.retaildemo", C08F.A00(gvr29));
        A4o = GVN.A01("com.facebook.wearable.apps.roost", C08F.A00(gvr29));
        A4p = GVN.A01("com.facebook.wearable.apps.sleep", C08F.A00(gvr27));
        A4q = GVN.A01("com.facebook.wearable.apps.sports", C08F.A00(gvr27));
        A4r = GVN.A01("com.facebook.wearable.apps.stories", C08F.A00(gvr27));
        A4s = GVN.A01("com.facebook.wearable.apps.style_watchface", C08F.A00(gvr27));
        A4t = GVN.A01("com.facebook.wearable.apps.talkback", C08F.A00(gvr29));
        A4u = GVN.A01("com.facebook.wearable.apps.thread", C08F.A00(gvr27));
        A4v = GVN.A01("com.facebook.wearable.apps.turntable_watchface", C08F.A00(gvr27));
        A4w = GVN.A01("com.facebook.wearable.apps.voicenotes", C08F.A00(gvr29));
        A4x = GVN.A01("com.facebook.wearable.apps.wallet", AbstractC54852PDx.A0O(gvr27, gvr29));
        A4y = GVN.A01("com.facebook.wearable.apps.weather", C08F.A00(gvr27));
        A4z = GVN.A01("com.facebook.wearable.apps.whatsapp", C08F.A00(gvr27));
        A50 = GVN.A01("com.facebook.wearable.apps.wirelessdebug", AbstractC54852PDx.A0O(gvr4, gvr27));
        A51 = GVN.A01("com.facebook.wearable.apps.workout", C08F.A00(gvr27));
        A52 = GVN.A01("com.facebook.wearable.common.crashreporter", C08F.A00(gvr28));
        A53 = GVN.A01("com.facebook.wearable.gatekeeper", C08F.A00(gvr4));
        A54 = GVN.A01("com.facebook.wearable.lab", C08F.A00(gvr4));
        A55 = GVN.A01("com.facebook.wearable.sample.breathstreak", C08F.A00(gvr28));
        A56 = GVN.A01("com.facebook.wearable.sample.flan", C08F.A00(gvr27));
        A57 = GVN.A01("com.facebook.wearable.sample.gesturecollector", C08F.A00(gvr28));
        A58 = GVN.A01("com.facebook.wearable.sample.locationtesttool", C08F.A00(gvr28));
        A59 = GVN.A01("com.facebook.wearable.sample.maps", AbstractC54852PDx.A0O(gvr, gvr2));
        A5A = GVN.A01("com.facebook.wearable.sample.milandaserver", C08F.A00(gvr));
        A5B = GVN.A01("com.facebook.wearable.sample.mlclient", C08F.A00(gvr27));
        A5C = GVN.A01("com.facebook.wearable.sample.notificationplayground", C08F.A00(gvr27));
        A5D = GVN.A01("com.facebook.wearable.sample.pioffloadplayground", C08F.A00(gvr27));
        A5E = GVN.A01("com.facebook.wearable.sample.quickmmai", C08F.A00(gvr27));
        A5F = GVN.A01("com.facebook.wearable.sample.sensorlogger", AbstractC54852PDx.A0O(gvr28, gvr29));
        A5G = GVN.A01("com.facebook.wearable.sample.tester", C08F.A00(gvr27));
        A5H = GVN.A01("com.facebook.wearable.sample.wearable_releases_test_app_one", C08F.A00(gvr28));
        A5I = GVN.A01("com.facebook.wearable.sample.wearable_releases_test_app_two", C08F.A00(gvr28));
        A5J = GVN.A01("com.facebook.wearable.system.accounts", C08F.A00(gvr29));
        A5K = GVN.A01("com.facebook.wearable.system.achievements", C08F.A00(gvr27));
        A5L = GVN.A01("com.facebook.wearable.system.analytics", C08F.A00(gvr29));
        A5M = GVN.A01("com.facebook.wearable.system.aod_service", C08F.A00(gvr4));
        A5N = GVN.A01("com.facebook.wearable.system.appmanager", C08F.A00(gvr29));
        A5O = GVN.A01("com.facebook.wearable.system.appmanagerprefs", C08F.A00(gvr29));
        A5P = GVN.A01("com.facebook.wearable.system.appstore", C08F.A00(gvr27));
        A5Q = GVN.A01("com.facebook.wearable.system.assistantservice", C08F.A00(gvr29));
        A5R = GVN.A01("com.facebook.wearable.system.autosharing", C08F.A00(gvr27));
        A5S = GVN.A01("com.facebook.wearable.system.backup", C08F.A00(gvr29));
        A5T = GVN.A01("com.facebook.wearable.system.bugreport", C08F.A00(gvr27));
        A5U = GVN.A01("com.facebook.wearable.system.cameraservicebridge", C08F.A00(gvr4));
        A5V = GVN.A01("com.facebook.wearable.system.carrier_config", C08F.A00(gvr29));
        A5W = GVN.A01("com.facebook.wearable.system.clawsysui", C08F.A00(gvr29));
        A5X = GVN.A01("com.facebook.wearable.system.configuration", C08F.A00(gvr27));
        A5Y = GVN.A01("com.facebook.wearable.system.connectivity", C08F.A00(gvr4));
        A5Z = GVN.A01("com.facebook.wearable.system.crashreporter", C08F.A00(gvr27));
        A5a = GVN.A01("com.facebook.wearable.system.data", C08F.A00(gvr29));
        A5b = GVN.A01("com.facebook.wearable.system.devicehealth", C08F.A00(gvr29));
        A5c = GVN.A01("com.facebook.wearable.system.deviceinfo", C08F.A00(gvr28));
        A5d = GVN.A01("com.facebook.wearable.system.devicestatereporter", C08F.A00(gvr29));
        A5e = GVN.A01("com.facebook.wearable.system.healthservices", C08F.A00(gvr29));
        A5f = GVN.A01("com.facebook.wearable.system.installer", C08F.A00(gvr29));
        A5g = GVN.A01("com.facebook.wearable.system.keyboard", C08F.A00(gvr27));
        A5h = GVN.A01("com.facebook.wearable.system.launcher", AbstractC54852PDx.A0O(gvr27, gvr29));
        A5j = GVN.A01("com.facebook.wearable.system.location.providers.network", C08F.A00(gvr4));
        A5k = GVN.A01("com.facebook.wearable.system.location.proxy", C08F.A00(gvr4));
        A5l = GVN.A01("com.facebook.wearable.system.location.service", AbstractC54852PDx.A0O(gvr29, gvr25));
        A5i = GVN.A01("com.facebook.wearable.system.locationsharing", C08F.A00(gvr29));
        A5m = GVN.A01("com.facebook.wearable.system.lockscreen", AbstractC54852PDx.A0O(gvr4, gvr27));
        A5n = GVN.A01("com.facebook.wearable.system.maps", C08F.A00(gvr27));
        A5o = GVN.A01("com.facebook.wearable.system.mcutransfer", C08F.A00(gvr29));
        A5p = GVN.A01("com.facebook.wearable.system.metaliftservice", C08F.A00(gvr29));
        A5q = GVN.A01("com.facebook.wearable.system.mfi", C08F.A00(gvr4));
        A5r = GVN.A01("com.facebook.wearable.system.mlservice", C08F.A00(gvr27));
        A5s = GVN.A01("com.facebook.wearable.system.networkproxy", C08F.A00(gvr29));
        A5t = GVN.A01("com.facebook.wearable.system.notification", C08F.A00(gvr29));
        A5u = GVN.A01("com.facebook.wearable.system.onboarding", C08F.A00(gvr29));
        A5v = GVN.A01("com.facebook.wearable.system.performance_manager.app", C08F.A00(gvr4));
        A5w = GVN.A01("com.facebook.wearable.system.pioffload", C08F.A00(gvr29));
        A5x = GVN.A01("com.facebook.wearable.system.platypus", AbstractC54852PDx.A0O(gvr27, gvr29));
        A5y = GVN.A01("com.facebook.wearable.system.selfcare", C08F.A00(gvr29));
        A5z = GVN.A01("com.facebook.wearable.system.selfcare_debug", C08F.A00(gvr27));
        A61 = GVN.A01("com.facebook.wearable.system.setting_service", C08F.A00(gvr4));
        A60 = GVN.A01("com.facebook.wearable.system.settings", C08F.A00(gvr29));
        A62 = GVN.A01("com.facebook.wearable.system.sleep_service", C08F.A00(gvr4));
        A63 = GVN.A01("com.facebook.wearable.system.smartreplyservice", C08F.A00(gvr27));
        A65 = GVN.A01("com.facebook.wearable.system.sound_and_haptics_manager", C08F.A00(gvr4));
        A64 = GVN.A01("com.facebook.wearable.system.soundandhapticsmanager", C08F.A00(gvr29));
        A66 = GVN.A01("com.facebook.wearable.system.speechaudiobridgeservice", C08F.A00(gvr4));
        A67 = GVN.A01("com.facebook.wearable.system.speechservice", C08F.A00(gvr29));
        A68 = GVN.A01("com.facebook.wearable.system.ssacoordinatorbridge", C08F.A00(gvr4));
        A69 = GVN.A01("com.facebook.wearable.system.statscollector", C08F.A00(gvr4));
        A6A = GVN.A01("com.facebook.wearable.system.systemserverproxy", C08F.A00(gvr29));
        A6B = GVN.A01("com.facebook.wearable.system.sysui", C08F.A00(gvr29));
        GVR[] gvrArrA0r2 = AbstractC54852PDx.A0r(gvr23, gvr29, 3);
        GVR gvr31 = PDz.A1R;
        A6C = GVN.A01("com.facebook.wearable.system.telecom", AbstractC148856g7.A1H(gvr31, gvrArrA0r2, 2));
        A6D = GVN.A01("com.facebook.wearable.system.unifiedtelemetry", AbstractC54852PDx.A0O(gvr4, gvr29));
        A6E = GVN.A01("com.facebook.wearable.system.updater", C08F.A00(gvr29));
        A6F = GVN.A01("com.facebook.wearable.system.watchface", C08F.A00(gvr29));
        A6G = GVN.A01("com.facebook.wearable.system.wifi", C08F.A00(gvr4));
        A6I = GVN.A01("com.facebook.wearable.system.wifi_metrics_upload", C08F.A00(gvr4));
        A6H = GVN.A01("com.facebook.wearable.system.wifibtmetricsupload", C08F.A00(gvr4));
        A6J = GVN.A01("com.facebook.wearable.system.wirelessservices", C08F.A00(gvr29));
        A6K = GVN.A01("com.facebook.wearable.system.wse", C08F.A00(gvr4));
        A6L = GVN.A01("com.facebook.wearable.system.zaxis", C08F.A00(gvr27));
        A6M = GVN.A01("com.facebook.wearable.wirelessinsight", C08F.A00(gvr4));
        A6N = GVN.A01("com.facebook.wearable.wirelessinsight.app", C08F.A00(gvr4));
        A6O = GVN.A01("com.facebook.wearable.zenservice", C08F.A00(gvr4));
        A6P = GVN.A01("com.facebook.weave", C08F.A00(PDz.A2m));
        A6Q = GVN.A01("com.facebook.work", AbstractC54852PDx.A0O(gvr6, gvr8));
        GVR[] gvrArr21 = new GVR[3];
        gvrArr21[0] = gvr7;
        A6R = GVN.A01("com.facebook.workchat", AbstractC54852PDx.A0P(gvr6, gvr8, gvrArr21, 1, 2));
        A6S = GVN.A01("com.facebook.workdev", C08F.A00(gvr7));
        GVR gvr32 = PDz.A1x;
        A6T = GVN.A01("com.facebook.workrooms", C08F.A00(gvr32));
        C05880Px c05880Px = C05880Px.A00;
        A6U = GVN.A01("com.facebook.workrooms.dev", c05880Px);
        A6V = GVN.A01("com.facebook.workrooms.stable", C08F.A00(gvr32));
        A6W = GVN.A01("com.facebook.workrooms.staging", C08F.A00(gvr32));
        A6X = GVN.A01("com.facebook.wse", C08F.A00(gvr4));
        A6Y = GVN.A01("com.facebook.x3d.nazare.vr", C08F.A00(gvr9));
        A6Z = GVN.A01("com.facebook.x3d.photoreal.vr", C08F.A00(gvr9));
        A6a = GVN.A01("com.facebook.x3d.photoreal.vr.dev", C08F.A00(gvr9));
        A6b = GVN.A01("com.forwardxp.metalauncher", C08F.A00(gvr25));
        GVR[] gvrArr22 = new GVR[2];
        gvrArr22[0] = PDz.A0x;
        A6c = GVN.A01("com.freebasics", AbstractC148856g7.A1H(PDz.A0y, gvrArr22, 1));
        A6d = GVN.A01("com.gieseckedevrient.lpa.gsma.v22", C08F.A00(gvr4));
        A6e = GVN.A01("com.google.android.exoplayer2.demo", C08F.A00(gvr11));
        A6k = GVN.A01("com.hsrmobile", AbstractC54852PDx.A0O(gvr21, gvr25));
        A6l = GVN.A01("com.instagram.airwave", C08F.A00(PDz.A18));
        GVR gvr33 = PDz.A1C;
        A6m = GVN.A01("com.instagram.android", AbstractC54852PDx.A0P(gvr33, gvr8, new GVR[2], 0, 1));
        GVR gvr34 = PDz.A1D;
        A6n = GVN.A01("com.instagram.barcelona", AbstractC54852PDx.A0P(gvr34, gvr8, new GVR[2], 0, 1));
        A6o = GVN.A01("com.instagram.basel", C08F.A00(gvr34));
        A6p = GVN.A01("com.instagram.boomerang", C08F.A00(gvr33));
        A6q = GVN.A01("com.instagram.diem", C08F.A00(gvr34));
        A6r = GVN.A01("com.instagram.lite", AbstractC54852PDx.A0O(gvr33, gvr8));
        A6s = GVN.A01("com.instagram.moonshot", C08F.A00(gvr34));
        A6t = GVN.A01("com.instagram.sample.videouploadtest", AbstractC54852PDx.A0O(gvr, gvr2));
        A6u = GVN.A01("com.leaplock.flash", C08F.A00(gvr7));
        A6v = GVN.A01("com.leaplock.moments", C08F.A00(gvr7));
        A6w = GVN.A01("com.mapillary.app", AbstractC54852PDx.A0P(PDz.A1I, gvr8, new GVR[2], 0, 1));
        A6x = GVN.A01("com.meta.AccountsCenter.pwa", C08F.A00(gvr25));
        A7f = GVN.A01("com.meta.HyperscapeHmdCapture", C08F.A00(gvr25));
        A7g = GVN.A01("com.meta.HyperscapeHmdCaptureAutomation", C08F.A00(gvr9));
        A6y = GVN.A01("com.meta.agenthome", C08F.A00(gvr21));
        A6z = GVN.A01("com.meta.agios.solaris.aria.ai.companion", C08F.A00(gvr21));
        A70 = GVN.A01("com.meta.agios.solaris.gesturesandbox", C08F.A00(gvr21));
        A71 = GVN.A01("com.meta.agios.solaris.hid", C08F.A00(gvr21));
        A72 = GVN.A01("com.meta.agios.solaris.oatmeal", C08F.A00(gvr21));
        A73 = GVN.A01("com.meta.agios.solaris.popai.companion", C08F.A00(gvr21));
        GVR gvr35 = PDz.A1t;
        A76 = GVN.A01("com.meta.ar.arcellularexperience", C08F.A00(gvr35));
        A77 = GVN.A01("com.meta.ar.fox.edge.capture", C08F.A00(gvr25));
        A78 = GVN.A01("com.meta.ar.fox.edge.instagram", C08F.A00(gvr25));
        A79 = GVN.A01("com.meta.ar.fox.edge.messenger", C08F.A00(gvr25));
        A7A = GVN.A01("com.meta.ar.fox.edge.music", C08F.A00(gvr25));
        A7B = GVN.A01("com.meta.ar.fox.edge.photos", C08F.A00(gvr25));
        A7C = GVN.A01("com.meta.ar.fox.phone", C08F.A00(gvr25));
        A7D = GVN.A01("com.meta.ar.fox.whatsapp_for_stage", C08F.A00(gvr25));
        A7E = GVN.A01("com.meta.ar.helix", C08F.A00(gvr25));
        A7F = GVN.A01("com.meta.ar.helixserver", C08F.A00(gvr25));
        A7G = GVN.A01("com.meta.ar.holodeck", C08F.A00(gvr25));
        A7H = GVN.A01("com.meta.ar.msysservice", C08F.A00(gvr25));
        A7I = GVN.A01("com.meta.ar.webview_service", C08F.A00(gvr25));
        A7J = GVN.A01("com.meta.ar.xrdriver", C08F.A00(gvr22));
        A74 = GVN.A01("com.meta.arena", C08F.A00(PDz.A0D));
        A75 = GVN.A01("com.meta.arfx.input.interactables_graph", C08F.A00(gvr25));
        A7K = GVN.A01("com.meta.attribution", C08F.A00(gvr17));
        A7L = GVN.A01("com.meta.codecavatar.workspace", C08F.A00(gvr9));
        A7M = GVN.A01("com.meta.codecavatar.workspace.underground", C08F.A00(gvr9));
        A7N = GVN.A01("com.meta.conductor.coca", C08F.A00(gvr19));
        A7O = GVN.A01("com.meta.credentialsmanager", C08F.A00(gvr25));
        A7P = GVN.A01("com.meta.discovero", C08F.A00(PDz.A0c));
        GVR gvr36 = PDz.A0j;
        A7Q = GVN.A01("com.meta.eclipse", AbstractC54852PDx.A0P(gvr36, gvr22, new GVR[2], 0, 1));
        A7R = GVN.A01("com.meta.federatedcomputing.oculus", C08F.A00(gvr22));
        A7S = GVN.A01("com.meta.forge", C08F.A00(gvr21));
        A7T = GVN.A01("com.meta.fracture", C08F.A00(gvr9));
        A7U = GVN.A01("com.meta.greenhouse", C08F.A00(gvr8));
        A7V = GVN.A01("com.meta.handseducationmodule", C08F.A00(gvr25));
        A7W = GVN.A01("com.meta.happy", C08F.A00(gvr21));
        A7X = GVN.A01("com.meta.happy.master", C08F.A00(gvr21));
        GVR gvr37 = PDz.A2D;
        A7Y = GVN.A01("com.meta.horizon.simulator.swm", C08F.A00(gvr37));
        A7Z = GVN.A01("com.meta.horizon.standalone.demo", C08F.A00(gvr25));
        A7a = GVN.A01("com.meta.horizon.standalone.dev", C08F.A00(gvr25));
        A7b = GVN.A01("com.meta.hpiassets", C08F.A00(PDz.A1X));
        A7c = GVN.A01("com.meta.hubble", AbstractC54852PDx.A0P(PDz.A13, gvr8, AbstractC54852PDx.A0r(gvr19, gvr36, 4), 2, 3));
        A7d = GVN.A01("com.meta.hubble.reflect", C08F.A00(gvr36));
        A7e = GVN.A01("com.meta.hyperscape", C08F.A00(gvr21));
        A7h = GVN.A01("com.meta.imeiqrreader", C08F.A00(gvr4));
        A7i = GVN.A01("com.meta.linktabula.viewer", C08F.A00(gvr25));
        A7j = GVN.A01("com.meta.littledreamwright", AbstractC148856g7.A1H(PDz.A1G, AbstractC54852PDx.A0r(gvr36, gvr21, 3), 2));
        A7k = GVN.A01("com.meta.metasdksample", AbstractC54852PDx.A0O(gvr, gvr2));
        A7l = GVN.A01("com.meta.nest.metamate_1877734942906295", C08F.A00(gvr21));
        A7m = GVN.A01("com.meta.nest.mobilehome_939743425411621", C08F.A00(gvr21));
        A7n = GVN.A01("com.meta.nest.tasks_1264515615256545", C08F.A00(gvr21));
        A7o = GVN.A01("com.meta.nest.workplace_1251122716596158", C08F.A00(gvr21));
        A7p = GVN.A01("com.meta.nuxeducation", C08F.A00(gvr25));
        A7q = GVN.A01("com.meta.oatmeal.metaconfig", C08F.A00(PDz.A1T));
        A7r = GVN.A01("com.meta.ota.florian", C08F.A00(PDz.A29));
        A7s = GVN.A01("com.meta.ota.greatwhite", C08F.A00(PDz.A2B));
        A7t = GVN.A01("com.meta.ota.hammerhead", C08F.A00(PDz.A2G));
        GVR[] gvrArr23 = new GVR[3];
        GVR gvr38 = PDz.A1d;
        gvrArr23[0] = gvr38;
        gvrArr23[1] = gvr35;
        GVR gvr39 = PDz.A28;
        A7v = GVN.A01("com.meta.pclink.arkio", AbstractC148856g7.A1H(gvr39, gvrArr23, 2));
        GVR[] gvrArr24 = new GVR[3];
        gvrArr24[0] = gvr38;
        A7w = GVN.A01("com.meta.pclink.gravitysketch", AbstractC54852PDx.A0P(gvr35, gvr39, gvrArr24, 1, 2));
        GVR[] gvrArr25 = new GVR[3];
        gvrArr25[0] = gvr38;
        A7x = GVN.A01("com.meta.pclink.quill", AbstractC54852PDx.A0P(gvr35, gvr39, gvrArr25, 1, 2));
        A7y = GVN.A01("com.meta.pclink.quill_proto_quest2", C08F.A00(gvr38));
        A7z = GVN.A01("com.meta.pclink.quill_proto_quest3", C08F.A00(gvr39));
        A80 = GVN.A01("com.meta.pclink.quill_proto_questpro", C08F.A00(gvr35));
        GVR[] gvrArr26 = new GVR[3];
        gvrArr26[0] = gvr38;
        A81 = GVN.A01("com.meta.pclink.substance3dmodeler", AbstractC54852PDx.A0P(gvr35, gvr39, gvrArr26, 1, 2));
        A7u = GVN.A01("com.meta.pclinkservice.server", C08F.A00(gvr25));
        A82 = GVN.A01("com.meta.portal.sdk.app", AbstractC54852PDx.A0O(gvr, gvr2));
        A83 = GVN.A01("com.meta.quest_hard_link", C08F.A00(gvr25));
        A84 = GVN.A01("com.meta.reflect", C08F.A00(gvr36));
        A85 = GVN.A01("com.meta.rl.trust.service", C08F.A00(gvr25));
        A86 = GVN.A01("com.meta.smartglass.app.accounts", AbstractC54852PDx.A0O(gvr23, gvr31));
        A87 = GVN.A01("com.meta.smartglass.app.ace", C08F.A00(gvr23));
        A88 = GVN.A01("com.meta.smartglass.app.activity", C08F.A00(gvr23));
        A89 = GVN.A01("com.meta.smartglass.app.aiagent", C08F.A00(gvr23));
        A8A = GVN.A01("com.meta.smartglass.app.aihistory", C08F.A00(gvr23));
        A8B = GVN.A01("com.meta.smartglass.app.aiplayground", C08F.A00(gvr23));
        A8C = GVN.A01("com.meta.smartglass.app.appmanager", AbstractC54852PDx.A0P(gvr29, gvr31, AbstractC54852PDx.A0r(gvr23, gvr27, 4), 2, 3));
        A8D = GVN.A01("com.meta.smartglass.app.assistant", C08F.A00(gvr23));
        A8E = GVN.A01("com.meta.smartglass.app.audiodatacollection", AbstractC54852PDx.A0O(gvr23, gvr31));
        A8F = GVN.A01("com.meta.smartglass.app.browser", C08F.A00(gvr23));
        A8G = GVN.A01("com.meta.smartglass.app.capture", C08F.A00(gvr23));
        A8H = GVN.A01("com.meta.smartglass.app.commshub", C08F.A00(gvr23));
        A8I = GVN.A01("com.meta.smartglass.app.connectivitysponge", C08F.A00(gvr23));
        A8J = GVN.A01("com.meta.smartglass.app.constellationplayground", C08F.A00(gvr23));
        A8K = GVN.A01("com.meta.smartglass.app.contacts", C08F.A00(gvr23));
        A8L = GVN.A01("com.meta.smartglass.app.displaytest", C08F.A00(gvr23));
        A8M = GVN.A01("com.meta.smartglass.app.dogfightar", C08F.A00(gvr23));
        A8N = GVN.A01("com.meta.smartglass.app.dwa", C08F.A00(gvr23));
        A8O = GVN.A01("com.meta.smartglass.app.externaldeviceinterface", C08F.A00(gvr23));
        A8P = GVN.A01("com.meta.smartglass.app.facebook", C08F.A00(gvr23));
        A8Q = GVN.A01("com.meta.smartglass.app.fairdemos", C08F.A00(gvr23));
        GVR gvr40 = PDz.A15;
        A8R = GVN.A01("com.meta.smartglass.app.fallingwordsgame", AbstractC54852PDx.A0P(gvr40, gvr23, new GVR[2], 0, 1));
        A8S = GVN.A01("com.meta.smartglass.app.files", C08F.A00(gvr23));
        A8T = GVN.A01("com.meta.smartglass.app.gallery", C08F.A00(gvr23));
        A8U = GVN.A01("com.meta.smartglass.app.game2048", C08F.A00(gvr23));
        A8V = GVN.A01("com.meta.smartglass.app.gamesspace", C08F.A00(gvr23));
        A8W = GVN.A01("com.meta.smartglass.app.groupconversations", AbstractC54852PDx.A0O(gvr23, gvr31));
        A8X = GVN.A01("com.meta.smartglass.app.handwritingprototype", AbstractC54852PDx.A0O(gvr40, gvr23));
        A8Y = GVN.A01("com.meta.smartglass.app.hatch", C08F.A00(gvr23));
        A8Z = GVN.A01("com.meta.smartglass.app.hearing", AbstractC54852PDx.A0O(gvr23, gvr31));
        A8a = GVN.A01("com.meta.smartglass.app.hypertrail", C08F.A00(gvr23));
        A8b = GVN.A01("com.meta.smartglass.app.igdirect", C08F.A00(gvr23));
        A8c = GVN.A01("com.meta.smartglass.app.igstories", C08F.A00(gvr23));
        A8d = GVN.A01("com.meta.smartglass.app.instagram", C08F.A00(gvr23));
        A8e = GVN.A01("com.meta.smartglass.app.jumpergame", C08F.A00(gvr23));
        A8f = GVN.A01("com.meta.smartglass.app.launcher", C08F.A00(gvr23));
        A8g = GVN.A01("com.meta.smartglass.app.lego", C08F.A00(gvr23));
        A8h = GVN.A01("com.meta.smartglass.app.livestream", AbstractC54852PDx.A0O(gvr23, gvr31));
        A8i = GVN.A01("com.meta.smartglass.app.messaging", C08F.A00(gvr23));
        A8j = GVN.A01("com.meta.smartglass.app.metaai", C08F.A00(gvr23));
        A8k = GVN.A01("com.meta.smartglass.app.nabu", C08F.A00(gvr23));
        A8l = GVN.A01("com.meta.smartglass.app.nativemessaging", C08F.A00(gvr23));
        A8m = GVN.A01("com.meta.smartglass.app.navigation", C08F.A00(gvr23));
        A8n = GVN.A01("com.meta.smartglass.app.novasample", C08F.A00(gvr23));
        A8o = GVN.A01("com.meta.smartglass.app.offload", AbstractC54852PDx.A0O(gvr23, gvr31));
        A8p = GVN.A01("com.meta.smartglass.app.oobe", AbstractC54852PDx.A0O(gvr23, gvr31));
        A8q = GVN.A01("com.meta.smartglass.app.orbitservicehostapp", C08F.A00(gvr23));
        A8r = GVN.A01("com.meta.smartglass.app.phone", AbstractC54852PDx.A0O(gvr23, gvr31));
        A8s = GVN.A01("com.meta.smartglass.app.retaildemo", AbstractC54852PDx.A0O(gvr23, gvr31));
        A8t = GVN.A01("com.meta.smartglass.app.sample", C08F.A00(gvr23));
        A8u = GVN.A01("com.meta.smartglass.app.sensorlogger", C08F.A00(gvr23));
        A8v = GVN.A01("com.meta.smartglass.app.settings", C08F.A00(gvr23));
        A8w = GVN.A01("com.meta.smartglass.app.smartsuggestions", AbstractC54852PDx.A0O(gvr23, gvr31));
        A8x = GVN.A01("com.meta.smartglass.app.spaceshooter", C08F.A00(gvr23));
        A8y = GVN.A01("com.meta.smartglass.app.systemui", AbstractC54852PDx.A0O(gvr23, gvr31));
        A8z = GVN.A01("com.meta.smartglass.app.talkback", C08F.A00(gvr23));
        A90 = GVN.A01("com.meta.smartglass.app.threads", C08F.A00(gvr23));
        A91 = GVN.A01("com.meta.smartglass.app.tunnelrider", C08F.A00(gvr23));
        A92 = GVN.A01("com.meta.smartglass.app.utilities", C08F.A00(gvr23));
        A93 = GVN.A01("com.meta.smartglass.app.voicenotes", AbstractC54852PDx.A0O(gvr23, gvr31));
        A94 = GVN.A01("com.meta.smartglass.app.whatsapp", C08F.A00(gvr23));
        A95 = GVN.A01("com.meta.smartglass.app.wirelessinsight", C08F.A00(gvr23));
        A96 = GVN.A01("com.meta.smartglass.app.youtube", C08F.A00(gvr23));
        A97 = GVN.A01("com.meta.solo", C08F.A00(gvr21));
        A99 = GVN.A01("com.meta.spatial.apps.hzos.education", C08F.A00(gvr25));
        A98 = GVN.A01("com.meta.spatialsim", C08F.A00(gvr37));
        A9A = GVN.A01("com.meta.surfacetypingnux", C08F.A00(gvr25));
        A9B = GVN.A01("com.meta.teleopvr", C08F.A00(gvr21));
        A9C = GVN.A01("com.meta.testing", C08F.A00(PDz.A20));
        A9D = GVN.A01("com.meta.transport", C08F.A00(gvr25));
        A9E = GVN.A01("com.meta.utilities.app.teleprompter", C08F.A00(gvr23));
        A9F = GVN.A01("com.meta.waddle", C08F.A00(PDz.A2X));
        GVR[] gvrArr27 = new GVR[3];
        gvrArr27[0] = gvr23;
        A9M = GVN.A01("com.meta.wearable.app.notification", AbstractC54852PDx.A0P(gvr27, gvr31, gvrArr27, 1, 2));
        A9N = GVN.A01("com.meta.wearable.app.novasample", AbstractC54852PDx.A0O(gvr23, gvr31));
        A9I = GVN.A01("com.meta.wearable.apps.camera3", AbstractC54852PDx.A0O(gvr27, gvr29));
        A9J = GVN.A01("com.meta.wearable.apps.clawmagotchi", AbstractC54852PDx.A0O(gvr27, gvr29));
        A9K = GVN.A01("com.meta.wearable.apps.novasample", C08F.A00(gvr29));
        A9L = GVN.A01("com.meta.wearable.apps.roost", C08F.A00(gvr29));
        A9O = GVN.A01("com.meta.wearable.carrier", C08F.A00(gvr29));
        A9P = GVN.A01("com.meta.wearable.cellular", C08F.A00(gvr29));
        A9Q = GVN.A01("com.meta.wearable.codex", C08F.A00(gvr29));
        GVR[] gvrArr28 = new GVR[3];
        gvrArr28[0] = gvr23;
        gvrArr28[1] = PDz.A17;
        A9R = GVN.A01("com.meta.wearable.dat.developer", AbstractC148856g7.A1H(PDz.A1S, gvrArr28, 2));
        A9S = GVN.A01("com.meta.wearable.dat.internalsampleapps.hackathon.ninjatodo", C08F.A00(gvr21));
        A9T = GVN.A01("com.meta.wearable.dat.internalsampleapps.hackathon.wartable", C08F.A00(gvr21));
        A9U = GVN.A01("com.meta.wearable.mfgapp", C08F.A00(gvr4));
        A9V = GVN.A01("com.meta.wearable.musicplatform.sampleapp", C08F.A00(gvr));
        GVR[] gvrArrA0r3 = AbstractC54852PDx.A0r(gvr23, gvr27, 5);
        gvrArrA0r3[2] = gvr29;
        A9W = GVN.A01("com.meta.wearable.oxide.service", AbstractC54852PDx.A0P(gvr31, gvr25, gvrArrA0r3, 3, 4));
        A9X = GVN.A01("com.meta.wearable.spatialai", C08F.A00(gvr25));
        A9Y = GVN.A01("com.meta.wearable.system.clawsysui", C08F.A00(gvr29));
        A9Z = GVN.A01("com.meta.wearable.system.notification", C08F.A00(gvr27));
        A9G = GVN.A01("com.meta.wearables.backup", C08F.A00(gvr29));
        A9H = GVN.A01("com.meta.wearables.copresencetabletop", C08F.A00(PDz.A0R));
        GVR[] gvrArr29 = new GVR[3];
        GVR gvr41 = PDz.A1m;
        gvrArr29[0] = gvr41;
        gvrArr29[1] = gvr35;
        GVR gvr42 = PDz.A1u;
        A9a = GVN.A01("com.meta.wirelessinsight", AbstractC148856g7.A1H(gvr42, gvrArr29, 2));
        A9b = GVN.A01("com.meta.worlds", C08F.A00(gvr25));
        A9c = GVN.A01("com.meta.worlds.dev", c05880Px);
        A9d = GVN.A01("com.meta.worlds.stable", C08F.A00(gvr25));
        A9e = GVN.A01("com.meta.worlds.staging", C08F.A00(gvr25));
        A9f = GVN.A01("com.meta.wrist.os.power.scenariotracker", C08F.A00(gvr4));
        A9g = GVN.A01("com.meta.wrist.os.sdk.resources", C08F.A00(PDz.A0K));
        A9h = GVN.A01("com.meta.xrmark", C08F.A00(gvr9));
        A9i = GVN.A01("com.meta.xrserendipity", C08F.A00(gvr9));
        A9j = GVN.A01("com.meta.xrteleporter", C08F.A00(gvr9));
        AAH = GVN.A01("com.oculus.HapticsStudio", C08F.A00(PDz.A1p));
        AAV = GVN.A01("com.oculus.LucidApp", C08F.A00(gvr35));
        A9k = GVN.A01("com.oculus.accessibility", C08F.A00(gvr25));
        A9l = GVN.A01("com.oculus.accountscenter", C08F.A00(gvr25));
        A9m = GVN.A01("com.oculus.appautomation", c05880Px);
        GVR[] gvrArr30 = new GVR[3];
        gvrArr30[0] = gvr38;
        A9n = GVN.A01("com.oculus.appsafety", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr30, 1, 2));
        A9o = GVN.A01("com.oculus.asrservice", C08F.A00(gvr25));
        GVR gvr43 = PDz.A1q;
        A9p = GVN.A01("com.oculus.assistant", C08F.A00(gvr43));
        A9q = GVN.A01("com.oculus.authtester", C08F.A00(gvr25));
        A9r = GVN.A01("com.oculus.avatareditor", C08F.A00(gvr25));
        GVR[] gvrArr31 = new GVR[2];
        GVR gvr44 = PDz.A1e;
        gvrArr31[0] = gvr44;
        GVR gvr45 = PDz.A1n;
        A9s = GVN.A01("com.oculus.backuptransportservice", AbstractC148856g7.A1H(gvr45, gvrArr31, 1));
        A9t = GVN.A01("com.oculus.bodyapiservice", C08F.A00(gvr25));
        A9u = GVN.A01("com.oculus.browser", C08F.A00(gvr22));
        A9v = GVN.A01("com.oculus.bugreporter", AbstractC54852PDx.A0O(gvr38, gvr41));
        GVR[] gvrArr32 = new GVR[3];
        gvrArr32[0] = gvr38;
        A9w = GVN.A01("com.oculus.bugreportservice", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr32, 1, 2));
        A9x = GVN.A01("com.oculus.calibration.inspector", C08F.A00(gvr25));
        A9y = GVN.A01("com.oculus.captionservice", AbstractC54852PDx.A0O(gvr44, gvr45));
        A9z = GVN.A01("com.oculus.captis", C08F.A00(gvr9));
        GVR[] gvrArr33 = new GVR[3];
        gvrArr33[0] = gvr38;
        AA0 = GVN.A01("com.oculus.companion.server", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr33, 1, 2));
        AA1 = GVN.A01("com.oculus.configuration", C08F.A00(gvr25));
        AA2 = GVN.A01("com.oculus.cvp", C08F.A00(gvr25));
        GVR[] gvrArrA0r4 = AbstractC54852PDx.A0r(gvr4, gvr38, 5);
        gvrArrA0r4[2] = gvr41;
        AA3 = GVN.A01("com.oculus.deviceauthserver", AbstractC54852PDx.A0P(gvr35, gvr42, gvrArrA0r4, 3, 4));
        GVR[] gvrArrA0r5 = AbstractC54852PDx.A0r(gvr4, gvr5, 5);
        gvrArrA0r5[2] = gvr41;
        AA4 = GVN.A01("com.oculus.devicecerttest", AbstractC54852PDx.A0P(gvr35, gvr42, gvrArrA0r5, 3, 4));
        AA5 = GVN.A01("com.oculus.deviceidentitytest", AbstractC54852PDx.A0P(gvr35, gvr42, AbstractC54852PDx.A0r(gvr38, gvr41, 4), 2, 3));
        AA6 = GVN.A01("com.oculus.dynamicfpstester", C08F.A00(gvr41));
        AA7 = GVN.A01("com.oculus.explore", C08F.A00(gvr22));
        GVR[] gvrArr34 = new GVR[3];
        gvrArr34[0] = gvr38;
        AA8 = GVN.A01("com.oculus.externalstorage", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr34, 1, 2));
        AA9 = GVN.A01("com.oculus.eyetrackingnux", C08F.A00(gvr25));
        AAA = GVN.A01("com.oculus.facebook", C08F.A00(gvr25));
        AAB = GVN.A01("com.oculus.firsttimenux", C08F.A00(gvr25));
        GVR[] gvrArr35 = new GVR[3];
        gvrArr35[0] = gvr38;
        AAC = GVN.A01("com.oculus.gatekeeperservice", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr35, 1, 2));
        AAD = GVN.A01("com.oculus.guardian", C08F.A00(gvr22));
        AAE = GVN.A01("com.oculus.guardiansetup", C08F.A00(gvr22));
        AAF = GVN.A01("com.oculus.guidebook", C08F.A00(gvr22));
        AAG = GVN.A01("com.oculus.handshotfixservice", AbstractC54852PDx.A0O(gvr38, gvr41));
        AAI = GVN.A01("com.oculus.headsetsfx", C08F.A00(gvr41));
        AAJ = GVN.A01("com.oculus.helpcenter", C08F.A00(gvr25));
        AAK = GVN.A01("com.oculus.highwindservice", C08F.A00(gvr22));
        GVR gvr46 = PDz.A1r;
        AAL = GVN.A01("com.oculus.horizon", C08F.A00(gvr46));
        AAM = GVN.A01("com.oculus.horizonmediaplayer", C08F.A00(gvr25));
        AAN = GVN.A01("com.oculus.hzosgallery", C08F.A00(gvr25));
        AAO = GVN.A01("com.oculus.identitymanagement.service", C08F.A00(gvr25));
        AAP = GVN.A01("com.oculus.igvr", C08F.A00(gvr25));
        AAQ = GVN.A01("com.oculus.inputinjectionservice", C08F.A00(gvr41));
        AAR = GVN.A01("com.oculus.inputmethod.pacific", C08F.A00(gvr41));
        AAS = GVN.A01("com.oculus.integrity", C08F.A00(gvr25));
        GVR[] gvrArr36 = new GVR[3];
        gvrArr36[0] = gvr38;
        AAT = GVN.A01("com.oculus.linefrequencyservice", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr36, 1, 2));
        GVR[] gvrArr37 = new GVR[3];
        gvrArr37[0] = gvr38;
        AAU = GVN.A01("com.oculus.location.geocoder", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr37, 1, 2));
        AAW = GVN.A01("com.oculus.magicislandcastingservice", C08F.A00(gvr25));
        AAX = GVN.A01("com.oculus.mediahdrdemo", C08F.A00(gvr25));
        GVR gvr47 = PDz.A1Z;
        AAY = GVN.A01("com.oculus.metacam", C08F.A00(gvr47));
        GVR[] gvrArrA0r6 = AbstractC54852PDx.A0r(gvr4, gvr5, 6);
        gvrArrA0r6[2] = gvr41;
        gvrArrA0r6[3] = gvr35;
        AAZ = GVN.A01("com.oculus.mfgapp", AbstractC54852PDx.A0P(gvr42, gvr39, gvrArrA0r6, 4, 5));
        GVR[] gvrArr38 = new GVR[3];
        gvrArr38[0] = gvr38;
        AAa = GVN.A01("com.oculus.micservice", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr38, 1, 2));
        AAb = GVN.A01("com.oculus.mrds", C08F.A00(gvr22));
        GVR[] gvrArr39 = new GVR[3];
        gvrArr39[0] = gvr38;
        AAc = GVN.A01("com.oculus.notification_proxy", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr39, 1, 2));
        GVR[] gvrArr40 = new GVR[3];
        gvrArr40[0] = gvr38;
        AAd = GVN.A01("com.oculus.nux.ota", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr40, 1, 2));
        AAe = GVN.A01("com.oculus.ocms", C08F.A00(gvr46));
        AAf = GVN.A01("com.oculus.oemconfig", C08F.A00(gvr25));
        AAg = GVN.A01("com.oculus.os.blescanservice", C08F.A00(gvr41));
        AAh = GVN.A01("com.oculus.os.chargecontrol", AbstractC54852PDx.A0P(gvr35, gvr42, AbstractC54852PDx.A0r(gvr38, gvr41, 4), 2, 3));
        GVR[] gvrArr41 = new GVR[3];
        gvrArr41[0] = gvr38;
        AAi = GVN.A01("com.oculus.os.clearactivity", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr41, 1, 2));
        AAj = GVN.A01("com.oculus.os.cm", AbstractC54852PDx.A0O(gvr35, gvr42));
        GVR[] gvrArrA0r7 = AbstractC54852PDx.A0r(gvr44, gvr45, 3);
        GVR gvr48 = PDz.A1o;
        AAk = GVN.A01("com.oculus.os.dialoghost", AbstractC148856g7.A1H(gvr48, gvrArrA0r7, 2));
        AAl = GVN.A01("com.oculus.os.dialoglauncher", C08F.A00(gvr41));
        AAm = GVN.A01("com.oculus.os.flashdriverecording", C08F.A00(gvr41));
        AAn = GVN.A01("com.oculus.os.logcollector", AbstractC54852PDx.A0P(gvr35, gvr42, AbstractC54852PDx.A0r(gvr38, gvr41, 4), 2, 3));
        GVR[] gvrArr42 = new GVR[3];
        gvrArr42[0] = gvr41;
        AAo = GVN.A01("com.oculus.os.logviewer", AbstractC54852PDx.A0P(gvr35, gvr42, gvrArr42, 1, 2));
        AAp = GVN.A01("com.oculus.os.memoryeater", C08F.A00(gvr45));
        AAq = GVN.A01("com.oculus.os.music", C08F.A00(gvr45));
        GVR gvr49 = PDz.A0Q;
        AAr = GVN.A01("com.oculus.os.nullhome", C08F.A00(gvr49));
        AAs = GVN.A01("com.oculus.os.qrcodereader", AbstractC54852PDx.A0O(gvr41, gvr35));
        AAt = GVN.A01("com.oculus.os.settings", C08F.A00(gvr41));
        AAu = GVN.A01("com.oculus.os.voiceenrollment", C08F.A00(gvr41));
        GVR[] gvrArr43 = new GVR[3];
        gvrArr43[0] = gvr38;
        AAv = GVN.A01("com.oculus.os.vrbrowserlauncher", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr43, 1, 2));
        GVR[] gvrArr44 = new GVR[3];
        gvrArr44[0] = gvr38;
        AAw = GVN.A01("com.oculus.os.vrlockscreen", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr44, 1, 2));
        AAx = GVN.A01("com.oculus.os.vrmtpapp", C08F.A00(gvr41));
        AAy = GVN.A01("com.oculus.os.vrusb", AbstractC54852PDx.A0P(PDz.A1f, gvr48, new GVR[2], 0, 1));
        AAz = GVN.A01("com.oculus.ovrmonitormetricsservice", c05880Px);
        AB1 = GVN.A01("com.oculus.panelapp.calendar", C08F.A00(gvr25));
        AB2 = GVN.A01("com.oculus.panelapp.devicepairing", C08F.A00(gvr25));
        AB3 = GVN.A01("com.oculus.panelapp.kiosk", C08F.A00(gvr25));
        AB4 = GVN.A01("com.oculus.panelapp.library", C08F.A00(gvr25));
        AB5 = GVN.A01("com.oculus.panelapp.settings", AbstractC54852PDx.A0O(gvr25, gvr8));
        AB0 = GVN.A01("com.oculus.panelapps.workauth", C08F.A00(gvr25));
        GVR[] gvrArr45 = new GVR[3];
        gvrArr45[0] = gvr38;
        AB7 = GVN.A01("com.oculus.preloader", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr45, 1, 2));
        AB8 = GVN.A01("com.oculus.prescriptionlens", C08F.A00(gvr25));
        AB9 = GVN.A01("com.oculus.presence", AbstractC54852PDx.A0O(gvr47, gvr8));
        GVR[] gvrArrA0r8 = AbstractC54852PDx.A0r(gvr4, gvr5, 6);
        gvrArrA0r8[2] = gvr38;
        gvrArrA0r8[3] = gvr41;
        ABA = GVN.A01("com.oculus.provisioningservice", AbstractC54852PDx.A0P(gvr35, gvr42, gvrArrA0r8, 4, 5));
        ABC = GVN.A01("com.oculus.q4b.mdm", C08F.A00(PDz.A1j));
        ABB = GVN.A01("com.oculus.q4bservice", C08F.A00(gvr43));
        ABD = GVN.A01("com.oculus.qalabresetservice", AbstractC54852PDx.A0O(gvr38, gvr41));
        ABE = GVN.A01("com.oculus.quickpromotionservice", C08F.A00(gvr25));
        ABF = GVN.A01("com.oculus.remotedesktop", C08F.A00(gvr25));
        ABG = GVN.A01("com.oculus.rlcontinuoussli", C08F.A00(gvr9));
        ABH = GVN.A01("com.oculus.rlcp.synctest", C08F.A00(gvr25));
        ABI = GVN.A01("com.oculus.sessions", C08F.A00(gvr25));
        ABJ = GVN.A01("com.oculus.shutdown", C08F.A00(gvr41));
        ABK = GVN.A01("com.oculus.socialplatform", C08F.A00(gvr22));
        ABL = GVN.A01("com.oculus.statscollector", AbstractC54852PDx.A0P(gvr35, gvr42, AbstractC54852PDx.A0r(gvr38, gvr41, 4), 2, 3));
        ABM = GVN.A01("com.oculus.statscollectorn", C08F.A00(gvr41));
        ABN = GVN.A01("com.oculus.stella.cloudimport.bridge", C08F.A00(gvr5));
        ABO = GVN.A01("com.oculus.stella.ota", C08F.A00(gvr5));
        ABP = GVN.A01("com.oculus.stella.wifi", C08F.A00(gvr5));
        ABQ = GVN.A01("com.oculus.store", C08F.A00(gvr22));
        ABR = GVN.A01("com.oculus.supernatural", C08F.A00(gvr25));
        ABS = GVN.A01("com.oculus.systemactivities", C08F.A00(gvr22));
        ABT = GVN.A01("com.oculus.systemdriver", AbstractC54852PDx.A0O(gvr22, gvr37));
        ABU = GVN.A01("com.oculus.systemintelligence", C08F.A00(gvr25));
        ABV = GVN.A01("com.oculus.systemresource", C08F.A00(gvr25));
        ABW = GVN.A01("com.oculus.systemutilities", C08F.A00(gvr22));
        ABX = GVN.A01("com.oculus.systemux", C08F.A00(gvr47));
        ABY = GVN.A01("com.oculus.tasktracker", C08F.A00(gvr9));
        ABZ = GVN.A01("com.oculus.telemetry", C08F.A00(gvr41));
        ABa = GVN.A01("com.oculus.thvr", C08F.A00(gvr25));
        ABb = GVN.A01("com.oculus.tv", C08F.A00(PDz.A1v));
        ABc = GVN.A01("com.oculus.twilight", AbstractC54852PDx.A0O(gvr22, gvr8));
        GVR[] gvrArr46 = new GVR[3];
        gvrArr46[0] = gvr38;
        ABd = GVN.A01("com.oculus.unifiedtelemetry", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr46, 1, 2));
        ABe = GVN.A01("com.oculus.updater", C08F.A00(gvr46));
        ABf = GVN.A01("com.oculus.userserver2", C08F.A00(gvr43));
        GVR[] gvrArr47 = new GVR[3];
        gvrArr47[0] = gvr38;
        ABg = GVN.A01("com.oculus.vralertservice", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr47, 1, 2));
        ABh = GVN.A01("com.oculus.vraudiodatadumpmanager", C08F.A00(gvr41));
        GVR[] gvrArr48 = new GVR[3];
        gvrArr48[0] = gvr38;
        ABi = GVN.A01("com.oculus.vrcast", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr48, 1, 2));
        ABj = GVN.A01("com.oculus.vrdesktop", C08F.A00(gvr41));
        ABk = GVN.A01("com.oculus.vrosassetchunktest", C08F.A00(gvr9));
        ABl = GVN.A01("com.oculus.vrpowermanager", C08F.A00(gvr41));
        ABm = GVN.A01("com.oculus.vrprivacycheckup", C08F.A00(gvr25));
        ABn = GVN.A01("com.oculus.vrshell", C08F.A00(gvr22));
        ABo = GVN.A01("com.oculus.vrshell.desktop", AbstractC54852PDx.A0O(gvr38, gvr41));
        ABp = GVN.A01("com.oculus.websafety", AbstractC54852PDx.A0O(gvr41, gvr35));
        ABq = GVN.A01("com.oculus.wifiindoze", C08F.A00(gvr41));
        GVR[] gvrArr49 = new GVR[3];
        gvrArr49[0] = gvr38;
        ABr = GVN.A01("com.oculus.xrstreamingclient", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr49, 1, 2));
        GVR[] gvrArr50 = new GVR[3];
        gvrArr50[0] = gvr38;
        ABs = GVN.A01("com.oculus.yadi", AbstractC54852PDx.A0P(gvr41, gvr35, gvrArr50, 1, 2));
        ABt = GVN.A01("com.onavo.spaceship", C08F.A00(gvr7));
        AC0 = GVN.A01("com.qti.confuridialer", C08F.A00(gvr5));
        AC1 = GVN.A01("com.qti.dpmserviceapp", C08F.A00(gvr4));
        AC2 = GVN.A01("com.qti.qualcomm.datastatusnotification", C08F.A00(gvr4));
        AC3 = GVN.A01("com.qualm.embms", C08F.A00(gvr4));
        AC4 = GVN.A01("com.qualm.location", C08F.A00(gvr4));
        AC5 = GVN.A01("com.qualm.location.XT", C08F.A00(gvr4));
        AC6 = GVN.A01("com.qualm.qcrilmsgtunnel", C08F.A00(gvr4));
        AC7 = GVN.A01("com.qualm.qti.callfeaturessetting", C08F.A00(gvr4));
        AC8 = GVN.A01("com.qualm.qti.cne", C08F.A00(gvr4));
        AC9 = GVN.A01("com.qualm.qti.contextualmode", C08F.A00(gvr4));
        ACA = GVN.A01("com.qualm.qti.ims", C08F.A00(gvr4));
        ACB = GVN.A01("com.qualm.qti.networksetting", C08F.A00(gvr4));
        ACC = GVN.A01("com.qualm.qti.poweroffalarm", C08F.A00(gvr4));
        ACD = GVN.A01("com.qualm.qti.qmmi", C08F.A00(gvr5));
        ACE = GVN.A01("com.qualm.qti.seccamservice", C08F.A00(gvr4));
        ACF = GVN.A01("com.qualm.qti.settings.ctsintenthandler", C08F.A00(gvr4));
        ACG = GVN.A01("com.qualm.qti.settings.watchairplanemode", C08F.A00(gvr4));
        ACH = GVN.A01("com.qualm.qti.settings.watchbluetooth", C08F.A00(gvr4));
        ACI = GVN.A01("com.qualm.qti.settings.watchdeveloperoptions", C08F.A00(gvr4));
        ACJ = GVN.A01("com.qualm.qti.simsettings", C08F.A00(gvr4));
        ACK = GVN.A01("com.qualm.qti.telephonyservice", C08F.A00(gvr4));
        GVR[] gvrArrA0r9 = AbstractC54852PDx.A0r(gvr4, gvr5, 6);
        gvrArrA0r9[2] = gvr38;
        gvrArrA0r9[3] = gvr41;
        ACL = GVN.A01("com.qualm.timeservice", AbstractC54852PDx.A0P(gvr35, gvr42, gvrArrA0r9, 4, 5));
        GVR[] gvrArr51 = new GVR[3];
        gvrArr51[0] = gvr5;
        ACM = GVN.A01("com.qualm.wfd.service", AbstractC54852PDx.A0P(gvr38, gvr41, gvrArr51, 1, 2));
        ACN = GVN.A01("com.quicinc.cne.CNEService", C08F.A00(gvr5));
        ACO = GVN.A01("com.svox.pico", C08F.A00(gvr45));
        GVR[] gvrArr52 = new GVR[2];
        GVR gvr50 = PDz.A2n;
        gvrArr52[0] = gvr50;
        GVR gvr51 = PDz.A2q;
        ACQ = GVN.A01("com.whatsapp", AbstractC148856g7.A1H(gvr51, gvrArr52, 1));
        ACR = GVN.A01("com.whatsapp.orbit.stickerstore", C08F.A00(gvr21));
        ACS = GVN.A01("com.whatsapp.prototype", C08F.A00(gvr21));
        ACT = GVN.A01("com.whatsapp.w4b", AbstractC54852PDx.A0O(gvr50, gvr51));
        ACV = GVN.A01("com.xbox.pwa", C08F.A00(PDz.A2r));
        A6g = GVN.A01("horizon.platform.providers", C08F.A00(gvr25));
        GVR gvr52 = PDz.A14;
        A6h = GVN.A01("horizon.platform.service", AbstractC54852PDx.A0P(gvr52, gvr25, new GVR[2], 0, 1));
        A6i = GVN.A01("horizon.platform.spatialsim", C08F.A00(gvr37));
        A6j = GVN.A01("horizon.platform.wearable.providers", C08F.A00(gvr52));
        GVR[] gvrArr53 = new GVR[3];
        gvrArr53[0] = gvr52;
        A6f = GVN.A01("horizonos.supplement.hzplatformclientcore", AbstractC54852PDx.A0P(gvr25, gvr37, gvrArr53, 1, 2));
        AB6 = GVN.A01("oculus.platform", AbstractC54852PDx.A0P(gvr35, gvr42, AbstractC54852PDx.A0r(gvr38, gvr41, 4), 2, 3));
        ABu = GVN.A01("org.chromium.chrome", C08F.A00(PDz.A05));
        ABv = GVN.A01("org.chromium.trichromelibrary", C08F.A00(gvr22));
        ABw = GVN.A01("org.codeaurora.bluetooth", C08F.A00(gvr41));
        ABx = GVN.A01("org.codeaurora.btmultisim", C08F.A00(gvr5));
        ABy = GVN.A01("org.codeaurora.ims", C08F.A00(gvr4));
        ABz = GVN.A01("org.codeaurora.snapcam", C08F.A00(gvr49));
        ACP = GVN.A01("vendor.qti.hardware.cacert.server", C08F.A00(gvr4));
        GVR[] gvrArr54 = new GVR[2];
        gvrArr54[0] = gvr8;
        ACU = GVN.A01("within.flow.android.flowapp", AbstractC148856g7.A1H(PDz.A2U, gvrArr54, 1));
        ACW = GVN.A01("xrcia.constellus.volmedia", C08F.A00(gvr9));
        A01 = A00(AbstractC54902PFy.A01, PE0.A0p);
        A00 = A00(AbstractC54902PFy.A00, PE0.A0n);
    }
}
