package com.meta.wearable.comms.calling.hera.engine.base;

import X.AbstractC25328B9w;
import X.AbstractC25330B9y;
import X.AbstractC32971bt;
import X.AbstractC81803lj;
import X.AbstractC81823ll;
import X.C26698BmO;
import com.google.protobuf.Internal;
import com.meta.wearable.comms.calling.hera.engine.base.EngineErrno;
import com.whatsapp.calling.opengl.MediaCodecVideoEncoder;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* JADX INFO: loaded from: classes7.dex */
public final class EngineErrno implements Internal.EnumLite {
    public static final /* synthetic */ EngineErrno[] $VALUES;
    public static final EngineErrno ENGINE_ERR_FAILURE;
    public static final EngineErrno ENGINE_ERR_OK;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_ACCOUNT_NOT_MATCH;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_AIRPLANE_MODE_ENABLED;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_BLUETOOTH_PERMISSION_DENIED;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_CALLEE_ON_SAME_DEVICE;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_CALLEE_UNREACHABLE;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_AIRPLANE_MODE_ENABLED;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_CONFIG_ERROR;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_DEVICE_DISCONNECTED;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_ENCRYPTION_ERROR;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_NO_RESPONSE;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_TRANSPORT_ERROR;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_CONTACT_BLOCKED;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_DATAX_SEND_FAILURE;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_EMPTY_RESPONSE;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_ENGINE_NOT_FOUND;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_APP_WAKE_FAILED;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_AUTH_FAILED;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_CALL_INTENT_FAILED;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_NOT_INSTALLED;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_NOT_LINKED;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_NOT_LOGGED_IN;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_NO_RESPONSE;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_OUTDATED;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_GROUP_CALL_ALREADY_ACTIVE;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_GROUP_PARTICIPANTS_LIMIT_EXCEEDED;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_INVALID_WHATSAPP_ID;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_MICROPHONE_PERMISSION_DENIED;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_MICROPHONE_PERMISSION_REQUESTED;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_MISSING_CALL_PERMISSION;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_MISSING_PHONE_ACCOUNT;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_NETWORK;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_NO_HFP;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_NO_VALID_PARTICIPANTS;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_PENDING_INVITE;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_PHONE_CAMERA_PERMISSION_DENIED;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_PROTOCOL;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_THERMAL_THROTTLING;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_UNKNOWN;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_VOIP_DISABLED;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_WA_IN_BAD_STATE;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_WHILE_CALL_IN_PROGRESS;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_ROUTE_HINGES_CLOSED_NO_HFP;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_ROUTE_HINGES_OPEN_DATAX_DISCONNECTED_NO_HFP;
    public static final EngineErrno ENGINE_ERR_OUTGOING_CALL_ROUTE_HINGE_UNKNOWN_NO_HFP;
    public static final EngineErrno UNRECOGNIZED;
    public static final Internal.EnumLiteMap internalValueMap;
    public final int value;

    static {
        EngineErrno engineErrno = new EngineErrno("ENGINE_ERR_OK", 0, 0);
        ENGINE_ERR_OK = engineErrno;
        EngineErrno engineErrno2 = new EngineErrno("ENGINE_ERR_FAILURE", 1, 1);
        ENGINE_ERR_FAILURE = engineErrno2;
        EngineErrno engineErrnoA0R = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_MICROPHONE_PERMISSION_DENIED", 2, C26698BmO.MESSAGE_HISTORY_NOTICE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_MICROPHONE_PERMISSION_DENIED = engineErrnoA0R;
        EngineErrno engineErrnoA0R2 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_MICROPHONE_PERMISSION_REQUESTED", 3, C26698BmO.GROUP_STATUS_MESSAGE_V2_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_MICROPHONE_PERMISSION_REQUESTED = engineErrnoA0R2;
        EngineErrno engineErrnoA0R3 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_MISSING_CALL_PERMISSION", 4, C26698BmO.BOT_FORWARDED_MESSAGE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_MISSING_CALL_PERMISSION = engineErrnoA0R3;
        EngineErrno engineErrnoA0R4 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_CONTACT_BLOCKED", 5, C26698BmO.STATUS_QUESTION_ANSWER_MESSAGE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_CONTACT_BLOCKED = engineErrnoA0R4;
        EngineErrno engineErrnoA0R5 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_NETWORK", 6, C26698BmO.QUESTION_REPLY_MESSAGE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_NETWORK = engineErrnoA0R5;
        EngineErrno engineErrnoA0R6 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_VOIP_DISABLED", 7, C26698BmO.QUESTION_RESPONSE_MESSAGE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_VOIP_DISABLED = engineErrnoA0R6;
        EngineErrno engineErrnoA0R7 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_WHILE_CALL_IN_PROGRESS", 8, C26698BmO.NEWSLETTER_FOLLOWER_INVITE_MESSAGE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_WHILE_CALL_IN_PROGRESS = engineErrnoA0R7;
        EngineErrno engineErrnoA0R8 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_PHONE_CAMERA_PERMISSION_DENIED", 9, C26698BmO.STATUS_QUOTED_MESSAGE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_PHONE_CAMERA_PERMISSION_DENIED = engineErrnoA0R8;
        EngineErrno engineErrnoA0R9 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_NOT_LINKED", 10, C26698BmO.STATUS_STICKER_INTERACTION_MESSAGE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_NOT_LINKED = engineErrnoA0R9;
        EngineErrno engineErrnoA0R10 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_NO_RESPONSE", 11, C26698BmO.POLL_CREATION_MESSAGE_V5_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_NO_RESPONSE = engineErrnoA0R10;
        EngineErrno engineErrnoA0R11 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_UNKNOWN", 12, 112);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_UNKNOWN = engineErrnoA0R11;
        EngineErrno engineErrnoA0R12 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_NO_RESPONSE", 13, C26698BmO.NEWSLETTER_FOLLOWER_INVITE_MESSAGE_V2_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_NO_RESPONSE = engineErrnoA0R12;
        EngineErrno engineErrnoA0R13 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_THERMAL_THROTTLING", 14, 114);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_THERMAL_THROTTLING = engineErrnoA0R13;
        EngineErrno engineErrnoA0R14 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_ACCOUNT_NOT_MATCH", 15, C26698BmO.POLL_RESULT_SNAPSHOT_MESSAGE_V3_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_ACCOUNT_NOT_MATCH = engineErrnoA0R14;
        EngineErrno engineErrnoA0R15 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_INVALID_WHATSAPP_ID", 16, C26698BmO.NEWSLETTER_ADMIN_PROFILE_MESSAGE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_INVALID_WHATSAPP_ID = engineErrnoA0R15;
        EngineErrno engineErrnoA0R16 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_BLUETOOTH_PERMISSION_DENIED", 17, 117);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_BLUETOOTH_PERMISSION_DENIED = engineErrnoA0R16;
        EngineErrno engineErrnoA0R17 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_ENGINE_NOT_FOUND", 18, C26698BmO.SPOILER_MESSAGE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_ENGINE_NOT_FOUND = engineErrnoA0R17;
        EngineErrno engineErrnoA0R18 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_NO_HFP", 19, C26698BmO.POLL_CREATION_MESSAGE_V6_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_NO_HFP = engineErrnoA0R18;
        EngineErrno engineErrnoA0R19 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_NO_VALID_PARTICIPANTS", 20, 120);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_NO_VALID_PARTICIPANTS = engineErrnoA0R19;
        EngineErrno engineErrnoA0R20 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_PROTOCOL", 21, C26698BmO.POLL_ADD_OPTION_MESSAGE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_PROTOCOL = engineErrnoA0R20;
        EngineErrno engineErrnoA0R21 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_EMPTY_RESPONSE", 22, C26698BmO.EVENT_INVITE_MESSAGE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_EMPTY_RESPONSE = engineErrnoA0R21;
        EngineErrno engineErrnoA0R22 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_OUTDATED", 23, C26698BmO.GROUP_ROOT_KEY_SHARE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_OUTDATED = engineErrnoA0R22;
        EngineErrno engineErrnoA0R23 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_WA_IN_BAD_STATE", 24, C26698BmO.PAYMENT_REMINDER_MESSAGE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_WA_IN_BAD_STATE = engineErrnoA0R23;
        EngineErrno engineErrnoA0R24 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_PENDING_INVITE", 25, C26698BmO.SPLIT_PAYMENT_MESSAGE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_PENDING_INVITE = engineErrnoA0R24;
        EngineErrno engineErrnoA0R25 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_AIRPLANE_MODE_ENABLED", 26, C26698BmO.NEWSLETTER_ADMIN_PROFILE_STATUS_MESSAGE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_AIRPLANE_MODE_ENABLED = engineErrnoA0R25;
        EngineErrno engineErrnoA0R26 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_ROUTE_HINGES_CLOSED_NO_HFP", 27, 127);
        ENGINE_ERR_OUTGOING_CALL_ROUTE_HINGES_CLOSED_NO_HFP = engineErrnoA0R26;
        EngineErrno engineErrnoA0R27 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_ROUTE_HINGES_OPEN_DATAX_DISCONNECTED_NO_HFP", 28, 128);
        ENGINE_ERR_OUTGOING_CALL_ROUTE_HINGES_OPEN_DATAX_DISCONNECTED_NO_HFP = engineErrnoA0R27;
        EngineErrno engineErrnoA0R28 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_ROUTE_HINGE_UNKNOWN_NO_HFP", 29, C26698BmO.MUSIC_MESSAGE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_ROUTE_HINGE_UNKNOWN_NO_HFP = engineErrnoA0R28;
        EngineErrno engineErrnoA0R29 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_MISSING_PHONE_ACCOUNT", 30, C26698BmO.STATUS_LINK_PREVIEW_METADATA_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_MISSING_PHONE_ACCOUNT = engineErrnoA0R29;
        EngineErrno engineErrnoA0R30 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_GROUP_CALL_ALREADY_ACTIVE", 31, C26698BmO.BOT_PLATFORM_REGISTRATION_SUCCESS_MESSAGE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_GROUP_CALL_ALREADY_ACTIVE = engineErrnoA0R30;
        EngineErrno engineErrnoA0R31 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_CALLEE_ON_SAME_DEVICE", 32, C26698BmO.NEWSLETTER_SCHEDULED_MESSAGE_FIELD_NUMBER);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_CALLEE_ON_SAME_DEVICE = engineErrnoA0R31;
        EngineErrno engineErrnoA0R32 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_NOT_INSTALLED", 33, 133);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_NOT_INSTALLED = engineErrnoA0R32;
        EngineErrno engineErrnoA0R33 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_AIRPLANE_MODE_ENABLED", 34, 134);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_AIRPLANE_MODE_ENABLED = engineErrnoA0R33;
        EngineErrno engineErrnoA0R34 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_NOT_LOGGED_IN", 35, 135);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_NOT_LOGGED_IN = engineErrnoA0R34;
        EngineErrno engineErrnoA0R35 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_AUTH_FAILED", 36, 136);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_AUTH_FAILED = engineErrnoA0R35;
        EngineErrno engineErrnoA0R36 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_CALLEE_UNREACHABLE", 37, 137);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_CALLEE_UNREACHABLE = engineErrnoA0R36;
        EngineErrno engineErrnoA0R37 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_DEVICE_DISCONNECTED", 38, 138);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_DEVICE_DISCONNECTED = engineErrnoA0R37;
        EngineErrno engineErrnoA0R38 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_ENCRYPTION_ERROR", 39, 139);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_ENCRYPTION_ERROR = engineErrnoA0R38;
        EngineErrno engineErrnoA0R39 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_TRANSPORT_ERROR", 40, 140);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_TRANSPORT_ERROR = engineErrnoA0R39;
        EngineErrno engineErrnoA0R40 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_CONFIG_ERROR", 41, 141);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_CONFIG_ERROR = engineErrnoA0R40;
        EngineErrno engineErrnoA0R41 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_DATAX_SEND_FAILURE", 42, 142);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_DATAX_SEND_FAILURE = engineErrnoA0R41;
        EngineErrno engineErrnoA0R42 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_APP_WAKE_FAILED", 43, 143);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_APP_WAKE_FAILED = engineErrnoA0R42;
        EngineErrno engineErrnoA0R43 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_GROUP_PARTICIPANTS_LIMIT_EXCEEDED", 44, MediaCodecVideoEncoder.MIN_ENCODER_HEIGHT);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_GROUP_PARTICIPANTS_LIMIT_EXCEEDED = engineErrnoA0R43;
        EngineErrno engineErrnoA0R44 = AbstractC25328B9w.A0R("ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_CALL_INTENT_FAILED", 45, 145);
        ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_CALL_INTENT_FAILED = engineErrnoA0R44;
        EngineErrno engineErrnoA0R45 = AbstractC25328B9w.A0R("UNRECOGNIZED", 46, -1);
        UNRECOGNIZED = engineErrnoA0R45;
        EngineErrno[] engineErrnoArr = new EngineErrno[47];
        engineErrnoArr[0] = engineErrno;
        AbstractC32971bt.A0h(engineErrno2, engineErrnoA0R, engineErrnoA0R2, engineErrnoA0R3, engineErrnoArr);
        engineErrnoArr[5] = engineErrnoA0R4;
        AbstractC32971bt.A0i(engineErrnoA0R5, engineErrnoA0R6, engineErrnoA0R7, engineErrnoA0R8, engineErrnoArr);
        AbstractC32971bt.A0j(engineErrnoA0R9, engineErrnoA0R10, engineErrnoA0R11, engineErrnoA0R12, engineErrnoArr);
        AbstractC81823ll.A1S(engineErrnoA0R13, engineErrnoA0R14, engineErrnoA0R15, engineErrnoArr);
        AbstractC32971bt.A0k(engineErrnoA0R16, engineErrnoA0R17, engineErrnoA0R18, engineErrnoA0R19, engineErrnoArr);
        AbstractC81823ll.A0y(engineErrnoA0R20, engineErrnoA0R21, engineErrnoA0R22, engineErrnoA0R23, engineErrnoArr);
        AbstractC81823ll.A0z(engineErrnoA0R24, engineErrnoA0R25, engineErrnoA0R26, engineErrnoA0R27, engineErrnoArr);
        AbstractC81803lj.A1L(engineErrnoA0R28, engineErrnoA0R29, engineErrnoArr);
        AbstractC81823ll.A10(engineErrnoA0R30, engineErrnoA0R31, engineErrnoA0R32, engineErrnoA0R33, engineErrnoArr);
        AbstractC81823ll.A11(engineErrnoA0R34, engineErrnoA0R35, engineErrnoA0R36, engineErrnoA0R37, engineErrnoArr);
        AbstractC81823ll.A12(engineErrnoA0R38, engineErrnoA0R39, engineErrnoA0R40, engineErrnoA0R41, engineErrnoArr);
        engineErrnoArr[43] = engineErrnoA0R42;
        engineErrnoArr[44] = engineErrnoA0R43;
        engineErrnoArr[45] = engineErrnoA0R44;
        engineErrnoArr[46] = engineErrnoA0R45;
        $VALUES = engineErrnoArr;
        internalValueMap = new Internal.EnumLiteMap() { // from class: X.D9O
            @Override // com.google.protobuf.Internal.EnumLiteMap
            public /* bridge */ /* synthetic */ Internal.EnumLite findValueByNumber(int i) {
                return EngineErrno.forNumber(i);
            }
        };
    }

    public static EngineErrno forNumber(int i) {
        if (i == 0) {
            return ENGINE_ERR_OK;
        }
        if (i == 1) {
            return ENGINE_ERR_FAILURE;
        }
        switch (i) {
            case C26698BmO.MESSAGE_HISTORY_NOTICE_FIELD_NUMBER /* 102 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_MICROPHONE_PERMISSION_DENIED;
            case C26698BmO.GROUP_STATUS_MESSAGE_V2_FIELD_NUMBER /* 103 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_MICROPHONE_PERMISSION_REQUESTED;
            case C26698BmO.BOT_FORWARDED_MESSAGE_FIELD_NUMBER /* 104 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_MISSING_CALL_PERMISSION;
            case C26698BmO.STATUS_QUESTION_ANSWER_MESSAGE_FIELD_NUMBER /* 105 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_CONTACT_BLOCKED;
            case C26698BmO.QUESTION_REPLY_MESSAGE_FIELD_NUMBER /* 106 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_NETWORK;
            case C26698BmO.QUESTION_RESPONSE_MESSAGE_FIELD_NUMBER /* 107 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_VOIP_DISABLED;
            case C26698BmO.NEWSLETTER_FOLLOWER_INVITE_MESSAGE_FIELD_NUMBER /* 108 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_WHILE_CALL_IN_PROGRESS;
            case C26698BmO.STATUS_QUOTED_MESSAGE_FIELD_NUMBER /* 109 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_PHONE_CAMERA_PERMISSION_DENIED;
            case C26698BmO.STATUS_STICKER_INTERACTION_MESSAGE_FIELD_NUMBER /* 110 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_NOT_LINKED;
            case C26698BmO.POLL_CREATION_MESSAGE_V5_FIELD_NUMBER /* 111 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_NO_RESPONSE;
            case 112:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_UNKNOWN;
            case C26698BmO.NEWSLETTER_FOLLOWER_INVITE_MESSAGE_V2_FIELD_NUMBER /* 113 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_NO_RESPONSE;
            case 114:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_THERMAL_THROTTLING;
            case C26698BmO.POLL_RESULT_SNAPSHOT_MESSAGE_V3_FIELD_NUMBER /* 115 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_ACCOUNT_NOT_MATCH;
            case C26698BmO.NEWSLETTER_ADMIN_PROFILE_MESSAGE_FIELD_NUMBER /* 116 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_INVALID_WHATSAPP_ID;
            case 117:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_BLUETOOTH_PERMISSION_DENIED;
            case C26698BmO.SPOILER_MESSAGE_FIELD_NUMBER /* 118 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_ENGINE_NOT_FOUND;
            case C26698BmO.POLL_CREATION_MESSAGE_V6_FIELD_NUMBER /* 119 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_NO_HFP;
            case 120:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_NO_VALID_PARTICIPANTS;
            case C26698BmO.POLL_ADD_OPTION_MESSAGE_FIELD_NUMBER /* 121 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_PROTOCOL;
            case C26698BmO.EVENT_INVITE_MESSAGE_FIELD_NUMBER /* 122 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_EMPTY_RESPONSE;
            case C26698BmO.GROUP_ROOT_KEY_SHARE_FIELD_NUMBER /* 123 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_OUTDATED;
            case C26698BmO.PAYMENT_REMINDER_MESSAGE_FIELD_NUMBER /* 124 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_WA_IN_BAD_STATE;
            case C26698BmO.SPLIT_PAYMENT_MESSAGE_FIELD_NUMBER /* 125 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_PENDING_INVITE;
            case C26698BmO.NEWSLETTER_ADMIN_PROFILE_STATUS_MESSAGE_FIELD_NUMBER /* 126 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_AIRPLANE_MODE_ENABLED;
            case 127:
                return ENGINE_ERR_OUTGOING_CALL_ROUTE_HINGES_CLOSED_NO_HFP;
            case 128:
                return ENGINE_ERR_OUTGOING_CALL_ROUTE_HINGES_OPEN_DATAX_DISCONNECTED_NO_HFP;
            case C26698BmO.MUSIC_MESSAGE_FIELD_NUMBER /* 129 */:
                return ENGINE_ERR_OUTGOING_CALL_ROUTE_HINGE_UNKNOWN_NO_HFP;
            case C26698BmO.STATUS_LINK_PREVIEW_METADATA_FIELD_NUMBER /* 130 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_MISSING_PHONE_ACCOUNT;
            case C26698BmO.BOT_PLATFORM_REGISTRATION_SUCCESS_MESSAGE_FIELD_NUMBER /* 131 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_GROUP_CALL_ALREADY_ACTIVE;
            case C26698BmO.NEWSLETTER_SCHEDULED_MESSAGE_FIELD_NUMBER /* 132 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_CALLEE_ON_SAME_DEVICE;
            case 133:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_NOT_INSTALLED;
            case 134:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_AIRPLANE_MODE_ENABLED;
            case 135:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_NOT_LOGGED_IN;
            case 136:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_AUTH_FAILED;
            case 137:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_CALLEE_UNREACHABLE;
            case 138:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_DEVICE_DISCONNECTED;
            case 139:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_ENCRYPTION_ERROR;
            case 140:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_TRANSPORT_ERROR;
            case 141:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_COMPANION_CONFIG_ERROR;
            case 142:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_DATAX_SEND_FAILURE;
            case 143:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_APP_WAKE_FAILED;
            case MediaCodecVideoEncoder.MIN_ENCODER_HEIGHT /* 144 */:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_GROUP_PARTICIPANTS_LIMIT_EXCEEDED;
            case 145:
                return ENGINE_ERR_OUTGOING_CALL_REQUEST_ERROR_FOA_CALL_INTENT_FAILED;
            default:
                return null;
        }
    }

    public static EngineErrno valueOf(String str) {
        return (EngineErrno) Enum.valueOf(EngineErrno.class, str);
    }

    public static EngineErrno[] values() {
        return (EngineErrno[]) $VALUES.clone();
    }

    @Override // com.google.protobuf.Internal.EnumLite
    public final int getNumber() {
        if (this != UNRECOGNIZED) {
            return this.value;
        }
        throw AbstractC25330B9y.A14();
    }

    public EngineErrno(String str, int i, int i2) {
        super(str, i);
        this.value = i2;
    }
}
