package com.facebook.distribgw.client;

import X.AbstractC466125o;
import X.AnonymousClass000;
import X.C51197Nbo;
import X.InterfaceC54578Ozq;
import X.J2B;
import com.whatsapp.calling.voipcalling.Voip;

/* JADX INFO: loaded from: classes11.dex */
public class DGWClientConfig {
    public static final String FB_GATEWAY_DOMAIN = "gateway.facebook.com";
    public static final String WP_GATEWAY_DOMAIN = "gateway.workplace.com";
    public boolean allowRetriableWithConnectivityAwareLayer;
    public final String appId;
    public final String appVersion;
    public final boolean applyQuicEgressQosToTcp;
    public final String certificateRevocationListJSON;
    public final String closeConnectionBlockedIsolationsCsv;
    public final boolean closeConnectionWhenNoRequests;
    public final long closeMnsConnectionThrottlingMs;
    public final boolean closeNetworkConnectionOnTimeout;
    public final int connectionTrafficTracingSamplingRate;
    public final ConnectivityManagerOptions connectivityManagerOptions;
    public final String deviceId;
    public final String deviceOS;
    public final boolean disableCancellationForTigonRequests;
    public final boolean disableRetriableLayer;
    public final String dnsRefreshHosts;
    public final long dnsRefreshIntervalMs;
    public final boolean dnsUseMultinetworkResolver;
    public final boolean eagerStreamGroupEnabled;
    public final boolean enableCertificateRevocation;
    public final boolean enableConnectivityAwareLayer;
    public boolean enableDGWForChatd;
    public boolean enableDGWMCLLogging;
    public final boolean enableEarlyData;
    public final boolean enableEligibilityHashHeader;
    public final boolean enableFetchRegionHintFromWww;
    public final boolean enableHTTP3;
    public final boolean enableHttpVersionCache;
    public final boolean enableLogoutOnAuthFailure;
    public final boolean enablePongOnlyReset;
    public final boolean enableProtocolFallback;
    public final boolean enableQlog;
    public final boolean enableSecureTcpEarlyData;
    public final boolean enableSeparateHTTPClientForTunnel;
    public final boolean enableStreamGroupLoadShedding;
    public final boolean enableTcpReachabilityProbe;
    public final boolean enableTunnelRetriableLayer;
    public final long evLoopThreadPriority;
    public final long eventLoopPriority;
    public final DGWFallbackConfig fallbackConfig;
    public final String familyDeviceId;
    public final boolean fizzMobileEnabled;
    public final boolean forceHTTP2ForTunnel;
    public String gatewayDomain;
    public final long h2MaxRequestsPerConnection;
    public final long h2PingIntervalSeconds;
    public final boolean highPriorityEvLoopThread;
    public final boolean initMNSOnly;
    public final boolean isWorkBuild;
    public final boolean keepStreamGroupAliveAfterLastStream;
    public final InterfaceC54578Ozq matchChatDHost;
    public final boolean matchMqttWakeup;
    public final long maxQlogLines;
    public final String mid;
    public boolean msysBufferRequestWhileNoConnectivity;
    public int msysStreamGroupTransportSampleRate;
    public int msysStreamLifecycleSampleRate;
    public final long mvfstKeepAliveTimeoutSeconds;
    public final Long mvfstMaximumPTOs;
    public final boolean mvfstUseHandshakeTimeout;
    public final boolean mvfstUseUDPSocketConnect;
    public final DGWPersonalizationConfig personalizationConfig;
    public final boolean pqcEnabled;
    public final boolean preferIPv6ForBothTCPAndQUIC;
    public final long qlogSamplingRate;
    public final long quicEgressDscp;
    public final long quicEgressSoPriority;
    public final long quicIdleTimeoutSec;
    public final long quicKeepaliveTimeoutSec;
    public final String quicKnobs;
    public final boolean quicUseMvfstMobileLibrary;
    public final long regionHintCacheTtlHours;
    public final boolean removeAsyncExecutorFromTunnelNetworkCallbacks;
    public final String responseCompression;
    public final DGWStreamGroupRetryableLayerConfig retryableLayerConfig;
    public final long secureTcpReadTimeoutSec;
    public final long secureTcpWriteTimeoutSec;
    public final String serviceIdsDefaultToPaidEndpointCsv;
    public final boolean shouldStreamGroupOwnsTransport;
    public final long streamGroupPingPeriod;
    public final long streamGroupPingTimeout;
    public final long streamGroupStopBgPingDelay;
    public final int streamGroupTrafficTracingSamplingRate;
    public final long streamIdleTimeoutMs;
    public final long tcpConnectTimeoutSec;
    public final long tcpDelayMs;
    public final long tigonCloseConnectionThrottleMs;
    public final boolean tigonCloseWhenNoRequests;
    public final boolean tigonNoCallbacksAfterCancel;
    public final long transactionReceiveTimeoutSec;
    public final boolean tunnelConnectAckDisableConnectionClosure;
    public final boolean tunnelConnectAckTimeoutAfterStreamReady;
    public final boolean tunnelDeferReadyStateCleanup;
    public final boolean useCachedStreamGroupsStatus;
    public final boolean useEventLoopPriority;
    public final boolean useExecutorProxies;
    public final boolean useExecutorProxiesPhaseThree;
    public final boolean useExecutorProxiesPhaseTwo;
    public final boolean useSharedEventLoop;
    public boolean useTigon;
    public boolean useTigonInDeprecatedMNSClient;
    public final boolean useTunnelExecutor;
    public final String userAgent;
    public final InterfaceC54578Ozq zeroRatingCachingEnabled;
    public final InterfaceC54578Ozq zeroRatingDefaultToFreeHost;
    public final InterfaceC54578Ozq zeroRatingEnabled;
    public final InterfaceC54578Ozq zeroUrlRewritingV2Enabled;

    public static C51197Nbo newBuilder() {
        return new C51197Nbo();
    }

    public String getDeviceOS(String str) {
        String str2 = this.deviceOS;
        return str2 != null ? str2 : str;
    }

    public DGWFallbackConfig getFallbackConfig() {
        DGWFallbackConfig dGWFallbackConfig = this.fallbackConfig;
        return dGWFallbackConfig == null ? new DGWFallbackConfig(false, Voip.REJECT_REASON_DECLINED, 0, Voip.REJECT_REASON_DECLINED) : dGWFallbackConfig;
    }

    public String getGatewayDomain() {
        String str = this.gatewayDomain;
        if (str == null) {
            return this.isWorkBuild ? WP_GATEWAY_DOMAIN : FB_GATEWAY_DOMAIN;
        }
        return str;
    }

    public String getPaidGatewayDomain() {
        return this.isWorkBuild ? WP_GATEWAY_DOMAIN : FB_GATEWAY_DOMAIN;
    }

    public String toString() {
        StringBuilder sbA08 = AnonymousClass000.A08();
        sbA08.append("{deviceOS:");
        sbA08.append(this.deviceOS);
        sbA08.append(",isWorkBuild:");
        sbA08.append(this.isWorkBuild);
        sbA08.append(",appVersion:");
        sbA08.append(this.appVersion);
        sbA08.append(",appId:");
        sbA08.append(this.appId);
        sbA08.append(",streamIdleTimeoutMs:");
        sbA08.append(this.streamIdleTimeoutMs);
        sbA08.append(",responseCompression:");
        sbA08.append(this.responseCompression);
        sbA08.append(",enableHTTP3:");
        sbA08.append(this.enableHTTP3);
        sbA08.append(",zeroRatingEnabled:");
        Boolean boolA11 = AbstractC466125o.A11();
        sbA08.append(boolA11);
        sbA08.append(",zeroUrlRewritingV2Enabled:");
        sbA08.append(boolA11);
        sbA08.append(",zeroRatingCachingEnabled:");
        sbA08.append(boolA11);
        sbA08.append(",matchChatDHost:");
        sbA08.append(boolA11);
        sbA08.append(",gatewayDomain:");
        sbA08.append(this.gatewayDomain);
        sbA08.append(",streamGroupPingPeriod:");
        sbA08.append(this.streamGroupPingPeriod);
        sbA08.append(",streamGroupPingTimeout:");
        sbA08.append(this.streamGroupPingTimeout);
        sbA08.append(",streamGroupStopBgPingDelay:");
        sbA08.append(this.streamGroupStopBgPingDelay);
        sbA08.append(",useCachedStreamGroupsStatus:");
        sbA08.append(this.useCachedStreamGroupsStatus);
        sbA08.append(",closeNetworkConnectionOnTimeout:");
        sbA08.append(this.closeNetworkConnectionOnTimeout);
        sbA08.append(",connectivityManagerOptions:");
        sbA08.append(this.connectivityManagerOptions);
        sbA08.append(",personalizationConfig:");
        sbA08.append(this.personalizationConfig);
        sbA08.append(",eagerStreamGroupEnabled:");
        sbA08.append(this.eagerStreamGroupEnabled);
        sbA08.append(",keepStreamGroupAliveAfterLastStream:");
        sbA08.append(this.keepStreamGroupAliveAfterLastStream);
        sbA08.append(",enableFetchRegionHintFromWww:");
        sbA08.append(this.enableFetchRegionHintFromWww);
        sbA08.append(",regionHintCacheTtlHours:");
        sbA08.append(this.regionHintCacheTtlHours);
        sbA08.append(",matchMqttWakeup:");
        sbA08.append(this.matchMqttWakeup);
        sbA08.append(",enableTunnelRetriableLayer:");
        sbA08.append(this.enableTunnelRetriableLayer);
        sbA08.append(",useExecutorProxies:");
        sbA08.append(this.useExecutorProxies);
        sbA08.append(",useExecutorProxiesPhaseTwo:");
        sbA08.append(this.useExecutorProxiesPhaseTwo);
        sbA08.append(",useExecutorProxiesPhaseThree:");
        sbA08.append(this.useExecutorProxiesPhaseThree);
        sbA08.append(",fallbackConfig:");
        sbA08.append(this.fallbackConfig);
        sbA08.append(",retryableLayerConfig:");
        sbA08.append(this.retryableLayerConfig);
        sbA08.append(",enableEligibilityHashHeader:");
        sbA08.append(this.enableEligibilityHashHeader);
        sbA08.append(",userAgent:");
        sbA08.append(this.userAgent);
        sbA08.append(",removeAsyncExecutorFromTunnelNetworkCallbacks:");
        sbA08.append(this.removeAsyncExecutorFromTunnelNetworkCallbacks);
        sbA08.append(",msysStreamGroupTransportSampleRate:");
        sbA08.append(this.msysStreamGroupTransportSampleRate);
        sbA08.append(",msysStreamLifecycleSampleRate:");
        sbA08.append(this.msysStreamLifecycleSampleRate);
        sbA08.append(",enableDGWForChatd:");
        sbA08.append(this.enableDGWForChatd);
        sbA08.append(",useTigon:");
        sbA08.append(this.useTigon);
        sbA08.append(",useTigonInDeprecatedMNSClient:");
        sbA08.append(this.useTigonInDeprecatedMNSClient);
        sbA08.append(",allowRetriableWithConnectivityAwareLayer:");
        sbA08.append(this.allowRetriableWithConnectivityAwareLayer);
        sbA08.append(",msysBufferRequestWhileNoConnectivity:");
        sbA08.append(this.msysBufferRequestWhileNoConnectivity);
        sbA08.append(", disableRetriableLayer:");
        sbA08.append(this.disableRetriableLayer);
        sbA08.append(", enableConnectivityAwareLayer:");
        sbA08.append(this.enableConnectivityAwareLayer);
        sbA08.append(", disableCancellationForTigonRequests:");
        sbA08.append(this.disableCancellationForTigonRequests);
        sbA08.append(", tigonCloseConnectionThrottleMs:");
        sbA08.append(this.tigonCloseConnectionThrottleMs);
        sbA08.append(", tigonCloseWhenNoRequests:");
        sbA08.append(this.tigonCloseWhenNoRequests);
        sbA08.append(", tigonNoCallbacksAfterCancel:");
        sbA08.append(this.tigonNoCallbacksAfterCancel);
        sbA08.append(", h2MaxRequestsPerConnection:");
        sbA08.append(this.h2MaxRequestsPerConnection);
        sbA08.append(", mvfstUseUDPSocketConnect:");
        sbA08.append(this.mvfstUseUDPSocketConnect);
        sbA08.append(", enableLogoutOnAuthFailure:");
        sbA08.append(this.enableLogoutOnAuthFailure);
        sbA08.append(", useTunnelExecutor:");
        sbA08.append(this.useTunnelExecutor);
        sbA08.append(", tunnelConnectAckDisableConnectionClosure:");
        sbA08.append(this.tunnelConnectAckDisableConnectionClosure);
        sbA08.append(", mvfstKeepAliveTimeoutSeconds:");
        sbA08.append(this.mvfstKeepAliveTimeoutSeconds);
        sbA08.append(", enableSeparateHTTPClientForTunnel:");
        sbA08.append(this.enableSeparateHTTPClientForTunnel);
        sbA08.append(", forceHTTP2ForTunnel:");
        sbA08.append(this.forceHTTP2ForTunnel);
        sbA08.append(", enableCertificateRevocation:");
        sbA08.append(this.enableCertificateRevocation);
        sbA08.append(", certificateRevocationListJSON:");
        sbA08.append(this.certificateRevocationListJSON);
        sbA08.append(", mvfstMaximumPTOs");
        return J2B.A0h(this.mvfstMaximumPTOs, sbA08);
    }

    public DGWClientConfig(int i, int i2, String str, String str2, String str3, String str4, ConnectivityManagerOptions connectivityManagerOptions, boolean z, String str5, String str6, long j, String str7, boolean z2, InterfaceC54578Ozq interfaceC54578Ozq, InterfaceC54578Ozq interfaceC54578Ozq2, InterfaceC54578Ozq interfaceC54578Ozq3, InterfaceC54578Ozq interfaceC54578Ozq4, InterfaceC54578Ozq interfaceC54578Ozq5, String str8, long j2, long j3, long j4, boolean z3, DGWPersonalizationConfig dGWPersonalizationConfig, DGWStreamGroupRetryableLayerConfig dGWStreamGroupRetryableLayerConfig, boolean z4, boolean z5, boolean z6, long j5, long j6, boolean z7, boolean z8, boolean z9, long j7, boolean z10, boolean z11, boolean z12, boolean z13, boolean z14, DGWFallbackConfig dGWFallbackConfig, boolean z15, String str9, boolean z16, int i3, int i4, boolean z17, boolean z18, boolean z19, boolean z20, boolean z21, boolean z22, boolean z23, long j8, long j9, long j10, long j11, boolean z24, boolean z25, boolean z26, boolean z27, boolean z28, long j12, long j13, long j14, long j15, long j16, boolean z29, long j17, boolean z30, boolean z31, long j18, long j19, boolean z32, String str10, boolean z33, boolean z34, boolean z35, boolean z36, long j20, boolean z37, boolean z38, boolean z39, long j21, boolean z40, boolean z41, long j22, boolean z42, boolean z43, boolean z44, boolean z45, boolean z46, boolean z47, long j23, boolean z48, boolean z49, boolean z50, String str11, long j24, boolean z51, String str12, String str13, boolean z52, String str14, long j25, boolean z53, boolean z54, boolean z55) {
        this.streamGroupTrafficTracingSamplingRate = i;
        this.connectionTrafficTracingSamplingRate = i2;
        this.deviceOS = str4;
        this.deviceId = str;
        this.familyDeviceId = str2;
        this.mid = str3;
        this.connectivityManagerOptions = connectivityManagerOptions;
        this.isWorkBuild = z;
        this.appId = str5;
        this.appVersion = str6;
        this.streamIdleTimeoutMs = j;
        this.responseCompression = str7;
        this.enableHTTP3 = z2;
        this.zeroRatingEnabled = interfaceC54578Ozq;
        this.zeroUrlRewritingV2Enabled = interfaceC54578Ozq2;
        this.zeroRatingCachingEnabled = interfaceC54578Ozq3;
        this.matchChatDHost = interfaceC54578Ozq4;
        this.zeroRatingDefaultToFreeHost = interfaceC54578Ozq5;
        this.gatewayDomain = str8;
        this.streamGroupPingPeriod = j2;
        this.streamGroupPingTimeout = j3;
        this.streamGroupStopBgPingDelay = j4;
        this.enableStreamGroupLoadShedding = z3;
        this.personalizationConfig = dGWPersonalizationConfig;
        this.retryableLayerConfig = dGWStreamGroupRetryableLayerConfig;
        this.useCachedStreamGroupsStatus = z4;
        this.closeNetworkConnectionOnTimeout = z5;
        this.enableQlog = z6;
        this.qlogSamplingRate = j5;
        this.maxQlogLines = j6;
        this.eagerStreamGroupEnabled = z7;
        this.keepStreamGroupAliveAfterLastStream = z8;
        this.enableFetchRegionHintFromWww = z9;
        this.regionHintCacheTtlHours = j7;
        this.matchMqttWakeup = z10;
        this.enableTunnelRetriableLayer = z11;
        this.useExecutorProxies = z12;
        this.useExecutorProxiesPhaseTwo = z13;
        this.useExecutorProxiesPhaseThree = z14;
        this.fallbackConfig = dGWFallbackConfig;
        this.enableEligibilityHashHeader = z15;
        this.userAgent = str9;
        this.removeAsyncExecutorFromTunnelNetworkCallbacks = z16;
        this.msysStreamGroupTransportSampleRate = i3;
        this.msysStreamLifecycleSampleRate = i4;
        this.enableDGWMCLLogging = z17;
        this.enableDGWForChatd = z18;
        this.useTigon = z19;
        this.useTigonInDeprecatedMNSClient = z20;
        this.initMNSOnly = z21;
        this.allowRetriableWithConnectivityAwareLayer = z22;
        this.msysBufferRequestWhileNoConnectivity = z23;
        this.quicIdleTimeoutSec = j8;
        this.quicKeepaliveTimeoutSec = j9;
        this.quicEgressDscp = j10;
        this.quicEgressSoPriority = j11;
        this.applyQuicEgressQosToTcp = z24;
        this.enableEarlyData = z25;
        this.enableSecureTcpEarlyData = z26;
        this.fizzMobileEnabled = z27;
        this.pqcEnabled = z28;
        this.tcpDelayMs = j12;
        this.tcpConnectTimeoutSec = j13;
        this.secureTcpReadTimeoutSec = j14;
        this.secureTcpWriteTimeoutSec = j15;
        this.transactionReceiveTimeoutSec = j16;
        this.highPriorityEvLoopThread = z29;
        this.evLoopThreadPriority = j17;
        this.useSharedEventLoop = z30;
        this.useEventLoopPriority = z31;
        this.eventLoopPriority = j18;
        this.h2PingIntervalSeconds = j19;
        this.enableHttpVersionCache = z32;
        this.quicKnobs = str10;
        this.quicUseMvfstMobileLibrary = z33;
        this.mvfstUseHandshakeTimeout = z34;
        this.preferIPv6ForBothTCPAndQUIC = z35;
        this.closeConnectionWhenNoRequests = z36;
        this.closeMnsConnectionThrottlingMs = j20;
        this.disableRetriableLayer = z37;
        this.enableConnectivityAwareLayer = z38;
        this.disableCancellationForTigonRequests = z39;
        this.tigonCloseConnectionThrottleMs = j21;
        this.tigonCloseWhenNoRequests = z40;
        this.tigonNoCallbacksAfterCancel = z41;
        this.h2MaxRequestsPerConnection = j22;
        this.mvfstUseUDPSocketConnect = z42;
        this.enableLogoutOnAuthFailure = z43;
        this.useTunnelExecutor = z44;
        this.tunnelConnectAckDisableConnectionClosure = z45;
        this.tunnelConnectAckTimeoutAfterStreamReady = z46;
        this.tunnelDeferReadyStateCleanup = z47;
        this.mvfstKeepAliveTimeoutSeconds = j23;
        this.enableSeparateHTTPClientForTunnel = z48;
        this.forceHTTP2ForTunnel = z49;
        this.enableCertificateRevocation = z50;
        this.certificateRevocationListJSON = str11;
        this.mvfstMaximumPTOs = Long.valueOf(j24);
        this.shouldStreamGroupOwnsTransport = z51;
        this.closeConnectionBlockedIsolationsCsv = str12;
        this.serviceIdsDefaultToPaidEndpointCsv = str13;
        this.enableTcpReachabilityProbe = z52;
        this.dnsRefreshHosts = str14;
        this.dnsRefreshIntervalMs = j25;
        this.enableProtocolFallback = z53;
        this.dnsUseMultinetworkResolver = z54;
        this.enablePongOnlyReset = z55;
    }
}
