package com.google.android.gms.internal.mlkit_genai_speech;

import X.C26698BmO;
import X.C46447KtI;
import X.L4C;
import X.ME6;
import X.MIc;
import com.whatsapp.calling.opengl.MediaCodecVideoEncoder;
import com.whatsapp.ui.coreui.base.WaTextView;

/* JADX INFO: loaded from: classes12.dex */
public final class zzqj implements MIc {
    public static final C46447KtI zzA;
    public static final C46447KtI zzB;
    public static final C46447KtI zzC;
    public static final C46447KtI zzD;
    public static final C46447KtI zzE;
    public static final C46447KtI zzF;
    public static final C46447KtI zzG;
    public static final C46447KtI zzH;
    public static final C46447KtI zzI;
    public static final C46447KtI zzJ;
    public static final C46447KtI zzK;
    public static final C46447KtI zzL;
    public static final C46447KtI zzM;
    public static final C46447KtI zzN;
    public static final C46447KtI zzO;
    public static final C46447KtI zzP;
    public static final C46447KtI zzQ;
    public static final C46447KtI zzR;
    public static final C46447KtI zzS;
    public static final C46447KtI zzT;
    public static final C46447KtI zzU;
    public static final C46447KtI zzV;
    public static final C46447KtI zzW;
    public static final C46447KtI zzX;
    public static final C46447KtI zzY;
    public static final C46447KtI zzZ;
    public static final zzqj zza = new zzqj();
    public static final C46447KtI zzaA;
    public static final C46447KtI zzaB;
    public static final C46447KtI zzaC;
    public static final C46447KtI zzaD;
    public static final C46447KtI zzaE;
    public static final C46447KtI zzaF;
    public static final C46447KtI zzaG;
    public static final C46447KtI zzaH;
    public static final C46447KtI zzaI;
    public static final C46447KtI zzaJ;
    public static final C46447KtI zzaK;
    public static final C46447KtI zzaL;
    public static final C46447KtI zzaM;
    public static final C46447KtI zzaN;
    public static final C46447KtI zzaO;
    public static final C46447KtI zzaP;
    public static final C46447KtI zzaQ;
    public static final C46447KtI zzaR;
    public static final C46447KtI zzaS;
    public static final C46447KtI zzaT;
    public static final C46447KtI zzaU;
    public static final C46447KtI zzaV;
    public static final C46447KtI zzaW;
    public static final C46447KtI zzaX;
    public static final C46447KtI zzaY;
    public static final C46447KtI zzaZ;
    public static final C46447KtI zzaa;
    public static final C46447KtI zzab;
    public static final C46447KtI zzac;
    public static final C46447KtI zzad;
    public static final C46447KtI zzae;
    public static final C46447KtI zzaf;
    public static final C46447KtI zzag;
    public static final C46447KtI zzah;
    public static final C46447KtI zzai;
    public static final C46447KtI zzaj;
    public static final C46447KtI zzak;
    public static final C46447KtI zzal;
    public static final C46447KtI zzam;
    public static final C46447KtI zzan;
    public static final C46447KtI zzao;
    public static final C46447KtI zzap;
    public static final C46447KtI zzaq;
    public static final C46447KtI zzar;
    public static final C46447KtI zzas;
    public static final C46447KtI zzat;
    public static final C46447KtI zzau;
    public static final C46447KtI zzav;
    public static final C46447KtI zzaw;
    public static final C46447KtI zzax;
    public static final C46447KtI zzay;
    public static final C46447KtI zzaz;
    public static final C46447KtI zzb;
    public static final C46447KtI zzbA;
    public static final C46447KtI zzbB;
    public static final C46447KtI zzbC;
    public static final C46447KtI zzbD;
    public static final C46447KtI zzbE;
    public static final C46447KtI zzbF;
    public static final C46447KtI zzbG;
    public static final C46447KtI zzbH;
    public static final C46447KtI zzbI;
    public static final C46447KtI zzbJ;
    public static final C46447KtI zzbK;
    public static final C46447KtI zzbL;
    public static final C46447KtI zzbM;
    public static final C46447KtI zzbN;
    public static final C46447KtI zzbO;
    public static final C46447KtI zzbP;
    public static final C46447KtI zzbQ;
    public static final C46447KtI zzbR;
    public static final C46447KtI zzbS;
    public static final C46447KtI zzbT;
    public static final C46447KtI zzbU;
    public static final C46447KtI zzba;
    public static final C46447KtI zzbb;
    public static final C46447KtI zzbc;
    public static final C46447KtI zzbd;
    public static final C46447KtI zzbe;
    public static final C46447KtI zzbf;
    public static final C46447KtI zzbg;
    public static final C46447KtI zzbh;
    public static final C46447KtI zzbi;
    public static final C46447KtI zzbj;
    public static final C46447KtI zzbk;
    public static final C46447KtI zzbl;
    public static final C46447KtI zzbm;
    public static final C46447KtI zzbn;
    public static final C46447KtI zzbo;
    public static final C46447KtI zzbp;
    public static final C46447KtI zzbq;
    public static final C46447KtI zzbr;
    public static final C46447KtI zzbs;
    public static final C46447KtI zzbt;
    public static final C46447KtI zzbu;
    public static final C46447KtI zzbv;
    public static final C46447KtI zzbw;
    public static final C46447KtI zzbx;
    public static final C46447KtI zzby;
    public static final C46447KtI zzbz;
    public static final C46447KtI zzc;
    public static final C46447KtI zzd;
    public static final C46447KtI zze;
    public static final C46447KtI zzf;
    public static final C46447KtI zzg;
    public static final C46447KtI zzh;
    public static final C46447KtI zzi;
    public static final C46447KtI zzj;
    public static final C46447KtI zzk;
    public static final C46447KtI zzl;
    public static final C46447KtI zzm;
    public static final C46447KtI zzn;
    public static final C46447KtI zzo;
    public static final C46447KtI zzp;
    public static final C46447KtI zzq;
    public static final C46447KtI zzr;
    public static final C46447KtI zzs;
    public static final C46447KtI zzt;
    public static final C46447KtI zzu;
    public static final C46447KtI zzv;
    public static final C46447KtI zzw;
    public static final C46447KtI zzx;
    public static final C46447KtI zzy;
    public static final C46447KtI zzz;

    static {
        L4C l4cA06 = L4C.A06("systemInfo");
        zzjz zzjzVar = zzjz.DEFAULT;
        zzb = L4C.A07(zzjzVar, l4cA06, 1);
        zzc = L4C.A07(zzjzVar, L4C.A06("eventName"), 2);
        zzd = L4C.A07(zzjzVar, L4C.A06("isThickClient"), 37);
        zze = L4C.A07(zzjzVar, L4C.A06("clientType"), 61);
        zzf = L4C.A07(zzjzVar, L4C.A06("modelDownloadLogEvent"), 3);
        zzg = L4C.A07(zzjzVar, L4C.A06("customModelLoadLogEvent"), 20);
        zzh = L4C.A07(zzjzVar, L4C.A06("customModelInferenceLogEvent"), 4);
        zzi = L4C.A07(zzjzVar, L4C.A06("customModelCreateLogEvent"), 29);
        zzj = L4C.A07(zzjzVar, L4C.A06("onDeviceFaceDetectionLogEvent"), 5);
        zzk = L4C.A07(zzjzVar, L4C.A06("onDeviceFaceLoadLogEvent"), 59);
        zzl = L4C.A07(zzjzVar, L4C.A06("onDeviceTextDetectionLogEvent"), 6);
        zzm = L4C.A07(zzjzVar, L4C.A06("onDeviceTextDetectionLoadLogEvent"), 79);
        zzn = L4C.A07(zzjzVar, L4C.A06("onDeviceBarcodeDetectionLogEvent"), 7);
        zzo = L4C.A07(zzjzVar, L4C.A06("onDeviceBarcodeLoadLogEvent"), 58);
        zzp = L4C.A07(zzjzVar, L4C.A06("onDeviceImageLabelCreateLogEvent"), 48);
        zzq = L4C.A07(zzjzVar, L4C.A06("onDeviceImageLabelLoadLogEvent"), 49);
        zzr = L4C.A07(zzjzVar, L4C.A06("onDeviceImageLabelDetectionLogEvent"), 18);
        zzs = L4C.A07(zzjzVar, L4C.A06("onDeviceObjectCreateLogEvent"), 26);
        zzt = L4C.A07(zzjzVar, L4C.A06("onDeviceObjectLoadLogEvent"), 27);
        zzu = L4C.A07(zzjzVar, L4C.A06("onDeviceObjectInferenceLogEvent"), 28);
        zzv = L4C.A07(zzjzVar, L4C.A06("onDevicePoseDetectionLogEvent"), 44);
        zzw = L4C.A07(zzjzVar, L4C.A06("onDeviceSegmentationLogEvent"), 45);
        zzx = L4C.A07(zzjzVar, L4C.A06("onDeviceSmartReplyLogEvent"), 19);
        zzy = L4C.A07(zzjzVar, L4C.A06("onDeviceLanguageIdentificationLogEvent"), 21);
        zzz = L4C.A07(zzjzVar, L4C.A06("onDeviceTranslationLogEvent"), 22);
        zzA = L4C.A07(zzjzVar, L4C.A06("cloudFaceDetectionLogEvent"), 8);
        zzB = L4C.A07(zzjzVar, L4C.A06("cloudCropHintDetectionLogEvent"), 9);
        zzC = L4C.A07(zzjzVar, L4C.A06("cloudDocumentTextDetectionLogEvent"), 10);
        zzD = L4C.A07(zzjzVar, L4C.A06("cloudImagePropertiesDetectionLogEvent"), 11);
        zzE = L4C.A07(zzjzVar, L4C.A06("cloudImageLabelDetectionLogEvent"), 12);
        zzF = L4C.A07(zzjzVar, L4C.A06("cloudLandmarkDetectionLogEvent"), 13);
        zzG = L4C.A07(zzjzVar, L4C.A06("cloudLogoDetectionLogEvent"), 14);
        zzH = L4C.A07(zzjzVar, L4C.A06("cloudSafeSearchDetectionLogEvent"), 15);
        zzI = L4C.A07(zzjzVar, L4C.A06("cloudTextDetectionLogEvent"), 16);
        zzJ = L4C.A07(zzjzVar, L4C.A06("cloudWebSearchDetectionLogEvent"), 17);
        zzK = L4C.A07(zzjzVar, L4C.A06("automlImageLabelingCreateLogEvent"), 23);
        zzL = L4C.A07(zzjzVar, L4C.A06("automlImageLabelingLoadLogEvent"), 24);
        zzM = L4C.A07(zzjzVar, L4C.A06("automlImageLabelingInferenceLogEvent"), 25);
        zzN = L4C.A07(zzjzVar, L4C.A06("isModelDownloadedLogEvent"), 39);
        zzO = L4C.A07(zzjzVar, L4C.A06("deleteModelLogEvent"), 40);
        zzP = L4C.A07(zzjzVar, L4C.A06("aggregatedAutomlImageLabelingInferenceLogEvent"), 30);
        zzQ = L4C.A07(zzjzVar, L4C.A06("aggregatedCustomModelInferenceLogEvent"), 31);
        zzR = L4C.A07(zzjzVar, L4C.A06("aggregatedOnDeviceFaceDetectionLogEvent"), 32);
        zzS = L4C.A07(zzjzVar, L4C.A06("aggregatedOnDeviceBarcodeDetectionLogEvent"), 33);
        zzT = L4C.A07(zzjzVar, L4C.A06("aggregatedOnDeviceImageLabelDetectionLogEvent"), 34);
        zzU = L4C.A07(zzjzVar, L4C.A06("aggregatedOnDeviceObjectInferenceLogEvent"), 35);
        zzV = L4C.A07(zzjzVar, L4C.A06("aggregatedOnDeviceTextDetectionLogEvent"), 36);
        zzW = L4C.A07(zzjzVar, L4C.A06("aggregatedOnDevicePoseDetectionLogEvent"), 46);
        zzX = L4C.A07(zzjzVar, L4C.A06("aggregatedOnDeviceSegmentationLogEvent"), 47);
        zzY = L4C.A07(zzjzVar, L4C.A06("pipelineAccelerationInferenceEvents"), 69);
        zzZ = L4C.A07(zzjzVar, L4C.A06("remoteConfigLogEvent"), 42);
        zzaa = L4C.A07(zzjzVar, L4C.A06("inputImageConstructionLogEvent"), 50);
        zzab = L4C.A07(zzjzVar, L4C.A06("leakedHandleEvent"), 51);
        zzac = L4C.A07(zzjzVar, L4C.A06("cameraSourceLogEvent"), 52);
        zzad = L4C.A07(zzjzVar, L4C.A06("imageLabelOptionalModuleLogEvent"), 53);
        zzae = L4C.A07(zzjzVar, L4C.A06("languageIdentificationOptionalModuleLogEvent"), 54);
        zzaf = L4C.A07(zzjzVar, L4C.A06("faceDetectionOptionalModuleLogEvent"), 60);
        zzag = L4C.A07(zzjzVar, L4C.A06("documentDetectionOptionalModuleLogEvent"), 85);
        zzah = L4C.A07(zzjzVar, L4C.A06("documentCroppingOptionalModuleLogEvent"), 86);
        zzai = L4C.A07(zzjzVar, L4C.A06("documentEnhancementOptionalModuleLogEvent"), 87);
        zzaj = L4C.A07(zzjzVar, L4C.A06("nlClassifierOptionalModuleLogEvent"), 55);
        zzak = L4C.A07(zzjzVar, L4C.A06("nlClassifierClientLibraryLogEvent"), 56);
        zzal = L4C.A07(zzjzVar, L4C.A06("accelerationAllowlistLogEvent"), 57);
        zzam = L4C.A07(zzjzVar, L4C.A06("toxicityDetectionCreateEvent"), 62);
        zzan = L4C.A07(zzjzVar, L4C.A06("toxicityDetectionLoadEvent"), 63);
        zzao = L4C.A07(zzjzVar, L4C.A06("toxicityDetectionInferenceEvent"), 64);
        zzap = L4C.A07(zzjzVar, L4C.A06("barcodeDetectionOptionalModuleLogEvent"), 65);
        zzaq = L4C.A07(zzjzVar, L4C.A06("customImageLabelOptionalModuleLogEvent"), 66);
        zzar = L4C.A07(zzjzVar, L4C.A06("codeScannerScanApiEvent"), 67);
        zzas = L4C.A07(zzjzVar, L4C.A06("codeScannerOptionalModuleEvent"), 68);
        zzat = L4C.A07(zzjzVar, L4C.A06("onDeviceExplicitContentCreateLogEvent"), 70);
        zzau = L4C.A07(zzjzVar, L4C.A06("onDeviceExplicitContentLoadLogEvent"), 71);
        zzav = L4C.A07(zzjzVar, L4C.A06("onDeviceExplicitContentInferenceLogEvent"), 72);
        zzaw = L4C.A07(zzjzVar, L4C.A06("aggregatedOnDeviceExplicitContentLogEvent"), 73);
        zzax = L4C.A07(zzjzVar, L4C.A06("onDeviceFaceMeshCreateLogEvent"), 74);
        zzay = L4C.A07(zzjzVar, L4C.A06("onDeviceFaceMeshLoadLogEvent"), 75);
        zzaz = L4C.A07(zzjzVar, L4C.A06("onDeviceFaceMeshLogEvent"), 76);
        zzaA = L4C.A07(zzjzVar, L4C.A06("aggregatedOnDeviceFaceMeshLogEvent"), 77);
        zzaB = L4C.A07(zzjzVar, L4C.A06("smartReplyOptionalModuleLogEvent"), 78);
        zzaC = L4C.A07(zzjzVar, L4C.A06("textDetectionOptionalModuleLogEvent"), 80);
        zzaD = L4C.A07(zzjzVar, L4C.A06("onDeviceImageQualityAnalysisCreateLogEvent"), 81);
        zzaE = L4C.A07(zzjzVar, L4C.A06("onDeviceImageQualityAnalysisLoadLogEvent"), 82);
        zzaF = L4C.A07(zzjzVar, L4C.A06("onDeviceImageQualityAnalysisLogEvent"), 83);
        zzaG = L4C.A07(zzjzVar, L4C.A06("aggregatedOnDeviceImageQualityAnalysisLogEvent"), 84);
        zzaH = L4C.A07(zzjzVar, L4C.A06("imageQualityAnalysisOptionalModuleLogEvent"), 88);
        zzaI = L4C.A07(zzjzVar, L4C.A06("imageCaptioningOptionalModuleLogEvent"), 89);
        zzaJ = L4C.A07(zzjzVar, L4C.A06("onDeviceImageCaptioningCreateLogEvent"), 90);
        zzaK = L4C.A07(zzjzVar, L4C.A06("onDeviceImageCaptioningLoadLogEvent"), 91);
        zzaL = L4C.A07(zzjzVar, L4C.A06("onDeviceImageCaptioningInferenceLogEvent"), 92);
        zzaM = L4C.A07(zzjzVar, L4C.A06("aggregatedOnDeviceImageCaptioningInferenceLogEvent"), 93);
        zzaN = L4C.A07(zzjzVar, L4C.A06("onDeviceDocumentDetectionCreateLogEvent"), 94);
        zzaO = L4C.A07(zzjzVar, L4C.A06("onDeviceDocumentDetectionLoadLogEvent"), 95);
        zzaP = L4C.A07(zzjzVar, L4C.A06("onDeviceDocumentDetectionLogEvent"), 96);
        zzaQ = L4C.A07(zzjzVar, L4C.A06("aggregatedOnDeviceDocumentDetectionLogEvent"), 97);
        zzaR = L4C.A07(zzjzVar, L4C.A06("onDeviceDocumentCroppingCreateLogEvent"), 98);
        zzaS = L4C.A07(zzjzVar, L4C.A06("onDeviceDocumentCroppingLoadLogEvent"), 99);
        zzaT = L4C.A07(zzjzVar, L4C.A06("onDeviceDocumentCroppingLogEvent"), 100);
        zzaU = L4C.A07(zzjzVar, L4C.A06("aggregatedOnDeviceDocumentCroppingLogEvent"), 101);
        zzaV = L4C.A07(zzjzVar, L4C.A06("onDeviceDocumentEnhancementCreateLogEvent"), C26698BmO.MESSAGE_HISTORY_NOTICE_FIELD_NUMBER);
        zzaW = L4C.A07(zzjzVar, L4C.A06("onDeviceDocumentEnhancementLoadLogEvent"), C26698BmO.GROUP_STATUS_MESSAGE_V2_FIELD_NUMBER);
        zzaX = L4C.A07(zzjzVar, L4C.A06("onDeviceDocumentEnhancementLogEvent"), C26698BmO.BOT_FORWARDED_MESSAGE_FIELD_NUMBER);
        zzaY = L4C.A07(zzjzVar, L4C.A06("aggregatedOnDeviceDocumentEnhancementLogEvent"), C26698BmO.STATUS_QUESTION_ANSWER_MESSAGE_FIELD_NUMBER);
        zzaZ = L4C.A07(zzjzVar, L4C.A06("scannerAutoZoomEvent"), C26698BmO.QUESTION_REPLY_MESSAGE_FIELD_NUMBER);
        zzba = L4C.A07(zzjzVar, L4C.A06("lowLightAutoExposureComputationEvent"), C26698BmO.QUESTION_RESPONSE_MESSAGE_FIELD_NUMBER);
        zzbb = L4C.A07(zzjzVar, L4C.A06("lowLightFrameProcessEvent"), C26698BmO.NEWSLETTER_FOLLOWER_INVITE_MESSAGE_FIELD_NUMBER);
        zzbc = L4C.A07(zzjzVar, L4C.A06("lowLightSceneDetectionEvent"), C26698BmO.STATUS_QUOTED_MESSAGE_FIELD_NUMBER);
        zzbd = L4C.A07(zzjzVar, L4C.A06("onDeviceStainRemovalLogEvent"), C26698BmO.STATUS_STICKER_INTERACTION_MESSAGE_FIELD_NUMBER);
        zzbe = L4C.A07(zzjzVar, L4C.A06("aggregatedOnDeviceStainRemovalLogEvent"), C26698BmO.POLL_CREATION_MESSAGE_V5_FIELD_NUMBER);
        zzbf = L4C.A07(zzjzVar, L4C.A06("stainRemovalOptionalModuleLogEvent"), 112);
        zzbg = L4C.A07(zzjzVar, L4C.A06("onDeviceShadowRemovalLogEvent"), C26698BmO.NEWSLETTER_FOLLOWER_INVITE_MESSAGE_V2_FIELD_NUMBER);
        zzbh = L4C.A07(zzjzVar, L4C.A06("aggregatedOnDeviceShadowRemovalLogEvent"), 114);
        zzbi = L4C.A07(zzjzVar, L4C.A06("shadowRemovalOptionalModuleLogEvent"), C26698BmO.POLL_RESULT_SNAPSHOT_MESSAGE_V3_FIELD_NUMBER);
        zzbj = L4C.A07(zzjzVar, L4C.A06("onDeviceDigitalInkSegmentationLogEvent"), C26698BmO.NEWSLETTER_ADMIN_PROFILE_MESSAGE_FIELD_NUMBER);
        zzbk = L4C.A07(zzjzVar, L4C.A06("onDeviceDocumentScannerStartLogEvent"), 117);
        zzbl = L4C.A07(zzjzVar, L4C.A06("onDeviceDocumentScannerFinishLogEvent"), C26698BmO.SPOILER_MESSAGE_FIELD_NUMBER);
        zzbm = L4C.A07(zzjzVar, L4C.A06("onDeviceDocumentScannerUiStartLogEvent"), C26698BmO.POLL_CREATION_MESSAGE_V6_FIELD_NUMBER);
        zzbn = L4C.A07(zzjzVar, L4C.A06("onDeviceDocumentScannerUiFinishLogEvent"), 120);
        zzbo = L4C.A07(zzjzVar, L4C.A06("documentScannerUiOptionalModuleSessionStartLogEvent"), C26698BmO.POLL_ADD_OPTION_MESSAGE_FIELD_NUMBER);
        zzbp = L4C.A07(zzjzVar, L4C.A06("documentScannerUiOptionalModuleSessionFinishLogEvent"), C26698BmO.EVENT_INVITE_MESSAGE_FIELD_NUMBER);
        zzbq = L4C.A07(zzjzVar, L4C.A06("onDeviceDocumentScannerUiCreateLogEvent"), C26698BmO.GROUP_ROOT_KEY_SHARE_FIELD_NUMBER);
        zzbr = L4C.A07(zzjzVar, L4C.A06("onDeviceSubjectSegmentationCreateLogEvent"), C26698BmO.PAYMENT_REMINDER_MESSAGE_FIELD_NUMBER);
        zzbs = L4C.A07(zzjzVar, L4C.A06("onDeviceSubjectSegmentationLoadLogEvent"), C26698BmO.SPLIT_PAYMENT_MESSAGE_FIELD_NUMBER);
        zzbt = L4C.A07(zzjzVar, L4C.A06("onDeviceSubjectSegmentationInferenceLogEvent"), C26698BmO.NEWSLETTER_ADMIN_PROFILE_STATUS_MESSAGE_FIELD_NUMBER);
        zzbu = L4C.A07(zzjzVar, L4C.A06("aggregatedOnDeviceSubjectSegmentationLogEvent"), 127);
        zzbv = L4C.A07(zzjzVar, L4C.A06("subjectSegmentationOptionalModuleLogEvent"), 128);
        zzbw = L4C.A07(zzjzVar, L4C.A06("documentScannerUiModuleScreenViewEvent"), C26698BmO.MUSIC_MESSAGE_FIELD_NUMBER);
        zzbx = L4C.A07(zzjzVar, L4C.A06("documentScannerUiModuleScreenClickEvent"), C26698BmO.STATUS_LINK_PREVIEW_METADATA_FIELD_NUMBER);
        zzby = L4C.A07(zzjzVar, L4C.A06("documentScannerUiModuleScreenErrorEvent"), C26698BmO.BOT_PLATFORM_REGISTRATION_SUCCESS_MESSAGE_FIELD_NUMBER);
        zzbz = L4C.A07(zzjzVar, L4C.A06("documentScannerUiModuleScreenTransitionEvent"), MediaCodecVideoEncoder.MIN_ENCODER_HEIGHT);
        zzbA = L4C.A07(zzjzVar, L4C.A06("documentScannerUiModulePreviewScreenUserWaitingEvent"), 145);
        zzbB = L4C.A07(zzjzVar, L4C.A06("documentScannerUiModulePageProcessingEvent"), 146);
        zzbC = L4C.A07(zzjzVar, L4C.A06("sapiSummarizationInferenceEvent"), C26698BmO.NEWSLETTER_SCHEDULED_MESSAGE_FIELD_NUMBER);
        zzbD = L4C.A07(zzjzVar, L4C.A06("sapiProofreadingInferenceEvent"), 133);
        zzbE = L4C.A07(zzjzVar, L4C.A06("sapiRewritingInferenceEvent"), 134);
        zzbF = L4C.A07(zzjzVar, L4C.A06("sapiSummarizationCreateEvent"), 135);
        zzbG = L4C.A07(zzjzVar, L4C.A06("sapiSummarizationCloseEvent"), 136);
        zzbH = L4C.A07(zzjzVar, L4C.A06("sapiProofreadingCreateEvent"), 137);
        zzbI = L4C.A07(zzjzVar, L4C.A06("sapiProofreadingCloseEvent"), 138);
        zzbJ = L4C.A07(zzjzVar, L4C.A06("sapiRewritingCreateEvent"), 139);
        zzbK = L4C.A07(zzjzVar, L4C.A06("sapiRewritingCloseEvent"), 140);
        zzbL = L4C.A07(zzjzVar, L4C.A06("sapiImageDescriptionInferenceEvent"), 141);
        zzbM = L4C.A07(zzjzVar, L4C.A06("sapiImageDescriptionCreateEvent"), 142);
        zzbN = L4C.A07(zzjzVar, L4C.A06("sapiImageDescriptionCloseEvent"), 143);
        zzbO = L4C.A07(zzjzVar, L4C.A06("sapiGenerationInferenceEvent"), 147);
        zzbP = L4C.A07(zzjzVar, L4C.A06("sapiGenerationCreateEvent"), 148);
        zzbQ = L4C.A07(zzjzVar, L4C.A06("sapiGenerationCloseEvent"), 149);
        zzbR = L4C.A07(zzjzVar, L4C.A06("sapiGenerationCountTokensEvent"), 153);
        zzbS = L4C.A07(zzjzVar, L4C.A06("speechRecognitionCreateEvent"), WaTextView.ONE_LINE_DISPLAY_TEXT_LENGTH_LIMIT);
        zzbT = L4C.A07(zzjzVar, L4C.A06("speechRecognitionInferenceEvent"), 151);
        zzbU = L4C.A07(zzjzVar, L4C.A06("speechRecognitionCloseEvent"), 152);
    }

    @Override // X.MBe
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) {
        zzxt zzxtVar = (zzxt) obj;
        ME6 me6 = (ME6) obj2;
        me6.add(zzb, zzxtVar.zza);
        me6.add(zzc, zzxtVar.zzb);
        me6.add(zzd, (Object) null);
        me6.add(zze, (Object) null);
        me6.add(zzf, (Object) null);
        me6.add(zzg, (Object) null);
        me6.add(zzh, (Object) null);
        me6.add(zzi, (Object) null);
        me6.add(zzj, (Object) null);
        me6.add(zzk, (Object) null);
        me6.add(zzl, (Object) null);
        me6.add(zzm, (Object) null);
        me6.add(zzn, (Object) null);
        me6.add(zzo, (Object) null);
        me6.add(zzp, (Object) null);
        me6.add(zzq, (Object) null);
        me6.add(zzr, (Object) null);
        me6.add(zzs, (Object) null);
        me6.add(zzt, (Object) null);
        me6.add(zzu, (Object) null);
        me6.add(zzv, (Object) null);
        me6.add(zzw, (Object) null);
        me6.add(zzx, (Object) null);
        me6.add(zzy, (Object) null);
        me6.add(zzz, (Object) null);
        me6.add(zzA, (Object) null);
        me6.add(zzB, (Object) null);
        me6.add(zzC, (Object) null);
        me6.add(zzD, (Object) null);
        me6.add(zzE, (Object) null);
        me6.add(zzF, (Object) null);
        me6.add(zzG, (Object) null);
        me6.add(zzH, (Object) null);
        me6.add(zzI, (Object) null);
        me6.add(zzJ, (Object) null);
        me6.add(zzK, (Object) null);
        me6.add(zzL, (Object) null);
        me6.add(zzM, (Object) null);
        me6.add(zzN, (Object) null);
        me6.add(zzO, (Object) null);
        me6.add(zzP, (Object) null);
        me6.add(zzQ, (Object) null);
        me6.add(zzR, (Object) null);
        me6.add(zzS, (Object) null);
        me6.add(zzT, (Object) null);
        me6.add(zzU, (Object) null);
        me6.add(zzV, (Object) null);
        me6.add(zzW, (Object) null);
        me6.add(zzX, (Object) null);
        me6.add(zzY, (Object) null);
        me6.add(zzZ, (Object) null);
        me6.add(zzaa, (Object) null);
        me6.add(zzab, (Object) null);
        me6.add(zzac, (Object) null);
        me6.add(zzad, (Object) null);
        me6.add(zzae, (Object) null);
        me6.add(zzaf, (Object) null);
        me6.add(zzag, (Object) null);
        me6.add(zzah, (Object) null);
        me6.add(zzai, (Object) null);
        me6.add(zzaj, (Object) null);
        me6.add(zzak, (Object) null);
        me6.add(zzal, (Object) null);
        me6.add(zzam, (Object) null);
        me6.add(zzan, (Object) null);
        me6.add(zzao, (Object) null);
        me6.add(zzap, (Object) null);
        me6.add(zzaq, (Object) null);
        me6.add(zzar, (Object) null);
        me6.add(zzas, (Object) null);
        me6.add(zzat, (Object) null);
        me6.add(zzau, (Object) null);
        me6.add(zzav, (Object) null);
        me6.add(zzaw, (Object) null);
        me6.add(zzax, (Object) null);
        me6.add(zzay, (Object) null);
        me6.add(zzaz, (Object) null);
        me6.add(zzaA, (Object) null);
        me6.add(zzaB, (Object) null);
        me6.add(zzaC, (Object) null);
        me6.add(zzaD, (Object) null);
        me6.add(zzaE, (Object) null);
        me6.add(zzaF, (Object) null);
        me6.add(zzaG, (Object) null);
        me6.add(zzaH, (Object) null);
        me6.add(zzaI, (Object) null);
        me6.add(zzaJ, (Object) null);
        me6.add(zzaK, (Object) null);
        me6.add(zzaL, (Object) null);
        me6.add(zzaM, (Object) null);
        me6.add(zzaN, (Object) null);
        me6.add(zzaO, (Object) null);
        me6.add(zzaP, (Object) null);
        me6.add(zzaQ, (Object) null);
        me6.add(zzaR, (Object) null);
        me6.add(zzaS, (Object) null);
        me6.add(zzaT, (Object) null);
        me6.add(zzaU, (Object) null);
        me6.add(zzaV, (Object) null);
        me6.add(zzaW, (Object) null);
        me6.add(zzaX, (Object) null);
        me6.add(zzaY, (Object) null);
        me6.add(zzaZ, (Object) null);
        me6.add(zzba, (Object) null);
        me6.add(zzbb, (Object) null);
        me6.add(zzbc, (Object) null);
        me6.add(zzbd, (Object) null);
        me6.add(zzbe, (Object) null);
        me6.add(zzbf, (Object) null);
        me6.add(zzbg, (Object) null);
        me6.add(zzbh, (Object) null);
        me6.add(zzbi, (Object) null);
        me6.add(zzbj, (Object) null);
        me6.add(zzbk, (Object) null);
        me6.add(zzbl, (Object) null);
        me6.add(zzbm, (Object) null);
        me6.add(zzbn, (Object) null);
        me6.add(zzbo, (Object) null);
        me6.add(zzbp, (Object) null);
        me6.add(zzbq, (Object) null);
        me6.add(zzbr, (Object) null);
        me6.add(zzbs, (Object) null);
        me6.add(zzbt, (Object) null);
        me6.add(zzbu, (Object) null);
        me6.add(zzbv, (Object) null);
        me6.add(zzbw, (Object) null);
        me6.add(zzbx, (Object) null);
        me6.add(zzby, (Object) null);
        me6.add(zzbz, (Object) null);
        me6.add(zzbA, (Object) null);
        me6.add(zzbB, (Object) null);
        me6.add(zzbC, (Object) null);
        me6.add(zzbD, (Object) null);
        me6.add(zzbE, (Object) null);
        me6.add(zzbF, (Object) null);
        me6.add(zzbG, (Object) null);
        me6.add(zzbH, (Object) null);
        me6.add(zzbI, (Object) null);
        me6.add(zzbJ, (Object) null);
        me6.add(zzbK, (Object) null);
        me6.add(zzbL, (Object) null);
        me6.add(zzbM, (Object) null);
        me6.add(zzbN, (Object) null);
        me6.add(zzbO, (Object) null);
        me6.add(zzbP, (Object) null);
        me6.add(zzbQ, (Object) null);
        me6.add(zzbR, (Object) null);
        me6.add(zzbS, zzxtVar.zzc);
        me6.add(zzbT, zzxtVar.zzd);
        me6.add(zzbU, zzxtVar.zze);
    }
}
