.class public final LX/ML0;
.super Ljava/lang/Object;
.source ""


# static fields
.field public static final A11:Ljava/util/HashSet;


# instance fields
.field public A00:I

.field public A01:I

.field public A02:I

.field public A03:I

.field public A04:I

.field public A05:J

.field public A06:J

.field public A07:LX/ML5;

.field public A08:LX/ML5;

.field public A09:LX/ML7;

.field public A0A:LX/ML2;

.field public A0B:LX/MLE;

.field public A0C:LX/MLC;

.field public A0D:LX/J2m;

.field public A0E:LX/MLB;

.field public A0F:LX/J2l;

.field public A0G:LX/ML1;

.field public A0H:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

.field public A0I:LX/MKy;

.field public A0J:LX/ML3;

.field public A0K:LX/MLD;

.field public A0L:LX/ML9;

.field public A0M:LX/ML9;

.field public A0N:LX/MLG;

.field public A0O:Ljava/lang/String;

.field public A0P:Ljava/util/HashSet;

.field public A0Q:Ljava/util/Map;

.field public A0R:Ljava/util/Set;

.field public A0S:Ljava/util/Set;

.field public A0T:Ljava/util/Set;

.field public A0U:Ljava/util/Set;

.field public A0V:Ljava/util/Set;

.field public A0W:Ljava/util/Set;

.field public A0X:Ljava/util/Set;

.field public A0Y:Ljava/util/Set;

.field public A0Z:Ljava/util/Set;

.field public A0a:Z

.field public A0b:Z

.field public A0c:Z

.field public A0d:Z

.field public A0e:Z

.field public A0f:Z

.field public A0g:Z

.field public A0h:Z

.field public A0i:Z

.field public A0j:Z

.field public A0k:Z

.field public A0l:Z

.field public A0m:Z

.field public A0n:Z

.field public A0o:Z

.field public A0p:Z

.field public A0q:Z

.field public A0r:Z

.field public A0s:Z

.field public A0t:Z

.field public A0u:Z

.field public A0v:Z

.field public A0w:Z

.field public A0x:Z

.field public A0y:Z

.field public A0z:Z

.field public A10:Z


# direct methods
.method public static constructor <clinit>()V
    .locals 3

    .line 0
    const/4 v0, 0x7

    .line 1
    new-array v2, v0, [Ljava/lang/String;

    .line 2
    .line 3
    const/4 v1, 0x0

    .line 4
    const-string v0, "omx.sprd.av1.decoder"

    .line 5
    .line 6
    aput-object v0, v2, v1

    .line 7
    .line 8
    const/4 v1, 0x1

    .line 9
    const-string v0, "c2.qti.av1.decoder"

    .line 10
    .line 11
    aput-object v0, v2, v1

    .line 12
    .line 13
    const/4 v1, 0x2

    .line 14
    const-string v0, "c2.qti.av1.decoder.low_latency"

    .line 15
    .line 16
    aput-object v0, v2, v1

    .line 17
    .line 18
    const/4 v1, 0x3

    .line 19
    const-string v0, "c2.exynos.av1.decoder"

    .line 20
    .line 21
    aput-object v0, v2, v1

    .line 22
    .line 23
    const/4 v1, 0x4

    .line 24
    const-string v0, "c2.mtk.av1.decoder"

    .line 25
    .line 26
    aput-object v0, v2, v1

    .line 27
    .line 28
    const/4 v1, 0x5

    .line 29
    const-string v0, "omx.mtk.video.decoder.av1"

    .line 30
    .line 31
    aput-object v0, v2, v1

    .line 32
    .line 33
    const/4 v1, 0x6

    .line 34
    const-string v0, "c2.unisoc.av1.decoder"

    .line 35
    .line 36
    invoke-static {v0, v2, v1}, LX/MJm;->A0t(Ljava/lang/Object;[Ljava/lang/Object;I)Ljava/util/List;

    .line 37
    .line 38
    .line 39
    move-result-object v0

    .line 40
    invoke-static {v0}, LX/B9w;->A18(Ljava/util/Collection;)Ljava/util/HashSet;

    .line 41
    .line 42
    .line 43
    move-result-object v0

    .line 44
    sput-object v0, LX/ML0;->A11:Ljava/util/HashSet;

    .line 45
    .line 46
    return-void
.end method

.method public constructor <init>()V
    .locals 8

    .line 0
    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    .line 1
    .line 2
    .line 3
    const/4 v1, 0x0

    .line 4
    const/4 v2, 0x1

    .line 5
    const/4 v7, -0x1

    .line 6
    new-instance v0, LX/ML1;

    .line 7
    .line 8
    invoke-direct {v0}, LX/ML1;-><init>()V

    .line 9
    .line 10
    .line 11
    iput-object v0, p0, LX/ML0;->A0G:LX/ML1;

    .line 12
    .line 13
    sget-object v0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A00:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 14
    .line 15
    iput-object v0, p0, LX/ML0;->A0H:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    .line 16
    .line 17
    iput-boolean v1, p0, LX/ML0;->A0c:Z

    .line 18
    .line 19
    const/4 v0, 0x3

    .line 20
    iput v0, p0, LX/ML0;->A02:I

    .line 21
    .line 22
    const/16 v3, 0x7d0

    .line 23
    .line 24
    const-string v0, "ExoService"

    .line 25
    .line 26
    iput-object v0, p0, LX/ML0;->A0O:Ljava/lang/String;

    .line 27
    .line 28
    iput-boolean v2, p0, LX/ML0;->A0z:Z

    .line 29
    .line 30
    new-instance v0, LX/MLH;

    .line 31
    .line 32
    invoke-direct {v0}, Ljava/lang/Object;-><init>()V

    .line 33
    .line 34
    .line 35
    iget-boolean v2, v0, LX/MLH;->A00:Z

    .line 36
    .line 37
    new-instance v0, LX/J2l;

    .line 38
    .line 39
    invoke-direct {v0, v2}, LX/J2l;-><init>(Z)V

    .line 40
    .line 41
    .line 42
    iput-object v0, p0, LX/ML0;->A0F:LX/J2l;

    .line 43
    .line 44
    const/16 v4, 0x1f4

    .line 45
    .line 46
    new-instance v0, LX/ML9;

    .line 47
    .line 48
    invoke-direct {v0, v4, v3}, LX/ML9;-><init>(II)V

    .line 49
    .line 50
    .line 51
    iput-object v0, p0, LX/ML0;->A0L:LX/ML9;

    .line 52
    .line 53
    new-instance v0, LX/ML9;

    .line 54
    .line 55
    invoke-direct {v0, v1, v1}, LX/ML9;-><init>(II)V

    .line 56
    .line 57
    .line 58
    iput-object v0, p0, LX/ML0;->A0M:LX/ML9;

    .line 59
    .line 60
    const/16 v6, 0xfa0

    .line 61
    .line 62
    new-instance v0, LX/ML3;

    .line 63
    .line 64
    invoke-direct {v0}, LX/ML3;-><init>()V

    .line 65
    .line 66
    .line 67
    iput-object v0, p0, LX/ML0;->A0J:LX/ML3;

    .line 68
    .line 69
    new-instance v2, LX/MLJ;

    .line 70
    .line 71
    invoke-direct {v2}, LX/MLJ;-><init>()V

    .line 72
    .line 73
    .line 74
    new-instance v0, LX/J2m;

    .line 75
    .line 76
    invoke-direct {v0, v2}, LX/J2m;-><init>(LX/MLJ;)V

    .line 77
    .line 78
    .line 79
    iput-object v0, p0, LX/ML0;->A0D:LX/J2m;

    .line 80
    .line 81
    sget-object v0, LX/MLC;->A00:LX/MLC;

    .line 82
    .line 83
    iput-object v0, p0, LX/ML0;->A0C:LX/MLC;

    .line 84
    .line 85
    new-instance v0, LX/MLE;

    .line 86
    .line 87
    invoke-direct {v0}, LX/MLE;-><init>()V

    .line 88
    .line 89
    .line 90
    iput-object v0, p0, LX/ML0;->A0B:LX/MLE;

    .line 91
    .line 92
    new-instance v2, LX/ML8;

    .line 93
    .line 94
    invoke-direct {v2}, LX/ML8;-><init>()V

    .line 95
    .line 96
    .line 97
    new-instance v0, LX/ML2;

    .line 98
    .line 99
    invoke-direct {v0, v2}, LX/ML2;-><init>(LX/ML8;)V

    .line 100
    .line 101
    .line 102
    iput-object v0, p0, LX/ML0;->A0A:LX/ML2;

    .line 103
    .line 104
    new-instance v0, LX/MLB;

    .line 105
    .line 106
    invoke-direct {v0}, LX/MLB;-><init>()V

    .line 107
    .line 108
    .line 109
    iput-object v0, p0, LX/ML0;->A0E:LX/MLB;

    .line 110
    .line 111
    new-instance v0, LX/MLG;

    .line 112
    .line 113
    invoke-direct {v0}, LX/MLG;-><init>()V

    .line 114
    .line 115
    .line 116
    iput-object v0, p0, LX/ML0;->A0N:LX/MLG;

    .line 117
    .line 118
    iput-boolean v1, p0, LX/ML0;->A0w:Z

    .line 119
    .line 120
    new-instance v2, LX/MLA;

    .line 121
    .line 122
    invoke-direct {v2}, Ljava/lang/Object;-><init>()V

    .line 123
    .line 124
    .line 125
    const v0, 0x186a0

    .line 126
    .line 127
    .line 128
    iput v0, v2, LX/MLA;->A00:I

    .line 129
    .line 130
    const/16 v0, 0x3e8

    .line 131
    .line 132
    iput v0, v2, LX/MLA;->A03:I

    .line 133
    .line 134
    iput v4, v2, LX/MLA;->A02:I

    .line 135
    .line 136
    const/16 v0, 0xfa

    .line 137
    .line 138
    iput v0, v2, LX/MLA;->A01:I

    .line 139
    .line 140
    new-instance v0, LX/ML5;

    .line 141
    .line 142
    invoke-direct {v0, v2}, LX/ML5;-><init>(LX/MLA;)V

    .line 143
    .line 144
    .line 145
    iput-object v0, p0, LX/ML0;->A07:LX/ML5;

    .line 146
    .line 147
    new-instance v2, LX/MLA;

    .line 148
    .line 149
    invoke-direct {v2}, Ljava/lang/Object;-><init>()V

    .line 150
    .line 151
    .line 152
    iput v3, v2, LX/MLA;->A00:I

    .line 153
    .line 154
    const v0, 0x249f0

    .line 155
    .line 156
    .line 157
    iput v0, v2, LX/MLA;->A03:I

    .line 158
    .line 159
    const v0, 0x86470

    .line 160
    .line 161
    .line 162
    iput v0, v2, LX/MLA;->A02:I

    .line 163
    .line 164
    const v0, 0x1e8480

    .line 165
    .line 166
    .line 167
    iput v0, v2, LX/MLA;->A01:I

    .line 168
    .line 169
    new-instance v0, LX/ML5;

    .line 170
    .line 171
    invoke-direct {v0, v2}, LX/ML5;-><init>(LX/MLA;)V

    .line 172
    .line 173
    .line 174
    iput-object v0, p0, LX/ML0;->A08:LX/ML5;

    .line 175
    .line 176
    iput-boolean v1, p0, LX/ML0;->A0i:Z

    .line 177
    .line 178
    iput-boolean v1, p0, LX/ML0;->A0q:Z

    .line 179
    .line 180
    iput-boolean v1, p0, LX/ML0;->A0e:Z

    .line 181
    .line 182
    iput-boolean v1, p0, LX/ML0;->A0m:Z

    .line 183
    .line 184
    iput-boolean v1, p0, LX/ML0;->A0l:Z

    .line 185
    .line 186
    iput-boolean v1, p0, LX/ML0;->A0d:Z

    .line 187
    .line 188
    iput-boolean v1, p0, LX/ML0;->A0s:Z

    .line 189
    .line 190
    iput-boolean v1, p0, LX/ML0;->A0r:Z

    .line 191
    .line 192
    iput-boolean v1, p0, LX/ML0;->A0t:Z

    .line 193
    .line 194
    const-wide/16 v4, 0x0

    .line 195
    .line 196
    iput-boolean v1, p0, LX/ML0;->A0x:Z

    .line 197
    .line 198
    const-wide/32 v2, 0x927c0

    .line 199
    .line 200
    .line 201
    iput-wide v2, p0, LX/ML0;->A06:J

    .line 202
    .line 203
    invoke-static {}, LX/25m;->A1D()Ljava/util/HashSet;

    .line 204
    .line 205
    .line 206
    move-result-object v0

    .line 207
    iput-object v0, p0, LX/ML0;->A0P:Ljava/util/HashSet;

    .line 208
    .line 209
    iput-wide v4, p0, LX/ML0;->A05:J

    .line 210
    .line 211
    iput-boolean v1, p0, LX/ML0;->A0u:Z

    .line 212
    .line 213
    invoke-static {}, LX/25m;->A1D()Ljava/util/HashSet;

    .line 214
    .line 215
    .line 216
    move-result-object v0

    .line 217
    iput-object v0, p0, LX/ML0;->A0R:Ljava/util/Set;

    .line 218
    .line 219
    invoke-static {}, LX/25m;->A1C()Ljava/util/HashMap;

    .line 220
    .line 221
    .line 222
    move-result-object v0

    .line 223
    iput-object v0, p0, LX/ML0;->A0Q:Ljava/util/Map;

    .line 224
    .line 225
    iput-boolean v1, p0, LX/ML0;->A0n:Z

    .line 226
    .line 227
    const/16 v0, 0x7530

    .line 228
    .line 229
    iput v0, p0, LX/ML0;->A01:I

    .line 230
    .line 231
    iput v7, p0, LX/ML0;->A04:I

    .line 232
    .line 233
    iput v6, p0, LX/ML0;->A00:I

    .line 234
    .line 235
    invoke-static {}, LX/25m;->A1D()Ljava/util/HashSet;

    .line 236
    .line 237
    .line 238
    move-result-object v0

    .line 239
    iput-object v0, p0, LX/ML0;->A0X:Ljava/util/Set;

    .line 240
    .line 241
    invoke-static {}, LX/25m;->A1D()Ljava/util/HashSet;

    .line 242
    .line 243
    .line 244
    move-result-object v0

    .line 245
    iput-object v0, p0, LX/ML0;->A0W:Ljava/util/Set;

    .line 246
    .line 247
    invoke-static {}, LX/25m;->A1D()Ljava/util/HashSet;

    .line 248
    .line 249
    .line 250
    move-result-object v0

    .line 251
    iput-object v0, p0, LX/ML0;->A0Y:Ljava/util/Set;

    .line 252
    .line 253
    invoke-static {}, LX/25m;->A1D()Ljava/util/HashSet;

    .line 254
    .line 255
    .line 256
    move-result-object v0

    .line 257
    iput-object v0, p0, LX/ML0;->A0S:Ljava/util/Set;

    .line 258
    .line 259
    new-instance v0, LX/MLD;

    .line 260
    .line 261
    invoke-direct {v0}, LX/MLD;-><init>()V

    .line 262
    .line 263
    .line 264
    iput-object v0, p0, LX/ML0;->A0K:LX/MLD;

    .line 265
    .line 266
    invoke-static {}, LX/25m;->A1D()Ljava/util/HashSet;

    .line 267
    .line 268
    .line 269
    move-result-object v0

    .line 270
    iput-object v0, p0, LX/ML0;->A0V:Ljava/util/Set;

    .line 271
    .line 272
    invoke-static {}, LX/25m;->A1D()Ljava/util/HashSet;

    .line 273
    .line 274
    .line 275
    move-result-object v0

    .line 276
    iput-object v0, p0, LX/ML0;->A0U:Ljava/util/Set;

    .line 277
    .line 278
    invoke-static {}, LX/25m;->A1D()Ljava/util/HashSet;

    .line 279
    .line 280
    .line 281
    move-result-object v0

    .line 282
    iput-object v0, p0, LX/ML0;->A0Z:Ljava/util/Set;

    .line 283
    .line 284
    invoke-static {}, LX/25m;->A1D()Ljava/util/HashSet;

    .line 285
    .line 286
    .line 287
    move-result-object v0

    .line 288
    iput-object v0, p0, LX/ML0;->A0T:Ljava/util/Set;

    .line 289
    .line 290
    iput-boolean v1, p0, LX/ML0;->A0b:Z

    .line 291
    .line 292
    iput-boolean v1, p0, LX/ML0;->A0j:Z

    .line 293
    .line 294
    iput-boolean v1, p0, LX/ML0;->A0k:Z

    .line 295
    .line 296
    const/4 v0, 0x0

    .line 297
    iput-object v0, p0, LX/ML0;->A0I:LX/MKy;

    .line 298
    .line 299
    iput-boolean v1, p0, LX/ML0;->A0p:Z

    .line 300
    .line 301
    iput-boolean v1, p0, LX/ML0;->A0h:Z

    .line 302
    .line 303
    iput-boolean v1, p0, LX/ML0;->A0g:Z

    .line 304
    .line 305
    iput-boolean v1, p0, LX/ML0;->A0f:Z

    .line 306
    .line 307
    const/16 v3, 0x3e8

    .line 308
    .line 309
    const/16 v4, 0x7d0

    .line 310
    .line 311
    const v7, 0x8000

    .line 312
    .line 313
    .line 314
    new-instance v2, LX/ML7;

    .line 315
    .line 316
    move v6, v3

    .line 317
    move v5, v3

    .line 318
    invoke-direct/range {v2 .. v7}, LX/ML7;-><init>(IIIII)V

    .line 319
    .line 320
    .line 321
    iput-object v2, p0, LX/ML0;->A09:LX/ML7;

    .line 322
    .line 323
    const/16 v0, 0x1a

    .line 324
    .line 325
    iput v0, p0, LX/ML0;->A03:I

    .line 326
    .line 327
    iput-boolean v1, p0, LX/ML0;->A10:Z

    .line 328
    .line 329
    iput-boolean v1, p0, LX/ML0;->A0a:Z

    .line 330
    .line 331
    iput-boolean v1, p0, LX/ML0;->A0y:Z

    .line 332
    .line 333
    iput-boolean v1, p0, LX/ML0;->A0o:Z

    .line 334
    .line 335
    return-void
.end method
