package com.facebook.video.heroplayer.setting;

import X.C43322J2o;
import com.whatsapp.calling.voipcalling.Voip;
import java.io.Serializable;

/* JADX INFO: loaded from: classes10.dex */
public class FbAutogeneratedSettings implements Serializable {
    public static final long serialVersionUID = 968006291006349357L;
    public final int autoAddIntParams;
    public final boolean enableSloHttpHeaderLogging;
    public final String grootPrefetchSuboriginBlocklist;
    public final int maxAllowed503RetryCount;

    public FbAutogeneratedSettings(C43322J2o c43322J2o) {
        this.autoAddIntParams = 101;
        this.maxAllowed503RetryCount = -1;
        this.enableSloHttpHeaderLogging = false;
        this.grootPrefetchSuboriginBlocklist = Voip.REJECT_REASON_DECLINED;
    }
}
